"""End-to-end tests for scripts-available/sc_36_dell_health.sh.

`sc_36` reads fans, temperatures, power consumption and PSUs from Dell OMSA's
`omreport`, which cannot be containerised — so `omreport` is a fake binary early
on `PATH` that records its argv and replays captured output.

**Fixture provenance matters here more than the test cases do.** Two sources,
and they do not entirely agree:

* `test/containers/sc_36_dell_health_sample_output.txt` — a real capture of
  `omreport` in its **default human-readable** format, supplied 2026-09-14. It
  is the authority for realistic *values*: statuses, readings, probe names and
  threshold figures.
* the `#`-comments inside `sc_36_dell_health.sh` itself, which are real
  **`-fmt ssv`** captures including the column headers. Those are the authority
  for *column order*, because `-fmt ssv` is what the script actually runs and
  `cut -f N -d\\;` is how it reads the result.

The two formats are not the same shape. For temperatures they agree field for
field. For fans they do not — see
`test_the_fan_column_order_differs_between_the_two_captures`, which records the
conflict rather than silently picking a side.

So the fixtures below are built in `-fmt ssv` column order, carrying the values
from the human-readable capture.
"""

from __future__ import annotations

import pytest

SCRIPT = "sc_36_dell_health.sh"
TOOL = "/usr/local/bin/omreport"
CALL_LOG = "/tmp/omreport-calls.log"
FIXTURE_DIR = "/tmp/omreport-fixtures"

pytestmark = pytest.mark.slow

# `-fmt ssv` column order is taken from the script's own captured headers.
# Values are from sc_36_dell_health_sample_output.txt.
#
#   Index;Status;Probe Name;Reading;Min Warn;Max Warn;Min Fail;Max Fail
FANS_OK = (
    "Index;Status;Probe Name;Reading;Minimum Warning Threshold;"
    "Maximum Warning Threshold;Minimum Failure Threshold;Maximum Failure Threshold\n"
    "0;Ok;Fan 1;5400 RPM;1200 RPM;11000 RPM;600 RPM;12000 RPM\n"
    "1;Ok;Fan 2;5400 RPM;1200 RPM;11000 RPM;600 RPM;12000 RPM\n"
)

#   Index;Status;Probe Name;Reading;Min Warn;Max Warn;Min Fail;Max Fail
TEMPS_OK = (
    "Index;Status;Probe Name;Reading;Minimum Warning Threshold;"
    "Maximum Warning Threshold;Minimum Failure Threshold;Maximum Failure Threshold\n"
    "0;Ok;System Board Ambient Temp;27.0 C;8.0 C;42.0 C;3.0 C;47.0 C\n"
    "1;Ok;CPU1 Temp;37.0 C;8.0 C;95.0 C;3.0 C;100.0 C\n"
)

#   Index;Status;Location;Type;Rated Input;Max Output;FW;Online Status;PwrMon
PSU_OK = (
    "0;Ok;PS 1 Status;AC;750 W;750 W;07.18.7F;Presence Detected;Yes\n"
    "1;Ok;PS 2 Status;AC;750 W;750 W;07.18.7F;Presence Detected;Yes\n"
)

#   Index;Status;Probe Name;Reading;Warning Threshold;Failure Threshold
PWR_OK = (
    "Index;Status;Probe Name;Reading;Warning Threshold;Failure Threshold\n"
    "1;Ok;System Board Pwr Consumption;539 W;994 W;1400 W\n"
)

FAKE_OMREPORT = f"""#!/bin/bash
echo "$*" >> {CALL_LOG}
case "$1 $2" in
  "chassis fans")          fixture=fans ;;
  "chassis temps")         fixture=temps ;;
  "chassis pwrsupplies")   fixture=pwrsupplies ;;
  "chassis pwrmonitoring") fixture=pwrmonitoring ;;
  *) echo "omreport: unsupported command: $*" >&2 ; exit 1 ;;
esac
if [ ! -f "{FIXTURE_DIR}/$fixture" ] ; then
  echo "omreport: no data" >&2
  exit 1
fi
cat "{FIXTURE_DIR}/$fixture"
"""


def config(*, fans=(0, 1), temps=(0, 1), psu=(0, 1), pwrid=1,
           delltool: str = TOOL) -> str:
    lines = ["# generated by test_sc_36_dell_health.py\n",
             f"DELLTOOL={delltool}\n"]
    for i, f in enumerate(fans):
        lines.append(f'FANS[{i}]="{f}"\n')
    for i, t in enumerate(temps):
        lines.append(f'TEMPS[{i}]="{t}"\n')
    for i, p in enumerate(psu):
        lines.append(f'PSU[{i}]="{p}"\n')
    lines.append(f"PWRID={pwrid}\n")
    return "".join(lines)


@pytest.fixture
def dell(syscheck):
    """A healthy Dell chassis: fake omreport replaying the captured values."""
    syscheck.exec(f"rm -f {CALL_LOG} ; mkdir -p {FIXTURE_DIR}")
    syscheck.install_fake_bin("omreport", FAKE_OMREPORT)
    set_fixtures(syscheck)
    syscheck.set_script_config("36", config())
    return syscheck


def set_fixtures(sc, *, fans=FANS_OK, temps=TEMPS_OK,
                 pwrsupplies=PSU_OK, pwrmonitoring=PWR_OK) -> None:
    for name, body in (("fans", fans), ("temps", temps),
                       ("pwrsupplies", pwrsupplies),
                       ("pwrmonitoring", pwrmonitoring)):
        sc.write_file(f"{FIXTURE_DIR}/{name}", body)


def calls(sc) -> list[str]:
    if not sc.file_exists(CALL_LOG):
        return []
    return [l for l in sc.read_file(CALL_LOG).splitlines() if l.strip()]


def ok(run):
    return [m for m in run.messages if m.errno == "361"]


def bad(run):
    return [m for m in run.messages if m.errno == "362"]


# --- the healthy chassis ----------------------------------------------------

def test_a_healthy_chassis_reports_every_component_ok(dell):
    """Two fans, two temperatures, one power reading and two PSUs — seven
    components, all INFO."""
    run = dell.run_script(SCRIPT)

    assert len(ok(run)) == 7, run.describe()
    assert bad(run) == [], run.describe()


def test_each_component_gets_its_own_message_index(dell):
    """One index per component, in fans / temps / power / PSU order, so each has
    its own service in the monitoring system."""
    run = dell.run_script(SCRIPT)

    assert [m.index for m in run.messages] == [
        "01", "02", "03", "04", "05", "06", "07"], run.describe()


def test_the_tool_is_asked_for_each_configured_component(dell):
    """`omreport` is invoked per fan and per temperature, but only once each for
    PSUs and power — the PSU call has no `index=`, so the whole table is fetched
    and then grepped."""
    dell.run_script(SCRIPT)

    assert "chassis fans index=0 -fmt ssv" in calls(dell), calls(dell)
    assert "chassis fans index=1 -fmt ssv" in calls(dell), calls(dell)
    assert "chassis temps index=0 -fmt ssv" in calls(dell), calls(dell)
    assert "chassis pwrsupplies -fmt ssv" in calls(dell), calls(dell)
    assert "chassis pwrmonitoring -fmt ssv" in calls(dell), calls(dell)


# --- the failure states -----------------------------------------------------

@pytest.mark.parametrize("status", ["Critical", "Non-Critical", "Warning", "Unknown"])
def test_a_fan_that_is_not_ok_is_an_error(dell, status):
    """`Ok` is the only accepted status — everything else is an error. Driven
    with the states OMSA actually reports."""
    set_fixtures(dell, fans=FANS_OK.replace("0;Ok;Fan 1", f"0;{status};Fan 1"))

    run = dell.run_script(SCRIPT)

    assert len(bad(run)) == 1, run.describe()
    assert status in bad(run)[0].text, bad(run)[0].text


def test_a_temperature_that_is_not_ok_is_an_error(dell):
    set_fixtures(dell, temps=TEMPS_OK.replace(
        "1;Ok;CPU1 Temp", "1;Critical;CPU1 Temp"))

    run = dell.run_script(SCRIPT)

    assert len(bad(run)) == 1, run.describe()
    assert "CPU1 Temp" in bad(run)[0].text, bad(run)[0].text


def test_a_psu_that_is_not_ok_is_an_error(dell):
    set_fixtures(dell, pwrsupplies=PSU_OK.replace(
        "1;Ok;PS 2 Status", "1;Critical;PS 2 Status"))

    run = dell.run_script(SCRIPT)

    assert len(bad(run)) == 1, run.describe()
    assert "PS 2 Status" in bad(run)[0].text, bad(run)[0].text


def test_power_consumption_that_is_not_ok_is_an_error(dell):
    set_fixtures(dell, pwrmonitoring=PWR_OK.replace(
        "1;Ok;System", "1;Critical;System"))

    run = dell.run_script(SCRIPT)

    assert len(bad(run)) == 1, run.describe()


def test_one_failed_component_does_not_mask_the_others(dell):
    """A degraded fan must not stop the temperature, power or PSU checks: the
    run still reports seven components."""
    set_fixtures(dell, fans=FANS_OK.replace("0;Ok;Fan 1", "0;Critical;Fan 1"))

    run = dell.run_script(SCRIPT)

    assert len(run.messages) == 7, run.describe()
    assert len(bad(run)) == 1 and len(ok(run)) == 6, run.describe()


# --- what the messages carry ------------------------------------------------

def test_the_fan_message_carries_the_name_and_speed_from_the_right_columns(dell):
    """The `cut -f3` / `cut -f4` indices are the whole contract with `omreport`:
    off by one and the operator is told a fan speed where the name should be.
    Pinned against the captured `-fmt ssv` column order."""
    run = dell.run_script(SCRIPT, "-v")

    assert "name: Fan 1" in run.stdout + run.stderr, run.describe()
    assert "rpm: 5400 RPM" in run.stdout + run.stderr, run.describe()


def test_the_temperature_message_carries_the_reading(dell):
    run = dell.run_script(SCRIPT)

    first = ok(run)[2]  # fans occupy 0 and 1
    assert "27.0 C" in first.text, first.text


def test_the_temperature_verbose_line_carries_the_warning_threshold(dell):
    """`cut -f6` is the Maximum Warning Threshold, not the failure threshold —
    42.0 C rather than 47.0 C in the capture."""
    run = dell.run_script(SCRIPT, "-v")

    assert "max: 42.0 C" in run.stdout + run.stderr, run.describe()


def test_the_psu_message_carries_the_output_wattage(dell):
    """`cut -f6` on the PSU row is Maximum Output Wattage, the column after
    Rated Input Wattage. Both are `750 W` in the capture, so the verbose line is
    asserted for the name too, which would move if the index were wrong."""
    run = dell.run_script(SCRIPT, "-v")

    out = run.stdout + run.stderr
    assert "name: PS 1 Status" in out, run.describe()
    assert "watt: 750 W" in out, run.describe()


def test_the_power_message_carries_the_current_draw(dell):
    run = dell.run_script(SCRIPT)

    power = [m for m in run.messages if "powerid" in m.text]
    assert power, run.describe()
    assert "539 W" in power[0].text, power[0].text


# --- the tool itself --------------------------------------------------------

def test_a_missing_tool_is_reported_and_stops_the_run(dell):
    """Without OMSA installed there is nothing to report about, so the check
    says so once rather than calling every component unhealthy."""
    dell.set_script_config("36", config(delltool="/opt/dell/srvadmin/bin/omreport"))

    run = dell.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "363"), run.describe()


def test_a_component_absent_from_the_tool_output_is_an_error(dell):
    """A fan index that OMSA does not know about: the `grep` finds nothing, the
    status is empty, and an empty status is not `Ok`."""
    dell.set_script_config("36", config(fans=(0, 9)))

    run = dell.run_script(SCRIPT)

    assert len(bad(run)) == 1, run.describe()


def test_a_tool_that_fails_is_reported_as_a_bad_component(dell):
    """`omreport` exiting non-zero is not distinguished from a component being
    unhealthy — the check only ever looks at the parsed status field. Pinned so
    the limitation is on the record."""
    dell.exec(f"rm -f {FIXTURE_DIR}/temps")

    run = dell.run_script(SCRIPT)

    assert len(bad(run)) == 2, run.describe()


# --- fixture provenance -----------------------------------------------------

def test_the_fan_column_order_differs_between_the_two_captures(dell):
    """A record of a conflict in the fixture sources, not a test of the script.

    `sc_36_dell_health.sh` carries this `-fmt ssv` capture in its comments:

        Index;Status;Probe Name;Reading;Minimum Warning Threshold;...
        0;Ok;System Board Fan2A;7200 RPM;840 RPM;[N/A];600 RPM;[N/A]

    while `sc_36_dell_health_sample_output.txt` shows the human-readable form
    with different labels *and* a different order:

        Index : 0 / Status : Ok / Reading : 5400 RPM / Location : Fan 1

    `Reading` comes before `Location` there, but after `Probe Name` in the ssv
    header. For temperatures the two agree exactly, so this is specific to fans
    — most likely an OMSA version difference, or the two outputs simply not
    sharing a column order.

    These fixtures follow the **ssv** capture, because `-fmt ssv` is what the
    script runs. If the human-readable order is the correct one for ssv too,
    then `cut -f3`/`cut -f4` are swapped and every fan message names a speed and
    reports a location. **A real `omreport chassis fans index=0 -fmt ssv`
    capture would settle it** — until then this is unresolved, and the test
    above asserting `name: Fan 1` encodes the ssv reading of it."""
    source = dell.read_file(dell.script_path(SCRIPT))

    assert "Index;Status;Probe Name;Reading;" in source, (
        "the ssv header these fixtures are built from is gone from the script")


def test_the_configured_cpu_list_is_never_checked(dell):
    """`config/36.conf` defines `CPU[0]` under a `# check cpus with omreport
    chassis processors` comment, but the script has no processor check and never
    reads `CPU[]`. An operator adding CPUs to that list gets no coverage and no
    warning. Pinned so the dead setting is visible."""
    source = dell.read_file(dell.script_path(SCRIPT))

    assert "CPU[" not in source and "processors" not in source
    shipped = dell.read_file("/src/config/36.conf")
    assert "CPU[0]" in shipped, "the dead CPU setting was removed from the config"


def test_help_documents_every_error_code(dell):
    res = dell.exec([dell.script_path(SCRIPT), "--help"])

    for errno in ("361", "362", "363"):
        assert f"{errno} / " in res.output, res.output
