"""End-to-end tests for related-available/931_mysql_backup_encrypt_send_to_remote_host.sh.

`931` chains three steps: take a database backup with `904`, encrypt it with a
vendor tool, then ship the encrypted file to each configured backup host via
`906`. A lock file serialises concurrent runs of the encryption step.

Mixed strategy, because the chain spans three different kinds of dependency:

* **REAL-SVC** for the backup — the real `904` against a real `mariadb:11`.
* **FAKE-BIN** for `OPENENC_TOOL`, which is `/opt/certificate-services/openenc/openenc.sh`,
  a vendor tool that is not in this tree.
* **Stub `906`**, written over the real one in `related-available/`. That tree
  is in the harness's `MUTABLE_TREES`, so `reset()` restores it from `/src`
  before every test and the stub cannot leak between them.

  `931` used to reach `906` through `related-enabled/`, which ships empty apart
  from a README — so an unenabled `906` meant every transfer failed silently.
  The path moved to `related-available/` on 2026-09-18, as `905`, `919` and
  `925` did, and this seam moved with it.

The local encrypted file is **deleted** after a successful transfer, so the
tests check what survives on disk as well as what is reported.
"""

from __future__ import annotations

import pytest

from conftest import MARIADB_DATABASE, MARIADB_ROOT_PASSWORD

SCRIPT = "related-available/931_mysql_backup_encrypt_send_to_remote_host.sh"
HELPER = "related-available/906_ssh-copy-to-remote-machine.sh"
BACKUPDIR = "/tmp/931/backup"
ARCHIVE = "/tmp/931/to-archive"
ENC_LOG = "/tmp/931/openenc.log"
SSH_LOG = "/tmp/931/906.log"

pytestmark = pytest.mark.slow


def mariadb_config() -> str:
    return (f"DB_NAME={MARIADB_DATABASE}\n"
            f'MYSQLROOT_PASSWORD="{MARIADB_ROOT_PASSWORD}"\n'
            "MYSQL_BIN=/usr/bin/mariadb\n"
            "MYSQLDUMP_BIN=/usr/bin/mariadb-dump\n"
            "MYSQLDUMP_OPTIONS=(--single-transaction --quick)\n")


def backup_config() -> str:
    return ("DATESTING='%Y-%m-%d_%H.%M.%S'\n"
            f"MYSQLBACKUPDIR={BACKUPDIR}\n"
            "SUBDIR_DEFAULT=default\nSUBDIR_DAILY=daily\n"
            "SUBDIR_WEEKLY=weekly\nSUBDIR_MONTHLY=monthly\nSUBDIR_YEARLY=yearly\n"
            f'DBNAME[0]="{MARIADB_DATABASE}"\nTABLENAMES[0]=""\n')


def config(*, hosts=("bak1",), shared: str = "false") -> str:
    lines = ["# generated by test_931_mysql_backup_encrypt_send.py\n",
             "OPENENC_TOOL=/usr/local/bin/openenc.sh\n",
             f"TOARCHIVE_DIR={ARCHIVE}\n",
             "LOCKFILE_MAX_WAIT_SEC=5\n",
             "SUBDIR_DEFAULT=default\nSUBDIR_DAILY=daily\n",
             "SUBDIR_WEEKLY=weekly\nSUBDIR_MONTHLY=monthly\nSUBDIR_YEARLY=yearly\n",
             f'SHARED_STORAGE="{shared}"\n']
    for i, host in enumerate(hosts):
        lines.append(f"BACKUP_HOST[{i}]={host}\n")
        lines.append(f"BACKUP_DIR[{i}]=/backup/ca/\n")
        lines.append(f"BACKUP_USER[{i}]=bakuser\n")
        lines.append(f"BACKUP_SSHFROMKEY[{i}]=/root/.ssh/id_rsa\n")
    return "".join(lines)


def install_openenc(sc, *, rc: int = 0) -> None:
    """Stands in for the vendor encrypt tool: copies the file into the archive
    directory with a `.enc` suffix, which is enough for `931`'s purposes."""
    sc.install_fake_bin("openenc.sh",
                        "#!/bin/bash\n"
                        f'echo "$@" >> {ENC_LOG}\n'
                        f"[ {rc} -ne 0 ] && {{ echo 'encrypt failed' ; exit {rc} ; }}\n"
                        'cp "$2" "$3/$(basename "$2").enc"\n'
                        "exit 0\n")


def install_906(sc, *, rc: int = 0) -> None:
    sc.write_file(f"{sc.home}/{HELPER}",
                  "#!/bin/bash\n"
                  f'echo "$@" >> {SSH_LOG}\n'
                  f"exit {rc}\n",
                  mode=0o755)


@pytest.fixture
def chain(syscheck, mariadb_node):
    syscheck.write_file("/root/.my.cnf", f"[client]\nhost={mariadb_node}\n")
    syscheck.exec(f"rm -rf /tmp/931 && mkdir -p {BACKUPDIR}/default {ARCHIVE}").check()
    syscheck.exec(["mariadb", "-h", mariadb_node, "-uroot",
                   f"-p{MARIADB_ROOT_PASSWORD}", MARIADB_DATABASE, "-e",
                   "DROP TABLE IF EXISTS CertificateData;"
                   "CREATE TABLE CertificateData (fingerprint VARCHAR(64) PRIMARY KEY);"
                   "INSERT INTO CertificateData VALUES ('aa')"]).check()
    install_openenc(syscheck)
    install_906(syscheck)
    syscheck.set_script_config("mariadb", mariadb_config())
    syscheck.set_script_config("904", backup_config())
    syscheck.set_script_config("931", config())
    return syscheck


def own(run) -> list:
    return [m for m in run.messages if m.scriptid == "931"]


def archived(sc) -> list[str]:
    res = sc.exec(f"ls -1 {ARCHIVE} 2>/dev/null")
    return sorted(f for f in res.stdout.splitlines() if f.strip())


# --- the chain --------------------------------------------------------------

def test_a_backup_is_taken_encrypted_and_transferred(chain):
    """The whole point, end to end: `904` produces a dump, the encrypt tool is
    handed that exact path, and `906` is asked to ship the result."""
    chain.run_script(SCRIPT)

    enc = chain.read_file(ENC_LOG)
    assert "encrypt" in enc and ".gz" in enc, enc
    assert chain.file_exists(SSH_LOG), "906 was never called"
    assert ".enc" in chain.read_file(SSH_LOG), chain.read_file(SSH_LOG)


def test_a_successful_transfer_is_reported(chain):
    run = chain.run_script(SCRIPT)

    ok = [m for m in own(run) if m.errno == "9311"]
    assert ok, run.describe()
    assert "bak1" in ok[0].text, ok[0].text


def test_the_local_copy_is_removed_after_a_successful_transfer(chain):
    """`931` deletes the encrypted file once every host has taken it, so the
    staging directory does not grow without bound."""
    chain.run_script(SCRIPT)

    assert archived(chain) == [], archived(chain)


def test_a_failing_transfer_is_reported_and_keeps_the_local_copy(chain):
    """The other half of the same contract: if the file did not reach the
    remote host it must not be deleted locally."""
    install_906(chain, rc=1)

    run = chain.run_script(SCRIPT)

    failed = [m for m in own(run) if m.errno == "9314"]
    assert failed, run.describe()
    # DESCR[1] and DESCR[4] gained a second placeholder so several configured
    # hosts can be told apart by more than the index alone
    assert "bak1" in failed[0].text, failed[0].text
    assert archived(chain), "the only copy was deleted after a failed transfer"


def test_a_failing_encryption_is_reported(chain):
    install_openenc(chain, rc=1)

    run = chain.run_script(SCRIPT)

    assert any(m.errno == "9313" for m in own(run)), run.describe()


def test_every_configured_host_receives_the_file(chain):
    chain.set_script_config("931", config(hosts=("bak1", "bak2")))

    chain.run_script(SCRIPT)

    log = chain.read_file(SSH_LOG)
    assert "--host=bak1" in log and "--host=bak2" in log, log


def test_each_transfer_reports_under_its_own_index(chain):
    chain.set_script_config("931", config(hosts=("bak1", "bak2")))

    run = chain.run_script(SCRIPT)

    indexes = [m.index for m in own(run) if m.errno in ("9311", "9314")]
    assert len(set(indexes)) == len(indexes), run.describe()


def test_shared_storage_sends_to_only_one_host(chain):
    """With `SHARED_STORAGE=true` the hosts are different doors onto the same
    filesystem, so one successful copy is enough and the loop breaks."""
    chain.set_script_config("931", config(hosts=("bak1", "bak2"), shared="true"))

    chain.run_script(SCRIPT)

    log = chain.read_file(SSH_LOG)
    assert "--host=bak1" in log, log
    assert "--host=bak2" not in log, log


# --- the lock ---------------------------------------------------------------

def test_the_lock_file_is_released(chain):
    """The lock is created with `noclobber` and holds the owning PID; a run that
    finishes must leave nothing behind, or the next run waits out
    `LOCKFILE_MAX_WAIT_SEC` for no reason."""
    chain.run_script(SCRIPT)

    assert not chain.file_exists(f"{ARCHIVE}/encback.lock")


def test_a_stale_lock_from_a_dead_run_is_cleared(chain):
    """A lock older than `LOCKFILE_MAX_WAIT_SEC` is removed and reported, so a
    crashed run cannot block backups forever."""
    chain.exec(f"echo 999999 > {ARCHIVE}/encback.lock && "
               f"touch -d '1 hour ago' {ARCHIVE}/encback.lock").check()

    run = chain.run_script(SCRIPT)

    assert any(m.errno == "9315" for m in own(run)), run.describe()
    assert not chain.file_exists(f"{ARCHIVE}/encback.lock")


# --- known defects ----------------------------------------------------------

def test_a_later_successful_transfer_still_cleans_up(chain):
    """D103, fixed 2026-09-18. `FILETRANS=1` was set **once**, above the loop
    over files. Inside, a failed transfer set it to 0 and nothing ever set it
    back.

    So the first file that failed to reach a host latched the flag off for the
    rest of the run, and every subsequent file — including ones that transferred
    to every host successfully — was left in the staging directory, which then
    grew until a human noticed.

    The flag is now reset at the top of each file's iteration. That reads as
    what was intended all along, since it is assigned again inside the
    `SHARED_STORAGE` branch, where it deliberately recovers from an earlier
    host's failure because one copy to shared storage is enough.

    The stub below fails only its **first** call, so whichever file `find`
    yields first fails and every later one succeeds — the latch is then the only
    thing that could keep the successful file on disk. Driving it through two
    separate runs does not work: each invocation is a fresh shell, so
    `FILETRANS` starts at 1 again."""
    chain.exec(f"echo stale > {ARCHIVE}/leftover.enc").check()
    chain.write_file(f"{chain.home}/{HELPER}",
                     "#!/bin/bash\n"
                     f'echo "$@" >> {SSH_LOG}\n'
                     f'n=$(cat {ARCHIVE}/../count 2>/dev/null || echo 0)\n'
                     f'echo $((n + 1)) > {ARCHIVE}/../count\n'
                     '[ "$n" = "0" ] && exit 1\n'
                     "exit 0\n",
                     mode=0o755)

    chain.run_script(SCRIPT)

    assert len(archived(chain)) == 1, (
        "the file that transferred successfully was left behind: "
        f"{archived(chain)}")


def test_the_log_file_is_not_shipped_offsite(chain):
    """D104, fixed 2026-09-18. The guard read

        if [ "x${TRANSFERFILENAME}" = "xencback.log" ] ; then continue

    but `TRANSFERFILENAME` comes from `find ${TOARCHIVE_DIR}/ -type f`, so it is
    always a full path such as `/backup/to-archive/encback.log`. It could never
    equal the bare name, so the log was transferred to every backup host like a
    backup, and then deleted locally by the cleanup at the end of the loop.

    Fixed with `basename` rather than a `*/encback.log` glob, because `906`
    already uses `basename` for the same job."""
    chain.exec(f"echo logline > {ARCHIVE}/encback.log").check()

    chain.run_script(SCRIPT)

    log = chain.read_file(SSH_LOG)
    assert "encback.log" not in log, log


def test_a_failing_backup_is_reported_with_its_error_number(chain):
    """D105, fixed 2026-09-17. The call read

        printlogmess ... -e $ERRNO[2] -d "${DESCR[2]}"

    Without braces, `$ERRNO[2]` is `$ERRNO` — element 0 of the array, which is
    unset — followed by the literal text `[2]`. So the error number reported is
    the string `[2]` rather than `9312`.

    `DESCR[2]` also carries a `(%s)` placeholder that this call passes nothing
    for, so the message cannot say what went wrong either."""
    chain.set_script_config("904", backup_config().replace(
        f"MYSQLBACKUPDIR={BACKUPDIR}", "MYSQLBACKUPDIR=/tmp/931/gone"))

    run = chain.run_script(SCRIPT)

    assert any(m.errno == "9312" for m in own(run)), run.describe()


def test_cleanup_skips_a_file_that_has_already_gone(chain):
    """The `rm` now checks the file is still there. Nothing in `931` guarantees
    it — the encryption step writes into the same directory the loop is walking,
    and `find` captured the list before any of it ran — so removing a path that
    has since gone would print an error for a run that actually succeeded."""
    chain.run_script(SCRIPT)

    res = chain.exec(f"ls -1 {ARCHIVE}")
    assert "No such file" not in res.output, res.output


def test_help_documents_every_error_code(chain):
    res = chain.exec([chain.script_path(SCRIPT), "--help"])

    for errno in ("9311", "9312", "9313", "9314", "9315"):
        assert f"{errno} / " in res.output, res.output
