"""End-to-end tests for related-available/925_publish_crl_from_file.sh.

`925` publishes a CRL file to each configured verification host by delegating
the transfer to `906`. It owns no transport of its own.

REAL-SVC: the shared key-only `sshd_node`, the real `906` and the real `915`
beneath it.

Until 2026-09-16 `925` called `906` with **positional** arguments, which `906`
does not accept — the same defect that had `913` and `921` deleted. It was
converted to named options rather than removed, and at the same time `-c` was
declared to `getopt` (the case arm existed but the option did not) and
`SCRIPTINDEX` was made to advance per host. This suite covers the result.
"""

from __future__ import annotations

import pytest

from conftest import SSH_KEY, SSH_REMOTE_USER

SCRIPT = "related-available/925_publish_crl_from_file.sh"
WORK = "/tmp/925"
CRL = f"{WORK}/current.crl"
REMOTE_DIR = f"/home/{SSH_REMOTE_USER}/crl"

pytestmark = pytest.mark.slow

SSH_OPTS = ('"-o ConnectTimeout=10 -o StrictHostKeyChecking=no '
            '-o UserKnownHostsFile=/dev/null -o LogLevel=ERROR"')


def config(sc, *, hosts=None, directory: str = REMOTE_DIR) -> str:
    hosts = hosts or [sc.sshd]
    lines = ["# generated by test_925_publish_crl_from_file.py\n"]
    for i, host in enumerate(hosts):
        lines.append(f"VERIFY_HOST[{i}]={host}\n")
        lines.append(f"CRLTO_DIR[{i}]={directory}\n")
        lines.append(f"SSHKEY[{i}]={SSH_KEY}\n")
        lines.append(f"SSHUSER[{i}]={SSH_REMOTE_USER}\n")
    return "".join(lines)


@pytest.fixture
def publish(syscheck, sshd_node):
    syscheck.sshd = sshd_node
    syscheck.exec(f"rm -rf {WORK} && mkdir -p {WORK} && "
                  f"printf 'crl-bytes\\n' > {CRL}").check()
    syscheck.set_script_config("906", f"SSHTIMEOUT={SSH_OPTS}\n")
    syscheck.set_script_config("915", f"SSHOPTIONS={SSH_OPTS}\n")
    syscheck.set_script_config("925", config(syscheck))

    def remote(command: str):
        return syscheck.exec([
            "ssh", "-o", "StrictHostKeyChecking=no",
            "-o", "UserKnownHostsFile=/dev/null", "-o", "LogLevel=ERROR",
            "-i", SSH_KEY, "-l", SSH_REMOTE_USER, sshd_node, command])

    remote(f"rm -rf {REMOTE_DIR} && mkdir -p {REMOTE_DIR}").check()
    syscheck.remote = remote
    return syscheck


def own(run) -> list:
    return [m for m in run.messages if m.scriptid == "925"]


# --- the transfer -----------------------------------------------------------

def test_the_crl_reaches_the_verification_host(publish):
    """The regression test for the positional-call fix: before it, `906`
    refused on a missing `--file` and nothing was ever published."""
    publish.run_script(SCRIPT, f"--crlfile={CRL}")

    assert "current.crl" in publish.remote(f"ls -1 {REMOTE_DIR}").stdout


def test_the_published_crl_matches_the_local_file(publish):
    publish.run_script(SCRIPT, f"--crlfile={CRL}")

    res = publish.remote(f"cat {REMOTE_DIR}/current.crl")
    assert "crl-bytes" in res.stdout, res.output


def test_a_successful_publish_is_reported(publish):
    run = publish.run_script(SCRIPT, f"--crlfile={CRL}")

    assert any(m.errno == "9251" and m.level == "I" for m in own(run)), run.describe()


def test_every_configured_host_receives_the_crl(publish):
    publish.set_script_config("925", config(publish, hosts=[publish.sshd,
                                                            publish.sshd]))

    run = publish.run_script(SCRIPT, f"--crlfile={CRL}")

    assert len(own(run)) == 2, run.describe()


def test_each_host_reports_under_its_own_index(publish):
    """Added with the named-option conversion: before it, every host reported at
    the same `SCRIPTINDEX` and the last one overwrote the rest."""
    publish.set_script_config("925", config(publish, hosts=[publish.sshd,
                                                            publish.sshd]))

    run = publish.run_script(SCRIPT, f"--crlfile={CRL}")

    indexes = [m.index for m in own(run)]
    assert len(set(indexes)) == len(indexes), run.describe()


# --- options ----------------------------------------------------------------

def test_the_short_option_works(publish):
    """`-c` had a case arm but was never declared to `getopt`, so only the long
    form worked. Declared as part of the same change."""
    publish.run_script(SCRIPT, "-c", CRL)

    assert "current.crl" in publish.remote(f"ls -1 {REMOTE_DIR}").stdout


# --- guards -----------------------------------------------------------------

def test_running_without_a_crl_file_is_reported(publish):
    run = publish.run_script(SCRIPT)

    assert own(run)[0].errno == "9252", run.describe()


def test_an_unreadable_crl_file_is_reported(publish):
    run = publish.run_script(SCRIPT, f"--crlfile={WORK}/no-such.crl")

    assert own(run)[0].errno == "9253", run.describe()


def test_nothing_is_published_when_the_file_is_missing(publish):
    publish.run_script(SCRIPT, f"--crlfile={WORK}/no-such.crl")

    assert publish.remote(f"ls -1 {REMOTE_DIR}").stdout.strip() == ""


# --- failures ---------------------------------------------------------------

def test_an_unreachable_host_is_reported(publish):
    publish.set_script_config("925", config(publish, hosts=["no-such-host"]))

    run = publish.run_script(SCRIPT, f"--crlfile={CRL}")

    msg = own(run)[0]
    assert (msg.level, msg.errno) == ("E", "9254"), run.describe()


def test_one_failing_host_does_not_stop_the_others(publish):
    publish.set_script_config("925", config(publish, hosts=["no-such-host",
                                                            publish.sshd]))

    run = publish.run_script(SCRIPT, f"--crlfile={CRL}")

    assert [m.errno for m in own(run)] == ["9254", "9251"], run.describe()
    assert "current.crl" in publish.remote(f"ls -1 {REMOTE_DIR}").stdout


# --- known defect -----------------------------------------------------------

def test_the_outcome_message_names_the_host_and_file(publish):
    """D127, fixed 2026-09-17. Both branches passed `-1 "$CRLHOST" -2 "$CRLFILE"`,
    which was the right shape — but

        DESCR[1]="Publish crl run successfully"
        DESCR[4]="scp script failed"

    carry no `%s` at all, so both arguments are discarded. `DESCR[3]` in the
    same file does have one.

    With several verification hosts configured, the log says a publish failed
    and gives no way to tell which host or which CRL. The index distinguishes
    them only if you have the config to hand.

    This is the inverse of the usual fault in this tree: the call site is
    correct and the language file is short, rather than the other way round."""
    publish.set_script_config("925", config(publish, hosts=["no-such-host"]))

    run = publish.run_script(SCRIPT, f"--crlfile={CRL}")

    assert "no-such-host" in own(run)[0].text, own(run)[0].text


def test_help_documents_every_error_code(publish):
    res = publish.exec([publish.script_path(SCRIPT), "--help"])

    for errno in ("9251", "9252", "9253", "9254"):
        assert f"{errno} / " in res.output, res.output
