"""End-to-end tests for scripts-available/sc_28_check_vip.sh.

`sc_28` asks two cluster nodes, over ssh, whether they hold the virtual IP, and
reports which one does. It owns none of the ssh: it shells out to
`related-enabled/915_remote_command_via_ssh.sh` and interprets the output.

So that is where the seam is. These tests drive `sc_28` against a **stub 915**
that records how it was called and prints a chosen `ifconfig` line — which
covers `sc_28`'s entire contract (ask both nodes, classify the four possible
answers) without an ssh server. The real `915` is exercised separately, at the
one point that matters here: whether it understands the way `sc_28` calls it.
It does not — see D56. Testing `915`'s ssh transport itself belongs to Phase 4,
which covers the `related` scripts.

`HOSTNAME_VIRTUAL` is compared against the address parsed out of `ifconfig`, so
despite the name it holds an IP address, and the parsing
(`awk '{print $2}' | sed 's/addr://g'`) expects the classic
`inet addr:10.0.0.9` format rather than iproute2's `inet 10.0.0.9`.
"""

from __future__ import annotations

import pytest

SCRIPT = "sc_28_check_vip.sh"
HELPER = "related-enabled/915_remote_command_via_ssh.sh"

NODE1 = "node1.example.com"
NODE2 = "node2.example.com"
VIP = "10.0.0.9"
CALL_LOG = "/tmp/915-calls.log"

pytestmark = pytest.mark.slow


def config() -> str:
    return (
        "# generated by test_sc_28_check_vip.py\n"
        f"HOSTNAME_NODE1={NODE1}\n"
        f"HOSTNAME_NODE2={NODE2}\n"
        f"HOSTNAME_VIRTUAL={VIP}\n"
        "SSH_USER=syscheck\n"
        "SSH_KEY=/root/.ssh/id_rsa\n"
        "IFCONFIG=/sbin/ifconfig\n"
    )


def install_stub_915(sc, holders: set[str]) -> None:
    """A stand-in for 915 that records its argv and answers as the nodes in
    `holders` would: the classic `inet addr:<vip>` line, and silence from a node
    that does not hold the address (which is what `ifconfig | grep <vip>`
    returns there).

    It matches on `--host=`, the named form `915` actually accepts, so this stub
    would not answer a positional call either — which is what D56 was."""
    cases = "\n".join(
        f'  *--host={host}*) echo "          inet addr:{VIP}  Bcast:10.0.0.255  '
        f'Mask:255.255.255.0" ;;'
        for host in sorted(holders)
    )
    sc.write_file(
        f"{sc.home}/{HELPER}",
        "#!/bin/bash\n"
        f'echo "$*" >> {CALL_LOG}\n'
        'case "$*" in\n'
        f"{cases}\n"
        "  *) : ;;\n"
        "esac\n"
        "exit 0\n",
        mode=0o755,
    )


def calls(sc) -> list[str]:
    if not sc.file_exists(CALL_LOG):
        return []
    return [l for l in sc.read_file(CALL_LOG).splitlines() if l.strip()]


@pytest.fixture
def vip(syscheck):
    syscheck.exec(["rm", "-f", CALL_LOG])
    syscheck.set_script_config("28", config())
    return syscheck


# --- the helper has to be enabled -------------------------------------------

def test_a_missing_helper_is_reported_and_stops_the_check(vip):
    """`related-enabled/` ships with nothing in it but a README, so this is the
    behaviour of a stock install: the check says the ssh tool is not activated
    and does not pretend to know where the VIP is."""
    run = vip.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "285"), run.describe()


def test_the_helper_is_asked_about_both_nodes(vip):
    """Both nodes must be queried every run — checking only one cannot tell a
    failover apart from a split brain."""
    install_stub_915(vip, {NODE1})

    vip.run_script(SCRIPT)

    assert len(calls(vip)) == 2, calls(vip)
    assert NODE1 in calls(vip)[0] and NODE2 in calls(vip)[1], calls(vip)


def test_the_helper_is_asked_to_grep_ifconfig_for_the_vip(vip):
    """The command sent to the node is built from `IFCONFIG` and
    `HOSTNAME_VIRTUAL`; if either is missing the node answers about the wrong
    thing."""
    install_stub_915(vip, {NODE1})

    vip.run_script(SCRIPT)

    assert "/sbin/ifconfig" in calls(vip)[0], calls(vip)
    assert VIP in calls(vip)[0], calls(vip)


# --- the four states --------------------------------------------------------

def test_the_vip_on_node_two_is_reported(vip):
    install_stub_915(vip, {NODE2})

    run = vip.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("I", "282"), run.describe()


def test_the_vip_on_both_nodes_is_an_error(vip):
    """Split brain: two nodes answering for the same address. The most serious
    state this check exists to find."""
    install_stub_915(vip, {NODE1, NODE2})

    run = vip.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "283"), run.describe()


def test_the_vip_on_neither_node_is_an_error(vip):
    """Nobody is serving the address — the cluster is down."""
    install_stub_915(vip, set())

    run = vip.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "284"), run.describe()


def test_the_vip_on_node_one_is_reported_without_contradiction(vip):
    """Before the D57 fix the second block tested `$NODE1`, a variable never
    assigned anywhere in the script — the one holding node 1's answer is
    `$CHECK_VIP_NODE1`. `$NODE1` was empty on every run, so the first half of
    the condition was always true and the "nobody has the VIP" verdict was
    decided by node 2 alone.

    A cluster sitting healthily on its primary node therefore emitted both
    `Node 1 has the VIP` and `None of the nodes has the VIP` in the same run,
    and the ERROR is the one that pages."""
    install_stub_915(vip, {NODE1})

    run = vip.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("I", "281"), run.describe()


def test_the_vip_on_node_one_does_not_also_raise_the_nobody_error(vip):
    """The other half of D57: exactly one message, not a verdict and its
    contradiction."""
    install_stub_915(vip, {NODE1})

    run = vip.run_script(SCRIPT)

    assert [m.errno for m in run.messages] == ["281"], run.describe()


def test_both_nodes_get_the_same_treatment(vip):
    """D57 misfired for node 1 only, which is why it survived so long — half the
    cluster behaved. Either node holding the VIP must now give one message."""
    install_stub_915(vip, {NODE2})
    assert len(vip.run_script(SCRIPT).messages) == 1

    vip.exec(["rm", "-f", CALL_LOG])
    install_stub_915(vip, {NODE1})

    assert len(vip.run_script(SCRIPT).messages) == 1


# --- the interface to 915 ---------------------------------------------------

def test_the_real_helper_understands_how_the_check_calls_it(vip):
    """`sc_28` owns none of the ssh — it shells out to `915`. Before the D56 fix
    it invoked the helper **positionally**

        915_remote_command_via_ssh.sh $HOST "$CMD" $USER $KEY

    while `915` parses with `getopt` and reads only `--host`, `--command`,
    `--user` and `--key`, as its own `HELP` documents. The positional arguments
    landed after `--`, `SSHHOST` stayed empty, and `915` bailed out before
    running ssh — reporting "Host not found" through `printlogmess`, which
    without `--screen` writes to syslog rather than stdout, and stdout is all
    `sc_28` captures. So `sc_28` saw an empty answer from both nodes on every
    run, with no indication why.

    Asserted on the evidence that separates the two calling conventions: the
    helper has to get far enough to attempt the connection, which ssh reports
    on stdout."""
    vip.exec(f"cp {vip.home}/related-available/915_remote_command_via_ssh.sh "
             f"{vip.home}/{HELPER} && chmod 755 {vip.home}/{HELPER}").check()

    res = vip.exec([f"{vip.home}/{HELPER}", "--host", NODE1,
                    "--command", "/sbin/ifconfig", "--user", "syscheck",
                    "--key", "/root/.ssh/id_rsa"])

    assert "hostname" in res.output, (
        "the helper never attempted ssh: " + repr(res.output))


def test_the_check_asks_the_real_helper_with_named_options(vip):
    """D56 end to end, with the **real** helper in place. Both nodes are
    unreachable here, so the verdict is still "nobody has the VIP" — but the
    point is that ssh was genuinely attempted, which is what the positional call
    never managed."""
    vip.exec(f"cp {vip.home}/related-available/915_remote_command_via_ssh.sh "
             f"{vip.home}/{HELPER} && chmod 755 {vip.home}/{HELPER}").check()

    run = vip.run_script(SCRIPT)

    assert "284" in run.errnos, run.describe()
    source = vip.read_file(vip.script_path(SCRIPT))
    assert '--host="${HOSTNAME_NODE1}"' in source, source


def test_help_documents_every_error_code(vip):
    res = vip.exec([vip.script_path(SCRIPT), "--help"])

    for n in range(1, 6):
        assert f"28{n} / " in res.output, res.output
