"""End-to-end tests for related-available/912_deactivate_VIP.sh.

`912` releases the virtual IP: it checks the VIP is actually on this node,
brings the alias interface down, and removes the marker file that says this node
holds it.

FAKE-BIN: `ifconfig` is stubbed, recording its argv and reporting whether the
VIP is locally configured. That is the only external command `912` uses.

`911` and `912` are a pair — one writes `var/this_node_has_the_vip`, the other
removes it — so the last test here drives both in sequence, which is the only
way to check the marker's whole lifecycle.
"""

from __future__ import annotations

import pytest

SCRIPT = "related-available/912_deactivate_VIP.sh"
ACTIVATE = "related-available/911_activate_VIP.sh"
LOG = "/tmp/912/calls"
MARKER = "/opt/syscheck/var/this_node_has_the_vip"
VIP = "192.168.0.10"
IFACE = "eth1:0"

pytestmark = pytest.mark.slow


def config() -> str:
    return ("# generated by test_912_deactivate_vip.py\n"
            "IFCONFIG=/usr/local/bin/ifconfig\n"
            "ROUTE=/usr/local/bin/route\n"
            f"HOSTNAME_VIRTUAL={VIP}\n"
            "NETMASK_VIRTUAL=255.255.255.0\n"
            f'IF_VIRTUAL="{IFACE}"\n')


def install_ifconfig(sc, *, vip_is_local: bool = True, down_rc: int = 0) -> None:
    line = (f"          inet addr:{VIP}  Bcast:192.168.0.255  Mask:255.255.255.0"
            if vip_is_local else
            "          inet addr:10.0.0.5  Bcast:10.0.0.255  Mask:255.255.255.0")
    sc.exec(f"mkdir -p /tmp/912 && rm -f {LOG}.ifconfig").check()
    sc.install_fake_bin("ifconfig",
                        "#!/bin/bash\n"
                        f'echo "$@" >> {LOG}.ifconfig\n'
                        f'case "$*" in *down) exit {down_rc} ;; esac\n'
                        f'echo "{IFACE} Link encap:Ethernet"\n'
                        f'echo "{line}"\n'
                        "exit 0\n")


@pytest.fixture
def vip(syscheck):
    install_ifconfig(syscheck)
    syscheck.exec(f"date > {MARKER}").check()
    syscheck.set_script_config("912", config())
    syscheck.set_script_config("911", config())
    return syscheck


def own(run) -> list:
    return [m for m in run.messages if m.scriptid == "912"]


def calls(sc) -> list[str]:
    path = f"{LOG}.ifconfig"
    if not sc.file_exists(path):
        return []
    return [l for l in sc.read_file(path).splitlines() if l.strip()]


# --- releasing --------------------------------------------------------------

def test_the_interface_is_brought_down(vip):
    """Unlike `911`, `912` writes this line as a plain command rather than an
    array assignment, so it really runs — see D134."""
    vip.run_script(SCRIPT)

    assert any("down" in c for c in calls(vip)), calls(vip)


def test_a_successful_release_is_reported(vip):
    run = vip.run_script(SCRIPT)

    assert any(m.errno == "9121" for m in own(run)), run.describe()


def test_the_marker_file_is_removed(vip):
    """The marker is how the cluster answers "who holds the VIP?". Leaving it
    behind after a release would point at a node that no longer has it."""
    vip.run_script(SCRIPT)

    assert not vip.file_exists(MARKER)


def test_a_failing_ifconfig_is_reported(vip):
    install_ifconfig(vip, down_rc=1)

    run = vip.run_script(SCRIPT)

    assert any(m.errno == "9122" for m in own(run)), run.describe()


def test_a_failed_release_keeps_the_marker(vip):
    """If the interface is still up, this node still holds the VIP — removing
    the marker would lose that fact."""
    install_ifconfig(vip, down_rc=1)

    vip.run_script(SCRIPT)

    assert vip.file_exists(MARKER), "the marker was removed despite the failure"


# --- when there is nothing to release ---------------------------------------

def test_a_vip_not_held_here_is_reported_as_already_inactive(vip):
    install_ifconfig(vip, vip_is_local=False)

    run = vip.run_script(SCRIPT)

    assert any(m.errno == "9123" for m in own(run)), run.describe()


def test_a_vip_not_held_here_is_not_brought_down(vip):
    """Taking down an alias this node does not hold could disturb whatever else
    is on that interface."""
    install_ifconfig(vip, vip_is_local=False)

    vip.run_script(SCRIPT)

    assert not any("down" in c for c in calls(vip)), calls(vip)


def test_a_vip_not_held_here_is_not_an_error(vip):
    """Releasing something you do not hold is a no-op, not a failure — a
    failover script may well call `912` on both nodes."""
    install_ifconfig(vip, vip_is_local=False)

    run = vip.run_script(SCRIPT)

    assert own(run) and own(run)[0].level == "I", run.describe()


# --- the pair ---------------------------------------------------------------

def test_activate_then_deactivate_leaves_no_marker(vip):
    """The lifecycle across both scripts. `911` writes the marker, `912` removes
    it, and the pair has to agree about the filename — they are the only two
    places in the tree that touch it."""
    vip.exec(f"rm -f {MARKER}").check()
    vip.install_fake_bin("route",
                         "#!/bin/bash\necho 'Kernel IP routing table'\n"
                         "echo '0.0.0.0  192.168.0.1  0.0.0.0  UG  0 0 0 eth0'\n")
    vip.install_fake_bin("ping", "#!/bin/bash\nexit 1\n")
    vip.install_fake_bin("arping", "#!/bin/bash\nexit 0\n")
    install_ifconfig(vip, vip_is_local=False)

    vip.run_script(ACTIVATE)
    assert vip.file_exists(MARKER), "911 did not write the marker"

    install_ifconfig(vip, vip_is_local=True)
    vip.run_script(SCRIPT)

    assert not vip.file_exists(MARKER), "912 did not remove the marker"


# --- known defect -----------------------------------------------------------

def test_the_messages_carry_their_description_text(vip):
    """D136, fixed 2026-09-17. Every one of `912`'s three calls wrote `-d "$DESCR[N]"` unbraced.
    That is `$DESCR` — element 0 of the array, unset — followed by the literal
    `[N]`, so the messages arrive as the three characters `[1]`, `[2]` and `[3]`
    with the real text dropped.

    `911`, the other half of the pair, braces all six of its references. `905`
    had the same split and was fixed on 2026-09-17 (D131); this is the same
    defect as D77 in `917`.

    The two `-1 "$?"` arguments are moot alongside it: `$?` is expanded *inside*
    the branch, where the last command is the `[` test that returned 0 to enter
    it, so the value is always the literal `0` — and `DESCR[1]` has no
    placeholder to render it into anyway."""
    run = vip.run_script(SCRIPT)

    assert own(run), run.describe()
    assert own(run)[0].text.strip() not in ("[1]", "[2]", "[3]"), own(run)[0].text


def test_help_documents_every_error_code(vip):
    res = vip.exec([vip.script_path(SCRIPT), "--help"])

    for errno in ("9121", "9122", "9123"):
        assert f"{errno} / " in res.output, res.output
