"""End-to-end tests for scripts-available/sc_40_cluster.sh.

sc_40 is three checks and a summary: is mysqld running, does a SELECT answer,
and are the Galera `wsrep_*` status variables at their expected values.

Two halves, two strategies, as PLAN.md sets out:

* **liveness and SELECT** — a real `mariadb:11` on the test network, reached
  through `~/.my.cnf`, plus a local process standing in for mysqld (the server
  is in its own container, so the *local* process check cannot see it).
* **Galera** — the client is wrapped rather than replaced: `show status like
  'wsrep_%'` is answered from the fixture, everything else goes to the real
  server. A plain MariaDB *does* carry the `wsrep_*` variables — inactive, with
  `wsrep_cluster_size 0` and `wsrep_connected OFF` — so the unhealthy path is
  real, and only the healthy one needs the wrapper.

    # UNVERIFIED SHAPE
    The `show status` rows are written from Galera's documented variable names
    and the two-column `Variable_name  Value` layout `mysql` prints; no capture
    from a real Galera node exists in this repo. The script reads column 2 of
    each row, which is the part that matters.
"""

from __future__ import annotations

import pytest

from conftest import MARIADB_DATABASE, MARIADB_ROOT_PASSWORD

SCRIPT = "sc_40_cluster.sh"
TABLE = "CertificateData"

pytestmark = pytest.mark.slow

HEALTHY_WSREP = {
    "wsrep_cluster_size": "3",
    "wsrep_cluster_status": "Primary",
    "wsrep_connected": "ON",
    "wsrep_local_recv_queue_avg": "0.1",
}

CLUSTER_CHECKS = [
    ("wsrep_cluster_size", "3", "!="),
    ("wsrep_cluster_status", "Primary", "!="),
    ("wsrep_connected", "ON", "!="),
    ("wsrep_local_recv_queue_avg", "0.4", ">"),
]


def mariadb_config(*, mysql_bin: str = "/usr/local/bin/mysql",
                   database: str = MARIADB_DATABASE, table: str = TABLE) -> str:
    """config/mariadb.conf — where the database settings actually live.

    `sc_40` sources it with `getconfig "mariadb"` *after* its own config, so
    these win over anything set in `config/40.conf`. Same arrangement as `sc_18`
    and `sc_32`. Before the D38 fix `sc_40` never sourced it at all, which is
    why the SELECT ran an empty pipeline."""
    return (
        "# generated by test_sc_40_cluster.py\n"
        f"MYSQL_BIN={mysql_bin}\n"
        f"DB_NAME={database}\n"
        f"DB_TEST_TABLE={table}\n"
    )


def config(*, procname: str = "/usr/local/bin/mysqld",
           pidfile: str = "/no/such/mysqld.pid",
           cluster_checks=CLUSTER_CHECKS) -> str:
    lines = [
        "# generated by test_sc_40_cluster.py\n",
        "SCRIPTNAME=check_mysql\n",
        f"pidfile={pidfile}\n",
        f"procname={procname}\n",
    ]
    for i, (name, result, operand) in enumerate(cluster_checks):
        lines.append(f'CLUSTER[{i}]="{name}"\n')
        lines.append(f'RESULT[{i}]="{result}"\n')
        lines.append(f'OPERAND[{i}]="{operand}"\n')
    return "".join(lines)


def wsrep_wrapper(values: dict) -> str:
    """A client that answers wsrep status queries and passes the rest on.

    Installed as `/usr/local/bin/mysql` and pointed at by `MYSQL_BIN`, so both
    `sc_40`'s SELECT and its `show status` go through it — the script uses
    `$MYSQL_BIN` for both since 2026-09-16.
    """
    cases = "".join(
        f"    *{name}*) printf '%s\\t%s\\n' 'Variable_name' 'Value' ; "
        f"printf '%s\\t%s\\n' '{name}' '{value}' ; exit 0 ;;\n"
        for name, value in values.items()
    )
    return (
        "#!/bin/bash\n"
        "QUERY=$(cat)\n"
        'case "$QUERY" in\n'
        "  *wsrep*)\n"
        '    case "$QUERY" in\n'
        f"{cases}"
        "      *) exit 0 ;;\n"
        "    esac\n"
        "    ;;\n"
        "esac\n"
        'printf "%s" "$QUERY" | /usr/bin/mariadb "$@"\n'
    )


@pytest.fixture
def cluster(syscheck, mariadb_node):
    """sc_40 against the shared MariaDB, with mysqld running locally."""
    syscheck.write_file(
        "/root/.my.cnf",
        f"[client]\nhost={mariadb_node}\nuser=root\npassword={MARIADB_ROOT_PASSWORD}\n",
    )
    syscheck.exec([
        "mariadb", "-h", mariadb_node, "-uroot", f"-p{MARIADB_ROOT_PASSWORD}",
        MARIADB_DATABASE, "-e",
        f"CREATE TABLE IF NOT EXISTS {TABLE} (fingerprint VARCHAR(64) PRIMARY KEY)",
    ]).check()
    syscheck.start_process("mysqld")
    syscheck.install_fake_bin("mysql", wsrep_wrapper(HEALTHY_WSREP))
    syscheck.set_script_config("mariadb", mariadb_config())
    syscheck.set_script_config("40", config())
    return syscheck


def messages_by_errno(run, errno):
    return [m for m in run.messages if m.errno == errno]


def test_a_healthy_node_reports_every_check_ok(cluster):
    run = cluster.run_script(SCRIPT)

    assert len(run.messages) == 7, run.describe()   # liveness, select, 4 cluster, summary
    assert run.errnos == ["401", "403", "405", "405", "405", "405", "407"], run.describe()
    assert run.levels == ["I"] * 7, run.describe()


def test_a_stopped_mysqld_is_reported_and_counted(cluster):
    """The local process check — nothing named mysqld is running."""
    cluster.kill_stray_processes()

    run = cluster.run_script(SCRIPT)

    assert messages_by_errno(run, "402"), run.describe()
    summary = run.messages[-1]
    assert summary.errno == "408", run.describe()
    assert "number of errors detected: 1" in summary.text, summary.text


def test_a_select_that_fails_is_reported_and_counted(cluster):
    """The table is gone: the server answers, the query does not."""
    cluster.set_script_config("mariadb", mariadb_config(table="NoSuchTable"))

    run = cluster.run_script(SCRIPT)

    assert messages_by_errno(run, "404"), run.describe()
    assert run.messages[-1].errno == "408", run.describe()


def test_an_unreachable_server_fails_the_select(cluster):
    cluster.write_file("/root/.my.cnf", "[client]\nhost=no-such-database-host\n")

    run = cluster.run_script(SCRIPT)

    assert messages_by_errno(run, "404"), run.describe()


@pytest.mark.parametrize("variable, bad_value", [
    ("wsrep_cluster_size", "2"),
    ("wsrep_local_recv_queue_avg", "1.5"),
])
def test_a_numeric_cluster_variable_at_a_bad_value_is_an_error(cluster, variable, bad_value):
    """One variable off its expected value at a time, so a check that only ever
    looked at the first one would be caught. Only the two numeric variables are
    here — the string ones cannot be detected at all, see D39."""
    values = dict(HEALTHY_WSREP, **{variable: bad_value})
    cluster.install_fake_bin("mysql", wsrep_wrapper(values))

    run = cluster.run_script(SCRIPT)

    failed = messages_by_errno(run, "406")
    assert len(failed) == 1, run.describe()
    assert variable in failed[0].text, failed[0].text
    assert bad_value in failed[0].text, failed[0].text


def test_the_queue_average_is_compared_as_a_number_not_a_string(cluster):
    """`wsrep_local_recv_queue_avg` is the one check with a `>` operand, and the
    values are decimals: 0.10 is under the 0.4 limit and 1.5 is over it, which
    string comparison would get backwards."""
    cluster.install_fake_bin("mysql", wsrep_wrapper(
        dict(HEALTHY_WSREP, wsrep_local_recv_queue_avg="0.39")))
    assert not messages_by_errno(cluster.run_script(SCRIPT), "406")

    cluster.install_fake_bin("mysql", wsrep_wrapper(
        dict(HEALTHY_WSREP, wsrep_local_recv_queue_avg="0.41")))
    assert messages_by_errno(cluster.run_script(SCRIPT), "406")


def test_an_inactive_cluster_on_a_real_server_is_reported(cluster):
    """No wrapper: the real MariaDB answers. It is not part of a cluster, and it
    reports that honestly — `wsrep_cluster_size 0`, `wsrep_cluster_status
    Disconnected`, `wsrep_connected OFF`, and no value at all for the queue
    average. This is what a host whose cluster stack failed to start looks like.

    All four are now caught. Before the D39 fix only two were: the size, by a
    numeric comparison, and the queue average, by the empty-value guard. The two
    *string* variables — the ones that actually say the cluster is
    disconnected — were reported OK, because `Sub_Compare` fed them to awk as
    bare words, where they became uninitialised **variables** and every string
    comparison reduced to `"" != ""`."""
    cluster.set_script_config("mariadb", mariadb_config(mysql_bin="/usr/bin/mariadb"))

    run = cluster.run_script(SCRIPT)

    failed = [m.text for m in messages_by_errno(run, "406")]
    assert len(failed) == 4, run.describe()
    assert any("wsrep_cluster_size 0" in text for text in failed), failed
    assert any("wsrep_cluster_status Disconnected" in text for text in failed), failed
    assert any("wsrep_connected OFF" in text for text in failed), failed


def test_no_configured_cluster_variables_still_reports_the_other_checks(cluster):
    cluster.set_script_config("40", config(cluster_checks=[]))

    run = cluster.run_script(SCRIPT)

    assert run.errnos == ["401", "403", "407"], run.describe()


def test_the_summary_counts_every_failure(cluster):
    """The summary is the message an operator watches: it has to add up. Three
    failures here — mysqld down, the SELECT failing, and the cluster size wrong
    — and all three are of the kinds this script can actually detect."""
    cluster.kill_stray_processes()
    cluster.set_script_config("mariadb", mariadb_config(table="NoSuchTable"))
    cluster.install_fake_bin("mysql", wsrep_wrapper(
        dict(HEALTHY_WSREP, wsrep_cluster_size="1")))

    run = cluster.run_script(SCRIPT)

    summary = run.messages[-1]
    assert summary.errno == "408", run.describe()
    assert "number of errors detected: 3" in summary.text, summary.text


def test_the_summary_is_submitted_under_index_00(cluster):
    """Deliberate, unlike the D29 cases: sc_40 sets `SCRIPTINDEX=00` explicitly
    for its summary, so index 00 is this script's "whole check" service and the
    numbered indexes are its parts."""
    run = cluster.run_script(SCRIPT)

    assert run.indexes == ["01", "02", "03", "04", "05", "06", "00"], run.describe()


def test_help_documents_every_error_code(cluster):
    res = cluster.exec([cluster.script_path(SCRIPT), "--help"])

    for errno in ("401", "402", "403", "404", "405", "406", "407", "408"):
        assert f"{errno} / " in res.output, res.output


def test_the_select_check_cannot_pass_without_a_database(cluster):
    """`config/40.conf` defines neither `MYSQL_BIN` nor `DB_NAME` nor
    `DB_TEST_TABLE` — those live in `config/mariadb.conf` — and `sc_40`, unlike
    the ten other database scripts, never called `getconfig "mariadb"`. So the
    SELECT expanded to

        echo "SELECT * FROM  LIMIT 1" |  2>&1 > /dev/null

    a pipeline whose right-hand side is nothing but redirections. Bash opens
    them and exits **0**, so the check reported "mysql is running and answering"
    having run no query against no database, on a host with no MySQL at all.

    Fixed by adding `getconfig "mariadb"` after `initscript`, as `sc_18` does.
    A guard was added alongside it: if any of the three settings is still empty
    the check reports a configuration error rather than running an empty
    pipeline, so this cannot silently return to passing."""
    shipped = cluster.read_file("/src/config/40.conf")
    cluster.set_script_config("40", shipped)
    cluster.set_script_config("mariadb", cluster.read_file("/src/config/mariadb.conf"))
    cluster.write_file("/root/.my.cnf", "[client]\nhost=no-such-database-host\n")

    run = cluster.run_script(SCRIPT)

    assert not messages_by_errno(run, "403"), run.describe()


def test_an_unset_database_setting_is_reported_as_a_config_error(cluster):
    """The guardrail behind the D38 fix. With `MYSQL_BIN`, `DB_NAME` and
    `DB_TEST_TABLE` all empty the check must say so, not run an empty pipeline
    that exits 0."""
    cluster.set_script_config("mariadb", "MYSQL_BIN=\nDB_NAME=\nDB_TEST_TABLE=\n")
    cluster.set_script_config("40", "pidfile=/nonexistent\nprocname=nosuchproc\n")

    run = cluster.run_script(SCRIPT)

    assert messages_by_errno(run, "404"), run.describe()
    assert not messages_by_errno(run, "403"), run.describe()


@pytest.mark.parametrize("variable, bad_value", [
    ("wsrep_cluster_status", "Disconnected"),
    ("wsrep_connected", "OFF"),
])
def test_a_string_cluster_variable_at_a_bad_value_is_an_error(cluster, variable, bad_value):
    """The comparison is built by string interpolation into awk:

        Sub_Compare()( IFS=" " ; exec awk "BEGIN{ if (!($*)) exit(1)}" )
        Sub_Compare "${STATUS} ${OPERAND} ${RESULT}"

    With numbers that works. With strings the operands arrive as *bare words*,
    which awk reads as uninitialized variables — both empty, therefore equal —
    so `Disconnected != Primary` is false and the check reports OK.

    Two of the four shipped cluster checks are string-valued, and they are the
    two that say whether the node is actually in the cluster:
    `wsrep_cluster_status` and `wsrep_connected`. Neither can ever fail, on any
    host, whatever the cluster is doing.

    Quoting the operands fixes the string case but breaks the numeric one —
    `"0.39" > "0.4"` is true as strings — so the fix has to pick a comparison
    per type rather than just add quotes."""
    values = dict(HEALTHY_WSREP, **{variable: bad_value})
    cluster.install_fake_bin("mysql", wsrep_wrapper(values))

    run = cluster.run_script(SCRIPT)

    failed = messages_by_errno(run, "406")
    assert len(failed) == 1, run.describe()
    assert variable in failed[0].text, failed[0].text
