"""End-to-end tests for scripts-available/sc_03_memory-usage.sh.

The script reads `free`, so the thresholds can only be driven from both sides by
replacing `free` with a fake that prints a chosen total/used pair. The fixture
output is shaped like real `free(1)` from procps-ng — header row, `Mem:` row,
`Swap:` row — because the script picks columns out of it with
`grep Mem | awk '{print $2}'`, and a fixture with a different column layout would
only prove the script parses our invention.

One case deliberately uses the container's real `free`, so the parse is pinned
against genuine output too.
"""

from __future__ import annotations

import pytest

SCRIPT = "sc_03_memory-usage.sh"

# a plausible 16 GiB / 2 GiB host, in the kB units free(1) reports by default
MEM_TOTAL = 16316280
SWAP_TOTAL = 2097148


def free_output(mem_total: int, mem_used: int,
                swap_total: int, swap_used: int) -> str:
    """One `free` report, laid out exactly as procps-ng prints it."""
    mem_free = max(mem_total - mem_used, 0)
    swap_free = max(swap_total - swap_used, 0)
    return (
        "               total        used        free      shared  buff/cache   available\n"
        f"Mem:      {mem_total:12d}{mem_used:12d}{mem_free:12d}       12345     1800000{mem_total - mem_used:12d}\n"
        f"Swap:     {swap_total:12d}{swap_used:12d}{swap_free:12d}\n"
    )


def config(mem_percent: int = 80, swap_percent: int = 50,
           human_readable: int = 0) -> str:
    return (
        "# generated by test_sc_03_memory_usage.py\n"
        f"HUMAN_READABLE={human_readable}\n"
        f"MEM_PERCENT={mem_percent}\n"
        f"SWAP_PERCENT={swap_percent}\n"
    )


@pytest.fixture
def mem(syscheck):
    """sc_03 with a fake `free` under the test's control."""

    def set_free(mem_used: int, swap_used: int, *,
                 mem_total: int = MEM_TOTAL, swap_total: int = SWAP_TOTAL) -> None:
        body = "cat <<'EOT'\n" + free_output(mem_total, mem_used, swap_total, swap_used) + "EOT\n"
        syscheck.install_fake_bin("free", body)

    syscheck.set_free = set_free
    syscheck.set_script_config("03", config())
    return syscheck


def percent_of(total: int, percent: int) -> int:
    """The limit the script computes, by the same integer arithmetic it uses."""
    return total * percent // 100


def test_usage_below_both_limits_reports_two_info_messages(mem):
    mem.set_free(mem_used=percent_of(MEM_TOTAL, 10), swap_used=0)

    run = mem.run_script(SCRIPT)

    assert len(run.messages) == 2, run.describe()
    memory, swap = run.messages
    assert (memory.level, memory.errno, memory.index) == ("I", "032", "01")
    assert (swap.level, swap.errno, swap.index) == ("I", "034", "02")


def test_memory_above_its_limit_is_an_error_and_swap_is_still_reported(mem):
    mem.set_free(mem_used=percent_of(MEM_TOTAL, 95), swap_used=0)

    run = mem.run_script(SCRIPT)

    assert len(run.messages) == 2, run.describe()
    memory, swap = run.messages
    assert (memory.level, memory.errno) == ("E", "031"), run.describe()
    assert (swap.level, swap.errno) == ("I", "034")


def test_swap_above_its_limit_is_an_error_and_memory_is_still_reported(mem):
    mem.set_free(mem_used=percent_of(MEM_TOTAL, 10),
                 swap_used=percent_of(SWAP_TOTAL, 80))

    run = mem.run_script(SCRIPT)

    assert len(run.messages) == 2, run.describe()
    memory, swap = run.messages
    assert (memory.level, memory.errno) == ("I", "032")
    assert (swap.level, swap.errno) == ("E", "033"), run.describe()


def test_both_over_the_limit_are_reported_independently(mem):
    mem.set_free(mem_used=percent_of(MEM_TOTAL, 95),
                 swap_used=percent_of(SWAP_TOTAL, 90))

    run = mem.run_script(SCRIPT)

    assert run.levels == ["E", "E"], run.describe()
    assert run.errnos == ["031", "033"]


def test_usage_exactly_at_the_limit_is_not_an_error(mem):
    """`-gt`, not `-ge`: a host sitting exactly on 80% is inside the limit.
    Pinned because moving it would page an operator for a threshold they set."""
    mem.set_free(mem_used=percent_of(MEM_TOTAL, 80),
                 swap_used=percent_of(SWAP_TOTAL, 50))

    run = mem.run_script(SCRIPT)

    assert run.levels == ["I", "I"], run.describe()


def test_one_kilobyte_over_the_limit_is_an_error(mem):
    """The other side of the same boundary."""
    mem.set_free(mem_used=percent_of(MEM_TOTAL, 80) + 1,
                 swap_used=percent_of(SWAP_TOTAL, 50) + 1)

    run = mem.run_script(SCRIPT)

    assert run.levels == ["E", "E"], run.describe()


def test_the_configured_percentages_are_what_decides(mem):
    """Same usage, two configs: 30% of memory is fine at MEM_PERCENT=80 and an
    error at MEM_PERCENT=20."""
    used = percent_of(MEM_TOTAL, 30)
    mem.set_free(mem_used=used, swap_used=0)

    mem.set_script_config("03", config(mem_percent=80))
    assert mem.run_script(SCRIPT).messages[0].level == "I"

    mem.set_script_config("03", config(mem_percent=20))
    run = mem.run_script(SCRIPT)
    assert run.messages[0].level == "E", run.describe()


def test_missing_config_falls_back_to_defaults(mem):
    # If MEM_PERCENT and SWAP_PERCENT are omitted, they should fall back to 80 and 50 respectively.
    # Set usage to 70% memory (below default 80% limit) and 40% swap (below default 50% limit)
    mem_used = percent_of(MEM_TOTAL, 70)
    swap_used = percent_of(SWAP_TOTAL, 40)
    mem.set_free(mem_used=mem_used, swap_used=swap_used)

    # Write a config file with HUMAN_READABLE=0 but NO MEM_PERCENT or SWAP_PERCENT
    mem.set_script_config("03", "HUMAN_READABLE=0\n")

    run = mem.run_script(SCRIPT)
    # Should report healthy (I) because 70% < 80% and 40% < 50%
    assert run.levels == ["I", "I"], run.describe()

    # If usage is 85% memory, it should report error (E)
    mem_used_high = percent_of(MEM_TOTAL, 85)
    mem.set_free(mem_used=mem_used_high, swap_used=swap_used)
    run = mem.run_script(SCRIPT)
    assert run.levels == ["E", "I"], run.describe()


def test_kilobyte_output_carries_the_raw_numbers_and_the_kb_suffix(mem):
    """With HUMAN_READABLE=0 the message must state the kB figures the operator
    would see in `free`, and lang/03.english appends " KB" to both."""
    used = percent_of(MEM_TOTAL, 10)
    limit = percent_of(MEM_TOTAL, 80)
    mem.set_script_config("03", config(human_readable=0))
    mem.set_free(mem_used=used, swap_used=0)

    memory = mem.run_script(SCRIPT).messages[0]

    assert f"{used} KB" in memory.text, memory.text
    assert f"{limit} KB" in memory.text, memory.text


def test_human_readable_output_is_the_same_numbers_scaled(mem):
    """With HUMAN_READABLE=1 the numbers go through `numfmt --to=iec-i`, and the
    " KB" suffix must not come along — the unit is in the value now."""
    used = percent_of(MEM_TOTAL, 10)
    limit = percent_of(MEM_TOTAL, 80)
    mem.set_script_config("03", config(human_readable=1))
    mem.set_free(mem_used=used, swap_used=0)

    expected_used = mem.exec(f"numfmt --from-unit=Ki --to=iec-i {used}").check().stdout.strip()
    expected_limit = mem.exec(f"numfmt --from-unit=Ki --to=iec-i {limit}").check().stdout.strip()

    memory = mem.run_script(SCRIPT).messages[0]

    assert expected_used in memory.text, memory.text
    assert expected_limit in memory.text, memory.text
    assert "KB" not in memory.text, memory.text


def test_human_readable_falls_back_to_kb_when_numfmt_missing(mem):
    # Temporarily rename numfmt to make it missing
    mem.exec("mv /usr/bin/numfmt /usr/bin/numfmt.bak").check()
    try:
        # Set HUMAN_READABLE=1
        mem.set_script_config("03", config(human_readable=1))

        used = percent_of(MEM_TOTAL, 10)
        limit = percent_of(MEM_TOTAL, 80)
        mem.set_free(mem_used=used, swap_used=0)

        run = mem.run_script(SCRIPT)

        # Verify it fell back to KB output and included the " KB" suffix
        memory = run.messages[0]
        assert f"{used} KB" in memory.text, memory.text
        assert f"{limit} KB" in memory.text, memory.text
        assert "KB" in memory.text, memory.text

    finally:
        # Restore numfmt
        mem.exec("mv /usr/bin/numfmt.bak /usr/bin/numfmt").check()


def test_a_host_without_swap_is_not_reported_as_over_its_swap_limit(mem):
    """Containers and many appliances run with no swap at all, so `free` reports
    a total of 0. 0 used against a limit of 0 is not an error, and nothing may
    divide by the total."""
    mem.set_free(mem_used=percent_of(MEM_TOTAL, 10), swap_used=0,
                 swap_total=0)

    run = mem.run_script(SCRIPT)

    assert len(run.messages) == 2, run.describe()
    swap = run.messages[1]
    assert (swap.level, swap.errno) == ("I", "034"), run.describe()


def test_the_real_free_on_this_host_is_parsed(mem):
    """No fake binary: proves the column layout the fixtures use is the layout
    the script actually meets, which is the only thing the fixtures cannot."""
    mem.exec("rm -f /usr/local/bin/free")

    run = mem.run_script(SCRIPT)

    assert len(run.messages) == 2, run.describe()
    assert run.errnos[0] in ("031", "032")
    assert run.errnos[1] in ("033", "034")
    for message in run.messages:
        numbers = [word for word in message.text.replace("(", " ").replace(":", " ").split()
                   if word.isdigit()]
        assert numbers, f"no usage figure in {message.text!r}"


def test_every_run_reports_memory_and_swap_exactly_once(mem):
    """Two checks, two indexes, every time — the guard against the index and
    argument shifting that made sc_01 and sc_41 emit extra messages."""
    mem.set_free(mem_used=percent_of(MEM_TOTAL, 95), swap_used=0)

    run = mem.run_script(SCRIPT)

    assert run.indexes == ["01", "02"], run.describe()


def test_help_documents_every_error_code(mem):
    res = mem.exec([mem.script_path(SCRIPT), "--help"])

    for errno in ("031", "032", "033", "034", "035"):
        assert f"{errno} / " in res.output, res.output


def test_a_failing_free_is_not_reported_as_healthy(mem):
    """If `free` cannot be run the script must not claim the limits are fine."""
    mem.install_fake_bin("free", "echo 'free: command failed' >&2\nexit 1\n")

    run = mem.run_script(SCRIPT)

    assert "I" not in run.levels, run.describe()


def test_a_failing_free_is_reported_as_a_measurement_failure(mem):
    """The regression guard for D24. With `free` broken every figure is the
    empty string, so the test became `[ -gt ]` — a single non-empty argument,
    which `[` reports as true. Both checks took the *error* arm and paged an
    operator with

        ERROR - memoryusage Memory limit exceded (Memory usage is  KB: Limit is  KB)

    A breach that states neither the usage nor the limit was never measured, and
    the two cases need opposite responses: a real breach is a capacity problem
    on this host, an unreadable `free` is a broken check."""
    mem.install_fake_bin("free", "echo 'free: command failed' >&2\nexit 1\n")

    run = mem.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "035"), run.describe()


def test_a_free_that_prints_nothing_usable_is_a_measurement_failure(mem):
    """The other shape of the same fault: `free` runs and exits 0, but its
    output has no figures in it — a busybox `free`, or a wrapper that printed a
    warning instead."""
    mem.install_fake_bin("free", "echo 'Mem: unavailable unavailable'\n")

    run = mem.run_script(SCRIPT)

    assert run.only().errno == "035", run.describe()
