"""End-to-end tests for related-available/929_filter_syscheck_messages.sh.

`929` is the first stage of syscheck's outbound pipeline: it reduces
`var/last_status` — the latest result of every check — to just the script IDs a
remote monitoring host should see, writing `var/last_status_filtered` for `930`
to ship.

REAL-OS: a crafted `last_status` and the real `egrep`. Nothing is mocked; the
filter either selects the right lines or it does not.

The shipped `SEND_ONLY_SCRIPT_IDS` is `"01 03 06 17 31"` — disk, memory, RAID,
NTP and HP health — so the question these tests ask is whether exactly those
survive and nothing else does.
"""

from __future__ import annotations

import pytest

SCRIPT = "related-available/929_filter_syscheck_messages.sh"
LOCAL = "/opt/syscheck/var/last_status"
FILTERED = "/opt/syscheck/var/last_status_filtered"

pytestmark = pytest.mark.slow


def config(*, ids: str = "01 03 06 17 31") -> str:
    return ("# generated by test_929_filter_syscheck_messages.py\n"
            f"LOCAL_FILE={LOCAL}\n"
            f"FILTERED_FILE={FILTERED}\n"
            f'SEND_ONLY_SCRIPT_IDS="{ids}"\n')


def status_line(scriptid: str, index: str = "01", level: str = "I",
                text: str = "check ok") -> str:
    """One line in the shape `printlogmess` writes to `var/last_status`."""
    return (f"{scriptid}-{index}-{level}-{scriptid}1-PKI 20260917 06:00:00 "
            f"host: INFO - {text}")


@pytest.fixture
def filt(syscheck):
    syscheck.exec(f"rm -f {FILTERED}").check()
    syscheck.write_file(LOCAL, "\n".join([
        status_line("01", text="diskusage ok"),
        status_line("02", text="ejbca ok"),
        status_line("03", text="memory ok"),
        status_line("17", text="ntp ok"),
        status_line("42", text="receipts ok"),
    ]) + "\n")
    syscheck.set_script_config("929", config())
    return syscheck


def own(run) -> list:
    return [m for m in run.messages if m.scriptid == "929"]


def filtered_ids(sc) -> list[str]:
    if not sc.file_exists(FILTERED):
        return []
    return [l.split("-")[0] for l in sc.read_file(FILTERED).splitlines() if l.strip()]


# --- the filter -------------------------------------------------------------

def test_configured_script_ids_survive(filt):
    filt.run_script(SCRIPT)

    assert "01" in filtered_ids(filt), filtered_ids(filt)
    assert "03" in filtered_ids(filt), filtered_ids(filt)
    assert "17" in filtered_ids(filt), filtered_ids(filt)


def test_unconfigured_script_ids_are_dropped(filt):
    """The point of the script. D138, fixed 2026-09-17.

    See the test below for the mechanism. The fixture here is an ordinary
    `last_status`: five checks, all reporting at `SCRIPTINDEX` 01, which is what
    a single-instance check writes. With `SEND_ONLY_SCRIPT_IDS="01 03 06 17 31"`
    the unanchored `(01|03|06|17|31)-` matches the `-01-` index field in **every
    one of them**, so all five survive — including `02` and `42`, which were
    never configured.

    So on a typical host the filter passes essentially everything, and `930`
    ships the unfiltered status to whoever was supposed to see a subset."""
    filt.run_script(SCRIPT)

    assert "02" not in filtered_ids(filt), filtered_ids(filt)
    assert "42" not in filtered_ids(filt), filtered_ids(filt)


def test_the_whole_line_is_preserved(filt):
    """`930` ships this file onward verbatim, so the lines have to survive
    intact rather than being reduced to ids."""
    filt.run_script(SCRIPT)

    body = filt.read_file(FILTERED)
    assert "diskusage ok" in body, body
    assert "20260917 06:00:00" in body, body


def test_a_single_configured_id_works(filt):
    """Driven with an id that appears in no index field, so it isolates the
    script-id match from D138's index collision."""
    filt.set_script_config("929", config(ids="42"))

    filt.run_script(SCRIPT)

    assert filtered_ids(filt) == ["42"], filtered_ids(filt)


def test_a_successful_filter_is_reported(filt):
    run = filt.run_script(SCRIPT)

    msg = own(run)[0]
    assert (msg.level, msg.errno) == ("I", "9291"), run.describe()


def test_a_missing_input_file_is_reported(filt):
    filt.exec(f"rm -f {LOCAL}").check()

    run = filt.run_script(SCRIPT)

    assert own(run)[0].errno == "9292", run.describe()


# --- known defects ----------------------------------------------------------

def test_it_can_run_twice(filt):
    """D137, fixed 2026-09-17. `929` used to write its output with

        egrep "(${SEND_ONLY_SCRIPT_IDS_FMT})-" ${LOCAL_FILE} > ${FILTERED_FILE}

    to a fixed path, and `initscript` sets `noclobber`
    (`lib/libsyscheck.sh:56`). The second run could not overwrite what the first
    left behind:

        var/last_status_filtered: cannot overwrite existing file

    So `929` worked exactly once after installation. Every run after that
    reported `ERRNO[2]` and left the *first* run's file in place, which `930`
    then dutifully shipped onward — a monitoring host receiving a snapshot hours
    or days old while the local check reported a failure nobody was reading.

    Same defect as D85 in `933` and the marker write in `911`. Those took the
    one-line `set +o noclobber`; this one did not, because the redirect
    truncates its target *before* `egrep` runs, so simply allowing the overwrite
    would mean any failed run left an **empty** file for `930` to ship. Stale
    data looks wrong to a human; empty data looks like nothing is failing.

    `929` now builds into `mktemp` and `mv`s into place only on success, which
    is both atomic and unaffected by `noclobber` — `mv` is not a redirect."""
    filt.run_script(SCRIPT)
    assert filtered_ids(filt)

    run = filt.run_script(SCRIPT)

    assert own(run)[0].errno == "9291", run.describe()


def test_the_filter_matches_the_script_id_not_the_index(filt):
    """D138, fixed 2026-09-17. The pattern was built as `(01|03|06|17|31)-` and
    applied with no anchor, so it matched anywhere in the line — including the
    `SCRIPTINDEX` field that follows the script id.

    A message from script `99` at index `01` therefore survived a filter
    configured for `01 03 06 17 31`:

        99-01-I-991-PKI 20260917 ... INFO - unrelated check

    The leak was silent and, with the shipped `SEND_ONLY_SCRIPT_IDS`, close to
    total: `01` is the index almost every single-instance check reports at, so
    the filter passed nearly the whole file. Fixed by anchoring with `^`.

    This test isolates the mechanism with one line;
    `test_unconfigured_script_ids_are_dropped` shows the practical effect on an
    ordinary `last_status`."""
    filt.write_file(LOCAL, status_line("99", index="01", text="unrelated") + "\n")

    filt.run_script(SCRIPT)

    assert "99" not in filtered_ids(filt), filtered_ids(filt)


def test_matching_nothing_is_not_an_error(filt):
    """D139, fixed 2026-09-17. `egrep` exits 1 when no line matches, and `929`
    used to grade that `ERRNO[2]`, "Filter failed".

    But matching nothing is a legitimate state — a `last_status` holding only
    checks nobody asked to forward. The script could not tell "the filter broke"
    from "there was nothing to forward", the same conflation as D74 in `908`.

    It matters here because the result feeds `930`: an empty filtered file is a
    correct thing to ship, and an error is not.

    Measured exit codes: 0 matched, 1 no match, 2 a real error. The three are
    now graded separately, with `ERRNO[3]` added for the middle case rather than
    folding it into success — an empty result is informational, and worth being
    able to see when `SEND_ONLY_SCRIPT_IDS` has been mistyped into selecting
    nothing."""
    filt.write_file(LOCAL, status_line("99", index="99", text="unrelated") + "\n")

    run = filt.run_script(SCRIPT)

    msg = own(run)[0]
    assert (msg.level, msg.errno) == ("I", "9293"), run.describe()


def test_matching_nothing_names_the_configured_ids(filt):
    """`DESCR[3]` carries the configured list, so an operator seeing this
    repeatedly can tell at a glance whether the ids are the ones they meant."""
    filt.write_file(LOCAL, status_line("99", index="99", text="unrelated") + "\n")

    run = filt.run_script(SCRIPT)

    assert "01 03 06 17 31" in own(run)[0].text, own(run)[0].text


def test_matching_nothing_still_writes_an_empty_filtered_file(filt):
    """`930` ships whatever is there. After a quiet period that must be an
    empty file, not the previous run's contents — otherwise a monitoring host
    keeps receiving messages that are no longer current."""
    filt.run_script(SCRIPT)
    assert filtered_ids(filt)

    filt.write_file(LOCAL, status_line("99", index="99", text="unrelated") + "\n")
    filt.run_script(SCRIPT)

    assert filtered_ids(filt) == [], filtered_ids(filt)


def test_a_failed_run_leaves_the_previous_file_intact(filt):
    """The property the temp file exists for. A shell redirect truncates before
    the command runs, so writing straight to `FILTERED_FILE` would empty it the
    moment `egrep` failed — and `930` would ship that empty file as though
    nothing were wrong.

    Building into `mktemp` and moving on success means a failed run changes
    nothing, so `930` keeps shipping the last good snapshot."""
    filt.run_script(SCRIPT)
    before = filt.read_file(FILTERED)
    assert before.strip()

    filt.exec(f"rm -f {LOCAL}").check()
    run = filt.run_script(SCRIPT)

    assert own(run)[0].errno == "9292", run.describe()
    assert filt.read_file(FILTERED) == before, "the previous filtered file was lost"


def test_a_failed_run_leaves_no_temporary_file_behind(filt):
    filt.exec(f"rm -f {LOCAL}").check()

    filt.run_script(SCRIPT)

    res = filt.exec(f"ls -1 {FILTERED}.* 2>/dev/null | wc -l")
    assert res.stdout.strip() == "0", res.output


def test_help_documents_every_error_code(filt):
    res = filt.exec([filt.script_path(SCRIPT), "--help"])

    for errno in ("9291", "9292", "9293"):
        assert f"{errno} / " in res.output, res.output
