"""End-to-end tests for related-available/922-simple-database-replication-check.sh.

`922` writes a timestamp into a scratch table, waits a second, then reads the
value back from two nodes and compares them. It is a liveness test for
replication rather than a consistency check — `sc_32_check_db_sync.sh` is the
one that compares real data.

REAL-SVC: real `mariadb:11` containers. There is no replication between them, so
the two outcomes are produced structurally: pointing both `HOSTNAME_NODE1` and
`HOSTNAME_NODE2` at the *same* container is what "replicated" looks like to
`922`, and pointing them at two independent containers is what divergence looks
like. That is a fair substitute here precisely because `922` only ever compares
two `SELECT` results.

The script writes with no `-h`, so the node it writes to is chosen by
`~/.my.cnf`; the two reads are explicit.

Note the filename: `922-simple-database-replication-check.sh` uses hyphens where
every other script in the tree uses an underscore after the number.
"""

from __future__ import annotations

import pytest

from conftest import MARIADB_DATABASE, MARIADB_ROOT_PASSWORD
from syscheck_harness import start_mariadb_node

SCRIPT = "related-available/922-simple-database-replication-check.sh"
DB_USER = "ejbca"
DB_PASSWORD = "foo123"

pytestmark = pytest.mark.slow


@pytest.fixture(scope="module")
def two_nodes(syscheck_image, syscheck_network):
    started = []
    try:
        for _ in range(2):
            tc, name = start_mariadb_node(syscheck_network,
                                          root_password=MARIADB_ROOT_PASSWORD,
                                          database=MARIADB_DATABASE,
                                          user=DB_USER, password=DB_PASSWORD)
            started.append((tc, name))
        yield [name for _, name in started]
    finally:
        for tc, _ in started:
            tc.stop()


def mariadb_config() -> str:
    return ("# generated by test_922_simple_database_replication_check.py\n"
            f"DB_NAME={MARIADB_DATABASE}\n"
            f"DB_USER={DB_USER}\n"
            f'DB_PASSWORD="{DB_PASSWORD}"\n'
            f'MYSQLROOT_PASSWORD="{MARIADB_ROOT_PASSWORD}"\n'
            "MYSQL_BIN=/usr/bin/mariadb\n")


@pytest.fixture
def repl(syscheck, two_nodes):
    node1, node2 = two_nodes
    syscheck.write_file("/root/.my.cnf", f"[client]\nhost={node1}\n")
    syscheck.set_script_config("mariadb", mariadb_config())
    syscheck.nodes = two_nodes

    def point_at(n1: str, n2: str) -> None:
        syscheck.set_script_config("922", "# generated by test_922\n"
                                          f"HOSTNAME_NODE1={n1}\n"
                                          f"HOSTNAME_NODE2={n2}\n")

    point_at(node1, node1)
    syscheck.point_at = point_at
    return syscheck


def own(run) -> list:
    return [m for m in run.messages if m.scriptid == "922"]


# --- the two outcomes -------------------------------------------------------

def test_matching_values_report_replication_ok(repl):
    """Both names resolve to one server, so the value written is the value read
    twice — indistinguishable to `922` from working replication."""
    run = repl.run_script(SCRIPT)

    assert own(run), run.describe()
    assert own(run)[0].errno == "9221", run.describe()


def test_differing_values_are_reported(repl):
    """Two independent servers with no replication between them. Node2 needs the
    scratch table already present holding an older value — without it the read
    returns nothing and `922` reports "no value from node2" instead, which is a
    different branch and the subject of the next test."""
    repl.exec(["mariadb", "-h", repl.nodes[1], "-uroot",
               f"-p{MARIADB_ROOT_PASSWORD}", MARIADB_DATABASE, "-e",
               "DROP TABLE IF EXISTS relatedtest;"
               "CREATE TABLE relatedtest (value INT);"
               "INSERT INTO relatedtest SET value='1'"]).check()
    repl.point_at(repl.nodes[0], repl.nodes[1])

    run = repl.run_script(SCRIPT)

    assert own(run), run.describe()
    assert own(run)[0].errno == "9222", run.describe()
    # DESCR[2] gained placeholders so a divergence says what the two sides held
    assert "1" in own(run)[0].text, own(run)[0].text


def test_an_unreachable_second_node_names_that_node(repl):
    """`DESCR[3]`'s placeholder carries the hostname, not the value read back —
    this branch fires because that value was empty, so printing it could only
    ever render blank."""
    repl.point_at(repl.nodes[0], "no-such-host")

    run = repl.run_script(SCRIPT)

    assert own(run), run.describe()
    assert own(run)[0].errno == "9223", run.describe()
    assert "no-such-host" in own(run)[0].text, own(run)[0].text


def test_an_unreachable_first_node_names_that_node(repl):
    repl.point_at("no-such-host", repl.nodes[0])

    run = repl.run_script(SCRIPT)

    assert own(run), run.describe()
    assert own(run)[0].errno == "9224", run.describe()
    assert "no-such-host" in own(run)[0].text, own(run)[0].text


# --- the scratch table ------------------------------------------------------

def test_the_scratch_table_holds_a_fresh_value_each_run(repl):
    """The written value is `date +%s`, so a stale table cannot make a broken
    replica look healthy — the comparison is against a value that did not exist
    before this run."""
    repl.run_script(SCRIPT)
    first = repl.exec(["mariadb", "-h", repl.nodes[0], "-uroot",
                       f"-p{MARIADB_ROOT_PASSWORD}", MARIADB_DATABASE, "-N",
                       "-e", "select value from relatedtest"]).check().stdout.strip()

    repl.exec("sleep 1")
    repl.run_script(SCRIPT)
    second = repl.exec(["mariadb", "-h", repl.nodes[0], "-uroot",
                        f"-p{MARIADB_ROOT_PASSWORD}", MARIADB_DATABASE, "-N",
                        "-e", "select value from relatedtest"]).check().stdout.strip()

    assert first != second, f"{first} == {second}"


def test_the_temporary_sql_file_is_removed(repl):
    """It is written under `$SYSCHECK_HOME/tmp/` with a fixed name. Left behind,
    `noclobber` would make the next run's `>` fail — the same trap as D85."""
    repl.run_script(SCRIPT)

    assert not repl.file_exists(f"{repl.home}/tmp/tmp_create-test-table.sql")


# --- known defect -----------------------------------------------------------

def test_messages_carry_a_level_and_an_error_number(repl):
    """D99, fixed 2026-09-17. Every call in `922` used to be spelled

        printlogmess -n ${SCRIPTNAME} -i ${SCRIPTID} -x ${SCRIPTINDEX}  $LEVEL_1 ${ERRNO[1]} -d "${DESCR[1]}"

`$LEVEL_1` through `$LEVEL_4` *are* defined, in `lang/922.english`, and
    hold the right values — `LEVEL_1=$INFO`, `LEVEL_4=$ERROR`. The fault was
    that they were passed **positionally**, with no `-l` flag, and `${ERRNO[N]}`
    likewise with no `-e`. `printlogmess` bound neither and rejected the whole
    call:

        printlogmess: bad level (-l) '', expected I, W or E

    So `922` emitted **no message at all**, in any of its four branches. Not a
    replication failure graded wrongly — nothing reaching the log, syslog or
    `last_status`. Like `914` before it was deleted, enabling `922` bought no
    monitoring whatsoever, and unlike `914` it failed loudly to stderr where
    nothing was reading.

    The trailing values were positional too. Those now use `-1`/`-2`, and the
    two "no value from nodeN" branches pass the **hostname** rather than the
    value: they fire precisely because that value came back empty, so printing
    it could only ever render blank."""
    run = repl.run_script(SCRIPT)

    assert own(run), run.describe()
    assert own(run)[0].level in ("I", "W", "E"), run.describe()
    assert own(run)[0].errno.strip() != "", run.describe()


def test_help_documents_every_error_code(repl):
    res = repl.exec([repl.script_path(SCRIPT), "--help"])

    for errno in ("9221", "9222", "9223", "9224"):
        assert f"{errno} / " in res.output, res.output
