"""End-to-end tests for related-available/933_select_from_database.sh.

`933` runs a list of configured `SELECT` statements against the database, writes
each result to its own file under `var/`, and concatenates them into a summary
file with a header per query. It is a reporting job rather than a check — the
thing to prove is that results land in the right files and that a failing query
is distinguishable from an empty one.

REAL-SVC: a real `mariadb:11` on the test network answering the real client.
Nothing is mocked. Failures are produced by breaking something real — dropping
the table, using a wrong password.

Like `sc_18`, `933` issues no `-h`, so the server it talks to is chosen by
`~/.my.cnf` rather than by its own config.
"""

from __future__ import annotations

import pytest

from conftest import MARIADB_DATABASE, MARIADB_ROOT_PASSWORD

SCRIPT = "related-available/933_select_from_database.sh"
TABLE = "CertificateData"
SUMMARY = "db_export_summary"

pytestmark = pytest.mark.slow


def mariadb_config(*, user: str = "root", password: str = MARIADB_ROOT_PASSWORD,
                   database: str = MARIADB_DATABASE) -> str:
    return ("# generated by test_933_select_from_database.py\n"
            f"DB_NAME={database}\n"
            f"DB_USER={user}\n"
            f'DB_PASSWORD="{password}"\n'
            "MYSQL_BIN=/usr/bin/mariadb\n")


def config(*queries) -> str:
    """`queries` are (desc, sql, outfile) triples."""
    lines = ["# generated by test_933_select_from_database.py\n",
             f'SQL_SUMMARY_FILE="{SUMMARY}"\n']
    for i, (desc, sql, outfile) in enumerate(queries):
        lines.append(f'SQL_DESC[{i}]="{desc}"\n')
        lines.append(f'SQL_SELECT[{i}]="{sql}"\n')
        lines.append(f'OUTFILE[{i}]="{outfile}"\n')
    return "".join(lines)


@pytest.fixture
def db(syscheck, mariadb_node):
    syscheck.write_file("/root/.my.cnf", f"[client]\nhost={mariadb_node}\n")

    def sql(statement: str) -> None:
        syscheck.exec(["mariadb", "-h", mariadb_node, "-uroot",
                       f"-p{MARIADB_ROOT_PASSWORD}", MARIADB_DATABASE,
                       "-e", statement]).check()

    sql(f"DROP TABLE IF EXISTS {TABLE}")
    sql(f"CREATE TABLE {TABLE} (username VARCHAR(64), serialNumber VARCHAR(64))")
    sql(f"INSERT INTO {TABLE} VALUES ('alice','01'),('bob','02')")

    syscheck.exec(f"rm -f {syscheck.home}/var/out_* "
                  f"{syscheck.home}/var/{SUMMARY}")
    syscheck.set_script_config("mariadb", mariadb_config())
    syscheck.set_script_config("933", config(
        ("all users", f"select username from {TABLE} order by username;", "out_users")))
    syscheck.sql = sql
    return syscheck


def var(sc, name: str) -> str:
    return sc.read_file(f"{sc.home}/var/{name}")


def own(run) -> list:
    return [m for m in run.messages if m.scriptid == "933"]


# --- results land where they should -----------------------------------------

def test_a_select_writes_its_rows_to_its_own_file(db):
    db.run_script(SCRIPT)

    assert var(db, "out_users").split() == ["alice", "bob"], var(db, "out_users")


def test_column_names_are_suppressed(db):
    """`--skip-column-names` keeps the output machine-readable — a header row
    would be indistinguishable from data to anything consuming these files."""
    db.run_script(SCRIPT)

    assert "username" not in var(db, "out_users"), var(db, "out_users")


def test_a_successful_select_is_reported_as_ok(db):
    run = db.run_script(SCRIPT)

    msg = own(run)[0]
    assert (msg.level, msg.errno) == ("I", "9331"), run.describe()


def test_the_message_names_the_query_that_ran(db):
    """`SQL_DESC` is the only human-readable handle on which query this was."""
    run = db.run_script(SCRIPT)

    assert "all users" in own(run)[0].text, run.describe()


# --- several queries --------------------------------------------------------

def test_each_query_gets_its_own_file_and_index(db):
    db.set_script_config("933", config(
        ("users", f"select username from {TABLE} order by username;", "out_users"),
        ("count", f"select count(*) from {TABLE};", "out_count")))

    run = db.run_script(SCRIPT)

    assert [m.index for m in own(run)] == ["01", "02"], run.describe()
    assert var(db, "out_count").strip() == "2", var(db, "out_count")


def test_the_summary_collects_every_result_under_a_header(db):
    db.set_script_config("933", config(
        ("users", f"select username from {TABLE} order by username;", "out_users"),
        ("count", f"select count(*) from {TABLE};", "out_count")))

    db.run_script(SCRIPT)

    summary = var(db, SUMMARY)
    assert "### users ###" in summary, summary
    assert "### count ###" in summary, summary
    assert "alice" in summary and "2" in summary, summary


def test_no_configured_queries_still_writes_a_summary(db):
    """An empty config produces a summary holding only its timestamp — nothing
    claims to have exported anything."""
    db.set_script_config("933", config())

    run = db.run_script(SCRIPT)

    assert own(run) == [], run.describe()
    assert var(db, SUMMARY).strip() != ""


# --- failures ---------------------------------------------------------------

def test_a_query_against_a_missing_table_is_an_error(db):
    db.sql(f"DROP TABLE {TABLE}")

    run = db.run_script(SCRIPT)

    msg = own(run)[0]
    assert (msg.level, msg.errno) == ("E", "9332"), run.describe()


def test_a_wrong_password_is_an_error(db):
    db.set_script_config("mariadb", mariadb_config(password="wrongpw"))

    run = db.run_script(SCRIPT)

    assert own(run)[0].errno == "9332", run.describe()


def test_it_can_run_twice(db):
    """`933` writes each result with a plain truncating redirect:

        echo "${SQL_SELECT[$j]}" | $MYSQL_BIN ... >  ${SYSCHECK_HOME}/var/${OUTFILE[$j]}

    but `initscript` — which every syscheck script calls — does
    `set -o noclobber` (`lib/libsyscheck.sh:56`). With `noclobber` on, `>`
    refuses to overwrite an existing file:

        var/out_users: cannot overwrite existing file

    The redirection fails, so the query never runs, `$?` is non-zero and the
    result is reported as `9332`, "Could not get info from db".

    So `933` works exactly once. On a freshly installed host the first run
    succeeds; every run after it fails for every query, and the summary file —
    also written with a plain `>` — stops being updated while continuing to sit
    there holding the first run's data. A reader sees a stale report with no
    indication it is stale.

    That was D85, fixed on 2026-09-16 with `set +o noclobber` before the
    writes. `933` rewrites these files by design on every run, so the protection
    `initscript` turns on is simply the wrong default here.
    `sc_20_errors_ejbcalog.sh` meets the same constraint and resolves it the
    other way, with `2>|` at the one redirect that needs it."""
    db.run_script(SCRIPT)
    assert var(db, "out_users").split() == ["alice", "bob"]

    run = db.run_script(SCRIPT)

    assert own(run)[0].errno == "9331", run.describe()


def test_one_failing_query_does_not_stop_the_others(db):
    """Each query is independent, so a broken report must not suppress the rest
    — there is no `exit` in the loop."""
    db.set_script_config("933", config(
        ("broken", "select * from no_such_table;", "out_broken"),
        ("count", f"select count(*) from {TABLE};", "out_count")))

    run = db.run_script(SCRIPT)

    assert [m.errno for m in own(run)] == ["9332", "9331"], run.describe()
    assert var(db, "out_count").strip() == "2", var(db, "out_count")


# --- known defect -----------------------------------------------------------

def test_the_summary_timestamp_records_the_minute(db):
    """D84, fixed 2026-09-17. `933` stamped its summary with

        date +'%Y-%m-%d_%H.%m.%S'

    where the middle field of the time is `%m` — the *month*, not `%M` the
    minute. Every summary is stamped `HH.<month>.SS`, so two reports produced an
    hour apart within the same month carry timestamps that differ only in
    seconds, and the minute is unrecoverable.

    The same mistake appeared in `config/900.conf`, `901.conf` and `902.conf`,
    where it names archived files, and was fixed in `934` on 2026-09-15.

    Note this test previously never ran the script — it read the summary file
    directly, so its xfail was satisfied by a missing-file error rather than by
    the timestamp being wrong. It passed for the wrong reason for as long as the
    marker was on it."""
    db.run_script(SCRIPT)

    stamp = var(db, SUMMARY).splitlines()[0].strip()
    now = db.exec("date +%M").check().stdout.strip()

    assert stamp.split("_")[1].split(".")[1] == now, f"{stamp} vs minute {now}"


def test_help_documents_every_error_code(db):
    res = db.exec([db.script_path(SCRIPT), "--help"])

    for errno in ("9331", "9332"):
        assert f"{errno} / " in res.output, res.output
