"""End-to-end tests for related-available/917_archive_file.sh.

`917` moves a file into an "intransit" directory under a unique name, copies it
to an archive server, verifies the copy by md5sum, then moves the local copy
into a local archive directory. `916_archive_access_manager_logs.sh` is its one
caller in the tree.

REAL-OS: real directories in the container, real `mv`, real `mktemp`.

The suite stops at the remote transfer. `transferFile` delegates to `915` and
`906`, and `906` treats its `--dir` as a *directory* — it `put`s into `${SSHDIR}`
and verifies `${SSHDIR}/$(basename file)` — while `917` passes a full remote
*file path* built from a `mktemp` it claimed on the server. Those two contracts
cannot both hold, and since the remote path has never executed (see D76) there
is no prior behaviour to pin. Deciding which side gives way is a design call, so
it is recorded rather than tested.

Everything up to that point is covered, and that is the part `916` depends on.
"""

from __future__ import annotations

import pytest

SCRIPT = "related-available/917_archive_file.sh"
INTRANSIT = "/tmp/917/intransit"
ARCHIVE = "/tmp/917/archive"
SRC = "/tmp/917/src"

pytestmark = pytest.mark.slow


def config(*, intransit: str = INTRANSIT, archive: str = ARCHIVE) -> str:
    return ("# generated by test_917_archive_file.py\n"
            f"InTransitDir={intransit}\n"
            f"ArchiveDir={archive}\n")


@pytest.fixture
def archiver(syscheck):
    syscheck.exec(f"rm -rf /tmp/917 && mkdir -p {INTRANSIT} {ARCHIVE} {SRC}").check()
    syscheck.exec(f"echo payload > {SRC}/access.log").check()
    syscheck.set_script_config("917", config())
    return syscheck


def intransit_files(sc) -> list[str]:
    res = sc.exec(f"ls -1 {INTRANSIT} 2>/dev/null")
    return sorted(l for l in res.stdout.splitlines() if l.strip())


# --- argument parsing (D75) -------------------------------------------------

def test_the_first_positional_is_the_file_to_archive(archiver):
    """The D75 regression test. The option loop used to `break` on `--` without
    shifting past it, so `$1` was the literal string `--` and every argument
    landed one place to the right: `917` tried to archive a file named `--`,
    found it unreadable, skipped it and exited having done nothing.

    Proven here by the file actually moving out of `SRC`, which can only happen
    if `FileToArchive` received the path rather than `--`."""
    archiver.run_script(SCRIPT, f"{SRC}/access.log", "archivehost", ARCHIVE)

    assert intransit_files(archiver), "the file never reached the intransit dir"


def test_a_missing_file_argument_is_an_input_error(archiver):
    run = archiver.run_script(SCRIPT)

    assert run.messages[0].errno == "9173", run.describe()


def test_a_missing_host_argument_is_an_input_error(archiver):
    run = archiver.run_script(SCRIPT, f"{SRC}/access.log")

    assert run.messages[0].errno == "9173", run.describe()


def test_a_missing_archive_dir_argument_is_an_input_error(archiver):
    run = archiver.run_script(SCRIPT, f"{SRC}/access.log", "archivehost")

    assert run.messages[0].errno == "9173", run.describe()


def test_an_unknown_option_stops_the_run(archiver):
    """`getopt` rejecting an option used to fall through to `schelp` with no
    `exit`, so the script carried on with `eval set -- ""` and no arguments at
    all — reporting an input error for a typo rather than refusing to start."""
    res = archiver.exec([archiver.script_path(SCRIPT), "--no-such-option",
                         f"{SRC}/access.log", "archivehost", ARCHIVE])

    assert res.exit_code == 1, res.output
    assert not intransit_files(archiver), "it acted despite a bad option"


# --- --keep-org -------------------------------------------------------------

def test_keep_org_is_accepted_as_an_option(archiver):
    """`916` passes `--keep-org`. It was missing from the `getopt` long list, so
    `getopt` failed on it — the flag `916` relies on was the one flag `917`
    could not parse."""
    archiver.run_script(SCRIPT, "--keep-org", f"{SRC}/access.log",
                        "archivehost", ARCHIVE)

    assert intransit_files(archiver), "the file never reached the intransit dir"


def test_keep_org_leaves_the_original_in_place(archiver):
    archiver.run_script(SCRIPT, "--keep-org", f"{SRC}/access.log",
                        "archivehost", ARCHIVE)

    assert archiver.file_exists(f"{SRC}/access.log"), "the original was removed"


def test_without_keep_org_the_original_is_moved_away(archiver):
    archiver.run_script(SCRIPT, f"{SRC}/access.log", "archivehost", ARCHIVE)

    assert not archiver.file_exists(f"{SRC}/access.log"), "the original survived"


# --- the intransit staging --------------------------------------------------

def test_the_intransit_name_is_unique_and_keeps_the_original_name(archiver):
    """The staged name is `<timestamp>_orgname__<name>__<random>`, so two runs
    of the same file cannot collide and the original name stays recoverable."""
    archiver.run_script(SCRIPT, "--keep-org", f"{SRC}/access.log",
                        "archivehost", ARCHIVE)

    staged = intransit_files(archiver)
    assert len(staged) == 1, staged
    assert "_orgname__access.log__" in staged[0], staged[0]


def test_a_missing_intransit_dir_is_reported_and_stops_the_run(archiver):
    """Staging is the first thing that happens, so a missing directory has to
    stop the run rather than let the file be moved somewhere unexpected."""
    archiver.set_script_config("917", config(intransit="/tmp/917/does-not-exist"))

    run = archiver.run_script(SCRIPT, f"{SRC}/access.log", "archivehost", ARCHIVE)

    assert run.messages[0].errno == "9179", run.describe()
    assert archiver.file_exists(f"{SRC}/access.log"), "the original was moved anyway"


def test_an_unreadable_file_is_skipped_rather_than_failed(archiver):
    """The loop `continue`s past a file it cannot read. A log that rotated away
    between the glob and the read is normal, not an error."""
    archiver.run_script(SCRIPT, f"{SRC}/no-such.log", "archivehost", ARCHIVE)

    assert not intransit_files(archiver)


def test_one_failed_transfer_abandons_the_remaining_files_silently(archiver):
    """`FileToArchive` is looped over unquoted so a caller can pass a glob —
    which is how `916` hands over a day's worth of logs. Only the first of them
    is ever staged.

    `transferFile` runs inside a command substitution, so its `exit 1` kills
    only the subshell and `reFile` comes back empty. `archiveLocally` then hits

        if [ "x${remoteFileName}" = "x" ] ; then exit 1 ; fi

    which *is* the main shell, so the loop ends. The transfer failure itself is
    logged, but the files that were never attempted are not mentioned anywhere:
    a caller archiving ten logs against an unreachable server sees one error and
    no indication that nine files were skipped.

    Characterisation, not a claim about which behaviour is right — stopping on a
    dead archive server is defensible. What is worth pinning is that the scope
    of the failure is invisible."""
    archiver.exec(f"echo a > {SRC}/one.log ; echo b > {SRC}/two.log").check()

    archiver.run_script(SCRIPT, "--keep-org", f"{SRC}/one.log {SRC}/two.log",
                        "archivehost", ARCHIVE)

    staged = intransit_files(archiver)
    assert len(staged) == 1, staged
    assert "one.log" in staged[0], staged[0]


# --- message text (D77) -----------------------------------------------------

def test_messages_carry_their_description_text(archiver):
    """Every `printlogmess` in `917` used to pass `"$ARCHIVE_DESCR[N]"` with no
    `-d` flag. No `ARCHIVE_` prefixed arrays exist anywhere in the tree, so the
    expansion was an undefined variable followed by a literal subscript: every
    message arrived as the two-to-three characters `[N]`, and the stray word was
    passed to `printlogmess` as a positional argument rather than a description.

    `917` was the only script in the tree doing this."""
    run = archiver.run_script(SCRIPT)

    text = run.messages[0].text
    assert "[3]" != text.strip(), run.describe()
    assert "rgument" in text, run.describe()


def test_the_staging_message_names_both_paths(archiver):
    """`DESCR[7]` is `"File moved successfully to intransit folder (%s -> %s)"`
    — two placeholders, which only fill if the arguments are passed as `-1` and
    `-2` rather than trailing positionals."""
    run = archiver.run_script(SCRIPT, "--keep-org", f"{SRC}/access.log",
                             "archivehost", ARCHIVE)

    staging = [m for m in run.messages if m.errno == "9177"]
    assert staging, run.describe()
    assert f"{SRC}/access.log" in staging[0].text, staging[0].text
    assert INTRANSIT in staging[0].text, staging[0].text


def test_help_documents_every_error_code(archiver):
    res = archiver.exec([archiver.script_path(SCRIPT), "--help"])

    for n in range(1, 10):
        assert f"917{n} / " in res.output, res.output
