"""End-to-end tests for related-available/920_restore_mysql_db_from_backup.sh.

`920` restores a gzipped dump over the live database. Before doing so it asks
for interactive confirmation and takes a safety backup by calling `904`.

REAL-SVC: a real `mariadb:11`. The dumps restored here are produced by the real
`904`, so this suite and `test_904_make_mysql_db_backup.py` together prove a
genuine round trip — data goes out through `mysqldump` and comes back through
`920`, and the rows are checked on the far side.

`920` reads its confirmation from stdin, so every invocation here is driven
through `exec` with the answer piped in rather than through `run_script`.
"""

from __future__ import annotations

import pytest

from conftest import MARIADB_DATABASE, MARIADB_ROOT_PASSWORD
from syscheck_harness import parse_messages

SCRIPT = "related-available/920_restore_mysql_db_from_backup.sh"
BACKUP_SCRIPT = "related-available/904_make_mysql_db_backup.sh"
BACKUPDIR = "/tmp/920/backup"
TABLE = "CertificateData"
CONFIRM = "im really sure"

pytestmark = pytest.mark.slow


def mariadb_config(password: str = MARIADB_ROOT_PASSWORD) -> str:
    return ("# generated by test_920_restore_mysql_db_from_backup.py\n"
            f"DB_NAME={MARIADB_DATABASE}\n"
            f'MYSQLROOT_PASSWORD="{password}"\n'
            "MYSQL_BIN=/usr/bin/mariadb\n"
            "MYSQLDUMP_BIN=/usr/bin/mariadb-dump\n"
            "MYSQLDUMP_OPTIONS=(--single-transaction --quick)\n")


def backup_config() -> str:
    return ("# generated by test_920_restore_mysql_db_from_backup.py\n"
            "DATESTING='%Y-%m-%d_%H.%M.%S'\n"
            f"MYSQLBACKUPDIR={BACKUPDIR}\n"
            "SUBDIR_DEFAULT=default\n"
            "SUBDIR_DAILY=daily\nSUBDIR_WEEKLY=weekly\n"
            "SUBDIR_MONTHLY=monthly\nSUBDIR_YEARLY=yearly\n"
            f'DBNAME[0]="{MARIADB_DATABASE}"\n'
            'TABLENAMES[0]=""\n')


@pytest.fixture
def restore(syscheck, mariadb_node):
    syscheck.write_file("/root/.my.cnf", f"[client]\nhost={mariadb_node}\n")
    syscheck.exec(f"rm -rf /tmp/920 && mkdir -p {BACKUPDIR}/default").check()

    def sql(statement: str) -> str:
        res = syscheck.exec(["mariadb", "-h", mariadb_node, "-uroot",
                             f"-p{MARIADB_ROOT_PASSWORD}", MARIADB_DATABASE,
                             "-N", "-e", statement])
        assert res.exit_code == 0, res.output
        return res.stdout

    def rows() -> list[str]:
        return sorted(r for r in sql(f"select fingerprint from {TABLE}").split())

    sql(f"DROP TABLE IF EXISTS {TABLE}")
    sql(f"CREATE TABLE {TABLE} (fingerprint VARCHAR(64) PRIMARY KEY)")
    sql(f"INSERT INTO {TABLE} VALUES ('aa'),('bb')")

    syscheck.set_script_config("mariadb", mariadb_config())
    syscheck.set_script_config("904", backup_config())
    syscheck.sql = sql
    syscheck.rows = rows
    return syscheck


def make_backup(sc) -> str:
    """A real dump taken by the real `904`, which is what `920` restores.

    The trailing `sleep 1` is load-bearing. `904` names its file from
    `%Y-%m-%d_%H.%M.%S`, and `920` takes a safety backup of the same database
    moments later; within the same second the two names collide and D98
    destroys this file before it can be restored. One second apart is enough to
    keep these tests about `920` rather than about D98, which
    `test_904_make_mysql_db_backup.py` pins directly.
    """
    res = sc.exec([sc.script_path(BACKUP_SCRIPT), "--batch"]).check()
    name = [l.strip() for l in res.stdout.splitlines() if l.strip().endswith(".gz")]
    assert len(name) == 1, res.output
    sc.exec("sleep 1")
    return name[0]


def run(sc, *args, answer: str = CONFIRM, seconds: int = 60):
    argv = " ".join(args)
    res = sc.exec(f"printf '%s\\n' '{answer}' | "
                  f"timeout {seconds} {sc.script_path(SCRIPT)} --screen {argv}")
    messages, _j, _u = parse_messages(res.stdout + res.stderr)
    return res, [m for m in messages if m.scriptid == "920"]


# --- the round trip ---------------------------------------------------------

def test_a_backup_taken_by_904_restores_the_rows_it_held(restore):
    """The point of the pair. Dump two rows, destroy them, restore, get them
    back — through the real `mysqldump` and the real client."""
    dump = make_backup(restore)
    restore.sql(f"DELETE FROM {TABLE}")
    assert restore.rows() == []

    run(restore, f"--backupfile={dump}")

    assert restore.rows() == ["aa", "bb"]


def test_a_successful_restore_is_reported(restore):
    dump = make_backup(restore)

    _res, messages = run(restore, f"--backupfile={dump}")

    assert any(m.errno == "9202" for m in messages), messages


def test_rows_added_after_the_backup_are_rolled_back(restore):
    """Restoring is destructive by design — the dump replaces what is there.
    Proving it removes newer rows is proving the restore actually took."""
    dump = make_backup(restore)
    restore.sql(f"INSERT INTO {TABLE} VALUES ('cc')")
    assert restore.rows() == ["aa", "bb", "cc"]

    run(restore, f"--backupfile={dump}")

    assert restore.rows() == ["aa", "bb"]


# --- the safety backup ------------------------------------------------------

def test_a_safety_backup_is_taken_before_restoring(restore):
    """`920` calls `904` first, so the state being overwritten is recoverable.
    Two files in the backup directory afterwards: the one being restored and
    the one just taken."""
    dump = make_backup(restore)
    before = restore.exec(f"ls -1 {BACKUPDIR}/default | wc -l").check().stdout.strip()

    run(restore, f"--backupfile={dump}")

    after = restore.exec(f"ls -1 {BACKUPDIR}/default | wc -l").check().stdout.strip()
    assert int(after) == int(before) + 1, f"{before} -> {after}"


def test_a_failing_safety_backup_aborts_the_restore(restore):
    """If the pre-restore backup cannot be taken, the restore must not proceed —
    there would be no way back."""
    dump = make_backup(restore)
    restore.set_script_config("904", backup_config().replace(
        f"MYSQLBACKUPDIR={BACKUPDIR}", "MYSQLBACKUPDIR=/tmp/920/gone"))
    restore.sql(f"DELETE FROM {TABLE}")

    _res, messages = run(restore, f"--backupfile={dump}")

    assert any(m.errno == "9201" for m in messages), messages
    assert restore.rows() == [], "the restore ran despite the safety backup failing"


# --- the confirmation -------------------------------------------------------

def test_the_wrong_answer_aborts_without_touching_the_database(restore):
    dump = make_backup(restore)
    restore.sql(f"DELETE FROM {TABLE}")

    run(restore, f"--backupfile={dump}", answer="no")

    assert restore.rows() == [], "the database was restored despite declining"


def test_an_empty_answer_aborts(restore):
    dump = make_backup(restore)
    restore.sql(f"DELETE FROM {TABLE}")

    run(restore, f"--backupfile={dump}", answer="")

    assert restore.rows() == []


# --- missing input ----------------------------------------------------------

def test_running_without_a_backup_file_does_not_restore(restore):
    res, _messages = run(restore)

    assert res.exit_code != 124, "the script hung"
    assert restore.rows() == ["aa", "bb"]


# --- known defects ----------------------------------------------------------

def test_the_short_backupfile_option_works(restore):
    """D94, fixed 2026-09-17. `920` declared

        getopt --options "hsvb" --long "help,screen,verbose,backupfile:"

    with a colon after the long `backupfile` but none after the short `b`. So
    `-b /path/dump.gz` made `getopt` treat `-b` as flag-only and emit
    `-b -- '/path/dump.gz'`; the case arm assigned the `--` separator to
    `BACKUPFILE` and shifted past it, leaving `$1` on the path, which matched no
    arm and was never shifted. The loop spun forever.

    Exactly D82 as found in `900`, `901` and `902`, reached through the short
    form rather than the long one. The long `--backupfile=` was unaffected,
    which is why the rest of this suite could run at all."""
    dump = make_backup(restore)
    restore.sql(f"DELETE FROM {TABLE}")

    res, _messages = run(restore, "-b", dump, seconds=20)

    assert res.exit_code != 124, "the script hung until the timeout fired"


def test_the_confirmation_phrase_the_script_prints_is_the_one_it_accepts(restore):
    """D95, fixed 2026-09-17. `920` used to print

        enter 'im-really-sure' (without the '-') to continue or ctrl-c to abort

    Removing the hyphens from `im-really-sure` gives `imreallysure`, but the
    check wants `im really sure` — words separated by **spaces**. An operator
    following the printed instruction exactly could never proceed, and the
    script exited saying "ok probably wise choice".

    Harmless in that it failed safe, and precisely wrong in that the one
    documented way to use a disaster-recovery tool did not work — which is
    discovered during a disaster.

    Fixed by making the prompt state exactly what the check wants. Changing the
    check instead would have been equally valid, but silently alters a contract
    an operator may have memorised.

    This test reads the phrase out of the script's own prompt and answers with
    it, so the two cannot drift apart again."""
    dump = make_backup(restore)
    restore.sql(f"DELETE FROM {TABLE}")

    # a backupfile is needed to reach the prompt at all; "no" declines it
    prompt, _msgs = run(restore, f"--backupfile={dump}", answer="no")
    phrase = prompt.output.split("enter '")[1].split("'")[0]

    run(restore, f"--backupfile={dump}", answer=phrase)

    assert restore.rows() == ["aa", "bb"]


def test_the_restore_message_names_the_file_it_restored(restore):
    """D96, fixed 2026-09-17. Both outcome messages passed `-1 "$1"`, and after
    the `getopt` loop breaks on `--` that *is* `--` — the path lives in
    `$BACKUPFILE`. A restore reported "Restored the db from file (--)"."""
    dump = make_backup(restore)

    _res, messages = run(restore, f"--backupfile={dump}")

    restored = [m for m in messages if m.errno == "9202"]
    assert restored and dump in restored[0].text, messages


def test_running_without_a_backup_file_is_reported(restore):
    """D97, fixed 2026-09-17. The guard was

        printlogmess -n ${SCRIPTNAME} -i ${SCRIPTID} -x ${SCRIPTINDEX} -l $ERROR -d ${DESCR[4]}

    with three faults: `NO_OF_ERR=3` and `lang/920.english` defined only
    `DESCR[1..3]`, so `${DESCR[4]}` was empty; there was no `-e` at all, so the
    message carried no error number for monitoring to key on; and `${DESCR[4]}`
    was unquoted, so a non-empty value would word-split.

    `printlogmess` rejected the call on its "missing description" guard, so
    running `920` with no arguments reported nothing whatsoever.

    `NO_OF_ERR` is now 4 and `DESCR[4]`/`HELP[4]` exist, matching what `940` and
    `929` were given for the same shape of problem."""
    _res, messages = run(restore)

    assert messages, "no message was emitted for a missing backup file"
    assert messages[0].errno == "9204", messages


def test_a_failed_restore_names_the_safety_backup(restore):
    """The half an operator actually needs. `DESCR[3]` reads "Failed to restore
    the db from the file (%s) consider to restore to previously db (%s)" — that
    second placeholder is the backup taken moments earlier, the thing you roll
    back to.

    It used to receive `${BACKUPFILE}`: the file that had just failed to
    restore. The message told you to recover using the thing that did not work.

    `920` now captures the name from `904 --batch` and reports it. Driven by
    handing `920` a file that is not a valid dump, so the restore fails after
    the safety backup has been taken."""
    make_backup(restore)
    restore.exec(f"echo 'not a gzip dump' | gzip -c > /tmp/920/corrupt.gz").check()

    _res, messages = run(restore, "--backupfile=/tmp/920/corrupt.gz")

    failed = [m for m in messages if m.errno == "9203"]
    assert failed, messages
    assert "corrupt.gz" in failed[0].text, failed[0].text
    assert ".gz" in failed[0].text.split("previously db")[-1], failed[0].text


def test_an_aborted_safety_backup_exits_non_zero(restore):
    """`942` does `RESTORERET=$?` on `920` and propagates it. A bare `exit`
    returns the status of the preceding `printlogmess`, which succeeds — so an
    aborted restore used to report **success** upstream."""
    dump = make_backup(restore)
    restore.set_script_config("904", backup_config().replace(
        f"MYSQLBACKUPDIR={BACKUPDIR}", "MYSQLBACKUPDIR=/tmp/920/gone"))

    res, _messages = run(restore, f"--backupfile={dump}")

    assert res.exit_code != 0, res.output


def test_help_documents_every_error_code(restore):
    res = restore.exec([restore.script_path(SCRIPT), "--help"])

    for errno in ("9201", "9202", "9203", "9204"):
        assert f"{errno} / " in res.output, res.output
