"""End-to-end tests for related-available/940_mariadb_jobs.sh.

`940` runs a list of configured SQL "jobs" — typically stored-procedure calls
that prune old rows — reporting each one's success and the rows it returned. It
can run the whole list, list them without running, or run a single one.

REAL-SVC: a real `mariadb:11` answering real SQL. Jobs here are ordinary
statements rather than stored procedures, which is the same thing from `940`'s
side: it pipes a string to the client and reads the exit status.

Like `sc_18` and `933`, `940` passes no `-h`, so the server is chosen by
`~/.my.cnf`.
"""

from __future__ import annotations

import pytest

from conftest import MARIADB_DATABASE, MARIADB_ROOT_PASSWORD

SCRIPT = "related-available/940_mariadb_jobs.sh"
TABLE = "CertificateData"

pytestmark = pytest.mark.slow


def mariadb_config(password: str = MARIADB_ROOT_PASSWORD) -> str:
    return ("# generated by test_940_mariadb_jobs.py\n"
            f"DB_NAME={MARIADB_DATABASE}\n"
            f'MYSQLROOT_PASSWORD="{password}"\n'
            "MYSQL_BIN=/usr/bin/mariadb\n")


def config(*jobs) -> str:
    """`jobs` are (name, sql) pairs."""
    lines = ["# generated by test_940_mariadb_jobs.py\n"]
    for i, (name, sql) in enumerate(jobs):
        lines.append(f'DBJOBS_NAME[{i}]="{name}"\n')
        lines.append(f'DBJOBS_SQL[{i}]="{sql}"\n')
    return "".join(lines)


COUNT_SQL = f"use {MARIADB_DATABASE} ; select count(*) from {TABLE};"
DELETE_SQL = f"use {MARIADB_DATABASE} ; delete from {TABLE} where fingerprint='bb';"


@pytest.fixture
def jobs(syscheck, mariadb_node):
    syscheck.write_file("/root/.my.cnf", f"[client]\nhost={mariadb_node}\n")

    def sql(statement: str) -> None:
        syscheck.exec(["mariadb", "-h", mariadb_node, "-uroot",
                       f"-p{MARIADB_ROOT_PASSWORD}", MARIADB_DATABASE,
                       "-e", statement]).check()

    sql(f"DROP TABLE IF EXISTS {TABLE}")
    sql(f"CREATE TABLE {TABLE} (fingerprint VARCHAR(64) PRIMARY KEY)")
    sql(f"INSERT INTO {TABLE} VALUES ('aa'),('bb')")

    syscheck.set_script_config("mariadb", mariadb_config())
    syscheck.set_script_config("940", config(("count certs", COUNT_SQL),
                                             ("prune certs", DELETE_SQL)))
    syscheck.sql = sql
    return syscheck


def own(run) -> list:
    return [m for m in run.messages if m.scriptid == "940"]


# --- running the whole list -------------------------------------------------

def test_every_configured_job_runs(jobs):
    run = jobs.run_script(SCRIPT)

    assert [m.errno for m in own(run)] == ["9401", "9401"], run.describe()


def test_each_job_reports_under_its_own_index(jobs):
    """One index per job, so a job that starts failing is its own service
    rather than overwriting its neighbour."""
    run = jobs.run_script(SCRIPT)

    assert [m.index for m in own(run)] == ["01", "02"], run.describe()


def test_the_message_names_the_job(jobs):
    run = jobs.run_script(SCRIPT)

    assert "count certs" in own(run)[0].text, run.describe()


def test_the_message_carries_what_the_query_returned(jobs):
    """`DESCR[1]` is "Job: %s run ok: returns: %s" — for a pruning job the row
    counts before and after are the whole point of running it."""
    run = jobs.run_script(SCRIPT)

    assert "2" in own(run)[0].text, own(run)[0].text


def test_a_job_actually_changes_the_database(jobs):
    """These jobs exist to delete rows; proving the SQL really executed matters
    more than the message."""
    jobs.run_script(SCRIPT)

    res = jobs.exec(f"mariadb -uroot -p{MARIADB_ROOT_PASSWORD} "
                    f"{MARIADB_DATABASE} -N -e 'select count(*) from {TABLE}'")
    assert res.stdout.strip() == "1", res.output


# --- failures ---------------------------------------------------------------

def test_a_failing_job_is_reported_as_an_error(jobs):
    jobs.set_script_config("940", config(("broken", "select * from no_such_table;")))

    run = jobs.run_script(SCRIPT)

    msg = own(run)[0]
    assert (msg.level, msg.errno) == ("E", "9402"), run.describe()


def test_a_wrong_password_is_an_error(jobs):
    jobs.set_script_config("mariadb", mariadb_config(password="wrongpw"))

    run = jobs.run_script(SCRIPT)

    assert own(run)[0].errno == "9402", run.describe()


def test_one_failing_job_does_not_stop_the_others(jobs):
    jobs.set_script_config("940", config(("broken", "select * from no_such_table;"),
                                         ("count certs", COUNT_SQL)))

    run = jobs.run_script(SCRIPT)

    assert [m.errno for m in own(run)] == ["9402", "9401"], run.describe()


# --- listing and selecting --------------------------------------------------

def test_listjob_lists_without_running(jobs):
    res = jobs.exec([jobs.script_path(SCRIPT), "--listjob"])

    assert "count certs" in res.output and "prune certs" in res.output, res.output

    check = jobs.exec(f"mariadb -uroot -p{MARIADB_ROOT_PASSWORD} "
                      f"{MARIADB_DATABASE} -N -e 'select count(*) from {TABLE}'")
    assert check.stdout.strip() == "2", "a job ran despite --listjob"


def test_a_single_job_can_be_selected(jobs):
    run = jobs.run_script(SCRIPT, "--job", "1")

    assert len(own(run)) == 1, run.describe()
    assert "prune certs" in own(run)[0].text, run.describe()


# --- selecting a job that does not exist ------------------------------------

def test_a_job_named_rather_than_numbered_is_rejected(jobs):
    """The option is spelled `--job` and the array is `DBJOBS_NAME[]`, but the
    value is used as an *array subscript*:

        sqlret=$(echo "${DBJOBS_SQL[${jobname}]}" | $MYSQL_BIN ...)

    Bash evaluates a subscript as an arithmetic expression, where a bare word is
    read as a variable name; an unset variable is 0. So `--job prune` does not
    fail — it silently runs **job 0**, whatever that happens to be. (A value
    containing a space errors instead, which is a different and louder failure —
    the dangerous case is the single word that looks like a name.)

    For a tool whose jobs delete rows, running the wrong one because of a typo
    is the worst available outcome, and it reported success while doing it.

    Fixed 2026-09-16 (D90) with a digits-only `case` guard ahead of the
    subscript, reporting the new `ERRNO[3]`."""
    run = jobs.run_script(SCRIPT, "--job", "prune")

    assert [m.errno for m in own(run)] == ["9403"], run.describe()


def test_an_out_of_range_job_index_is_rejected(jobs):
    """`--job 99` yields an empty `DBJOBS_SQL[99]`, so the script pipes an empty
    string to the client. The client exits 0 on empty input, so `940` reports
    `9401` — "Job:  run ok: returns:" — with a blank name, for a job that was
    never configured and never ran.

    There was no bounds check against `${#DBJOBS_SQL[@]}`, which the script
    already uses for its own loop. Fixed 2026-09-16 (D91)."""
    run = jobs.run_script(SCRIPT, "--job", "99")

    assert [m.errno for m in own(run)] == ["9403"], run.describe()


def test_an_unknown_option_stops_the_run(jobs):
    """The guard reads

        if [ $? != 0 ] ; then help ; fi

    `help` is the **bash builtin**, not the script's own `schelp` — no `help`
    function is defined anywhere in the tree. So a bad option prints bash's
    builtin help text rather than the script's usage, and without an `exit` the
    script carries on with no arguments and runs every configured job.

    Same family as D44 in `sc_33`. It mattered more here: carrying on meant
    running every pruning job when the operator asked for one and mistyped.

    Fixed 2026-09-16 (D92) in two steps — `help` became `schelp`, and then the
    missing `exit 1` was added; `schelp` only prints, so the first change alone
    still let the run continue."""
    res = jobs.exec([jobs.script_path(SCRIPT), "--no-such-option"])

    assert res.exit_code != 0, res.output
    assert "Shell commands matching keyword" not in res.output, res.output


def test_help_documents_every_error_code(jobs):
    res = jobs.exec([jobs.script_path(SCRIPT), "--help"])

    for errno in ("9401", "9402", "9403"):
        assert f"{errno} / " in res.output, res.output
