"""End-to-end tests for related-available/934_check_validity_of_installed_certs.sh.

The first Phase 4 suite. `934` reads certificates out of PEM, DER, PKCS12 and
JKS keystores and reports how long each has left, against `WARNINGDAYS` and
`ERRORDAYS`.

Everything is real: certificates are minted by `openssl req -x509` in the
container, with `-not_before`/`-not_after` giving exact control over validity —
so an expired certificate here is genuinely expired rather than simulated. The
script's arithmetic comes from the real `lib/cmp_dates.py`.

As with `sc_08`, the tests hold the certificate's lifetime fixed and move the
thresholds. That needs no clock manipulation and exercises the two settings an
operator actually edits.

**JKS is not covered.** `checkJKS` shells out to `keytool`, which needs a JDK in
the base image; PEM, DER and PKCS12 need only `openssl`, which is already there.
All four formats funnel into `checkPEM`, so the verdict logic is covered
regardless — what is untested is the `keytool` extraction step.

Three defects were fixed here on 2026-09-15 before this suite was written; the
tests that would have caught them are marked in their docstrings.
"""

from __future__ import annotations

import pytest

SCRIPT = "related-available/934_check_validity_of_installed_certs.sh"
CERTDIR = "/tmp/certs"

pytestmark = pytest.mark.slow


def mint(sc, name: str, *, days: int = 365, expired: bool = False) -> str:
    """Create a PEM certificate valid for `days`, or already expired."""
    if expired:
        window = "-not_before 20200101000000Z -not_after 20200201000000Z"
    else:
        window = f"-days {days}"
    sc.exec(
        f"mkdir -p {CERTDIR} && openssl req -x509 -newkey rsa:2048 -nodes "
        f"-keyout {CERTDIR}/{name}.key -out {CERTDIR}/{name}.pem "
        f'-subj "/CN={name}.example.com" {window} 2>/dev/null'
    ).check()
    return f"{CERTDIR}/{name}.pem"


def to_der(sc, name: str) -> str:
    sc.exec(f"openssl x509 -in {CERTDIR}/{name}.pem -outform der "
            f"-out {CERTDIR}/{name}.der").check()
    return f"{CERTDIR}/{name}.der"


def to_p12(sc, name: str, password: str = "s3cret") -> str:
    sc.exec(
        f"openssl pkcs12 -export -in {CERTDIR}/{name}.pem "
        f"-inkey {CERTDIR}/{name}.key -out {CERTDIR}/{name}.p12 "
        f"-passout pass:{password} 2>/dev/null"
    ).check()
    return f"{CERTDIR}/{name}.p12"


def config(*entries, warningdays: int = 90, errordays: int = 10) -> str:
    """`entries` are (type, file) or (type, file, extra) where extra is the
    PKCS12 password or the JKS alias."""
    lines = ["# generated by test_934_cert_validity.py\n",
             f"WARNINGDAYS={warningdays}\n",
             f"ERRORDAYS={errordays}\n"]
    for i, entry in enumerate(entries):
        kind, path = entry[0], entry[1]
        lines.append(f'CERT_TYPE[{i}]="{kind}"\n')
        lines.append(f'CERT_FILE[{i}]="{path}"\n')
        if len(entry) > 2:
            key = "CERT_PASS" if kind == "P12" else "CERT_ALIAS"
            lines.append(f'{key}[{i}]="{entry[2]}"\n')
    return "".join(lines)


@pytest.fixture
def certs(syscheck):
    syscheck.exec(f"rm -rf {CERTDIR}")
    syscheck.pem = mint(syscheck, "fresh")
    syscheck.set_script_config("934", config(("PEM", syscheck.pem)))
    return syscheck


# --- the three verdicts -----------------------------------------------------

def test_a_certificate_with_plenty_of_life_is_ok(certs):
    """365 days left against a 90-day warning floor."""
    run = certs.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("I", "9341"), run.describe()
    assert "fresh.example.com" in msg.text, msg.text


def test_a_certificate_inside_the_warning_window_is_a_warning(certs):
    """Same certificate, warning floor raised above its remaining life."""
    certs.set_script_config("934", config(("PEM", certs.pem), warningdays=400))

    msg = certs.run_script(SCRIPT).only()

    assert (msg.level, msg.errno) == ("W", "9343"), msg.raw


def test_a_certificate_inside_the_error_window_is_an_error(certs):
    """Error floor above the remaining life wins over the warning floor."""
    certs.set_script_config("934", config(("PEM", certs.pem),
                                          warningdays=400, errordays=400))

    msg = certs.run_script(SCRIPT).only()

    assert (msg.level, msg.errno) == ("E", "9342"), msg.raw


def test_an_expired_certificate_is_an_error(certs):
    """Genuinely expired — `notAfter` is in 2020, so `cmp_dates.py` returns a
    negative number of minutes and it must stay below any threshold."""
    expired = mint(certs, "expired", expired=True)
    certs.set_script_config("934", config(("PEM", expired)))

    msg = certs.run_script(SCRIPT).only()

    assert (msg.level, msg.errno) == ("E", "9342"), msg.raw


def test_the_threshold_boundary_is_crossed_at_the_configured_day(certs):
    """Both sides of one boundary, so the comparison direction is pinned.

    A `-days 365` certificate reports **364**, not 365: `cmp_dates.py --minutes`
    returns the minutes remaining and the script divides by `60 / 24` with
    integer truncation, so 365 days minus a few seconds floors to 364."""
    certs.set_script_config("934", config(("PEM", certs.pem), warningdays=363))
    assert certs.run_script(SCRIPT).only().level == "I"

    certs.set_script_config("934", config(("PEM", certs.pem), warningdays=365))

    assert certs.run_script(SCRIPT).only().level == "W"


# --- the formats ------------------------------------------------------------

def test_a_der_certificate_is_read(certs):
    der = to_der(certs, "fresh")
    certs.set_script_config("934", config(("DER", der)))

    msg = certs.run_script(SCRIPT).only()

    assert (msg.level, msg.errno) == ("I", "9341"), msg.raw
    assert "fresh.example.com" in msg.text, msg.text


def test_a_pkcs12_keystore_is_read_with_its_password(certs):
    p12 = to_p12(certs, "fresh")
    certs.set_script_config("934", config(("P12", p12, "s3cret")))

    msg = certs.run_script(SCRIPT).only()

    assert (msg.level, msg.errno) == ("I", "9341"), msg.raw


def test_a_pkcs12_keystore_with_the_wrong_password_is_an_error(certs):
    """A rotated keystore password must not read as a healthy certificate."""
    p12 = to_p12(certs, "fresh")
    certs.set_script_config("934", config(("P12", p12, "wrong-password")))

    msg = certs.run_script(SCRIPT).only()

    assert msg.level == "E", msg.raw


def test_every_configured_certificate_gets_its_own_index(certs):
    """One index per entry, so each keystore is its own service."""
    other = mint(certs, "second")
    der = to_der(certs, "fresh")
    certs.set_script_config("934", config(("PEM", certs.pem), ("PEM", other),
                                          ("DER", der)))

    run = certs.run_script(SCRIPT)

    assert [m.index for m in run.messages] == ["01", "02", "03"], run.describe()


def test_an_unsupported_type_is_rejected(certs):
    certs.set_script_config("934", config(("P11", certs.pem)))

    res = certs.exec([certs.script_path(SCRIPT), "--screen"])

    assert "TYPE not supported" in res.output, res.output


# --- what the three fixes changed -------------------------------------------

def test_an_unreadable_certificate_is_an_error_not_an_ok(certs):
    """The defect this suite was written around.

    `cmp_dates.py`'s result was used without checking it, despite a
    `# TODO check error` on the very next line. When it fails `timeDiffMin` is
    empty, `let timeDiffDays="$timeDiffMin / 60 / 24"` errors and leaves the
    variable **unset**, the `-le` comparison then errors and is false, and the
    run falls through to the `else` — reporting the certificate as **fine**,
    with a blank day count.

    Worth stating because the intuitive reading is wrong: an empty value does
    not yield `0` days and therefore "expired". It yields no value at all and
    therefore "healthy", which is the dangerous direction."""
    certs.write_file(f"{CERTDIR}/garbage.pem", "not a certificate at all\n")
    certs.set_script_config("934", config(("PEM", f"{CERTDIR}/garbage.pem")))

    run = certs.run_script(SCRIPT)

    assert run.messages, run.describe()
    assert run.messages[0].level == "E", run.describe()


def test_a_missing_certificate_file_is_an_error(certs):
    certs.set_script_config("934", config(("PEM", f"{CERTDIR}/no-such.pem")))

    run = certs.run_script(SCRIPT)

    assert run.messages, run.describe()
    assert run.messages[0].level == "E", run.describe()


def test_no_debug_output_reaches_the_operator(certs):
    """`if [ $? -ne 0 ] ; then echo asdf ; exit ; fi` printed `asdf`, exited
    with no code (so 0, success), and tested `$?` after a pipeline ending in
    `sed` so it never fired anyway."""
    certs.write_file(f"{CERTDIR}/garbage.pem", "not a certificate at all\n")
    certs.set_script_config("934", config(("PEM", f"{CERTDIR}/garbage.pem")))

    res = certs.exec([certs.script_path(SCRIPT), "--screen"])

    assert "asdf" not in res.output, res.output


def test_the_message_labels_match_the_values_they_carry(certs):
    """All three descriptions used to read

        "File: %s subj: %s days until expiry: %s"

    while every call passes `-1 keystoreFile -2 timeDiffDays -3 subject`, so the
    day count landed under `subj:` and the subject under `days until expiry:`:

        File: /tmp/certs/fresh.pem subj: 364 days until expiry: subject=CN=...

    The information was all there, which is why it survived, but anything
    reading or parsing the line got the fields transposed. `lang/934.english`
    now labels them in the order the calls actually pass them."""
    msg = certs.run_script(SCRIPT).only()

    subj_field = msg.text.split("subj:")[1].split("days until expiry:")[0].strip()
    assert "CN=" in subj_field, f"'subj:' carried {subj_field!r}, not the subject"


def test_the_reported_day_count_is_not_skewed_by_the_clock(certs):
    """`nowDate` was built with `%H:%m:%S` — `%m` is the *month*, so the minutes
    field held the month number and "now" was wrong by up to 59 minutes. Every
    reported day count was quietly skewed.

    A certificate minted for exactly 365 days must report 364 or 365, never a
    value that a mis-built clock could produce."""
    msg = certs.run_script(SCRIPT).only()

    days = [int(w) for w in msg.text.replace(":", " ").split() if w.isdigit()]
    assert any(d in (363, 364, 365) for d in days), msg.text


def test_the_message_carries_the_subject_and_the_day_count(certs):
    """`DESCR[1]` is `"File: %s subj: %s days until expiry: %s"` — all three
    have to arrive, or the operator cannot tell which certificate is meant."""
    msg = certs.run_script(SCRIPT).only()

    assert "fresh.example.com" in msg.text, msg.text
    assert CERTDIR in msg.text, msg.text


def test_temporary_files_do_not_accumulate_across_entries(certs):
    """`checkDER`, `checkP12` and `checkJKS` each create a `mktemp` file. They
    used to register `trap "rm -f -- '$certFile'" EXIT` — but bash traps are
    global and a second `trap ... EXIT` **replaces** the first, so with several
    entries only the last file was removed.

    A `RETURN` trap does **not** fix this, which is worth recording: these
    functions nest (`checkJKS` -> `checkDER` -> `checkPEM`), and the inner
    function's `RETURN` trap replaces the outer's just as an `EXIT` trap does.
    Measured: two nested calls created four temp files and cleaned two.

    They now use `local certFile` plus an explicit `rm -f` after the nested
    call returns, which is correct at any depth. `local` also fixes a latent
    bug of its own — `certFile` was a global, so `checkJKS` calling `checkDER`
    had its own path overwritten before it could clean up."""
    before = certs.exec("ls -1 /tmp/tmp.* 2>/dev/null | wc -l").check().stdout.strip()

    der = to_der(certs, "fresh")
    second = mint(certs, "second")
    der2 = to_der(certs, "second")
    certs.set_script_config("934", config(("DER", der), ("DER", der2)))
    certs.run_script(SCRIPT)

    after = certs.exec("ls -1 /tmp/tmp.* 2>/dev/null | wc -l").check().stdout.strip()
    assert after == before, f"leaked {int(after) - int(before)} temp files"


def test_help_documents_every_error_code(certs):
    res = certs.exec([certs.script_path(SCRIPT), "--help"])

    for errno in ("9341", "9342", "9343"):
        assert f"{errno} / " in res.output, res.output
