"""End-to-end tests for related-available/942_restore_mysql_db_from_s3.sh.

`942` downloads a backup object from S3 with `curl --aws-sigv4`, decrypts it if
the key ends in `.gpg`, and hands the result to `920` to restore.

FAKE-BIN `curl`, recording its argv and writing whatever body the test wants.
Deliberately simple: no MinIO, and the `.gpg` path is not exercised because
`gpg` is not in the test image and an unencrypted key skips it entirely.

Same fidelity gap as `941`: this proves the request `942` builds and how it
reports, not that a real S3 answers it. See PLAN.md for the REAL-SVC upgrade.
"""

from __future__ import annotations

import pytest

from conftest import MARIADB_DATABASE, MARIADB_ROOT_PASSWORD

SCRIPT = "related-available/942_restore_mysql_db_from_s3.sh"
WORK = "/tmp/942"
CURL_LOG = f"{WORK}/curl.log"
PAYLOAD = f"{WORK}/payload.gz"

pytestmark = pytest.mark.slow


def config(*, endpoint: str = "https://s3.example.com") -> str:
    """Written to `config/941.conf`, not `942.conf`.

    `942` does `getconfig "941"` and its own config file says so: the S3
    destinations are deliberately shared with the upload side, so a restore
    cannot be pointed at a bucket the backups were never written to. `--index`
    selects which of them to pull from.
    """
    return ("# generated by test_942_restore_from_s3.py\n"
            f"S3_ENDPOINT[0]={endpoint}\n"
            "S3_REGION[0]=eu-north-1\n"
            "S3_BUCKET[0]=mysql-backups\n"
            "S3_PREFIX[0]=mysql\n"
            "S3_ACCESS_KEY[0]=AKIATEST\n"
            "S3_SECRET_KEY[0]=secret0\n")


def install_curl(sc, *, rc: int = 0, body: str = "404 NoSuchKey") -> None:
    """Writes the prepared payload to whatever --output names, so the restore
    downstream receives a real gzipped dump."""
    sc.install_fake_bin("curl",
                        "#!/bin/bash\n"
                        f'echo "$@" >> {CURL_LOG}\n'
                        "OUT=\n"
                        'while [ $# -gt 0 ]; do\n'
                        '  [ "$1" = "--output" ] && OUT=$2\n'
                        "  shift\n"
                        "done\n"
                        f'if [ {rc} -ne 0 ] ; then echo "{body}" ; exit {rc} ; fi\n'
                        f'[ -n "$OUT" ] && cp {PAYLOAD} "$OUT"\n'
                        "exit 0\n")


@pytest.fixture
def s3(syscheck, mariadb_node):
    syscheck.write_file("/root/.my.cnf", f"[client]\nhost={mariadb_node}\n")
    syscheck.exec(f"rm -rf {WORK} && mkdir -p {WORK}").check()
    syscheck.exec(["mariadb", "-h", mariadb_node, "-uroot",
                   f"-p{MARIADB_ROOT_PASSWORD}", MARIADB_DATABASE, "-e",
                   "DROP TABLE IF EXISTS CertificateData;"
                   "CREATE TABLE CertificateData (fingerprint VARCHAR(64) PRIMARY KEY);"
                   "INSERT INTO CertificateData VALUES ('aa'),('bb')"]).check()
    # a real dump, so the handoff to 920 has something valid to restore
    syscheck.exec(f"mariadb-dump -h {mariadb_node} -uroot "
                  f"-p{MARIADB_ROOT_PASSWORD} --single-transaction "
                  f"{MARIADB_DATABASE} | gzip -c >| {PAYLOAD}").check()
    install_curl(syscheck)
    syscheck.set_script_config("941", config())
    return syscheck


def run(sc, *args, answer: str = "im really sure", seconds: int = 60):
    argv = " ".join(args)
    return sc.exec(f"printf '%s\\n' '{answer}' | "
                   f"timeout {seconds} {sc.script_path(SCRIPT)} --screen {argv}")


def own(res) -> list:
    from syscheck_harness import parse_messages
    messages, _j, _u = parse_messages(res.stdout + res.stderr)
    return [m for m in messages if m.scriptid == "942"]


def calls(sc) -> list[str]:
    if not sc.file_exists(CURL_LOG):
        return []
    return [l for l in sc.read_file(CURL_LOG).splitlines() if l.strip()]


# --- guards -----------------------------------------------------------------

def test_no_object_key_is_reported(s3):
    res = run(s3)

    assert own(res)[0].errno == "9422", own(res)
    assert calls(s3) == [], calls(s3)


def test_an_unconfigured_endpoint_index_is_reported(s3):
    """`--index` selects which S3 destination to pull from; pointing at one
    that was never configured must not silently build a URL from empty
    strings."""
    res = run(s3, "--object", "mysql/default/x.gz", "--index", "3")

    assert own(res)[0].errno == "9423", own(res)
    assert calls(s3) == [], calls(s3)


# --- the request it builds --------------------------------------------------

def test_the_download_targets_the_configured_endpoint_and_key(s3):
    run(s3, "--object", "mysql/default/uuid-backup.gz")

    assert calls(s3), "curl was never called"
    assert ("https://s3.example.com/mysql-backups/mysql/default/uuid-backup.gz"
            in calls(s3)[0]), calls(s3)


def test_the_request_is_signed_for_the_configured_region(s3):
    run(s3, "--object", "mysql/default/x.gz")

    assert "--aws-sigv4 aws:amz:eu-north-1:s3" in calls(s3)[0], calls(s3)


def test_the_configured_credentials_are_used(s3):
    run(s3, "--object", "mysql/default/x.gz")

    assert "AKIATEST:secret0" in calls(s3)[0], calls(s3)


def test_the_short_option_works(s3):
    """`-o` is declared with a colon, unlike the `--cert`/`--crl` options that
    caused D82 in `900`, `901` and `902`."""
    run(s3, "-o", "mysql/default/x.gz")

    assert calls(s3), calls(s3)


# --- reporting --------------------------------------------------------------

def test_a_successful_download_is_reported(s3):
    res = run(s3, "--object", "mysql/default/uuid-backup.gz")

    ok = [m for m in own(res) if m.errno == "9421"]
    assert ok, own(res)
    assert "uuid-backup.gz" in ok[0].text, ok[0].text


def test_a_failing_download_is_reported_with_the_reason(s3):
    install_curl(s3, rc=22, body="404 NoSuchKey")

    res = run(s3, "--object", "mysql/default/missing.gz")

    failed = [m for m in own(res) if m.errno == "9424"]
    assert failed, own(res)
    assert "NoSuchKey" in failed[0].text, failed[0].text


def test_a_failing_download_does_not_restore(s3):
    """The important negative: a failed fetch must not reach `920`, which would
    otherwise be handed an empty file and asked to overwrite a live database."""
    install_curl(s3, rc=22)

    res = run(s3, "--object", "mysql/default/missing.gz")

    assert "Restored the db" not in res.output, res.output


# --- the handoff ------------------------------------------------------------

def test_a_downloaded_backup_is_handed_to_920(s3):
    """`942` does not restore anything itself — it fetches the object and hands
    the file to `920`, which owns the confirmation prompt, the safety backup and
    the actual load.

    Asserted at the handoff rather than by checking rows came back, because the
    restore itself is `920`'s behaviour and is covered by
    `test_920_restore_mysql_db_from_backup.py` against a real database. Driving
    it end to end here would mean configuring `904` as well, to satisfy `920`'s
    safety backup, for no additional guarantee about `942`."""
    res = run(s3, "--object", "mysql/default/uuid-backup.gz")

    assert "backup the current database" in res.output, res.output


def test_the_downloaded_file_is_cleaned_up(s3):
    """It lands in `mktemp`, and a restore job that leaves database dumps in
    /tmp is both a disk and a disclosure problem."""
    before = s3.exec("ls -1 /tmp/tmp.* 2>/dev/null | wc -l").stdout.strip()

    run(s3, "--object", "mysql/default/uuid-backup.gz")

    after = s3.exec("ls -1 /tmp/tmp.* 2>/dev/null | wc -l").stdout.strip()
    assert after == before, f"{before} -> {after}"


def test_help_documents_every_error_code(s3):
    res = s3.exec([s3.script_path(SCRIPT), "--help"])

    for n in range(1, 6):
        assert f"942{n} / " in res.output, res.output
