"""End-to-end tests for related-available/919_certpublisher_remotecommand.sh.

`919` reads fields out of a DER certificate — serial, DN, UID, CN,
serialNumber, or the whole PEM body — and runs a configured command on a remote
host with the chosen field appended. It is how a certificate event is pushed to
something outside syscheck.

FIXTURE for the certificate (real `openssl`), REAL-SVC for the remote end (the
shared key-only `sshd_node`).

`919` cannot currently do any of this. Three independent defects sit in its way,
and the first stops it before the certificate is ever opened. The suite is
written against the documented interface so it becomes a functional test once
they are fixed.
"""

from __future__ import annotations

import pytest

from conftest import SSH_KEY, SSH_REMOTE_USER

SCRIPT = "related-available/919_certpublisher_remotecommand.sh"
HELPER_SRC = "related-available/915_remote_command_via_ssh.sh"
HELPER_LINK = "related-enabled/915_remote_command_via_ssh.sh"
WORK = "/tmp/919"
CERT_DER = f"{WORK}/cert.der"
MARKER = f"/home/{SSH_REMOTE_USER}/published"

pytestmark = pytest.mark.slow

SSH_OPTS = ('"-o ConnectTimeout=10 -o StrictHostKeyChecking=no '
            '-o UserKnownHostsFile=/dev/null -o LogLevel=ERROR"')


def config(sc, *, arg: str = "CN") -> str:
    return ("# generated by test_919_certpublisher_remotecommand.py\n"
            f'REMOTE_HOST[0]="{sc.sshd}"\n'
            f"REMOTE_USER[0]='{SSH_REMOTE_USER}'\n"
            f"REMOTE_CMD[0]='tee -a {MARKER} <<<'\n"
            f"REMOTE_ARG[0]='{arg}'\n"
            f"SSHKEY[0]='{SSH_KEY}'\n")


@pytest.fixture
def publisher(syscheck, sshd_node):
    syscheck.sshd = sshd_node
    syscheck.exec(f"ln -sf {syscheck.home}/{HELPER_SRC} "
                  f"{syscheck.home}/{HELPER_LINK}").check()
    syscheck.exec(f"rm -rf {WORK} && mkdir -p {WORK} && "
                  f"openssl req -x509 -newkey rsa:2048 -nodes "
                  f"-keyout {WORK}/cert.key -out {WORK}/cert.pem "
                  f"-subj '/CN=publisher.example.com/serialNumber=SN12345' "
                  f"-days 365 2>/dev/null").check()
    syscheck.exec(f"openssl x509 -in {WORK}/cert.pem -outform der "
                  f"-out {CERT_DER}").check()
    syscheck.set_script_config("915", f"SSHOPTIONS={SSH_OPTS}\n")
    syscheck.set_script_config("919", config(syscheck))

    def remote(command: str):
        return syscheck.exec([
            "ssh", "-o", "StrictHostKeyChecking=no",
            "-o", "UserKnownHostsFile=/dev/null", "-o", "LogLevel=ERROR",
            "-i", SSH_KEY, "-l", SSH_REMOTE_USER, sshd_node, command])

    remote(f"rm -f {MARKER}").check()
    syscheck.remote = remote
    return syscheck


def run(sc, *args, seconds: int = 30):
    argv = " ".join(args)
    return sc.exec(f"timeout {seconds} {sc.script_path(SCRIPT)} --screen {argv}")


def own(res) -> list:
    from syscheck_harness import parse_messages
    messages, _j, _u = parse_messages(res.stdout + res.stderr)
    return [m for m in messages if m.scriptid == "919"]


# --- what is reachable ------------------------------------------------------

def test_it_terminates(publisher):
    res = run(publisher, f"--cert={CERT_DER}")

    assert res.exit_code != 124, "the script hung"


def test_an_unreadable_certificate_is_reported(publisher):
    """The `! -r` guard is the one thing in `919` that works as intended — and
    it is also where every run currently ends."""
    res = run(publisher, f"--cert={WORK}/no-such.der")

    assert any(m.errno == "9193" for m in own(res)), own(res)


def test_the_certificate_fixture_holds_the_fields_919_reads(publisher):
    """Guards the rest of the suite: if the CN and serialNumber are not in the
    subject, the xfails below would be about the fixture rather than `919`."""
    res = publisher.exec(
        f"openssl x509 -inform der -in {CERT_DER} -subject -noout").check()

    assert "publisher.example.com" in res.stdout, res.output
    assert "SN12345" in res.stdout, res.output


# --- known defects ----------------------------------------------------------

def test_the_certificate_option_reaches_the_script(publisher):
    """D128, fixed 2026-09-17. `919` used to contain the `getopt` block
    **twice**: the first declared only `help,screen,verbose`, the second added
    `cert:`.

    Because the first ran first, `getopt` rejected `--cert` as unrecognised and
    printed only the remainder to stdout:

        first getopt stdout: < -- '/tmp/919/cert.der'>

    `--cert` is gone. `eval set --` then replaces the argument list with that
    remainder, so by the time the *second* block — the one that would have
    understood the option — parses `"$@"`, there is nothing left to find.
    `CERTFILE` was never assigned and the `! -r ""` guard exited.

    The failure branch is `schelp` with no `exit`, which is what let the script
    carry on far enough to look like it had tried. The duplicate block was a
    leftover and deleting it was the fix."""
    res = run(publisher, f"--cert={CERT_DER}")

    assert not any(m.errno == "9193" for m in own(res)), own(res)


def test_the_remote_command_runs(publisher):
    """D129, fixed 2026-09-18. The transfer line read

        915_remote_command_via_ssh.sh ${REMOTE_HOST[$j]} ${RemoteCmd} \\
            ${REMOTE_USER[$j]} ${SSHKEY[$j]}

    while `915` parses with `getopt` and reads only `--host`, `--command`,
    `--user` and `--key`. Every positional landed after the `--` separator and
    was ignored, so `915` saw no host and exited on its own guard.

    The path also moved from `related-enabled/` to `related-available/`: `915`
    defaults to **disabled** in the ansible role, so the enabled path is the one
    likely to be missing.

    This is the defect that had `913`, `921`, `923` and `924` deleted, and D56
    in `sc_28` before them — the fourth distinct script in the tree to call a
    named-option helper positionally.

    Reachable as of the D128 fix, and fixed 2026-09-18.

    What this proves is that the command reached the remote host carrying a
    certificate field with it; `test_the_full_common_name_is_published` covers
    the field arriving intact."""
    run(publisher, f"--cert={CERT_DER}")

    assert "publisher.example.com" in publisher.remote(f"cat {MARKER}").stdout


def test_the_remote_command_outcome_is_reported(publisher):
    """D130, fixed 2026-09-18. `919` used `ERRNO[3]` at seven call sites and
    `ERRNO[4]` at one. `ERRNO[1]` — "Remote command ran successfully" — and
    `ERRNO[2]` — "Remote command failed" — were used **nowhere**.

    The `915` invocation's exit status was never checked and nothing was logged
    after it, so the one thing `919` exists to do was the one thing it never
    reported: every message it could emit was about reading the certificate.

    `SCRIPTINDEX` was never incremented either, so several remote hosts would
    have shared one monitoring key — the same defect as in `916` and the deleted
    `918`. It now advances once per host.

    The descriptions gained the placeholders the new call sites fill;
    one `%s` could not carry host, command and result."""
    res = run(publisher, f"--cert={CERT_DER}")

    assert any(m.errno in ("9191", "9192") for m in own(res)), own(res)


def test_a_failing_remote_command_is_reported(publisher):
    """That branch had never executed in the script's life — `ERRNO[2]` was
    dead code. Driven against a host that does not resolve, so `915` fails on
    the connection rather than on its own arguments."""
    publisher.set_script_config("919", config(publisher).replace(
        f'REMOTE_HOST[0]="{publisher.sshd}"', 'REMOTE_HOST[0]="no-such-host"'))

    res = run(publisher, f"--cert={CERT_DER}")

    failed = [m for m in own(res) if m.errno == "9192"]
    assert failed, own(res)
    assert "no-such-host" in failed[0].text, failed[0].text


def test_each_remote_host_reports_under_its_own_index(publisher):
    """`addOneToIndex` is now called per host, so two destinations are two
    monitoring services rather than one overwriting the other."""
    doubled = config(publisher) + config(publisher).replace("[0]", "[1]")
    publisher.set_script_config("919", doubled)

    res = run(publisher, f"--cert={CERT_DER}")

    outcomes = [m for m in own(res) if m.errno in ("9191", "9192")]
    assert len(outcomes) == 2, own(res)
    assert len({m.index for m in outcomes}) == 2, own(res)


def test_the_full_common_name_is_published(publisher):
    """D141, fixed 2026-09-18. `919` pulls fields out of the certificate subject
    with

        grep -oi 'cn=[[:alnum:][:space:]]*' | sed 's/cn=//gi'

    `[[:alnum:][:space:]]` covers letters, digits and spaces — but **not dots or
    hyphens** — so a CN of `publisher.example.com` matched only as far as the
    first dot and was published as `publisher`. Measured directly: that is what
    the remote host received.

    Hostname CNs almost always contain dots and organisation names routinely
    contain hyphens, so it truncated in the common case rather than an edge one,
    and whatever consumed the value got a name that did not identify the
    certificate.

    Both characters were added to the class, with the `-` last in the bracket
    expression so it stays literal. `CERTUID` and `CERTSN` used the same class
    and were corrected with it. `CERTDN` never had the problem — it takes the
    whole subject and rewrites the punctuation instead."""
    run(publisher, f"--cert={CERT_DER}")

    assert "publisher.example.com" in publisher.remote(f"cat {MARKER}").stdout


def test_help_documents_every_error_code(publisher):
    res = publisher.exec([publisher.script_path(SCRIPT), "--help"])

    for errno in ("9191", "9192", "9193", "9194"):
        assert f"{errno} / " in res.output, res.output
