"""End-to-end tests for scripts-available/sc_30_check_running_procs.sh.

sc_30 is the only check that *acts*: when a configured process is missing it
runs `RESTARTCMD[i]` and reports whether that worked. So the tests drive three
paths per entry — running, down-and-restarted, down-and-restart-failed — and the
restart command is a fake binary that leaves a marker file, so "the restart ran"
is asserted from evidence rather than from the message the script prints about
itself.

Processes are copies of `sleep` named after the daemon, as in
`test_sc_process_checks.py`; the lookup is `lib/proc_checker.sh`, covered on its
own in `test_proc_checker.py`.
"""

from __future__ import annotations

import pytest

SCRIPT = "sc_30_check_running_procs.sh"
MARKER = "/tmp/restart-ran"
ABSENT_PIDFILE = "/no/such/proc.pid"


def entry(index: int, proc: str, restartcmd: str = "",
          pidfile: str = ABSENT_PIDFILE) -> str:
    return (
        f"PROCNAME[{index}]=/usr/local/bin/{proc}\n"
        f'RESTARTCMD[{index}]="{restartcmd}"\n'
        f"PIDFILE[{index}]={pidfile}\n"
    )


def config(*entries: str) -> str:
    return "# generated by test_sc_30_check_running_procs.py\n" + "".join(entries)


@pytest.fixture
def procs(syscheck):
    """sc_30 with helpers for the restart command it is meant to run."""
    syscheck.exec(f"rm -f {MARKER} {MARKER}.argv")

    def restart_tool(name: str, exit_code: int = 0) -> str:
        """A fake restart command that records that it ran, and with what."""
        syscheck.install_fake_bin(
            name,
            f'echo "$@" >>{MARKER}.argv\n'
            f'echo ran >>{MARKER}\n'
            f"exit {exit_code}\n",
        )
        return f"/usr/local/bin/{name}"

    def restart_ran() -> bool:
        return syscheck.file_exists(MARKER)

    syscheck.restart_tool = restart_tool
    syscheck.restart_ran = restart_ran
    return syscheck


def test_a_running_process_is_reported_ok_and_not_restarted(procs):
    restart = procs.restart_tool("restarter")
    pid = procs.start_process("watched")
    procs.write_file("/var/run/watched.pid", f"{pid}\n")
    procs.set_script_config("30", config(
        entry(0, "watched", restart, "/var/run/watched.pid")))

    run = procs.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno, msg.index) == ("I", "301", "01"), run.describe()
    assert "/usr/local/bin/watched" in msg.text, msg.text
    assert not procs.restart_ran(), "a healthy process must not be restarted"


def test_a_process_found_by_name_alone_is_reported_ok(procs):
    """The shipped pidfile paths (`/var/run/apache2.pid`, ...) are absent on
    plenty of hosts, so the name fallback is the path that really runs."""
    procs.start_process("watched")
    procs.set_script_config("30", config(entry(0, "watched", procs.restart_tool("restarter"))))

    run = procs.run_script(SCRIPT)

    assert run.only().errno == "301", run.describe()
    assert not procs.restart_ran()


def test_a_missing_process_is_restarted_and_reported_as_a_warning(procs):
    restart = procs.restart_tool("restarter", exit_code=0)
    procs.set_script_config("30", config(entry(0, "absent", restart)))

    run = procs.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("W", "302"), run.describe()
    assert "/usr/local/bin/absent" in msg.text, msg.text
    assert procs.restart_ran(), "the restart command was never executed"


def test_a_failing_restart_is_reported_as_an_error(procs):
    restart = procs.restart_tool("restarter", exit_code=1)
    procs.set_script_config("30", config(entry(0, "absent", restart)))

    run = procs.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "303"), run.describe()
    assert procs.restart_ran()


def test_a_restart_command_that_does_not_exist_is_reported_as_an_error(procs):
    """The realistic misconfiguration: `RESTARTCMD` points at an init script
    this host does not have."""
    procs.set_script_config("30", config(entry(0, "absent", "/no/such/init.d/thing restart")))

    run = procs.run_script(SCRIPT)

    assert run.only().level == "E", run.describe()


def test_a_stale_pidfile_counts_as_down_and_triggers_the_restart(procs):
    """A pidfile left behind by an unclean shutdown names a pid that is gone."""
    restart = procs.restart_tool("restarter")
    procs.write_file("/var/run/watched.pid", f"{procs.free_pid()}\n")
    procs.set_script_config("30", config(
        entry(0, "watched", restart, "/var/run/watched.pid")))

    run = procs.run_script(SCRIPT)

    assert run.only().level == "W", run.describe()
    assert procs.restart_ran()


def test_a_missing_process_with_no_restart_command_is_reported_as_an_error(procs):
    procs.set_script_config("30", config(entry(0, "absent", "")))

    run = procs.run_script(SCRIPT)

    msg = run.only()
    assert msg.level == "E", run.describe()
    assert "/usr/local/bin/absent" in msg.text, msg.text


def test_every_configured_process_is_reported_once(procs):
    """Three entries, three messages, in configuration order — a per-entry
    check that stops at the first entry monitors one process out of three."""
    pid = procs.start_process("alive")
    procs.write_file("/var/run/alive.pid", f"{pid}\n")
    procs.set_script_config("30", config(
        entry(0, "alive", "", "/var/run/alive.pid"),
        entry(1, "gone", ""),
        entry(2, "alsogone", ""),
    ))

    run = procs.run_script(SCRIPT)

    assert len(run.messages) == 3, run.describe()
    assert run.levels == ["I", "E", "E"], run.describe()
    assert "/usr/local/bin/alive" in run.messages[0].text
    assert "/usr/local/bin/gone" in run.messages[1].text
    assert "/usr/local/bin/alsogone" in run.messages[2].text


def test_an_empty_configuration_reports_nothing_rather_than_failing(procs):
    """PROCNAME unset is what a host that has not configured sc_30 yet looks
    like; it must not produce a message about the empty entry."""
    procs.set_script_config("30", config())

    run = procs.run_script(SCRIPT)

    assert run.messages == [], run.describe()


def test_help_documents_every_error_code(procs):
    res = procs.exec([procs.script_path(SCRIPT), "--help"])

    for errno in ("301", "302", "303", "304"):
        assert f"{errno} / " in res.output, res.output


def test_the_message_indexes_are_contiguous(procs):
    """The regression guard for D25. `SCRIPTINDEX` used to be incremented once
    per entry *and* a second time before the restart, while only one message was
    emitted, so the burned index was never submitted. Each index is a distinct
    service name in Icinga/OP5, so a monitored service silently stopped
    receiving results whenever the entry before it needed a restart."""
    procs.set_script_config("30", config(
        entry(0, "gone", procs.restart_tool("restarter")),
        entry(1, "alsogone", ""),
    ))

    run = procs.run_script(SCRIPT)

    assert run.indexes == ["01", "02"], run.describe()


def test_a_restart_command_with_several_steps_runs_every_step(procs):
    """The regression guard for D26. The shipped `config/30.conf` contains
    `RESTARTCMD[2]="/etc/init.d/cups stop ; sleep 3 ; /etc/init.d/cups start"`,
    so the multi-step form is the documented way to write one. The call used to
    be `$(${RESTARTCMD[$i]})` — unquoted but never re-evaluated — so the `;`
    arrived as an argv element of the first command instead of separating
    commands: the stop ran with garbage arguments and the start never ran at
    all, leaving down the very service this check exists to recover."""
    restart = procs.restart_tool("restarter")
    procs.set_script_config("30", config(
        entry(0, "absent", f"{restart} stop ; {restart} start")))

    procs.run_script(SCRIPT)

    argv = procs.read_file(f"{MARKER}.argv")
    assert argv.splitlines() == ["stop", "start"], argv


def test_a_missing_restart_command_is_distinguishable_from_a_failed_restart(procs):
    """The regression guard for D27. `lang/30.english` has a fourth message,
    "Process %s was not running, no restart command defined", whose remedy is
    "restart manually". The script used not to use it — that branch sent
    `ERRNO[3]`/`DESCR[3]`, "restart failed" — and `NO_OF_ERR=3` meant `ERRNO[4]`
    was not even generated, so the operator was told a restart had been
    attempted and had failed when none was ever configured."""
    procs.set_script_config("30", config(entry(0, "absent", "")))

    run = procs.run_script(SCRIPT)

    msg = run.only()
    assert msg.errno == "304", run.describe()
    assert "no restart command" in msg.text, msg.text
