"""End-to-end tests for scripts-available/sc_39_hsm_health.sh.

`sc_39` drives two non-interactive `lunacm` sessions against a SafeNet Luna HSM
and grades the combined output. `lunacm` is faked as a binary that reads the
piped command list on **stdin** and answers each command from a fixture.

Fixtures come from [`sc_39_luna7_sample_output.txt`](sc_39_luna7_sample_output.txt),
a real Luna 7 capture taken from the Thales LunaCM Command Reference. Field
names, value formats and the `Command Result : No Error` trailer are all
genuine, which matters here because the script's parsing is unusually literal:
it extracts by field name (`Battery Voltage`, `Partition Status`), requires unit
suffixes it strips itself (`3.093 V`, `64 deg. C`), and counts successful
command results.

**Two commands are not in the capture** and are reconstructed:

* `slot list` — needed because the session guard compares `Current Slot Id`
  against the configured slot, and the real `slot set` line carries a
  parenthetical that breaks that comparison. See
  `test_the_session_guard_accepts_the_real_slot_set_line` (D70): the default
  fixture has `slot list` emit a bare `Current Slot Id:` line, which is the only
  assumption under which the check works at all.
* `hsm envshow` — the capture has `hsm showinfo`, whose `Environmental:` block
  carries the same field names, so that block is used verbatim.
"""

from __future__ import annotations

import pytest

SCRIPT = "sc_39_hsm_health.sh"
TOOL = "/usr/local/bin/lunacm"
CALL_LOG = "/tmp/lunacm-calls.log"
FIXTURE_DIR = "/tmp/lunacm-fixtures"

APP_SLOT = 3
ADMIN_SLOT = 4

pytestmark = pytest.mark.slow

# From the capture: `role show -name co` on an activated Crypto Officer.
ROLE_ACTIVATED = """State of role 'Crypto Officer':
Activated.
Command Result : No Error
"""

ROLE_NOT_INITIALIZED = """State of role 'Crypto Officer':
Not initialized.
Command Result : No Error
"""

# From the capture, `partition showinfo` (v1).
PARTITION_OK = """Partition Label -> myPCIePar
Partition Manufacturer -> SafeNet
Partition Model -> Luna K7
Partition Serial Number -> 157956935657
Partition Status -> L3 Device
HSM Part Number -> 808-000048-002
Slot Id -> 6
Session State -> CKS_RW_PUBLIC_SESSION
Role Status -> none logged in
Partition Storage:
Total Storage Space: 6627739
Used Storage Space: 84480
Free Storage Space: 6543259
Object Count: 256
Command Result : No Error
"""

# The `Environmental:` block of `hsm showinfo` from the capture.
ENVSHOW_OK = """Environmental:
Fan 1 Status : active
Fan 2 Status : active
Battery Voltage : 3.093 V
Battery Warning Threshold Voltage : 2.750 V
System Temp : 64 deg. C
System Temperature Warning Threshold : 75 deg. C
Command Result : No Error
"""

FAKE_LUNACM = f"""#!/bin/bash
IN=$(cat)
echo "$IN" >> {CALL_LOG}
while IFS= read -r cmd ; do
  case "$cmd" in
    "slot set"*)
        slot="${{cmd##*-slot }}"
        if [ -f "{FIXTURE_DIR}/slot_set" ] ; then
          sed "s/@SLOT@/$slot/g" "{FIXTURE_DIR}/slot_set"
        fi
        ;;
    "slot list")
        if [ -f "{FIXTURE_DIR}/slot_list" ] ; then
          sed "s/@SLOT@/$slot/g" "{FIXTURE_DIR}/slot_list"
        fi
        ;;
    "role show"*)        cat "{FIXTURE_DIR}/role_show" 2>/dev/null ;;
    "partition showinfo") cat "{FIXTURE_DIR}/partition" 2>/dev/null ;;
    "hsm envshow")       cat "{FIXTURE_DIR}/envshow" 2>/dev/null ;;
    exit) : ;;
  esac
done <<< "$IN"
exit ${{LUNACM_EXIT:-0}}
"""

# The real `slot set` answer from the capture, with its parenthetical.
SLOT_SET_REAL = ("Current Slot Id: @SLOT@ "
                 "(Luna User Slot 7.0.1 (PW) Signing With Cloning Mode)\n"
                 "Command Result : No Error\n")

# Reconstructed: a bare `Current Slot Id:` from `slot list`. The extractor keeps
# the last match, so this is what makes the session guard pass. See D70.
SLOT_LIST_BARE = "Current Slot Id: @SLOT@\nCommand Result : No Error\n"


def config(*, app_slot=APP_SLOT, admin_slot=ADMIN_SLOT, timeout=10,
           battery_margin="0.100", temp_margin="5",
           storage_warn="15", storage_err="5", lunacm: str = TOOL) -> str:
    return (
        "# generated by test_sc_39_hsm_health.py\n"
        f"LUNACM={lunacm}\n"
        f"LUNA_APPLICATION_SLOT={app_slot}\n"
        f"LUNA_ADMIN_SLOT={admin_slot}\n"
        f"LUNACM_TIMEOUT={timeout}\n"
        f"BATTERY_WARNING_MARGIN_V={battery_margin}\n"
        f"TEMPERATURE_WARNING_MARGIN_C={temp_margin}\n"
        f"STORAGE_WARNING_FREE_PERCENT={storage_warn}\n"
        f"STORAGE_ERROR_FREE_PERCENT={storage_err}\n"
    )


def set_fixtures(sc, *, slot_set=SLOT_SET_REAL, slot_list=SLOT_LIST_BARE,
                 role_show=ROLE_ACTIVATED, partition=PARTITION_OK,
                 envshow=ENVSHOW_OK) -> None:
    for name, body in (("slot_set", slot_set), ("slot_list", slot_list),
                       ("role_show", role_show), ("partition", partition),
                       ("envshow", envshow)):
        sc.write_file(f"{FIXTURE_DIR}/{name}", body)


@pytest.fixture
def hsm(syscheck):
    syscheck.exec(f"rm -f {CALL_LOG} ; mkdir -p {FIXTURE_DIR}")
    syscheck.install_fake_bin("lunacm", FAKE_LUNACM)
    set_fixtures(syscheck)
    syscheck.set_script_config("39", config())
    return syscheck


def summary(run):
    return run.messages[-1]


def by_errno(run, *errnos):
    return [m for m in run.messages if m.errno in errnos]


# --- a healthy HSM ----------------------------------------------------------

def test_a_healthy_hsm_reports_every_check_ok(hsm):
    """Six checks — CO activation, partition status, two fans, battery,
    temperature, storage — then the summary."""
    run = hsm.run_script(SCRIPT)

    assert all(m.level == "I" for m in run.messages), run.describe()
    assert (summary(run).level, summary(run).errno) == ("I", "3916"), run.describe()


def test_the_summary_has_its_own_index(hsm):
    """`sc_39` resets `SCRIPTINDEX` to `00` before the summary, which is what
    `sc_08` failed to do as D50."""
    run = hsm.run_script(SCRIPT)

    assert summary(run).index == "00", run.describe()
    assert all(m.index != "00" for m in run.messages[:-1]), run.describe()


def test_both_sessions_are_driven_with_the_configured_slots(hsm):
    """The application partition and the HSM administrative partition are
    different slots, and the commands differ between them."""
    hsm.run_script(SCRIPT)

    log = hsm.read_file(CALL_LOG)
    assert f"slot set -slot {APP_SLOT}" in log, log
    assert f"slot set -slot {ADMIN_SLOT}" in log, log
    assert "role show -name co" in log, log
    assert "partition showinfo" in log, log
    assert "hsm envshow" in log, log


# --- the individual checks --------------------------------------------------

def test_a_crypto_officer_that_is_not_activated_is_an_error(hsm):
    """The CO role has to be activated or the partition cannot sign."""
    set_fixtures(hsm, role_show=ROLE_NOT_INITIALIZED)

    run = hsm.run_script(SCRIPT)

    bad = by_errno(run, "392")
    assert bad, run.describe()
    assert "Not initialized" in bad[0].text, bad[0].text


def test_a_partition_that_is_not_l3_is_an_error(hsm):
    set_fixtures(hsm, partition=PARTITION_OK.replace(
        "Partition Status -> L3 Device", "Partition Status -> L2 Device"))

    run = hsm.run_script(SCRIPT)

    assert by_errno(run, "394"), run.describe()


def test_a_stopped_fan_is_an_error(hsm):
    set_fixtures(hsm, envshow=ENVSHOW_OK.replace(
        "Fan 2 Status : active", "Fan 2 Status : stopped"))

    run = hsm.run_script(SCRIPT)

    assert len(by_errno(run, "396")) == 1, run.describe()


def test_the_battery_voltage_is_read_with_its_unit_stripped(hsm):
    """`Battery Voltage : 3.093 V` — the capture's real format, including the
    unit the script's `parse_voltage` has to remove before comparing."""
    run = hsm.run_script(SCRIPT)

    battery = by_errno(run, "397")
    assert battery, run.describe()
    assert "current 3.093 V" in battery[0].text, battery[0].text


def test_a_battery_at_its_warning_threshold_is_an_error(hsm):
    """At or below the HSM's own warning threshold the battery is failing."""
    set_fixtures(hsm, envshow=ENVSHOW_OK.replace(
        "Battery Voltage : 3.093 V", "Battery Voltage : 2.750 V"))

    run = hsm.run_script(SCRIPT)

    assert by_errno(run, "399"), run.describe()


def test_a_battery_approaching_the_threshold_is_a_warning(hsm):
    """`BATTERY_WARNING_MARGIN_V` gives early notice before the HSM's own
    threshold is reached — 2.800 V is 0.050 V above a 2.750 V threshold, inside
    the configured 0.100 V margin."""
    set_fixtures(hsm, envshow=ENVSHOW_OK.replace(
        "Battery Voltage : 3.093 V", "Battery Voltage : 2.800 V"))

    run = hsm.run_script(SCRIPT)

    assert by_errno(run, "398"), run.describe()


def test_the_temperature_is_read_with_its_unit_stripped(hsm):
    """`System Temp : 64 deg. C` — `parse_temperature` has to handle the
    `deg. C` suffix the real HSM emits."""
    run = hsm.run_script(SCRIPT)

    temp = by_errno(run, "3910")
    assert temp, run.describe()
    assert "current 64" in temp[0].text, temp[0].text


def test_a_temperature_over_the_threshold_is_an_error(hsm):
    set_fixtures(hsm, envshow=ENVSHOW_OK.replace(
        "System Temp : 64 deg. C", "System Temp : 80 deg. C"))

    run = hsm.run_script(SCRIPT)

    assert by_errno(run, "3912"), run.describe()


def test_a_temperature_approaching_the_threshold_is_a_warning(hsm):
    """72 C is 3 below a 75 C threshold, inside the configured 5 degree margin."""
    set_fixtures(hsm, envshow=ENVSHOW_OK.replace(
        "System Temp : 64 deg. C", "System Temp : 72 deg. C"))

    run = hsm.run_script(SCRIPT)

    assert by_errno(run, "3911"), run.describe()


def test_partition_storage_is_reported_as_a_percentage_free(hsm):
    """The capture's partition has 6543259 of 6627739 bytes free — about 98.7%,
    comfortably above both thresholds."""
    run = hsm.run_script(SCRIPT)

    storage = by_errno(run, "3913")
    assert storage, run.describe()
    assert "objects 256" in storage[0].text, storage[0].text


def test_partition_storage_below_the_error_threshold_is_an_error(hsm):
    """4% free against a 5% error threshold."""
    set_fixtures(hsm, partition=PARTITION_OK
                 .replace("Used Storage Space: 84480", "Used Storage Space: 6360229")
                 .replace("Free Storage Space: 6543259", "Free Storage Space: 267510"))

    run = hsm.run_script(SCRIPT)

    assert by_errno(run, "3915"), run.describe()


def test_partition_storage_below_the_warning_threshold_is_a_warning(hsm):
    """10% free: under the 15% warning threshold, over the 5% error one."""
    set_fixtures(hsm, partition=PARTITION_OK
                 .replace("Used Storage Space: 84480", "Used Storage Space: 5964965")
                 .replace("Free Storage Space: 6543259", "Free Storage Space: 662774"))

    run = hsm.run_script(SCRIPT)

    assert by_errno(run, "3914"), run.describe()


# --- session and configuration failures -------------------------------------

def test_a_missing_lunacm_is_reported_on_every_check(hsm):
    """Without the tool nothing can be known, and each check says so rather than
    reporting a healthy HSM."""
    hsm.set_script_config("39", config(lunacm="/usr/safenet/lunaclient/bin/lunacm"))

    run = hsm.run_script(SCRIPT)

    assert all(m.level == "E" for m in run.messages), run.describe()
    assert "not found" in run.messages[0].text, run.messages[0].text


def test_a_lunacm_command_error_fails_the_session(hsm):
    """Any `Command Result` other than `No Error` invalidates the whole session
    — a partial answer must not be graded as if it were complete."""
    set_fixtures(hsm, partition=PARTITION_OK.replace(
        "Command Result : No Error", "Command Result : CKR_TOKEN_NOT_PRESENT"))

    run = hsm.run_script(SCRIPT)

    assert any("CKR_TOKEN_NOT_PRESENT" in m.text for m in run.messages), \
        run.describe()


def test_a_session_that_returns_too_few_results_is_rejected(hsm):
    """The guard counts `Command Result : No Error` lines; too few means some
    command silently produced nothing."""
    set_fixtures(hsm, role_show="State of role 'Crypto Officer':\nActivated.\n")

    run = hsm.run_script(SCRIPT)

    assert any("expected at least" in m.text for m in run.messages), run.describe()


def test_invalid_storage_thresholds_are_reported(hsm):
    """The error threshold must be below the warning threshold; inverted values
    would make the warning unreachable."""
    hsm.set_script_config("39", config(storage_warn="5", storage_err="15"))

    run = hsm.run_script(SCRIPT)

    assert any("Invalid storage thresholds" in m.text for m in run.messages), \
        run.describe()


def test_a_failure_reaches_the_summary(hsm):
    set_fixtures(hsm, role_show=ROLE_NOT_INITIALIZED)

    run = hsm.run_script(SCRIPT)

    assert (summary(run).level, summary(run).errno) == ("E", "3917"), run.describe()
    assert "CO activation" in summary(run).text, summary(run).text


# --- the reconstructed command, and what it hides ---------------------------

def test_the_session_guard_accepts_the_real_slot_set_line(hsm):
    """`slot set` answers, verbatim from the capture:

        Current Slot Id: 1 (Luna User Slot 7.0.1 (PW) Signing With Cloning Mode)

    `extract_colon_field ... "Current Slot Id"` returns the whole tail,
    parenthetical included, and the guard compares it with

        [[ ${APP_CURRENT_SLOT} != ${LUNA_APPLICATION_SLOT} ]]

    against a bare slot number. That can never match, so both sessions fail with
    "LunaCM did not select application partition slot" and every check reports
    the session error instead of the HSM's real state.

    Every other test in this file only passes because the fixture has `slot
    list` emit a second, bare `Current Slot Id:` line — the extractor keeps the
    **last** match, so that one wins. `slot list` output is **not** in the
    capture, so whether a real Luna emits it is unknown.

    Driven here with `slot list` silent, leaving only the real `slot set`
    answer. If a real `slot list` does emit a bare line the script is fine and
    this test should be deleted; if it does not, this is a defect that stops
    `sc_39` working at all. One capture of `lunacm slot list` settles it."""
    set_fixtures(hsm, slot_list="Command Result : No Error\n")

    run = hsm.run_script(SCRIPT)

    assert all(m.level == "I" for m in run.messages), run.describe()


def test_help_documents_every_error_code(hsm):
    res = hsm.exec([hsm.script_path(SCRIPT), "--help"])

    for n in range(1, 18):
        assert f"39{n} / " in res.output, res.output
