"""End-to-end tests for related-available/916_archive_access_manager_logs.sh.

`916` is a driver: for each configured glob it loops over the matching files and
hands each one to `917_archive_file.sh`, once per destination server. It owns no
transfer logic of its own — its job is choosing files and passing arguments.

REAL-OS: real log files in a temp tree, the real `917`.

The calls to `917` are **positional**, which is correct — `917` takes positional
arguments after its options, unlike `915` and `906`. That distinction is what
made `921` dead code while `916` is merely untested.

No archive server exists in the container, so `917` always fails at the transfer
step. That is the honest shape of these tests rather than a limitation: what
`916` is responsible for — which files it selects, whether it passes
`--keep-org`, and how it reports a failed child — is all observable before the
transfer. See `test_917_archive_file.py` for the staging behaviour itself, and
REPORT.md for why the remote path is unfinished.
"""

from __future__ import annotations

import pytest

SCRIPT = "related-available/916_archive_access_manager_logs.sh"
LOGS = "/tmp/916/logs"
INTRANSIT = "/tmp/916/intransit"
ARCHIVE = "/tmp/916/archive"

pytestmark = pytest.mark.slow


def config(*entries) -> str:
    """`entries` are (glob, server0, server1, dir, user); "" means unset."""
    lines = ["# generated by test_916_archive_access_manager_logs.py\n"]
    for i, (glob, s0, s1, d, user) in enumerate(entries):
        lines.append(f'FileName[{i}]="{glob}"\n')
        lines.append(f'ToServer0[{i}]="{s0}"\n')
        lines.append(f'ToServer1[{i}]="{s1}"\n')
        lines.append(f'ToServerDir[{i}]="{d}"\n')
        lines.append(f'ToUser[{i}]="{user}"\n')
    return "".join(lines)


def one(glob=f"{LOGS}/message.*", s0="archivehost", s1="", user="logtest") -> str:
    return config((glob, s0, s1, ARCHIVE, user))


@pytest.fixture
def driver(syscheck):
    syscheck.exec(f"rm -rf /tmp/916 && mkdir -p {LOGS} {INTRANSIT} {ARCHIVE}").check()
    syscheck.exec(f"echo one > {LOGS}/message.1 ; echo two > {LOGS}/message.2").check()
    syscheck.set_script_config("917", f"InTransitDir={INTRANSIT}\nArchiveDir={ARCHIVE}\n")
    syscheck.set_script_config("916", one())
    return syscheck


def staged(sc) -> list[str]:
    res = sc.exec(f"ls -1 {INTRANSIT} 2>/dev/null")
    return sorted(l for l in res.stdout.splitlines() if l.strip())


def own(run) -> list:
    """`916`'s own messages. It runs `917`, which runs `915`, and every one of
    them logs to the same sinks — so a run of `916` produces a mixed stream and
    only the `916` lines are this script's own reporting."""
    return [m for m in run.messages if m.scriptid == "916"]


def remaining_logs(sc) -> list[str]:
    res = sc.exec(f"ls -1 {LOGS} 2>/dev/null")
    return sorted(l for l in res.stdout.splitlines() if l.strip())


# --- file selection ---------------------------------------------------------

def test_a_configured_glob_reaches_917(driver):
    """`916`'s whole purpose. If the handoff works at all, the first matching
    log ends up staged in `917`'s intransit directory."""
    driver.run_script(SCRIPT)

    assert staged(driver), "no file was handed to 917"


def test_a_glob_matching_nothing_does_nothing_quietly(driver):
    """`files=$(ls ${FileName[$i]} 2>/dev/null)` yields an empty list and the
    inner loop never runs — a log that has not rotated yet is not an error."""
    driver.set_script_config("916", one(glob=f"{LOGS}/no-such.*"))

    run = driver.run_script(SCRIPT)

    assert own(run) == [], run.describe()
    assert staged(driver) == []


def test_an_entry_with_no_server_is_skipped(driver):
    """Both call sites are guarded on their server being set, so an entry
    configured with neither is inert rather than a failure."""
    driver.set_script_config("916", one(s0="", s1=""))

    run = driver.run_script(SCRIPT)

    assert own(run) == [], run.describe()
    assert staged(driver) == []


# --- the --keep-org decision ------------------------------------------------

def test_a_second_destination_gets_its_own_copy_of_the_file(driver):
    """With two servers the first `917` call gets `--keep-org`, which makes it
    `cp` rather than `mv`, because the second call still has to read the same
    file. The second call gets no flag and consumes the original.

    So the original is gone either way — what distinguishes the two-destination
    case is that *both* calls managed to stage a copy. With one file and two
    servers that is two staged files; if the first call had moved the original
    away, the second would have found nothing and staged one.

    This is the flag `917` could not parse until D75: `getopt` rejected
    `--keep-org` as an unknown long option, so `917` ran with no arguments at
    all and `916`'s two-destination mode was the most broken path in the
    script."""
    driver.exec(f"rm -f {LOGS}/message.2").check()
    driver.set_script_config("916", one(s0="archivehost", s1="archivehost2"))

    driver.run_script(SCRIPT)

    assert len(staged(driver)) == 2, staged(driver)


def test_a_single_destination_does_not_keep_the_original(driver):
    """One destination, so nothing else needs the file and `917` moves it."""
    driver.run_script(SCRIPT)

    assert "message.1" not in remaining_logs(driver), remaining_logs(driver)


# --- reporting the child's result -------------------------------------------

def test_a_failing_transfer_is_reported_as_an_error(driver):
    """No archive server exists, so `917` exits non-zero and `916` has to say
    so — this is the `$?` check on the child."""
    run = driver.run_script(SCRIPT)

    assert own(run), run.describe()
    assert own(run)[0].errno == "9162", run.describe()
    assert own(run)[0].level == "E", run.describe()


def test_the_error_names_the_file_and_the_destination(driver):
    """`DESCR[2]` carries two placeholders; an operator needs to know which log
    failed and where it was going."""
    run = driver.run_script(SCRIPT)

    text = own(run)[0].text
    assert "message." in text, text
    assert ARCHIVE in text, text


# --- known defects ----------------------------------------------------------

@pytest.mark.xfail(strict=True, reason="916 never increments SCRIPTINDEX, so every "
                                       "file reports under the same monitoring key")
def test_each_file_reports_under_its_own_index(driver):
    """`916` calls `addOneToIndex` nowhere, so every message it emits carries
    the same `SCRIPTINDEX`. Monitoring keys on `${SCRIPTID}-${SCRIPTINDEX}`, so
    with two logs failing, the second result overwrites the first and the
    dashboard shows one service instead of two.

    Same defect class as D50 in `sc_08`. It matters more here than it looks: the
    glob is explicitly designed to match many rotated logs, so collision is the
    normal case rather than an edge case."""
    run = driver.run_script(SCRIPT)

    indexes = [m.index for m in own(run)]
    assert len(set(indexes)) == len(indexes), run.describe()


def test_help_documents_every_error_code(driver):
    res = driver.exec([driver.script_path(SCRIPT), "--help"])

    for errno in ("9161", "9162"):
        assert f"{errno} / " in res.output, res.output
