"""End-to-end tests for scripts-available/sc_09_firewall.sh.

`iptables` cannot be exercised for real here — the container shares the host's
network namespace policy and loading rules would affect more than the test — so
it is replaced by a fake that replays an `iptables -L -n` listing.

The two ACCEPT lines in the fixture are the `IPTABLES_RULE1` and
`IPTABLES_RULE2` strings from the shipped `config/09.conf` verbatim, which is
itself a capture of real `iptables -L -n` output; the surrounding chain headers
follow the same listing. That makes this fixture a reproduction of real output
rather than an invention, which is what the grep the script performs is
sensitive to.
"""

from __future__ import annotations

import pytest

SCRIPT = "sc_09_firewall.sh"
IPTABLES = "/usr/local/bin/iptables"

SSH_RULE = "ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:22 ctstate NEW,UNTRACKED"
TELNET_RULE = "ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:23 ctstate NEW,UNTRACKED"

HEADER = """\
Chain INPUT (policy DROP)
target     prot opt source               destination
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
"""
FOOTER = """\

Chain FORWARD (policy DROP)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
"""


def listing(*rules: str) -> str:
    return HEADER + "".join(rule + "\n" for rule in rules) + FOOTER


def config(rule1: str = SSH_RULE, rule2: str = TELNET_RULE) -> str:
    return (
        "# generated by test_sc_09_firewall.py\n"
        f"IPTABLES_BIN={IPTABLES}\n"
        f'IPTABLES_RULE1="{rule1}"\n'
        f'IPTABLES_RULE2="{rule2}"\n'
    )


@pytest.fixture
def firewall(syscheck):
    """sc_09 with a fake `iptables` under the test's control."""

    def set_rules(*rules: str) -> None:
        syscheck.install_fake_bin("iptables", "cat <<'EOT'\n" + listing(*rules) + "EOT\n")

    syscheck.set_rules = set_rules
    syscheck.set_script_config("09", config())
    return syscheck


def test_the_required_rule_present_and_the_forbidden_rule_absent_is_ok(firewall):
    firewall.set_rules(SSH_RULE)

    run = firewall.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("I", "093"), run.describe()


def test_a_missing_required_rule_is_an_error(firewall):
    """The rule that must exist is gone — the firewall was flushed, or reloaded
    from an incomplete ruleset."""
    firewall.set_rules()

    run = firewall.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "092"), run.describe()


def test_a_present_forbidden_rule_is_an_error(firewall):
    """The second half of the check: a rule that must *not* be there, such as
    the telnet accept in the shipped config."""
    firewall.set_rules(SSH_RULE, TELNET_RULE)

    run = firewall.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "092"), run.describe()


def test_both_rules_wrong_is_still_a_single_error(firewall):
    firewall.set_rules(TELNET_RULE)

    run = firewall.run_script(SCRIPT)

    assert run.only().errno == "092", run.describe()


def test_iptables_failing_is_reported_and_stops_the_check(firewall):
    """Running `iptables -L -n` without CAP_NET_ADMIN, or with the kernel
    modules absent, exits non-zero. The listing is then an error message, and
    grepping it for rules would report a firewall failure — so the script must
    report the tool failure instead, and only that."""
    firewall.install_fake_bin(
        "iptables",
        "echo 'iptables v1.8.9 (nf_tables): Could not fetch rule set generation id: "
        "Permission denied (you must be root)' >&2\nexit 4\n",
    )

    run = firewall.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "091"), run.describe()


def test_an_absent_iptables_binary_is_reported_as_a_tool_failure(firewall):
    """`IPTABLES_BIN` is a hard-coded absolute path in the config and the two
    shipped candidates differ by distribution, so pointing at a path that does
    not exist is the most likely misconfiguration of this check."""
    firewall.exec(f"rm -f {IPTABLES}")

    run = firewall.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "091"), run.describe()


def test_the_rule_match_is_not_confused_by_a_similar_rule(firewall):
    """dpt:22 must not be satisfied by dpt:2222: a match on a longer port
    number would report ssh as protected when it is not."""
    firewall.set_rules(SSH_RULE.replace("dpt:22 ", "dpt:2222 "))

    run = firewall.run_script(SCRIPT)

    assert run.only().errno == "092", run.describe()


def test_exactly_one_message_is_emitted_per_run(firewall):
    firewall.set_rules(SSH_RULE)

    run = firewall.run_script(SCRIPT)

    assert len(run.messages) == 1, run.describe()
    assert run.indexes == ["02"], run.describe()


def test_help_documents_every_error_code(firewall):
    res = firewall.exec([firewall.script_path(SCRIPT), "--help"])

    for errno in ("091", "092", "093"):
        assert f"{errno} / " in res.output, res.output


@pytest.mark.parametrize("empty", ["rule1", "rule2"])
def test_an_unconfigured_rule_is_reported_as_a_config_error(firewall, empty):
    """The regression guard for D28. `grep ""` matches every line, so a config
    where `IPTABLES_RULE1` was never filled in — or was emptied by a typo —
    reported the firewall as correct on any host with any ruleset at all,
    including an empty one; the same expansion in the other direction pinned the
    check to a permanent error. Both are the D4 class: an empty config value
    must produce a complaint, not a verdict."""
    firewall.set_script_config("09", config(**{empty: ""}))
    firewall.set_rules()

    run = firewall.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "094"), run.describe()
    assert "IPTABLES_RULE" in msg.text, msg.text


def test_the_help_documents_the_config_error_code(firewall):
    res = firewall.exec([firewall.script_path(SCRIPT), "--help"])

    assert "094 / " in res.output, res.output
