"""End-to-end tests for scripts-available/sc_17_ntp.sh.

sc_17 supports two time clients and decides between them by asking `systemctl`
which one is active, so three tools are faked: `systemctl`, `timedatectl` and
`chronyc`. Each is installed per test with the answers that test needs.

    # UNVERIFIED SHAPE
    The `chronyc -c` CSV rows and the `timedatectl timesync-status` block are
    written from the documented field order, not captured from a running host —
    neither this repo nor its docs carry a sample. The field *order* is what the
    script depends on (it reads the CSV positionally into 14 and 10 names), so
    that is the part a capture would confirm.

The container has neither systemd nor chrony, which is also why this suite
cannot be REAL-OS: there is no init to ask.
"""

from __future__ import annotations

import pytest

SCRIPT = "sc_17_ntp.sh"
SERVER = "192.168.1.10"

# chronyc -n -c tracking: refid,server,stratum,reftime,systemoffset,lastoffset,
# rmsoffset,freq,residualfreq,skew,rootdelay,rootdisp,updateinterval,leapstatus
TRACKING_FIELDS = [
    "C0A8010A", SERVER, "2", "1757000000.0", "0.000001234", "0.000002345",
    "0.000003456", "-12.345", "0.001", "0.123", "0.012345", "0.023456",
    "64.2", "Normal",
]

# chronyc -n -c sources: mode,state,name,stratum,poll,reach,lastrx,offset,
# measuredoffset,error
SOURCE_FIELDS = ["^", "*", SERVER, "2", "6", "377", "23",
                 "0.000012", "0.000013", "0.000014"]


def tracking(**overrides) -> str:
    fields = list(TRACKING_FIELDS)
    for name, value in overrides.items():
        fields[{"refid": 0, "server": 1, "leap": 13}[name]] = value
    return ",".join(fields) + "\n"


def sources(reach: str = "377") -> str:
    fields = list(SOURCE_FIELDS)
    fields[5] = reach
    return ",".join(fields) + "\n"


def timesync_status(leap: str = "normal", packets: str = "7",
                    server: str = SERVER) -> str:
    return (
        f"       Server: {server} (ntp.example.com)\n"
        "Poll interval: 1min 4s (min: 32s; max 34min 8s)\n"
        f"         Leap: {leap}\n"
        "      Version: 4\n"
        "      Stratum: 2\n"
        "    Reference: C0A8010A\n"
        "       Offset: +1.234ms\n"
        "        Delay: 12.345ms\n"
        "       Jitter: 1.234ms\n"
        f" Packet count: {packets}\n"
        "    Frequency: +12.345ppm\n"
    )


def config() -> str:
    return (
        "# generated by test_sc_17_ntp.py\n"
        'SYSTEMCTLBIN="/usr/local/bin/systemctl"\n'
        'TIMEDATECTLBIN="/usr/local/bin/timedatectl"\n'
        'CHRONYBIN="/usr/local/bin/chronyc"\n'
    )


@pytest.fixture
def ntp(syscheck):
    """sc_17 with `systemctl`, `timedatectl` and `chronyc` under test control.

    Defaults to the healthy chrony host; every test overrides one piece of it.
    """

    def set_active(chrony: bool = False, timesyncd: bool = False) -> None:
        """`systemctl is-active --quiet <unit>` — exit status is the answer."""
        active = []
        if chrony:
            active += ["chronyd.service", "chrony.service"]
        if timesyncd:
            active += ["systemd-timesyncd.service"]
        cases = "".join(f"  {unit}) exit 0 ;;\n" for unit in active)
        syscheck.install_fake_bin(
            "systemctl",
            'if [ "$1" != "is-active" ] ; then exit 1 ; fi\n'
            'case "${!#}" in\n'
            f"{cases}"
            "  *) exit 3 ;;\n"
            "esac\n",
        )

    def set_timedatectl(kernel_synced: bool = True, status: str | None = None,
                        failing: bool = False) -> None:
        body = ["#!/bin/bash"]
        if failing:
            body += ["echo 'Failed to query server: Connection refused' >&2", "exit 1"]
        else:
            body += [
                'if [ "$1" = "show" ] ; then',
                f"  echo NTPSynchronized={'yes' if kernel_synced else 'no'}",
                "  exit 0",
                "fi",
                "cat <<'EOT'",
                status if status is not None else timesync_status(),
                "EOT",
            ]
        syscheck.install_fake_bin("timedatectl", "\n".join(body) + "\n")

    def set_chronyc(tracking_csv: str | None = None, sources_csv: str | None = None,
                    tracking_fails: bool = False, sources_fails: bool = False) -> None:
        tracking_csv = tracking() if tracking_csv is None else tracking_csv
        sources_csv = sources() if sources_csv is None else sources_csv
        body = [
            "#!/bin/bash",
            'case "${!#}" in',
            "  tracking)",
            "    " + ("exit 1" if tracking_fails else
                      "cat <<'EOT'\n" + tracking_csv + "EOT"),
            "    ;;",
            "  sources)",
            "    " + ("exit 1" if sources_fails else
                      "cat <<'EOT'\n" + sources_csv + "EOT"),
            "    ;;",
            "  *) exit 1 ;;",
            "esac",
        ]
        syscheck.install_fake_bin("chronyc", "\n".join(body) + "\n")

    syscheck.set_active = set_active
    syscheck.set_timedatectl = set_timedatectl
    syscheck.set_chronyc = set_chronyc

    syscheck.set_script_config("17", config())
    set_active(chrony=True)
    set_timedatectl()
    set_chronyc()
    return syscheck


def test_a_synchronised_chrony_host_is_reported_ok(ntp):
    run = ntp.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno, msg.index) == ("I", "171", "01"), run.describe()
    assert "synchronized" in msg.text, msg.text
    assert SERVER in msg.text, msg.text
    assert "reachable sources: 1" in msg.text, msg.text


def test_an_unsynchronised_chrony_host_is_an_error(ntp):
    """`Leap status` is anything but Normal/Insert second/Delete second — chrony
    is running but has given up on the clock."""
    ntp.set_chronyc(tracking_csv=tracking(leap="Not synchronised"))

    run = ntp.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "173"), run.describe()


def test_a_host_synchronised_only_to_itself_is_an_error(ntp):
    """Refid 7F7F0101 is chrony's local reference: the daemon reports a healthy
    leap status while tracking nothing but its own clock, which is exactly the
    drift this check exists to catch."""
    ntp.set_chronyc(tracking_csv=tracking(refid="7F7F0101"))

    run = ntp.run_script(SCRIPT)

    assert run.only().errno == "173", run.describe()


def test_no_reachable_source_is_a_warning(ntp):
    """`reach` 0: the source is configured but no packet has come back. The
    clock is still good — for now — so this is a warning, not an outage."""
    ntp.set_chronyc(sources_csv=sources(reach="0"))

    run = ntp.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("W", "172"), run.describe()
    assert "reachable sources: 0" in msg.text, msg.text


def test_a_kernel_that_is_not_synchronised_is_a_warning(ntp):
    """chrony believes it is in sync but the kernel's own NTP flag disagrees —
    the state that leaves `date` and the daemon telling different stories."""
    ntp.set_timedatectl(kernel_synced=False)

    run = ntp.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("W", "172"), run.describe()


def test_a_failing_chronyc_is_an_error(ntp):
    """The daemon is active per systemd but its control socket does not answer."""
    ntp.set_chronyc(tracking_fails=True)

    run = ntp.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "173"), run.describe()
    assert "tracking" in msg.text, msg.text


def test_a_failing_sources_query_is_an_error(ntp):
    ntp.set_chronyc(sources_fails=True)

    run = ntp.run_script(SCRIPT)

    assert run.only().errno == "173", run.describe()


def test_a_chronyc_that_answers_with_nothing_is_an_error(ntp):
    """Empty output is not "no sources" — it is a query that did not work, and
    reading it as zero sources would report a warning instead of an error."""
    ntp.set_chronyc(tracking_csv="")

    run = ntp.run_script(SCRIPT)

    assert run.only().errno == "173", run.describe()


def test_a_synchronised_timesyncd_host_is_reported_ok(ntp):
    """The other supported backend, selected by systemd-timesyncd being the
    active unit."""
    ntp.set_active(timesyncd=True)

    run = ntp.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("I", "171"), run.describe()
    assert SERVER in msg.text, msg.text


def test_an_unsynchronised_timesyncd_host_is_an_error(ntp):
    ntp.set_active(timesyncd=True)
    ntp.set_timedatectl(status=timesync_status(leap="not synchronized"))

    run = ntp.run_script(SCRIPT)

    assert run.only().errno == "173", run.describe()


def test_a_timesyncd_host_that_has_received_no_packets_is_an_error(ntp):
    """`Packet count: 0` — the unit is running and configured, and nothing has
    ever come back from the server."""
    ntp.set_active(timesyncd=True)
    ntp.set_timedatectl(status=timesync_status(packets="0"))

    run = ntp.run_script(SCRIPT)

    assert run.only().errno == "173", run.describe()


def test_a_failing_timedatectl_is_an_error(ntp):
    ntp.set_active(timesyncd=True)
    ntp.set_timedatectl(failing=True)

    run = ntp.run_script(SCRIPT)

    assert run.only().errno == "173", run.describe()


def test_two_active_time_clients_are_an_error(ntp):
    """chrony and systemd-timesyncd both stepping the same clock: they fight,
    and neither is authoritative."""
    ntp.set_active(chrony=True, timesyncd=True)

    run = ntp.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "174"), run.describe()
    assert "multiple time clients" in msg.text, msg.text


def test_no_active_time_client_is_an_error(ntp):
    """Nothing is keeping the clock — on a CA host, the failure behind
    certificates dated in the future."""
    ntp.set_active()

    run = ntp.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "175"), run.describe()
    assert "no supported time client" in msg.text, msg.text


def test_exactly_one_message_is_emitted_per_run(ntp):
    run = ntp.run_script(SCRIPT)

    assert len(run.messages) == 1, run.describe()


def test_help_documents_every_error_code(ntp):
    res = ntp.exec([ntp.script_path(SCRIPT), "--help"])

    for errno in ("171", "172", "173", "174", "175"):
        assert f"{errno} / " in res.output, res.output
