"""End-to-end tests for related-available/915_remote_command_via_ssh.sh.

`915` runs one command on a remote host over ssh and echoes its output. It is
the transport every other script in the ssh group leans on — `906`, `917`, `930`
and `sc_28` all delegate to it — so this suite is where the ssh machinery itself
is proven, and the others can treat `915` as a seam.

REAL-SVC: a real `sshd` on the test network, key-only, started by
`start_sshd_node`. The keypair is generated in the syscheck container and its
public half installed on the remote. Nothing about the connection is mocked:
real `ssh`, real host keys, real authentication.

The sshd node runs the syscheck image rather than a dedicated sshd image, so the
far end has the same coreutils the callers assume when they send things like
`df --block-size=M` or `mktemp -p` across.
"""

from __future__ import annotations

import pytest

from conftest import SSH_KEY as KEY, SSH_REMOTE_USER as REMOTE_USER

SCRIPT = "related-available/915_remote_command_via_ssh.sh"

pytestmark = pytest.mark.slow


@pytest.fixture
def remote(syscheck, sshd_node):
    syscheck.set_script_config(
        "915",
        "# generated by test_915_remote_command_via_ssh.py\n"
        # the stock value is just ConnectTimeout; a first connection to an
        # unknown host would otherwise block on the host-key prompt
        'SSHOPTIONS="-o ConnectTimeout=10 -o StrictHostKeyChecking=no '
        '-o UserKnownHostsFile=/dev/null -o LogLevel=ERROR"\n')
    syscheck.sshd = sshd_node
    return syscheck


def run(sc, *args):
    return sc.run_script(SCRIPT, *args)


def own(run) -> list:
    return [m for m in run.messages if m.scriptid == "915"]


def ok_args(sc, command: str) -> tuple[str, ...]:
    return (f"--host={sc.sshd}", f"--command={command}",
            f"--user={REMOTE_USER}", f"--key={KEY}")


# --- the transport ----------------------------------------------------------

def test_a_command_runs_on_the_remote_host(remote):
    """The whole purpose. `whoami` answers with the remote account, which is
    proof the command ran there rather than locally."""
    res = remote.exec([remote.script_path(SCRIPT), *ok_args(remote, "whoami")])

    assert REMOTE_USER in res.stdout, res.output


def test_the_command_output_is_returned_to_the_caller(remote):
    """Callers capture `915`'s stdout — `906` reads a `df` figure out of it and
    `sc_28` reads an interface address. The output has to come back clean."""
    res = remote.exec([remote.script_path(SCRIPT),
                       *ok_args(remote, "echo marker-42")])

    assert "marker-42" in res.stdout, res.output


def test_the_remote_filesystem_is_reachable(remote):
    """`906` sends `df --block-size=M` across and parses the answer, so the far
    end needs the real tool, not a shell builtin."""
    res = remote.exec([remote.script_path(SCRIPT),
                       *ok_args(remote, 'df --block-size=M "/home"')])

    assert "M" in res.stdout, res.output


def test_a_successful_command_is_reported(remote):
    run_ = remote.run_script(SCRIPT, *ok_args(remote, "true"))

    msg = own(run_)[0]
    assert (msg.level, msg.errno) == ("I", "9151"), run_.describe()


# --- failures ---------------------------------------------------------------

def test_a_failing_remote_command_is_reported_with_its_exit_code(remote):
    """`915` passes the remote exit status through, so a caller can branch on
    it — which is exactly what `917` and `906` do."""
    run_ = remote.run_script(SCRIPT, *ok_args(remote, "exit 3"))

    msg = own(run_)[0]
    assert (msg.level, msg.errno) == ("E", "9154"), run_.describe()
    assert "3" in msg.text, msg.text


def test_the_remote_exit_code_becomes_the_script_exit_code(remote):
    res = remote.exec([remote.script_path(SCRIPT), *ok_args(remote, "exit 7")])

    assert res.exit_code == 7, res.output


def test_an_unreachable_host_is_reported(remote):
    run_ = remote.run_script(SCRIPT, "--host=no-such-host",
                             "--command=true", f"--user={REMOTE_USER}",
                             f"--key={KEY}")

    assert any(m.errno == "9154" for m in own(run_)), run_.describe()


def test_a_wrong_key_is_refused(remote):
    """Authentication must fail closed — a key the remote does not trust is a
    failed command, not a silent success."""
    remote.exec(f"ssh-keygen -q -t ed25519 -N '' -f /tmp/wrong-key <<< y").check()

    run_ = remote.run_script(SCRIPT, f"--host={remote.sshd}", "--command=true",
                             f"--user={REMOTE_USER}", "--key=/tmp/wrong-key")

    assert any(m.errno == "9154" for m in own(run_)), run_.describe()


# --- argument guards --------------------------------------------------------

def test_a_missing_host_is_reported(remote):
    run_ = remote.run_script(SCRIPT, "--command=true", f"--user={REMOTE_USER}")

    assert own(run_)[0].errno == "9152", run_.describe()


def test_a_missing_command_is_reported(remote):
    run_ = remote.run_script(SCRIPT, f"--host={remote.sshd}",
                             f"--user={REMOTE_USER}")

    assert own(run_)[0].errno == "9153", run_.describe()


def test_a_missing_user_stops_the_run(remote):
    """`915` requires a user even though its callers treat it as optional —
    `917` documents its own user argument as "if not specified the executing
    user will be used". Pinned because that disagreement is real: `917` passing
    an empty `--user` gets a hard failure here."""
    run_ = remote.run_script(SCRIPT, f"--host={remote.sshd}", "--command=true")

    assert own(run_), run_.describe()
    assert own(run_)[0].level == "E", run_.describe()


# --- known defects ----------------------------------------------------------

def test_a_missing_user_is_not_reported_as_a_missing_command(remote):
    """D110, fixed 2026-09-18. The two guards were

        if [ "x$SSHCMD" = "x" ]    ; then ... ERRNO[3] ... DESCR[3] ...
        if [ "x$SSHTOUSER" = "x" ] ; then ... ERRNO[3] ... DESCR[3] ...

    so omitting the user reported `9153`, "Command not found" — naming the wrong
    argument entirely, and `HELP[3]` then advised "Specify a command to run".

    It reached beyond cosmetics: `917` documents its own user argument as
    optional, so `917` passing an empty `--user` landed here and was told to
    look at the command.

    All four codes were in use, so the fix needed a fifth. `NO_OF_ERR` is now 5
    with `DESCR[5]`/`HELP[5]`, following `DESCR[2]`'s model of one code per
    missing argument."""
    run_ = remote.run_script(SCRIPT, f"--host={remote.sshd}", "--command=true")

    assert own(run_)[0].errno == "9155", run_.describe()
    assert remote.sshd in own(run_)[0].text, own(run_)[0].text


def test_the_success_message_names_the_command_that_ran(remote):
    """D111, fixed 2026-09-18. `DESCR[1]` was `"Command executed successfully
    (%s)"` — a single placeholder — while the call passed

        -1 "${SSHTOUSER}" -2 "${SSHHOST}" -3 "${SSHCMD}"

    So the one `%s` took the *user*, and the host and command were dropped. The
    log recorded that someone successfully ran something, somewhere — and this
    is the script every remote operation in the tree funnels through, so that
    was the audit trail.

    Fixed in the language file rather than the call site, which was already
    passing all three."""
    run_ = remote.run_script(SCRIPT, *ok_args(remote, "echo marker-42"))

    assert "marker-42" in own(run_)[0].text, own(run_)[0].text


def test_a_failed_command_names_the_host_and_command(remote):
    """`DESCR[4]` used to carry only the exit number, which is the message
    someone reads during an incident. It now names what was attempted and
    where."""
    run_ = remote.run_script(SCRIPT, *ok_args(remote, "exit 5"))

    failed = [m for m in own(run_) if m.errno == "9154"]
    assert failed, run_.describe()
    assert remote.sshd in failed[0].text, failed[0].text
    assert "exit 5" in failed[0].text, failed[0].text


def test_the_guards_name_what_they_were_given(remote):
    """Each guard used to render its `(%s)` empty. They now report the
    complementary field, so an operator can tell which caller misconfigured."""
    run_ = remote.run_script(SCRIPT, "--command=true", f"--user={REMOTE_USER}")

    assert own(run_)[0].errno == "9152", run_.describe()
    assert "true" in own(run_)[0].text, own(run_)[0].text


def test_a_command_runs_without_a_key(remote):
    """`915` mandates a user but not a key, and `917` treats the key as
    optional too. With `SSHFROMKEY` empty and unquoted, `-i` used to swallow the
    `-l` that followed it:

        ssh -i -l bob h1 true

    The key is now assembled into an array that is simply absent when unset.
    Driven against a host that does not exist: what matters is that the command
    is well formed and fails on the connection, not on its own arguments."""
    run_ = remote.run_script(SCRIPT, "--host=no-such-host", "--command=true",
                             f"--user={REMOTE_USER}")

    assert own(run_), run_.describe()
    assert own(run_)[0].errno == "9154", run_.describe()
    assert "illegal option" not in run_.output.lower(), run_.output


def test_help_documents_every_error_code(remote):
    res = remote.exec([remote.script_path(SCRIPT), "--help"])

    for errno in ("9151", "9152", "9153", "9154", "9155"):
        assert f"{errno} / " in res.output, res.output
