"""End-to-end tests for scripts-available/sc_34_redis.sh against a real Redis.

No mock: `redis:7` with `requirepass` set, on the test network, and the real
`redis-cli` in the syscheck image talking to it. That covers the one thing a
fake could not — that `redis-cli -a <pw> ping` actually answers `PONG` through
this exact command line — as well as the failure paths, which are produced by
breaking the connection for real: wrong password, wrong port, stopped server.

The check is written for a VIP, so `REDIS_IP[]`, `REDIS_PORT[]` and `REDIS_PW[]`
are parallel arrays of instances; the tests drive one, several, and none.
"""

from __future__ import annotations

import pytest

from syscheck_harness import start_redis_node

SCRIPT = "sc_34_redis.sh"
PASSWORD = "s3cr3t-pw"
REDIS_PORT = 6379

pytestmark = pytest.mark.slow


@pytest.fixture(scope="module")
def redis_node(syscheck_network):
    """One Redis for the whole module — every test here only reads from it."""
    tc, name = start_redis_node(syscheck_network, password=PASSWORD)
    try:
        yield name
    finally:
        tc.stop()


def config(*instances: tuple[str, int, str], rediscli: str = "/usr/bin/redis-cli") -> str:
    lines = ["# generated by test_sc_34_redis.py\n", f"REDISCLI={rediscli}\n"]
    for i, (host, port, password) in enumerate(instances):
        lines.append(f"REDIS_IP[{i}]={host}\n")
        lines.append(f"REDIS_PORT[{i}]={port}\n")
        lines.append(f"REDIS_PW[{i}]={password}\n")
    return "".join(lines)


@pytest.fixture
def redis(syscheck, redis_node):
    """sc_34 pointed at the live Redis by container name."""
    syscheck.redis_host = redis_node
    syscheck.set_script_config("34", config((redis_node, REDIS_PORT, PASSWORD)))
    return syscheck


def test_a_live_server_answers_pong(redis):
    run = redis.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("I", "341"), run.describe()
    assert "PONG" in msg.text, msg.text
    assert redis.redis_host in msg.text and str(REDIS_PORT) in msg.text, msg.text


def test_a_wrong_password_is_reported_as_not_responding(redis):
    """The server is up and reachable; it just refuses this client. That has to
    read as a failure — a check that treated an auth error as "reachable" would
    stay green through a botched credential rotation."""
    redis.set_script_config("34", config((redis.redis_host, REDIS_PORT, "wrong-pw")))

    run = redis.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "342"), run.describe()


def test_a_closed_port_is_reported_as_not_responding(redis):
    """Nothing is listening there — the VIP moved, or the instance is down."""
    redis.set_script_config("34", config((redis.redis_host, 6399, PASSWORD)))

    run = redis.run_script(SCRIPT)

    assert run.only().errno == "342", run.describe()


def test_an_unresolvable_host_is_reported_as_not_responding(redis):
    redis.set_script_config("34", config(("no-such-redis-host", REDIS_PORT, PASSWORD)))

    run = redis.run_script(SCRIPT)

    assert run.only().errno == "342", run.describe()


def test_a_stopped_server_is_reported_as_not_responding(redis, syscheck_network):
    """The real failure this check exists for, produced for real: start a second
    Redis, prove it answers, stop it, and check the verdict flips."""
    tc, name = start_redis_node(syscheck_network, password=PASSWORD)
    try:
        redis.set_script_config("34", config((name, REDIS_PORT, PASSWORD)))
        assert redis.run_script(SCRIPT).only().errno == "341"
    finally:
        tc.stop()

    run = redis.run_script(SCRIPT)

    assert run.only().errno == "342", run.describe()


def test_every_configured_instance_is_checked(redis):
    """Three entries, three messages, in configuration order — the first live,
    the second on a closed port, the third unresolvable."""
    redis.set_script_config("34", config(
        (redis.redis_host, REDIS_PORT, PASSWORD),
        (redis.redis_host, 6399, PASSWORD),
        ("no-such-redis-host", REDIS_PORT, PASSWORD),
    ))

    run = redis.run_script(SCRIPT)

    assert run.levels == ["I", "E", "E"], run.describe()
    # the indexes used to start at 02: a raise at the top of the script burned
    # 01 before the loop, the same defect class as D25 and D29
    assert run.indexes == ["01", "02", "03"], run.describe()


def test_no_configured_instance_reports_nothing(redis):
    redis.set_script_config("34", config())

    run = redis.run_script(SCRIPT)

    assert run.messages == [], run.describe()


@pytest.mark.parametrize("missing, field", [
    ("host", 0), ("port", 1), ("password", 2),
])
def test_an_incomplete_instance_is_reported_as_a_config_error(redis, missing, field):
    """Each of the three settings is guarded separately by the script, and the
    message names which one was not supplied."""
    values = [redis.redis_host, str(REDIS_PORT), PASSWORD]
    values[field] = ""
    lines = ["REDISCLI=/usr/bin/redis-cli\n",
             f"REDIS_IP[0]={values[0]}\n",
             f"REDIS_PORT[0]={values[1]}\n",
             f"REDIS_PW[0]={values[2]}\n"]
    redis.set_script_config("34", "".join(lines))

    run = redis.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "343"), run.describe()
    assert "not sent" in msg.text, msg.text


def test_a_missing_redis_cli_is_reported_before_anything_is_checked(redis):
    """`REDISCLI` is an absolute path in the config, so a host without
    redis-tools installed — or with it somewhere else — must say so rather than
    report every instance down."""
    redis.set_script_config("34", config((redis.redis_host, REDIS_PORT, PASSWORD),
                                        rediscli=""))

    run = redis.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "344"), run.describe()


def test_help_documents_every_error_code(redis):
    res = redis.exec([redis.script_path(SCRIPT), "--help"])

    for errno in ("341", "342", "343", "344"):
        assert f"{errno} / " in res.output, res.output
