"""End-to-end tests for scripts-available/sc_38_mysql_connections.sh.

The figures come from a real `mysqladmin` talking to a real `mariadb:11`:
`Threads_connected` from `extended-status`, `max_connections` from `variables`.

The thresholds are driven two ways on purpose. Most cases move
`WARN_PERCENT`/`ERROR_PERCENT` around the connection count the server already
has, which is cheap and exact; one case instead opens real connections and
asserts the reported number goes up, which is the part a threshold test cannot
prove — that `Threads_connected` is being read at all, rather than some other
column of the same row.

sc_38 takes no `-h`, so the server is selected through `~/.my.cnf`, as on a host
whose database is not local.
"""

from __future__ import annotations

import time

import pytest

from conftest import MARIADB_DATABASE, MARIADB_ROOT_PASSWORD

SCRIPT = "sc_38_mysql_connections.sh"

pytestmark = pytest.mark.slow


def config(warn: int = 50, error: int = 70) -> str:
    return (
        "# generated by test_sc_38_mysql_connections.py\n"
        f"WARN_PERCENT={warn}\n"
        f"ERROR_PERCENT={error}\n"
    )


@pytest.fixture
def connections(syscheck, mariadb_node):
    """sc_38 pointed at the shared MariaDB through ~/.my.cnf."""
    syscheck.write_file(
        "/root/.my.cnf",
        f"[client]\nhost={mariadb_node}\nuser=root\npassword={MARIADB_ROOT_PASSWORD}\n",
    )
    syscheck.set_script_config("38", config())

    def open_connections(count: int, seconds: int = 15):
        """Hold `count` real connections open, and wait until the server sees
        them — asserting on a connection count that has not landed yet is the
        obvious way to make this suite flaky."""
        for _ in range(count):
            syscheck.exec(
                f"nohup mariadb {MARIADB_DATABASE} -e 'SELECT SLEEP({seconds})' "
                ">/dev/null 2>&1 & echo started"
            )
        deadline = time.monotonic() + 10
        while time.monotonic() < deadline:
            if threads_connected() >= count + 1:
                return
            time.sleep(0.2)
        raise AssertionError(f"server never reported {count} extra connections")

    def threads_connected() -> int:
        res = syscheck.exec(
            "mysqladmin extended-status | grep ' Threads_connected ' | awk '{print $4}'"
        ).check()
        return int(res.stdout.strip())

    syscheck.open_connections = open_connections
    syscheck.threads_connected = threads_connected
    return syscheck


def test_an_idle_server_is_well_under_the_limits(connections):
    run = connections.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno, msg.index) == ("I", "381", "01"), run.describe()


def test_the_message_carries_the_real_figures(connections):
    """current, max and the percentage, all three from the server rather than
    from the config."""
    current = connections.threads_connected()

    msg = connections.run_script(SCRIPT).only()

    assert f"curr: {current}" in msg.text, msg.text
    assert "max: 151" in msg.text, msg.text          # MariaDB's default
    assert "percent" in msg.text, msg.text


def test_opening_connections_raises_the_reported_number(connections):
    """The one thing the threshold cases cannot show: the figure tracks reality.
    Ten real connections must be visible to the check."""
    before = int(connections.run_script(SCRIPT).only().text.split("curr: ")[1].split()[0])

    connections.open_connections(10)

    after = int(connections.run_script(SCRIPT).only().text.split("curr: ")[1].split()[0])
    assert after >= before + 10, f"{before} -> {after}"


def test_crossing_the_warn_threshold_is_reported(connections):
    """`WARN_PERCENT=0` puts the server's existing connections over the warning
    line without opening 76 of them."""
    connections.set_script_config("38", config(warn=0, error=99))

    run = connections.run_script(SCRIPT)

    msg = run.only()
    assert msg.errno == "384", run.describe()
    assert msg.level == "W", run.describe()
    assert "percent" in msg.text, msg.text


def test_crossing_the_error_threshold_is_reported(connections):
    connections.set_script_config("38", config(warn=0, error=0))

    run = connections.run_script(SCRIPT)

    assert run.only().errno == "385", run.describe()
    assert run.only().level == "E", run.describe()


def test_sitting_exactly_on_the_threshold_is_not_a_breach(connections):
    """`-gt`, not `-ge`, on both limits."""
    current = connections.threads_connected()
    percent = 100 * current // 151
    connections.set_script_config("38", config(warn=percent, error=percent))

    run = connections.run_script(SCRIPT)

    assert run.only().errno == "381", run.describe()


def test_a_server_that_cannot_be_reached_is_reported(connections):
    """`mysqladmin` fails, so no figure comes back at all. The check must say so
    rather than divide by an empty string."""
    connections.write_file("/root/.my.cnf", "[client]\nhost=no-such-database-host\n")

    run = connections.run_script(SCRIPT)

    msg = run.only()
    assert msg.level == "E", run.describe()
    # this message used to go out under index 00, the D29 class
    assert msg.index == "01", run.describe()


def test_an_unreadable_max_connections_is_reported(connections):
    """`extended-status` answers but `variables` does not carry
    `max_connections` — the branch a live server cannot produce, so `mysqladmin`
    is wrapped rather than faked: every subcommand but `variables` goes to the
    real server."""
    connections.install_fake_bin(
        "mysqladmin",
        'if [ "$1" = "variables" ] ; then\n'
        '  /usr/bin/mysqladmin variables | grep -v "| max_connections"\n'
        "  exit 0\n"
        "fi\n"
        'exec /usr/bin/mysqladmin "$@"\n',
    )

    run = connections.run_script(SCRIPT)

    msg = run.only()
    assert msg.level == "E", run.describe()
    assert msg.index == "01", run.describe()


def test_exactly_one_message_is_emitted_per_run(connections):
    run = connections.run_script(SCRIPT)

    assert len(run.messages) == 1, run.describe()


def test_help_documents_every_error_code(connections):
    res = connections.exec([connections.script_path(SCRIPT), "--help"])

    for errno in ("381", "382", "383", "384", "385"):
        assert f"{errno} / " in res.output, res.output


def test_the_read_failure_messages_match_what_failed(connections):
    """D36, fixed 2026-09-18. `lang/38.english` has `DESCR[2]="problem reading
    max variable"` and `DESCR[3]="problem reading connections"`, but the script
    sent `ERRNO[2]` when *Threads_connected* could not be read and `ERRNO[3]`
    when *max_connections* could not be. An operator reading either message was
    sent to look at the wrong figure.

    Fixed by swapping the indices in the **script**, not the texts in the
    language file: the errno is the monitoring contract, so redefining what
    `382` means would have silently changed every historical record and any
    alert rule keyed on it."""
    connections.write_file("/root/.my.cnf", "[client]\nhost=no-such-database-host\n")

    run = connections.run_script(SCRIPT)

    assert "connections" in run.only().text, run.describe()


def test_the_warning_threshold_is_a_warning(connections):
    """D37, fixed 2026-09-18. The script defined two thresholds and reported
    both at `$ERROR`, with the texts the wrong way round on top of that:
    crossing `WARN_PERCENT` sent `DESCR[5]`, "Very Hugh level of connections",
    while crossing the higher `ERROR_PERCENT` sent `DESCR[4]`, "High level". The
    milder condition produced the louder message, and neither could be told
    apart by level — which is what the Icinga integration maps to a status code.

    `384` is now the warning and `385` the error, matching their texts and their
    severity ordering."""
    connections.set_script_config("38", config(warn=0, error=99))

    run = connections.run_script(SCRIPT)

    msg = run.only()
    assert msg.level == "W", run.describe()
    assert "High level" in msg.text, msg.text
