"""End-to-end tests for related-available/911_activate_VIP.sh.

`911` brings a virtual IP up on this node: it refuses if the VIP is already
local, refuses if another node answers it, otherwise configures the alias
interface, records that this node holds the VIP, and sends a gratuitous ARP so
the router updates its cache.

FAKE-BIN: `ifconfig`, `route`, `ping` and `arping` are stubbed. Real ones would
need NET_ADMIN and a second host to fail over from, and every branch here turns
on what those four commands *say* rather than on the kernel actually
reconfiguring — so the stubs sit exactly at the decision points.

Each stub records its argv, which is how the tests tell "reported success" from
"actually reconfigured the interface" — a distinction that matters more than
usual here, and is the subject of D134.
"""

from __future__ import annotations

import pytest

SCRIPT = "related-available/911_activate_VIP.sh"
LOG = "/tmp/911/calls"
MARKER = "/opt/syscheck/var/this_node_has_the_vip"
VIP = "192.168.0.10"
IFACE = "eth1:0"

pytestmark = pytest.mark.slow


def config(*, vip: str = VIP, iface: str = IFACE) -> str:
    return ("# generated by test_911_activate_vip.py\n"
            "IFCONFIG=/usr/local/bin/ifconfig\n"
            "ROUTE=/usr/local/bin/route\n"
            f"HOSTNAME_VIRTUAL={vip}\n"
            "NETMASK_VIRTUAL=255.255.255.0\n"
            f'IF_VIRTUAL="{iface}"\n')


def install_fakes(sc, *, vip_is_local: bool = False, vip_answers_ping: bool = False,
                  ifconfig_rc: int = 0, arping_rc: int = 0) -> None:
    local_line = (f"          inet addr:{VIP}  Bcast:192.168.0.255  "
                  "Mask:255.255.255.0" if vip_is_local else
                  "          inet addr:10.0.0.5  Bcast:10.0.0.255  Mask:255.255.255.0")
    sc.exec(f"mkdir -p /tmp/911 && rm -f {LOG}.*").check()
    sc.install_fake_bin("ifconfig",
                        "#!/bin/bash\n"
                        f'echo "$@" >> {LOG}.ifconfig\n'
                        f'case "$*" in *up) exit {ifconfig_rc} ;; esac\n'
                        f'echo "{IFACE} Link encap:Ethernet"\n'
                        f'echo "{local_line}"\n'
                        "exit 0\n")
    sc.install_fake_bin("route",
                        "#!/bin/bash\n"
                        f'echo "$@" >> {LOG}.route\n'
                        "echo 'Kernel IP routing table'\n"
                        "echo '0.0.0.0         192.168.0.1     0.0.0.0  UG  0 0 0 eth0'\n")
    sc.install_fake_bin("ping",
                        "#!/bin/bash\n"
                        f'echo "$@" >> {LOG}.ping\n'
                        f"exit {0 if vip_answers_ping else 1}\n")
    sc.install_fake_bin("arping",
                        "#!/bin/bash\n"
                        f'echo "$@" >> {LOG}.arping\n'
                        f"exit {arping_rc}\n")


@pytest.fixture
def vip(syscheck):
    install_fakes(syscheck)
    syscheck.exec(f"rm -f {MARKER}").check()
    syscheck.set_script_config("911", config())
    return syscheck


def own(run) -> list:
    return [m for m in run.messages if m.scriptid == "911"]


def calls(sc, tool: str) -> list[str]:
    path = f"{LOG}.{tool}"
    if not sc.file_exists(path):
        return []
    return [l for l in sc.read_file(path).splitlines() if l.strip()]


# --- the refusals -----------------------------------------------------------

def test_an_already_local_vip_is_refused(vip):
    """Bringing up an address this node already holds would be a no-op at best;
    `911` says so and stops."""
    install_fakes(vip, vip_is_local=True)

    run = vip.run_script(SCRIPT)

    assert own(run)[-1].errno == "9113", run.describe()


def test_an_already_local_vip_is_not_reconfigured(vip):
    install_fakes(vip, vip_is_local=True)

    vip.run_script(SCRIPT)

    assert not any("up" in c for c in calls(vip, "ifconfig")), calls(vip, "ifconfig")


def test_a_vip_answering_elsewhere_is_refused(vip):
    """The split-brain guard, and the most important refusal in the script: if
    something already answers the VIP, taking it here would give two hosts the
    same address."""
    install_fakes(vip, vip_answers_ping=True)

    run = vip.run_script(SCRIPT)

    assert own(run)[-1].errno == "9114", run.describe()


def test_a_vip_answering_elsewhere_is_not_taken(vip):
    install_fakes(vip, vip_answers_ping=True)

    vip.run_script(SCRIPT)

    assert not any("up" in c for c in calls(vip, "ifconfig")), calls(vip, "ifconfig")
    assert not vip.file_exists(MARKER), "the marker was written anyway"


def test_the_vip_is_pinged_before_being_taken(vip):
    vip.run_script(SCRIPT)

    assert any(VIP in c for c in calls(vip, "ping")), calls(vip, "ping")


# --- the happy path ---------------------------------------------------------

def test_a_free_vip_is_reported_as_activated(vip):
    run = vip.run_script(SCRIPT)

    assert any(m.errno == "9111" for m in own(run)), run.describe()


def test_the_marker_file_records_that_this_node_holds_the_vip(vip):
    """`var/this_node_has_the_vip` is how the cluster answers "who has it?", and
    `912` removes it again on release."""
    vip.run_script(SCRIPT)

    assert vip.file_exists(MARKER)


def test_the_marker_file_is_rewritten_on_a_later_activation(vip):
    """`initscript` sets `noclobber`, so the plain `>` here failed on every run
    after the first and the marker kept the first activation's timestamp
    forever. Fixed 2026-09-16 with `set +o noclobber`; this is its regression
    test, and the one the VIP group was missing when that fix was made."""
    vip.run_script(SCRIPT)
    first = vip.read_file(MARKER)

    vip.exec("sleep 1")
    install_fakes(vip)
    vip.run_script(SCRIPT)

    assert vip.read_file(MARKER) != first, first


def test_the_gateway_is_found_from_the_routing_table(vip):
    """The gratuitous ARP has to go to the default gateway, which `911` parses
    out of `route -n`."""
    vip.run_script(SCRIPT)

    assert any("192.168.0.1" in c for c in calls(vip, "arping")), calls(vip, "arping")


def test_a_gratuitous_arp_is_sent(vip):
    """Without it the router keeps the old MAC and the VIP is unreachable even
    though the interface is up."""
    vip.run_script(SCRIPT)

    assert calls(vip, "arping"), "no gratuitous ARP was sent"
    assert any(f"-s {VIP}" in c for c in calls(vip, "arping")), calls(vip, "arping")


def test_a_successful_arp_is_reported(vip):
    run = vip.run_script(SCRIPT)

    assert any(m.errno == "9115" for m in own(run)), run.describe()


# --- known defects ----------------------------------------------------------

def test_the_interface_is_actually_brought_up(vip):
    """D134, fixed 2026-09-17. The line that configures the VIP read

        res=($IFCONFIG ${IF_VIRTUAL} inet ${HOSTNAME_VIRTUAL} netmask ${NETMASK_VIRTUAL} up)

    `res=(...)` is bash **array assignment**, not command substitution. The
    words were stored in `res` and `ifconfig` was never executed. `$?` was then
    the status of the assignment — always 0 — so the guard below it never fired
    and `911` went on to write the marker file and report `ERRNO[1]`, "Activate
    VIP run successfully".

    So `911` claimed the VIP on every run without ever configuring it. For a
    failover script that is the worst available shape of failure: the cluster
    believes the address moved, the marker file agrees, monitoring is green, and
    the address is up nowhere.

    Fixed to `res=$(...)`, with `2>&1` added so the tool's own complaint reaches
    `DESCR[2]`'s placeholder. Line 62 was the only one of four assignments in
    the script written this way — the other three already used command
    substitution, which is what makes it a typo rather than an intention."""
    vip.run_script(SCRIPT)

    assert any("up" in c for c in calls(vip, "ifconfig")), calls(vip, "ifconfig")


def test_a_failing_ifconfig_is_reported(vip):
    """This guard had never been reachable. Until D134 was fixed `$?` was the
    array assignment's status, so `ERRNO[2]` could not fire whatever the
    interface did."""
    install_fakes(vip, ifconfig_rc=1)

    run = vip.run_script(SCRIPT)

    assert any(m.errno == "9112" for m in own(run)), run.describe()


def test_a_failing_ifconfig_writes_no_marker(vip):
    """The half that matters. The marker is what tells the cluster which node
    holds the VIP; writing it after a failed activation is how two nodes end up
    both believing they have it."""
    install_fakes(vip, ifconfig_rc=1)

    vip.run_script(SCRIPT)

    assert not vip.file_exists(MARKER), "the marker was written despite the failure"


def test_a_failing_ifconfig_sends_no_gratuitous_arp(vip):
    """Announcing an address that was never brought up would point the router
    at a host that cannot answer it."""
    install_fakes(vip, ifconfig_rc=1)

    vip.run_script(SCRIPT)

    assert calls(vip, "arping") == [], calls(vip, "arping")


def test_a_failed_gratuitous_arp_is_reported(vip):
    """D135, fixed 2026-09-17. The warning branch was spelled

        printlogmess ... -x ${SCRIPTINDEX}  $WARN ${ERRNO[6]} -d "${DESCR[6]}" -1 "$res"

    with no `-l` and no `-e`, so `printlogmess` rejects the call and nothing is
    logged. The success branch immediately below it is spelled correctly.

    A router that does not answer the gratuitous ARP is precisely the failure
    this branch exists to surface — the VIP is up locally but unreachable from
    the network — and it is the one outcome that produces no message at all.

    Same defect as D114 in the deleted `918` and D99 in `922`."""
    install_fakes(vip, arping_rc=1)

    run = vip.run_script(SCRIPT)

    assert any(m.errno == "9116" for m in own(run)), run.describe()


def test_help_documents_every_error_code(vip):
    res = vip.exec([vip.script_path(SCRIPT), "--help"])

    for n in range(1, 7):
        assert f"911{n} / " in res.output, res.output
