"""End-to-end tests for related-available/902_export_crl.sh.

`902` takes a DER-encoded CRL, records its issuer and lastUpdate in a log, and
writes a PEM copy into a dated archive directory.

FIXTURE: a real CA and a real CRL minted with `openssl ca -gencrl` in the
container, then converted to DER. Nothing is mocked — `902` runs real `openssl`
against a real CRL.

Until 2026-09-17 `902` could not run at all: the `--crl` option supplying its
only input was declared to `getopt` without a trailing colon, so the option loop
spun forever (D82), and its missing-file guard was missing the `printlogmess`
command name so nothing was ever reported (D83). Both are fixed; invocations
still run under `timeout` so a regression shows up as a bounded failure rather
than a hung suite.
"""

from __future__ import annotations

import pytest

from syscheck_harness import parse_messages

SCRIPT = "related-available/902_export_crl.sh"
CA = "/tmp/902/ca"
OUTPATH = "/tmp/902/out"
CRL_DER = f"{CA}/crl.der"

pytestmark = pytest.mark.slow

MAKE_CRL = r"""
set -e
rm -rf /tmp/902
mkdir -p CADIR/newcerts OUTDIR
cd CADIR
touch index.txt
echo 1000 > crlnumber
echo 1000 > serial
cat > ca.cnf <<'CFG'
[ ca ]
default_ca = CA_default
[ CA_default ]
dir = .
database = $dir/index.txt
new_certs_dir = $dir/newcerts
certificate = $dir/ca.crt
private_key = $dir/ca.key
serial = $dir/serial
crlnumber = $dir/crlnumber
default_md = sha256
default_crl_days = 30
policy = policy_any
[ policy_any ]
commonName = optional
countryName = optional
stateOrProvinceName = optional
organizationName = optional
organizationalUnitName = optional
emailAddress = optional
CFG
openssl req -x509 -newkey rsa:2048 -nodes -keyout ca.key -out ca.crt \
  -subj "/CN=Test CA/O=SysCheck" -days 365 2>/dev/null
openssl ca -config ca.cnf -gencrl -out crl.pem 2>/dev/null
openssl crl -in crl.pem -outform der -out crl.der
""".replace("CADIR", CA).replace("OUTDIR", OUTPATH)


def config() -> str:
    return ("# generated by test_902_export_crl.py\n"
            f"OUTPATH={OUTPATH}\n"
            f"CRLLOG={OUTPATH}/exportcrl.log\n"
            f'OUTPATH2="{OUTPATH}"\n')


@pytest.fixture
def crl(syscheck):
    syscheck.exec(MAKE_CRL).check()
    syscheck.set_script_config("902", config())
    return syscheck


def run(sc, *args, seconds: int = 15):
    """`902` can hang, so every invocation is bounded. Returns (result, messages)."""
    argv = " ".join(args)
    res = sc.exec(f"timeout {seconds} {sc.script_path(SCRIPT)} --screen {argv}")
    messages, _json, _unparsed = parse_messages(res.stdout + res.stderr)
    return res, [m for m in messages if m.scriptid == "902"]


# --- the fixture is real ----------------------------------------------------

def test_the_fixture_is_a_crl_openssl_can_read(crl):
    """Guards the rest of the suite: if this fails the fixture is wrong, not
    `902`."""
    res = crl.exec(f"openssl crl -inform der -in {CRL_DER} -issuer -noout").check()

    assert "Test CA" in res.stdout, res.stdout


# --- the option defect ------------------------------------------------------

def test_passing_a_crl_file_terminates(crl):
    """The headline defect. `902` declares

        getopt --options "hsvc" --long "help,screen,verbose,crl"

    with no colon after `crl` (nor after `c`), so `getopt` treats `--crl` as
    taking no argument and emits

        --crl -- '/path/to.crl'

    The case arm then runs `CRLFILE=$2; shift 2`, which assigns the `--`
    separator to `CRLFILE` and shifts past it, leaving `$1` on the file path.
    That matches no arm, nothing shifts, and `while true` spins forever.

    So `902` never terminates when given the option it exists to accept. Run
    from cron it accumulates a stuck process on every invocation, burning a core
    each time and never archiving a CRL. `925_publish_crl_from_file.sh` declares
    the equivalent option as `crlfile:` and is unaffected — the colon is the
    whole difference.

    `900_export_cert.sh` and `901_export_revocation.sh` share this defect
    exactly, with `cert` in place of `crl`."""
    res, _ = run(crl, "--crl", CRL_DER)

    assert res.exit_code != 124, "the script hung until the timeout fired"


def test_a_crl_is_exported_as_pem(crl):
    """What `902` is for. The exported file is named from the CRL's issuer, so
    an archive holds one predictably-named file per CA."""
    run(crl, "--crl", CRL_DER)

    res = crl.exec(f"ls -1 {OUTPATH}")
    assert any(f.endswith(".crl") for f in res.stdout.split()), res.stdout


def test_the_issuer_and_lastupdate_are_logged(crl):
    run(crl, "--crl", CRL_DER)

    log = crl.read_file(f"{OUTPATH}/exportcrl.log")
    assert "CRLISSUER:" in log and "CRLLASTUPDATE:" in log, log


# --- the guard for a missing file -------------------------------------------

def test_running_without_a_crl_file_is_reported(crl):
    """D83, fixed 2026-09-17. With no arguments `CRLFILE` is empty and the guard
    fires, but its first line was missing the command name entirely:

        if [ "x$CRLFILE" = "x" -o ! -r "$CRLFILE" ] ; then
             -n ${SCRIPTNAME} -i ${SCRIPTID} -x ${SCRIPTINDEX} -l $ERROR ...

    The line began with `-n`, so the shell tried to *execute* `-n`, failed with
    "command not found", and the script exited silently. `902` called without an
    input file reported nothing at all.

    The same line also paired `ERRNO[3]` with `DESCR[2]`, so restoring the
    command name alone would have printed "Export CRL failed (%s)" with an
    unfilled placeholder rather than `DESCR[3]`, "script called without file".
    Both were corrected, along with the wider `ERRNO` remapping below."""
    _res, messages = run(crl)

    assert messages, "no message was emitted for a missing input file"


def test_running_without_a_crl_file_does_not_hang(crl):
    """The no-argument path exits rather than spinning — the loop only breaks
    down once an option carrying a value is supplied."""
    res, _ = run(crl)

    assert res.exit_code != 124, "the script hung with no arguments"


def test_a_corrupt_crl_is_not_described_as_a_missing_one(crl):
    """`902` used `ERRNO[3]` at nine call sites and **`ERRNO[2]` nowhere**, so
    every failure — a corrupt CRL, an unparseable issuer, a failed write — was
    reported with `DESCR[3]`, "script called without file".

    Remapped 2026-09-17 to the arrangement `900` and `901` now use: `[3]` for
    the missing-file guard, `[2]` for processing failures, `[1]` for success.
    `DESCR[2]` is the only description carrying a placeholder, which also makes
    the old `-1 "$?"` moot twice over — `$?` was expanded inside the branch
    where the `[` test had just returned 0, so it was always the literal `0`,
    and `DESCR[3]` had no `%s` to render it into."""
    crl.exec(f"echo 'not a crl' > {CA}/junk.crl").check()

    _res, messages = run(crl, "--crl", f"{CA}/junk.crl")

    failing = [m for m in messages if m.level == "E"]
    assert failing, messages
    assert "without file" not in failing[0].text, failing[0].text
    assert "junk.crl" in failing[0].text, failing[0].text


def test_a_corrupt_crl_produces_no_archive(crl):
    crl.exec(f"echo 'not a crl' > {CA}/junk.crl").check()

    run(crl, "--crl", f"{CA}/junk.crl")

    res = crl.exec(f"ls -1 {OUTPATH}")
    assert not any(f.endswith(".crl") for f in res.stdout.split()), res.stdout


def test_help_documents_every_error_code(crl):
    res = crl.exec([crl.script_path(SCRIPT), "--help"])

    for errno in ("9021", "9022", "9023"):
        assert f"{errno} / " in res.output, res.output
