"""sc_12_mysql.sh against a real MariaDB server.

The check itself — pidfile, stale pidfile, name fallback — is covered with the
three other process checks in `test_sc_process_checks.py`. What that suite
cannot answer is whether the *shipped configuration* matches a real database
server, because it supplies its own `procname` and `pidfile`.

So this file asks a real `mariadb:11` what it is actually called and where it
actually keeps its pidfile, and compares that with `config/12.conf`. The server
runs in its own container — a check that reads the local process table cannot
see into it — so the comparison is made against the container's own `ps` rather
than by running the check against it.
"""

from __future__ import annotations

import pytest

from syscheck_harness import docker_exec

SCRIPT = "sc_12_mysql.sh"

pytestmark = pytest.mark.slow


def config(procname: str, pidfile: str) -> str:
    return (
        "# generated by test_sc_12_mysql.py\n"
        f"pidfile={pidfile}\n"
        f"procname={procname}\n"
    )


@pytest.fixture
def shipped_config(syscheck):
    """`config/12.conf` as shipped, parsed into procname and pidfile."""
    text = syscheck.read_file("/src/config/12.conf")
    values = {}
    for line in text.splitlines():
        line = line.strip()
        if line.startswith("procname=") or line.startswith("pidfile="):
            key, _, value = line.partition("=")
            values[key] = value
    assert {"procname", "pidfile"} <= values.keys(), text
    return values


@pytest.fixture
def server_facts(mariadb_node):
    """What the running server actually calls itself."""
    return {
        "argv": docker_exec(mariadb_node, ["ps", "-eo", "args"]),
        "pidfiles": docker_exec(
            mariadb_node,
            ["bash", "-c", "find /run /var/lib/mysql -name '*.pid' 2>/dev/null"],
        ).split(),
    }


def test_the_server_under_test_is_really_running(server_facts):
    """Guards the two comparisons below: if the server were not up, they would
    pass for the wrong reason."""
    assert "mariadbd" in server_facts["argv"], server_facts["argv"]
    assert server_facts["pidfiles"], "the server wrote no pidfile at all"


def test_a_correctly_configured_check_finds_the_database_process(syscheck):
    """Configured with the name a current MariaDB actually uses, the check works
    — so what D40 is about is the shipped default, not the mechanism."""
    pid = syscheck.start_process("mariadbd")
    syscheck.write_file("/var/run/mariadbd.pid", f"{pid}\n")
    syscheck.set_script_config("12", config("/usr/local/bin/mariadbd",
                                            "/var/run/mariadbd.pid"))

    run = syscheck.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("I", "121"), run.describe()


@pytest.mark.known_bug
@pytest.mark.xfail(strict=True,
                   reason="D40: the shipped procname is /usr/sbin/mysqld, a current MariaDB runs mariadbd")
def test_the_shipped_procname_matches_a_real_server(shipped_config, server_facts):
    """`config/12.conf` ships `procname=/usr/sbin/mysqld`. MariaDB 10.5 renamed
    the daemon, and `mariadb:11` runs `mariadbd`, so the name fallback — the
    path that runs whenever the pidfile is missing, which it also is — matches
    nothing. The check reports `mysql is NOT running` and exits 3 on a host
    whose database is perfectly healthy."""
    name = shipped_config["procname"].rsplit("/", 1)[-1]

    assert name in server_facts["argv"], (
        f"config/12.conf procname={shipped_config['procname']!r}, "
        f"server runs:\n{server_facts['argv']}"
    )


@pytest.mark.known_bug
@pytest.mark.xfail(strict=True,
                   reason="D40: the shipped pidfile is /var/lib/mysql/mysqld.pid, a current MariaDB writes /run/mysqld/mysqld.pid")
def test_the_shipped_pidfile_matches_a_real_server(shipped_config, server_facts):
    """The other half of the same default: the pidfile moved to `/run` years
    ago. Both halves being wrong is what makes this a false alarm rather than a
    slow one — the pidfile misses, so the check falls back to the name, and the
    name misses too."""
    assert shipped_config["pidfile"] in server_facts["pidfiles"], (
        f"config/12.conf pidfile={shipped_config['pidfile']!r}, "
        f"server wrote {server_facts['pidfiles']}"
    )
