"""End-to-end tests for related-available/901_export_revocation.sh.

`901` is `900`'s twin for revoked certificates: same DER input, same openssl
pipeline, same archive-and-ship shape, with `revoked-cert-` in place of
`archived-cert-` and its own log.

FIXTURE: real certificates minted with `openssl req -x509` and converted to DER.

The pair is worth testing separately rather than parametrising, because they
disagree in exactly the place that matters. `900` uses `ERRNO[3]` for every
failure and never touches `ERRNO[2]`; `901` uses `ERRNO[2]` for its missing-file
guard and `ERRNO[3]` for everything else — the opposite pairing. Both are wrong,
in opposite directions, and one shared test would have hidden that.

Like `900`, this script could not run at all until the D82 colon fix on
2026-09-16.
"""

from __future__ import annotations

import pytest

SCRIPT = "related-available/901_export_revocation.sh"
WORK = "/tmp/901"
ARCHIVE = f"{WORK}/archive"
CERT_DER = f"{WORK}/cert.der"
REVLOG = f"{ARCHIVE}/revokedcert.log"

pytestmark = pytest.mark.slow


def config(*, archive: str = ARCHIVE) -> str:
    return ("# generated by test_901_export_revocation.py\n"
            f"OUTPATH={archive}\n"
            f"REVLOG={archive}/revokedcert.log\n"
            "DATE=`date +'%Y-%m-%d_%H.%M.%S'`\n"
            f'OUTPATH2="{archive}"\n')


def make_cert(sc, *, subject: str = "/CN=revoked.example.com/O=SysCheck",
              name: str = "cert") -> str:
    sc.exec(f"mkdir -p {WORK} && openssl req -x509 -newkey rsa:2048 -nodes "
            f"-keyout {WORK}/{name}.key -out {WORK}/{name}.pem "
            f"-subj '{subject}' -days 365 2>/dev/null").check()
    sc.exec(f"openssl x509 -in {WORK}/{name}.pem -outform der "
            f"-out {WORK}/{name}.der").check()
    return f"{WORK}/{name}.der"


@pytest.fixture
def export(syscheck):
    syscheck.exec(f"rm -rf {WORK} && mkdir -p {ARCHIVE}").check()
    make_cert(syscheck)
    syscheck.set_script_config("901", config())
    return syscheck


def run(sc, *args, seconds: int = 20):
    argv = " ".join(args)
    return sc.exec(f"timeout {seconds} {sc.script_path(SCRIPT)} --screen {argv}")


def own(res) -> list:
    from syscheck_harness import parse_messages
    messages, _j, _u = parse_messages(res.stdout + res.stderr)
    return [m for m in messages if m.scriptid == "901"]


def archived(sc) -> list[str]:
    r = sc.exec(f"ls -1 {ARCHIVE} 2>/dev/null")
    return sorted(f for f in r.stdout.splitlines()
                  if f.strip() and not f.endswith(".log"))


# --- it runs at all (D82) ---------------------------------------------------

def test_passing_a_certificate_terminates(export):
    """The D82 regression test — `--cert` was declared without a colon, so the
    option loop never terminated."""
    res = run(export, f"--cert={CERT_DER}")

    assert res.exit_code != 124, "the script hung until the timeout fired"


# --- the export -------------------------------------------------------------

def test_a_revoked_certificate_is_exported_as_pem(export):
    run(export, f"--cert={CERT_DER}")

    assert len(archived(export)) == 1, archived(export)


def test_the_exported_file_is_valid_pem(export):
    run(export, f"--cert={CERT_DER}")

    name = archived(export)[0]
    res = export.exec(f"openssl x509 -in {ARCHIVE}/{name} -subject -noout").check()
    assert "revoked.example.com" in res.stdout, res.output


def test_the_filename_marks_it_as_revoked(export):
    """`revoked-cert-` rather than `archived-cert-` is the only thing
    distinguishing this archive from `900`'s, and the two can share a
    directory."""
    run(export, f"--cert={CERT_DER}")

    name = archived(export)[0]
    assert name.startswith("revoked-cert-"), name
    assert "revoked.example.com" in name, name


def test_the_log_records_the_serial_subject_and_body(export):
    run(export, f"--cert={CERT_DER}")

    log = export.read_file(REVLOG)
    assert "CERTSERIAL:" in log and "CERTSUBJECT:" in log, log
    assert "BEGIN CERTIFICATE" in log, log[:400]


def test_a_successful_export_is_reported(export):
    res = run(export, f"--cert={CERT_DER}")

    msg = [m for m in own(res) if m.errno == "9011"]
    assert msg and msg[0].level == "I", own(res)


def test_the_archive_directory_is_created_if_missing(export):
    export.set_script_config("901", config(archive=f"{WORK}/fresh"))

    run(export, f"--cert={CERT_DER}")

    assert export.file_exists(f"{WORK}/fresh")


# --- guards -----------------------------------------------------------------

def test_running_without_a_certificate_is_reported(export):
    res = run(export)

    assert own(res), "nothing was reported"
    assert own(res)[0].level == "E", own(res)


def test_an_unreadable_certificate_is_reported(export):
    res = run(export, f"--cert={WORK}/no-such-file.der")

    assert own(res), "nothing was reported"
    assert own(res)[0].level == "E", own(res)


def test_a_corrupt_certificate_produces_no_archive(export):
    export.exec(f"echo 'not a certificate' > {WORK}/junk.der").check()

    run(export, f"--cert={WORK}/junk.der")

    assert archived(export) == [], archived(export)


def test_a_corrupt_certificate_is_still_caught(export):
    """As in `900`, the two guards reading through `| sed` cannot fire — `$?` is
    sed's status and sed succeeds on empty input. The un-piped
    `CERT=`openssl x509 ...`` a few lines later catches it, so no failure is
    missed, only misattributed."""
    export.exec(f"echo 'not a certificate' > {WORK}/junk.der").check()

    res = run(export, f"--cert={WORK}/junk.der")

    assert any(m.level == "E" for m in own(res)), own(res)


# --- known defect -----------------------------------------------------------

def test_the_missing_file_message_says_the_file_was_missing(export):
    """D126, fixed 2026-09-17. `901` paired its missing-file guard with
    `ERRNO[2]`/`DESCR[2]`:

        DESCR[2]="Export revocation failed (%s) "
        DESCR[3]="Export revocation failed, script called without file"

    `DESCR[3]` is the text that fits, and it was used for everything *except*
    the case it describes. So `901` with no argument reported the generic
    "failed ( )" — empty placeholder, since the guard passes no `-1` — while a
    corrupt certificate reported "script called without file".

    Each message named the other one's condition. `900` was wrong the opposite
    way round, using `ERRNO[3]` everywhere and never touching `ERRNO[2]` (D125).
    Being wrong in mirror image is the strongest evidence the two were copied
    from one another and then edited independently.

    Both were rewired on 2026-09-17 to the same mapping: `[3]` for the
    missing-file guard, `[2]` for processing failures, `[1]` for success."""
    res = run(export)

    assert own(res) and "without file" in own(res)[0].text, own(res)


def test_help_documents_every_error_code(export):
    res = export.exec([export.script_path(SCRIPT), "--help"])

    for errno in ("9011", "9012", "9013"):
        assert f"{errno} / " in res.output, res.output
