"""End-to-end tests for related-available/910_deactivate_CAs.sh.

`910` is the mirror of `909`: it walks the configured CA list and runs
`ejbca.sh ca deactivateca <name>` for each one.

FAKE-BIN, same seam as `909` — a stub `ejbca.sh` under a temporary
`EJBCA_HOME`, which `config/common.conf` picks up from the environment.

`910` is the most broken script in this group. Three independent defects stack:
it has no CA list at all with the shipped config, it never passes the CA name to
the tool, and it cannot report a failure. Each is pinned separately below so
that fixing one does not silently mask the others.
"""

from __future__ import annotations

import pytest

SCRIPT = "related-available/910_deactivate_CAs.sh"
EJBCA_HOME = "/tmp/910/ejbca"

pytestmark = pytest.mark.slow


def config(*names) -> str:
    """Written to `config/909.conf`, not `910.conf`.

    `910` does `getconfig "909"` and reuses the activate side's `CANAME` list,
    so the two halves of a failover pair cannot drift apart about which CAs
    exist. Same arrangement as `942` reading `941`'s S3 destinations.
    """
    lines = ["# generated by test_910_deactivate_cas.py\n"]
    for i, name in enumerate(names):
        lines.append(f'CANAME[{i}]="{name}"\n')
    return "".join(lines)


def install_ejbca(sc, *, stdout: str = "", exit_code: int = 0) -> None:
    sc.exec(f"mkdir -p {EJBCA_HOME}/bin").check()
    sc.write_file(f"{EJBCA_HOME}/bin/ejbca.sh",
                  "#!/bin/bash\n"
                  f'echo "$@" >> {EJBCA_HOME}/calls.log\n'
                  f"cat <<'EOF'\n{stdout}\nEOF\n"
                  f"exit {exit_code}\n",
                  mode=0o755)


@pytest.fixture
def cas(syscheck):
    syscheck.exec("rm -rf /tmp/910").check()
    install_ejbca(syscheck)
    syscheck.set_script_config("909", config("eIDCA", "ServerCA"))
    return syscheck


def run(sc):
    return sc.run_script(SCRIPT, env={"EJBCA_HOME": EJBCA_HOME})


def calls(sc) -> list[str]:
    if not sc.file_exists(f"{EJBCA_HOME}/calls.log"):
        return []
    return [l for l in sc.read_file(f"{EJBCA_HOME}/calls.log").splitlines() if l.strip()]


def own(run) -> list:
    return [m for m in run.messages if m.scriptid == "910"]


# --- what it does run -------------------------------------------------------

def test_one_call_is_made_per_configured_ca(cas):
    """The loop count is driven by `CANAME`, and that much works — it is only
    the CA *name* that never reaches the tool."""
    run(cas)

    assert len(calls(cas)) == 2, calls(cas)


def test_each_ca_reports_under_its_own_index(cas):
    r = run(cas)

    assert [m.index for m in own(r)] == ["01", "02"], r.describe()


def test_an_empty_ca_list_does_nothing(cas):
    cas.set_script_config("909", config())

    r = run(cas)

    assert calls(cas) == []
    assert own(r) == [], r.describe()


# --- known defects ----------------------------------------------------------

def test_the_ca_name_is_passed_to_the_tool(cas):
    """`910` reads the configured name for its screen output:

        printtoscreen "Deactivating CA :  ${CANAME[$i]}"
        ./bin/ejbca.sh ca deactivateca $NAME | tee ...

    but `$NAME` is never assigned anywhere in the script — `909` sets
    `NAME=${CANAME[$i]}` at the top of its loop and `910` simply does not. The
    variable is unset and unquoted, so it vanishes from the argument list and
    the tool is invoked as `ca deactivateca` with no CA at all.

    The operator sees the right CA name on screen while nothing is deactivated.
    (That screen line used to end "on node $HOSTNAME_NODE2", implying a remote
    operation `910` never performs; the reference was removed on 2026-09-18 and
    `HOSTNAME_NODE2` is no longer used anywhere in the script.)
    For a script whose purpose is taking CAs offline — the thing you run before
    maintenance, or to contain a suspected key compromise — believing it worked
    is the dangerous failure mode."""
    run(cas)

    assert calls(cas) == ["ca deactivateca eIDCA",
                          "ca deactivateca ServerCA"], calls(cas)


def test_the_shipped_config_provides_a_ca_list(cas):
    """`config/910.conf` contains only a comment:

        # none, CA:s and pins are defined in common.conf

    but `CANAME` appears nowhere in `common.conf` — it is defined in
    `config/909.conf`, which `910` does not read (it makes no `getconfig` call).
    So `${#CANAME[@]}` is zero as installed, the loop body never executes, and
    `910` emits no messages whatsoever.

    Same root cause as D38 in `sc_40`, where the fix was the missing
    `getconfig "mariadb"` line. Deliberately driven through the *shipped* config
    rather than a generated one, since that is the thing that is wrong."""
    cas.set_script_config("910", "### shipped config for 910_deactivate_CAs.sh\n"
                                 "# none, the CA list is reused from config/909.conf\n")

    run(cas)

    assert calls(cas), "no CA was deactivated with the shipped configuration"


def test_a_failing_deactivation_is_reported_as_an_error(cas):
    """The same defect as D79 in `909`, and slightly worse here — `910` uses
    `cat` rather than `grep -v`, so it does not even filter a prompt line:

        ./bin/ejbca.sh ca deactivateca $NAME | tee ${SYSCHECK_HOME}/var/$0.output
        error=$(cat ${SYSCHECK_HOME}/var/$0.output)

    `$0` is the full script path, so the tee target is an unwritable nested
    path, `cat` reads a file that does not exist, and the empty result is the
    success condition."""
    install_ejbca(cas, stdout="ERROR: CA not found", exit_code=1)

    r = run(cas)

    assert any(m.errno == "9102" for m in own(r)), r.describe()


def test_help_documents_every_error_code(cas):
    res = cas.exec([cas.script_path(SCRIPT), "--help"])

    for errno in ("9101", "9102"):
        assert f"{errno} / " in res.output, res.output
