"""End-to-end tests for related-available/941_make_mysql_db_backup_and_transfer_to_s3.sh.

`941` takes a database backup with `904` and uploads it to each configured S3
endpoint with `curl --aws-sigv4`, optionally encrypting it first and optionally
removing the local copy afterwards.

FAKE-BIN `curl`, recording its argv. Deliberately kept simple: no MinIO, and the
PGP path is left at its shipped default of off, so no `gpg` is needed either
(it is not in the test image).

**Fidelity gap, stated plainly.** These tests prove the request `941` builds —
endpoint, bucket, object key, credentials, signing region — and how it reports
the outcome. They do **not** prove that a real S3 accepts that request. A
genuine MinIO service would be needed for that, and it is the one thing this
suite cannot speak to; `test/test-s3-backup-restore.bats` has the same limit.
The REAL-SVC upgrade is recorded in PLAN.md as the remaining work.
"""

from __future__ import annotations

import pytest

from conftest import MARIADB_DATABASE, MARIADB_ROOT_PASSWORD

SCRIPT = "related-available/941_make_mysql_db_backup_and_transfer_to_s3.sh"
WORK = "/tmp/941"
BACKUPDIR = f"{WORK}/backup"
CURL_LOG = f"{WORK}/curl.log"

pytestmark = pytest.mark.slow


def mariadb_config() -> str:
    return (f"DB_NAME={MARIADB_DATABASE}\n"
            f'MYSQLROOT_PASSWORD="{MARIADB_ROOT_PASSWORD}"\n'
            "MYSQL_BIN=/usr/bin/mariadb\n"
            "MYSQLDUMP_BIN=/usr/bin/mariadb-dump\n"
            "MYSQLDUMP_OPTIONS=(--single-transaction --quick)\n")


def backup_config() -> str:
    return ("DATESTING='%Y-%m-%d_%H.%M.%S'\n"
            f"MYSQLBACKUPDIR={BACKUPDIR}\n"
            "SUBDIR_DEFAULT=default\nSUBDIR_DAILY=daily\n"
            "SUBDIR_WEEKLY=weekly\nSUBDIR_MONTHLY=monthly\nSUBDIR_YEARLY=yearly\n"
            f'DBNAME[0]="{MARIADB_DATABASE}"\nTABLENAMES[0]=""\n')


def config(*, endpoints=("https://s3.example.com",), remove_local: str = "0") -> str:
    lines = ["# generated by test_941_backup_to_s3.py\n",
             "SUBDIR_DEFAULT=default\nSUBDIR_DAILY=daily\n",
             "SUBDIR_WEEKLY=weekly\nSUBDIR_MONTHLY=monthly\nSUBDIR_YEARLY=yearly\n",
             f"REMOVE_LOCAL_BACKUP={remove_local}\n",
             "PGP_ENCRYPT_BACKUP=0\n",
             "PGP_PUBKEY_FILE[0]=\n"]
    for i, ep in enumerate(endpoints):
        lines.append(f"S3_ENDPOINT[{i}]={ep}\n")
        lines.append(f"S3_REGION[{i}]=us-east-1\n")
        lines.append(f"S3_BUCKET[{i}]=mysql-backups\n")
        lines.append(f"S3_PREFIX[{i}]=mysql\n")
        lines.append(f"S3_ACCESS_KEY[{i}]=AKIATEST\n")
        lines.append(f"S3_SECRET_KEY[{i}]=secret{i}\n")
    return "".join(lines)


def install_curl(sc, *, rc: int = 0, body: str = "", etag: str = "abc123") -> None:
    """Stands in for curl: records argv and writes a plausible header dump."""
    sc.install_fake_bin("curl",
                        "#!/bin/bash\n"
                        f'echo "$@" >> {CURL_LOG}\n'
                        "HDR=\n"
                        'while [ $# -gt 0 ]; do\n'
                        '  [ "$1" = "--dump-header" ] && HDR=$2\n'
                        "  shift\n"
                        "done\n"
                        f'[ -n "$HDR" ] && printf \'HTTP/1.1 200 OK\\r\\nETag: "{etag}"\\r\\n\' >| "$HDR"\n'
                        f'[ {rc} -ne 0 ] && echo "{body}"\n'
                        f"exit {rc}\n")


@pytest.fixture
def s3(syscheck, mariadb_node):
    syscheck.write_file("/root/.my.cnf", f"[client]\nhost={mariadb_node}\n")
    syscheck.exec(f"rm -rf {WORK} && mkdir -p {BACKUPDIR}/default").check()
    syscheck.exec(["mariadb", "-h", mariadb_node, "-uroot",
                   f"-p{MARIADB_ROOT_PASSWORD}", MARIADB_DATABASE, "-e",
                   "DROP TABLE IF EXISTS CertificateData;"
                   "CREATE TABLE CertificateData (fingerprint VARCHAR(64) PRIMARY KEY);"
                   "INSERT INTO CertificateData VALUES ('aa')"]).check()
    install_curl(syscheck)
    syscheck.set_script_config("mariadb", mariadb_config())
    syscheck.set_script_config("904", backup_config())
    syscheck.set_script_config("941", config())
    return syscheck


def own(run) -> list:
    return [m for m in run.messages if m.scriptid == "941"]


def calls(sc) -> list[str]:
    if not sc.file_exists(CURL_LOG):
        return []
    return [l for l in sc.read_file(CURL_LOG).splitlines() if l.strip()]


def local_backups(sc) -> list[str]:
    r = sc.exec(f"ls -1 {BACKUPDIR}/default 2>/dev/null")
    return sorted(f for f in r.stdout.splitlines() if f.strip())


# --- the request it builds --------------------------------------------------

def test_a_backup_is_taken_and_uploaded(s3):
    s3.run_script(SCRIPT)

    assert local_backups(s3), "904 produced nothing"
    assert calls(s3), "curl was never called"


def test_the_upload_targets_the_configured_endpoint_and_bucket(s3):
    s3.run_script(SCRIPT)

    assert "https://s3.example.com/mysql-backups/mysql/default/" in calls(s3)[0], \
        calls(s3)


def test_the_request_is_signed_for_the_configured_region(s3):
    """`--aws-sigv4` is what makes this an S3 PUT rather than a plain HTTP one;
    a wrong region produces a signature the service rejects."""
    s3.run_script(SCRIPT)

    assert "--aws-sigv4 aws:amz:us-east-1:s3" in calls(s3)[0], calls(s3)


def test_the_configured_credentials_are_used(s3):
    s3.run_script(SCRIPT)

    assert "AKIATEST:secret0" in calls(s3)[0], calls(s3)


def test_the_object_key_is_unique_per_run(s3):
    """The key carries a UUID, so two backups of the same database on the same
    day cannot overwrite each other in the bucket."""
    s3.run_script(SCRIPT)
    s3.exec("sleep 1")
    s3.run_script(SCRIPT)

    keys = [c.split()[-1] for c in calls(s3)]
    assert len(set(keys)) == len(keys), keys


def test_the_local_backup_is_uploaded_not_a_placeholder(s3):
    """`--upload-file` must name the file `904` just wrote."""
    s3.run_script(SCRIPT)

    name = local_backups(s3)[0]
    assert name in calls(s3)[0], (name, calls(s3))


# --- reporting --------------------------------------------------------------

def test_a_successful_upload_is_reported_with_its_etag(s3):
    """The ETag is the receipt — it is how an operator later proves a given
    backup is the object sitting in the bucket."""
    run = s3.run_script(SCRIPT)

    ok = [m for m in own(run) if m.errno == "9411"]
    assert ok, run.describe()
    assert "abc123" in ok[0].text, ok[0].text


def test_a_failing_upload_is_reported_with_the_reason(s3):
    install_curl(s3, rc=22, body="403 SignatureDoesNotMatch")

    run = s3.run_script(SCRIPT)

    failed = [m for m in own(run) if m.errno == "9413"]
    assert failed, run.describe()
    assert "SignatureDoesNotMatch" in failed[0].text, failed[0].text


def test_every_configured_endpoint_receives_the_backup(s3):
    s3.set_script_config("941", config(endpoints=("https://s3.example.com",
                                                  "https://s3.backup.example.com")))

    run = s3.run_script(SCRIPT)

    assert len(calls(s3)) == 2, calls(s3)
    assert len([m for m in own(run) if m.errno == "9411"]) == 2, run.describe()


def test_a_failing_backup_uploads_nothing(s3):
    s3.set_script_config("904", backup_config().replace(
        f"MYSQLBACKUPDIR={BACKUPDIR}", "MYSQLBACKUPDIR=/tmp/941/gone"))

    run = s3.run_script(SCRIPT)

    assert any(m.errno == "9412" for m in own(run)), run.describe()
    assert calls(s3) == [], calls(s3)


# --- the local copy ---------------------------------------------------------

def test_the_local_backup_is_kept_by_default(s3):
    s3.run_script(SCRIPT)

    assert local_backups(s3), "the local backup was removed with REMOVE_LOCAL_BACKUP=0"


def test_the_local_backup_can_be_removed_after_upload(s3):
    s3.set_script_config("941", config(remove_local="1"))

    s3.run_script(SCRIPT)

    assert local_backups(s3) == [], local_backups(s3)


def test_a_failed_upload_keeps_the_local_backup(s3):
    """The property that matters most here: the only copy must not be deleted
    because of an upload nobody checked. `941` tracks `UPLOADFAILED` across
    every endpoint and removes the local file only if all of them took it."""
    install_curl(s3, rc=22, body="403 Forbidden")
    s3.set_script_config("941", config(remove_local="1"))

    s3.run_script(SCRIPT)

    assert local_backups(s3), "the local backup was deleted after a failed upload"


def test_one_failing_endpoint_keeps_the_local_backup(s3):
    """Two destinations, one refusing: the file has not reached everywhere it
    was meant to, so it stays."""
    s3.set_script_config("941", config(endpoints=("https://s3.example.com",
                                                  "https://s3.backup.example.com"),
                                       remove_local="1"))
    s3.install_fake_bin("curl",
                        "#!/bin/bash\n"
                        f'echo "$@" >> {CURL_LOG}\n'
                        'case "$*" in *s3.backup.example.com*) exit 22 ;; esac\n'
                        "HDR=\n"
                        'while [ $# -gt 0 ]; do\n'
                        '  [ "$1" = "--dump-header" ] && HDR=$2\n'
                        "  shift\n"
                        "done\n"
                        '[ -n "$HDR" ] && printf \'HTTP/1.1 200 OK\\r\\nETag: "abc123"\\r\\n\' >| "$HDR"\n'
                        "exit 0\n")

    s3.run_script(SCRIPT)

    assert local_backups(s3), "the local backup was deleted despite a failed endpoint"


def test_help_documents_every_error_code(s3):
    res = s3.exec([s3.script_path(SCRIPT), "--help"])

    for n in range(1, 6):
        assert f"941{n} / " in res.output, res.output
