"""End-to-end tests for scripts-available/sc_14_sw_raid.sh.

`mdadm` is replaced by a fake, since no container can present a real md array.

    # UNVERIFIED SHAPE
    The `mdadm --detail` fixtures below are written from the documented output
    format, not captured from a real array — neither this repo nor its docs
    contain a sample. The script only greps the device table for `active sync`
    and `fault`, so the part that matters is the per-device row; capturing one
    real `mdadm --detail` from a production host would settle it.

These tests were written against a check that could not work at all — it passed
the *string lengths* of its configured device names to the function that runs
`mdadm`, so every array on every host was reported as an unrecognised failure
(D30, since fixed). They are the regression guard for that.
"""

from __future__ import annotations

import pytest

SCRIPT = "sc_14_sw_raid.sh"
ARRAY = "/dev/md0"
DISK_A = "/dev/sda1"
DISK_B = "/dev/sdb1"


def detail(*device_rows: str) -> str:
    """One `mdadm --detail <array>` report."""
    return (
        f"{ARRAY}:\n"
        "           Version : 1.2\n"
        "        Raid Level : raid1\n"
        "        Array Size : 976630464 (931.39 GiB 1000.07 GB)\n"
        "      Raid Devices : 2\n"
        "     Total Devices : 2\n"
        "             State : clean\n"
        "    Active Devices : 2\n"
        "   Working Devices : 2\n"
        "    Failed Devices : 0\n"
        "     Spare Devices : 0\n"
        "\n"
        "    Number   Major   Minor   RaidDevice State\n"
        + "".join(row + "\n" for row in device_rows)
    )


HEALTHY = detail(
    f"       0       8        1        0      active sync   {DISK_A}",
    f"       1       8       17        1      active sync   {DISK_B}",
)
DEGRADED = detail(
    f"       0       8        1        0      active sync   {DISK_A}",
    f"       1       8       17        1      faulty   {DISK_B}",
)


def config(*disks: str, array: str = ARRAY) -> str:
    lines = ["# generated by test_sc_14_sw_raid.py\n"]
    for i, disk in enumerate(disks):
        lines.append(f"MDDEV[{i}]={array}\n")
        lines.append(f"HDDEV[{i}]={disk}\n")
    return "".join(lines)


@pytest.fixture
def raid(syscheck):
    """sc_14 with a fake `mdadm` under the test's control.

    The fake checks the array it was asked about and refuses anything else, as
    the real tool does. That is not decoration: sc_14 calls `mdadm --detail`
    with a *number* rather than a device path (see D30), and a fake that
    replayed its fixture whatever it was asked would answer that call happily
    and hide the defect completely."""

    def set_detail(output: str, exit_code: int = 0) -> None:
        body = (
            f'if [ "$2" != "{ARRAY}" ] ; then\n'
            '  echo "mdadm: cannot open $2: No such file or directory" >&2\n'
            "  exit 1\n"
            "fi\n"
            "cat <<'EOT'\n" + output + f"EOT\nexit {exit_code}\n"
        )
        syscheck.install_fake_bin("mdadm", body)

    syscheck.set_detail = set_detail
    syscheck.set_detail(HEALTHY)
    syscheck.set_script_config("14", config(DISK_A))
    return syscheck


def test_one_message_is_emitted_per_configured_disk(raid):
    """The loop is over `MDDEV`, and this part does work: two configured disks
    produce two messages with consecutive indexes."""
    raid.set_script_config("14", config(DISK_A, DISK_B))

    run = raid.run_script(SCRIPT)

    assert len(run.messages) == 2, run.describe()
    assert run.indexes == ["01", "02"], run.describe()


def test_no_configured_array_reports_nothing(raid):
    raid.set_script_config("14", config())

    run = raid.run_script(SCRIPT)

    assert run.messages == [], run.describe()


def test_an_array_mdadm_cannot_read_is_an_error(raid):
    """A configured array this host does not have — `mdadm --detail` writes an
    error and exits non-zero, so nothing in the output says `active sync`."""
    raid.set_script_config("14", config(DISK_A, array="/dev/md9"))

    run = raid.run_script(SCRIPT)

    msg = run.only()
    assert msg.level == "E", run.describe()


def test_an_absent_mdadm_is_an_error(raid):
    """`mdadm` is not installed on a host that has no software raid, and the
    script does not test for it before calling it."""
    raid.exec("rm -f /usr/local/bin/mdadm")

    run = raid.run_script(SCRIPT)

    assert run.only().level == "E", run.describe()


def test_a_healthy_array_is_reported_ok(raid):
    """The regression guard for D30. The call used to be

        swraidcheck ${#MDDEV[$i]} ${#DDDEV[$i]} $SCRIPTINDEX

    where `${#VAR[i]}` is the *length* of the element, so the function received
    `8` (the length of `/dev/md0`) and `0`, and ran `mdadm --detail 8`. `DDDEV`
    was a second bug on the same line: the config sets `HDDEV`. Every disk on
    every host took the `else` arm, so the check could neither confirm a healthy
    array nor detect a failed one."""
    run = raid.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("I", "141"), run.describe()
    assert ARRAY in msg.text and DISK_A in msg.text, msg.text


def test_a_faulty_disk_is_reported_as_a_raid_fault(raid):
    """The message this whole script exists to send. `ERRNO[2]` is reserved for
    a detected fault and `ERRNO[3]` for "failed some other way"; an operator
    paged by 143 has no reason to think a disk died."""
    raid.set_script_config("14", config(DISK_B))
    raid.set_detail(DEGRADED)

    run = raid.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "142"), run.describe()
    assert DISK_B in msg.text, msg.text


def test_help_documents_every_error_code(raid):
    res = raid.exec([raid.script_path(SCRIPT), "--help"])

    for errno in ("141", "142", "143"):
        assert f"{errno} / " in res.output, res.output
