"""End-to-end tests for scripts-available/sc_10_ocsp.sh.

Nothing here is mocked. A throwaway CA is built in the container, leaf
certificates are issued and one of them is revoked in the CA database, and a
real `openssl ocsp` responder serves signed responses over HTTP from its own
container. The script queries it with the real `openssl ocsp` client.

Two things about this check are easy to get wrong when reading it:

**The certificates to test are discovered, not configured.** `OCSP_TEST[i]` is a
*directory*; the script globs `test_*_cert*` inside it and derives everything
else from the filenames:

    test_<name>_cert_<expected-status>.pem   ->  the certificate to ask about
    test_<name>_issuer.pem                   ->  its issuer
    test_<name>_cacerts.pem                  ->  the chain to verify the response

The expected status is `cut -f4 -d_` of the basename. So the answer the check
requires is encoded in the filename of the file it is asking about.

**`config/10.conf` documents a different interface entirely** — `OCSP_CONNECT_URL[]`,
`OCSP_CERT[]`, `OCSP_EXPECTED_STATUS[]`, `OCSP_ISSUER[]`, `OCSP_CACHAIN[]`. The
script reads none of those names. See the D54 test at the bottom.

The check reports twice per certificate: once on the revocation status, and once
on how much life the *responder's own certificate* has left.
"""

from __future__ import annotations

import pytest

from syscheck_harness import OCSP_PKI_SH, start_ocsp_responder

SCRIPT = "sc_10_ocsp.sh"
PKI = "/tmp/ocsp-pki"
TESTDIR = "/tmp/ocsp-tests"

pytestmark = pytest.mark.slow


@pytest.fixture(scope="module")
def ocsp(_syscheck_session, syscheck_network):
    """One PKI and one live responder for the module.

    The PKI is built in the syscheck container (which needs the certificates to
    query with) and shipped to the responder container as a tar, so both sides
    are working from the same CA.
    """
    sc = _syscheck_session
    sc.write_file("/tmp/make-pki.sh", OCSP_PKI_SH)
    sc.exec(["bash", "/tmp/make-pki.sh", PKI]).check()
    tar_b64 = sc.exec(f"tar -c -C {PKI} . | base64 -w0").check().stdout.strip()

    responder, _ = start_ocsp_responder(syscheck_network, tar_b64)
    try:
        yield responder
    finally:
        responder.stop()


def install_case(sc, name: str, cert: str, expected: str,
                 issuer: str = "ca.crt", cachain: str = "ca.crt",
                 testdir: str = TESTDIR) -> None:
    """Lay out one test case under the naming convention the script globs for."""
    sc.exec(
        f"mkdir -p {testdir} && "
        f"cp {PKI}/{cert} {testdir}/test_{name}_cert_{expected}.pem && "
        f"cp {PKI}/{issuer} {testdir}/test_{name}_issuer.pem && "
        f"cp {PKI}/{cachain} {testdir}/test_{name}_cacerts.pem"
    ).check()


def config(url: str, *testdirs: str, warn: int = 57600, error: int = 28800) -> str:
    lines = ["# generated by test_sc_10_ocsp.py\n", "TIMEOUT=5\n", "RETRIES=1\n",
             "CHECKTOOL=openssl\n",
             f"WARN_OCSP_RESPONDER_CERT_EXPIRE={warn}\n",
             f"ERROR_OCSP_RESPONDER_CERT_EXPIRE={error}\n"]
    for i, d in enumerate(testdirs or (TESTDIR,)):
        lines.append(f'OCSP_TEST[{i}]="{d}"\n')
        lines.append(f'OCSP_URL[{i}]="{url}"\n')
    return "".join(lines)


@pytest.fixture
def sc10(syscheck, ocsp):
    syscheck.ocsp = ocsp
    syscheck.exec(f"rm -rf {TESTDIR}")
    syscheck.set_script_config("10", config(ocsp.url))
    return syscheck


def status_msgs(run):
    """The revocation-status verdicts: ERRNO 106 (matched) and 1010 (did not)."""
    return [m for m in run.messages if m.errno in ("106", "1010")]


def responder_cert_msgs(run):
    return [m for m in run.messages if m.errno in ("102", "103", "104", "105")]


def summary(run):
    return run.messages[-1]


# --- the revocation status --------------------------------------------------

def test_a_good_certificate_matching_its_expected_status_is_ok(sc10):
    install_case(sc10, "a", "good.crt", "good")

    run = sc10.run_script(SCRIPT)

    msg = status_msgs(run)[0]
    assert (msg.level, msg.errno) == ("I", "106"), run.describe()
    assert "good/good" in msg.text, msg.text


def test_a_revoked_certificate_expected_to_be_revoked_is_ok(sc10):
    """The check is "does the responder say what we expect", not "is the cert
    good" — a deliberately revoked test certificate proves the responder is
    still serving revocations at all."""
    install_case(sc10, "b", "revoked.crt", "revoked")

    run = sc10.run_script(SCRIPT)

    msg = status_msgs(run)[0]
    assert (msg.level, msg.errno) == ("I", "106"), run.describe()
    assert "revoked/revoked" in msg.text, msg.text


def test_a_revoked_certificate_expected_to_be_good_is_a_warning(sc10):
    """The failure this check exists for: the responder's answer no longer
    matches what it should be. Produced for real — the certificate really is
    revoked in the CA database."""
    install_case(sc10, "c", "revoked.crt", "good")

    run = sc10.run_script(SCRIPT)

    msg = status_msgs(run)[0]
    assert (msg.level, msg.errno) == ("W", "1010"), run.describe()
    assert "revoked/good" in msg.text, msg.text


def test_a_good_certificate_expected_to_be_revoked_is_a_warning(sc10):
    """The other direction, which is the more alarming one in production: a
    certificate that was revoked is being answered `good`."""
    install_case(sc10, "d", "good.crt", "revoked")

    run = sc10.run_script(SCRIPT)

    assert status_msgs(run)[0].errno == "1010", run.describe()


def test_a_certificate_from_another_ca_is_unknown(sc10):
    """The responder's database has never heard of this issuer, so it answers
    `unknown` — which does not match `good` and must be flagged."""
    install_case(sc10, "e", "unknown.crt", "good",
                 issuer="other-ca.crt", cachain="ca.crt")

    run = sc10.run_script(SCRIPT)

    assert status_msgs(run)[0].errno == "1010", run.describe()


def test_a_responder_that_is_not_listening_is_reported(sc10):
    """No response at all: the status parsed out of empty output cannot match
    the expected one, so the check must not read that as agreement."""
    install_case(sc10, "f", "good.crt", "good")
    sc10.set_script_config("10", config("http://127.0.0.1:9/"))

    run = sc10.run_script(SCRIPT)

    assert status_msgs(run)[0].errno == "1010", run.describe()


def test_every_certificate_in_the_directory_is_queried(sc10):
    """The directory is a glob, so one entry can hold a whole matrix of cases."""
    install_case(sc10, "a", "good.crt", "good")
    install_case(sc10, "b", "revoked.crt", "revoked")
    install_case(sc10, "c", "revoked.crt", "good")

    run = sc10.run_script(SCRIPT)

    assert len(status_msgs(run)) == 3, run.describe()
    assert sorted(m.errno for m in status_msgs(run)) == sorted(
        ["106", "106", "1010"]), run.describe()


# --- the responder's own certificate ----------------------------------------

def test_the_responder_certificate_validity_is_reported(sc10):
    """A second, independent verdict per query: the responder's signing
    certificate has its own expiry, and a responder whose certificate lapses
    stops being trusted even though it is still answering."""
    install_case(sc10, "a", "good.crt", "good")

    run = sc10.run_script(SCRIPT)

    msg = responder_cert_msgs(run)[0]
    assert (msg.level, msg.errno) == ("I", "102"), run.describe()


def test_a_responder_certificate_inside_the_warn_window_is_a_warning(sc10):
    """The responder certificate is valid for 10 years; a warn threshold larger
    than that puts it inside the window. Same technique as sc_08 — move the
    threshold rather than the clock."""
    install_case(sc10, "a", "good.crt", "good")
    # 11 years in minutes, comfortably beyond the certificate's remaining life
    sc10.set_script_config("10", config(sc10.ocsp.url, warn=11 * 365 * 24 * 60,
                                        error=28800))

    run = sc10.run_script(SCRIPT)

    msg = responder_cert_msgs(run)[0]
    assert (msg.level, msg.errno) == ("W", "103"), run.describe()


def test_a_responder_certificate_inside_the_error_window_is_an_error(sc10):
    install_case(sc10, "a", "good.crt", "good")
    sc10.set_script_config("10", config(sc10.ocsp.url, warn=11 * 365 * 24 * 60,
                                        error=11 * 365 * 24 * 60))

    run = sc10.run_script(SCRIPT)

    msg = responder_cert_msgs(run)[0]
    assert (msg.level, msg.errno) == ("E", "104"), run.describe()


# --- the summary ------------------------------------------------------------

def test_a_clean_run_ends_with_an_ok_summary(sc10):
    install_case(sc10, "a", "good.crt", "good")

    run = sc10.run_script(SCRIPT)

    assert (summary(run).level, summary(run).errno) == ("I", "109"), run.describe()


def test_a_mismatched_status_reaches_the_summary_as_a_warning(sc10):
    install_case(sc10, "c", "revoked.crt", "good")

    run = sc10.run_script(SCRIPT)

    assert (summary(run).level, summary(run).errno) == ("W", "108"), run.describe()


def test_the_summary_has_its_own_index(sc10):
    """`sc_10` does what `sc_08` forgets (D50): it resets `SCRIPTINDEX` to `00`
    before the summary, so the summary and the per-certificate verdicts are
    pushed to different monitoring services and cannot overwrite each other."""
    install_case(sc10, "a", "good.crt", "good")

    run = sc10.run_script(SCRIPT)

    assert summary(run).index == "00", run.describe()
    assert all(m.index != "00" for m in status_msgs(run)), run.describe()


def test_an_empty_test_directory_is_reported_as_an_error(sc10):
    """No `test_*_cert*` files, so the glob does not match and bash passes the
    pattern through literally. The script tries to open it, fails, and says so
    — which is the right verdict for a test directory that has lost its
    contents."""
    sc10.exec(f"mkdir -p {TESTDIR}")

    run = sc10.run_script(SCRIPT)

    assert "101" in run.errnos, run.describe()
    assert "test_*_cert*" in run.messages[0].text, run.describe()


def test_an_unreadable_certificate_reaches_the_summary(sc10):
    """The three `! -f` guards in `checkocsp` — missing cert, missing issuer,
    missing chain — each print an ERROR and `return 1`. Before the D55 fix none
    of them incremented `ERRSTATUS`, which is what the summary is computed from,
    so a run ended:

        10-01-E-101 ... Can NOT find OCSP_CERT .../test_*_cert*
        10-00-I-109 ... OCSP Summary OK

    The summary flatly contradicted the line above it. Since `sc_10`'s summary
    gets its own index `00`, a dashboard watching it saw a healthy OCSP check
    while the responder was never queried."""
    sc10.exec(f"mkdir -p {TESTDIR}")

    run = sc10.run_script(SCRIPT)

    assert summary(run).level == "E", run.describe()


# --- configuration ----------------------------------------------------------

def test_a_missing_certificate_file_is_reported(sc10):
    """The glob found a name but the issuer file the convention implies is not
    there — the usual way a hand-built test directory is wrong."""
    install_case(sc10, "a", "good.crt", "good")
    sc10.exec(f"rm -f {TESTDIR}/test_a_issuer.pem")

    run = sc10.run_script(SCRIPT)

    assert "101" in run.errnos, run.describe()


def test_the_shipped_config_documents_the_settings_the_script_reads(sc10):
    """`config/10.conf` used to document `OCSP_CONNECT_URL[]`, `OCSP_CERT[]`,
    `OCSP_EXPECTED_STATUS[]`, `OCSP_ISSUER[]` and `OCSP_CACHAIN[]` — none of
    which the script reads. It reads `OCSP_TEST[]`, a *directory*, and
    `OCSP_URL[]`, taking the certificate, issuer, chain and expected status from
    filenames inside it.

    An operator who filled in the shipped example configured a check that
    iterated zero times and then reported `OCSP Summary OK`, having contacted no
    responder at all.

    The config was corrected rather than the script: the directory interface is
    what works and what this suite covers. Asserted by driving the script with
    the settings the config now documents."""
    install_case(sc10, "a", "good.crt", "good")
    shipped = sc10.read_file("/src/config/10.conf")
    assert "OCSP_TEST[0]=" in shipped and "OCSP_URL[0]=" in shipped, shipped
    assert "OCSP_CONNECT_URL" not in shipped, shipped
    assert "OCSP_EXPECTED_STATUS" not in shipped, shipped

    sc10.set_script_config("10", (
        "TIMEOUT=5\n"
        "CHECKTOOL=openssl\n"
        "WARN_OCSP_RESPONDER_CERT_EXPIRE=57600\n"
        "ERROR_OCSP_RESPONDER_CERT_EXPIRE=28800\n"
        f'OCSP_TEST[0]="{TESTDIR}"\n'
        f'OCSP_URL[0]="{sc10.ocsp.url}"\n'
    ))

    run = sc10.run_script(SCRIPT)

    assert status_msgs(run), (
        "the documented config queried no responder at all: " + run.describe())


def test_an_unconfigured_check_says_so_instead_of_reporting_ok(sc10):
    """With no `OCSP_TEST[]` at all the loop never runs. It used to end on
    `OCSP Summary OK` — a check that contacted no responder and looked identical
    to a healthy one.

    It now reports `ERRNO[11]` and the summary is an error. This is a deliberate
    behaviour change: an install that enables `sc_10` and leaves it unconfigured
    starts alerting rather than staying quietly green."""
    sc10.set_script_config("10", (
        "TIMEOUT=5\n"
        "CHECKTOOL=openssl\n"
        "WARN_OCSP_RESPONDER_CERT_EXPIRE=57600\n"
        "ERROR_OCSP_RESPONDER_CERT_EXPIRE=28800\n"
    ))

    run = sc10.run_script(SCRIPT)

    assert "1011" in run.errnos, run.describe()
    assert summary(run).level == "E", run.describe()


def test_help_documents_every_error_code(sc10):
    res = sc10.exec([sc10.script_path(SCRIPT), "--help"])

    for n in range(1, 12):
        assert f"10{n} / " in res.output, res.output
