"""End-to-end tests for the four plain "is this daemon up?" scripts:

    sc_05_pcscd.sh   sc_12_mysql.sh   sc_15_apache.sh   sc_16_ldap.sh

These four are the same check four times over — read `pidfile` and `procname`
from the config, ask `lib/proc_checker.sh`, emit `ERRNO[1]` or `ERRNO[2]` — so
they are driven from one parametrised file rather than four near-identical ones.
The per-script differences that do exist are pinned explicitly: `sc_05` rolls
its own `ps` fallback instead of letting `proc_checker.sh` do the name lookup,
and `sc_12` is the only one that exits non-zero when the daemon is down.

`proc_checker.sh` itself is covered separately in `test_proc_checker.py`.

The processes are copies of `sleep` named after the daemon: every one of these
scripts looks only at the command line `ps` reports, never at what the process
does. `procname` is set to the full `/usr/local/bin/...` path so it matches the
argv exactly, rather than relying on the shipped paths, which exist on none of
the hosts this suite runs on.
"""

from __future__ import annotations

import pytest

PIDFILE = "/var/run/probe.pid"
ABSENT_PIDFILE = "/no/such/probe.pid"

# script, scriptid, process name, running text, stopped text, exit code when down
FAMILY = [
    ("sc_05_pcscd.sh", "05", "pcscd",
     "pcscd is running", "pcscd is NOT running", 0),
    ("sc_12_mysql.sh", "12", "mysqld",
     "mysql is running", "mysql is NOT running", 3),
    ("sc_15_apache.sh", "15", "apache2",
     "Apache webserver is running", "Apache webserver is not running", 0),
    ("sc_16_ldap.sh", "16", "slapd",
     "LDAP directory server is running", "LDAP directory server is not running", 0),
]
IDS = ["pcscd", "mysql", "apache", "ldap"]

ALL = "script, sid, proc, ok_text, bad_text, down_exit"
# the cases that assert on neither the message text nor the exit code
CORE = "script, sid, proc"
CORE_PARAMS = [(script, sid, proc) for script, sid, proc, *_ in FAMILY]


@pytest.fixture(autouse=True)
def _no_leftover_pidfile(syscheck):
    """reset() restores the install but does not clean /var/run, so the pidfile
    a previous test wrote has to go explicitly."""
    syscheck.exec(f"rm -f {PIDFILE}")


def config(sid: str, proc: str, pidfile: str) -> str:
    return f"# generated by test_sc_process_checks.py for {sid}\npidfile={pidfile}\nprocname=/usr/local/bin/{proc}\n"


@pytest.mark.parametrize(ALL, FAMILY, ids=IDS)
def test_a_running_daemon_with_a_valid_pidfile_is_reported_ok(
    syscheck, script, sid, proc, ok_text, bad_text, down_exit
):
    pid = syscheck.start_process(proc)
    syscheck.write_file(PIDFILE, f"{pid}\n")
    syscheck.set_script_config(sid, config(sid, proc, PIDFILE))

    run = syscheck.run_script(script)

    msg = run.only()
    assert msg.level == "I"
    assert msg.errno == f"{sid}1"
    assert msg.index == "01"
    assert msg.text == ok_text, run.describe()


@pytest.mark.parametrize(ALL, FAMILY, ids=IDS)
def test_a_daemon_that_is_not_running_is_reported_as_an_error(
    syscheck, script, sid, proc, ok_text, bad_text, down_exit
):
    syscheck.set_script_config(sid, config(sid, proc, ABSENT_PIDFILE))

    run = syscheck.run_script(script)

    msg = run.only()
    assert msg.level == "E"
    assert msg.errno == f"{sid}2"
    assert msg.index == "01"
    assert msg.text == bad_text, run.describe()


@pytest.mark.parametrize(CORE, CORE_PARAMS, ids=IDS)
def test_a_running_daemon_is_found_by_name_when_the_pidfile_is_absent(
    syscheck, script, sid, proc
):
    """The shipped pidfile paths point at locations most hosts do not use, so
    the name fallback is the path that actually runs in production."""
    syscheck.start_process(proc)
    syscheck.set_script_config(sid, config(sid, proc, ABSENT_PIDFILE))

    run = syscheck.run_script(script)

    msg = run.only()
    assert msg.level == "I", run.describe()
    assert msg.errno == f"{sid}1"


@pytest.mark.parametrize(CORE, CORE_PARAMS, ids=IDS)
def test_a_stale_pidfile_is_reported_as_an_error(syscheck, script, sid, proc):
    """A pidfile left behind by an unclean shutdown names a pid that is gone.
    The daemon is down and must be reported down, not assumed up because the
    file exists."""
    syscheck.write_file(PIDFILE, f"{syscheck.free_pid()}\n")
    syscheck.set_script_config(sid, config(sid, proc, PIDFILE))

    run = syscheck.run_script(script)

    msg = run.only()
    assert msg.level == "E", run.describe()
    assert msg.errno == f"{sid}2"


@pytest.mark.parametrize(CORE, CORE_PARAMS, ids=IDS)
def test_exactly_one_message_is_emitted_per_run(syscheck, script, sid, proc):
    """Each of these scripts checks one thing, so it reports once. Guards
    against the index/arg-shifting failures that made sc_01 and sc_41 emit a
    second meaningless message."""
    pid = syscheck.start_process(proc)
    syscheck.write_file(PIDFILE, f"{pid}\n")
    syscheck.set_script_config(sid, config(sid, proc, PIDFILE))

    run = syscheck.run_script(script)

    assert len(run.messages) == 1, run.describe()


@pytest.mark.parametrize(ALL, FAMILY, ids=IDS)
def test_the_exit_code_when_the_daemon_is_down(
    syscheck, script, sid, proc, ok_text, bad_text, down_exit
):
    """Pins an inconsistency rather than asserting a contract: nothing consumes
    these exit codes (see D5 in REPORT.md), and three of the four scripts exit 0
    on the error path while `sc_12` exits 3. Recorded so a later cleanup is a
    deliberate choice instead of an accident."""
    syscheck.set_script_config(sid, config(sid, proc, ABSENT_PIDFILE))

    run = syscheck.run_script(script)

    assert run.exit_code == down_exit, run.describe()


@pytest.mark.parametrize(ALL, FAMILY, ids=IDS)
def test_help_documents_every_error_code(
    syscheck, script, sid, proc, ok_text, bad_text, down_exit
):
    res = syscheck.exec([syscheck.script_path(script), "--help"])

    for errno in (f"{sid}1", f"{sid}2"):
        assert f"{errno} / " in res.output, res.output
