"""End-to-end tests for related-available/908_clean_old_backups.sh.

`908` deletes backup files older than a retention period. It is the most
destructive script in `related-available/` that runs unattended, so the property
worth proving is not that it deletes — it is that it deletes **only** what the
pattern selects.

REAL-OS: a populated temp tree in the container, real `rm`, real globs. Nothing
is mocked.

`FILENAME[i]` is a **glob**, not a path — the shipped config builds it as
`"${BACKUPDIR[i]}/ejbcabackup-${DATESTR[i]}*"` where `DATESTR` comes from
`x-days-ago-datestr`. That is why the `rm` is unquoted, and why quoting it would
break the script rather than harden it (see item #9 in
`related-available/BUGFIXES_AND_IMPROVEMENTS.md`).
"""

from __future__ import annotations

import pytest

SCRIPT = "related-available/908_clean_old_backups.sh"
BACKUPDIR = "/tmp/backups"

pytestmark = pytest.mark.slow


def config(*entries) -> str:
    """`entries` are (glob, datestr); datestr may be "" to drive the guard."""
    lines = ["# generated by test_908_clean_old_backups.py\n",
             "SCRIPTNAME=clean_old_db_backups\n"]
    for i, (pattern, datestr) in enumerate(entries):
        lines.append(f'FILENAME[{i}]="{pattern}"\n')
        lines.append(f'DATESTR[{i}]="{datestr}"\n')
    return "".join(lines)


def populate(sc, *names: str) -> None:
    sc.exec(f"rm -rf {BACKUPDIR} && mkdir -p {BACKUPDIR}").check()
    for n in names:
        sc.exec(f"echo backup > {BACKUPDIR}/{n}").check()


def remaining(sc) -> list[str]:
    res = sc.exec(f"ls -1 {BACKUPDIR} 2>/dev/null")
    return sorted(l for l in res.stdout.splitlines() if l.strip())


@pytest.fixture
def backups(syscheck):
    populate(syscheck,
             "ejbcabackup-2026-09-01.gz",
             "ejbcabackup-2026-09-01.sql",
             "ejbcabackup-2026-09-14.gz")
    syscheck.set_script_config("908", config(
        (f"{BACKUPDIR}/ejbcabackup-2026-09-01*", "2026-09-01")))
    return syscheck


# --- what it deletes, and what it leaves ------------------------------------

def test_files_matching_the_pattern_are_deleted(backups):
    run = backups.run_script(SCRIPT)

    assert remaining(backups) == ["ejbcabackup-2026-09-14.gz"]
    assert run.messages[0].level == "I", run.describe()


def test_files_outside_the_pattern_are_left_alone(backups):
    """The property that matters. The glob names one date; everything else on
    the same path must survive, including files whose names share a prefix."""
    populate(backups,
             "ejbcabackup-2026-09-01.gz",
             "ejbcabackup-2026-09-010.gz",
             "ejbcabackup-2026-09-1.gz",
             "other-2026-09-01.gz")
    backups.set_script_config("908", config(
        (f"{BACKUPDIR}/ejbcabackup-2026-09-01.gz", "2026-09-01")))

    backups.run_script(SCRIPT)

    assert remaining(backups) == ["ejbcabackup-2026-09-010.gz",
                                  "ejbcabackup-2026-09-1.gz",
                                  "other-2026-09-01.gz"]


def test_a_pattern_matching_nothing_deletes_nothing(backups):
    """A retention window with no backups in it — the normal case on a quiet
    day. It must not be an error, and it must not touch anything."""
    backups.set_script_config("908", config(
        (f"{BACKUPDIR}/ejbcabackup-1999-01-01*", "1999-01-01")))

    run = backups.run_script(SCRIPT)

    assert len(remaining(backups)) == 3
    assert all(m.level == "I" for m in run.messages), run.describe()


def test_a_pattern_matching_nothing_is_reported_as_did_not_exist(backups):
    backups.set_script_config("908", config(
        (f"{BACKUPDIR}/ejbcabackup-1999-01-01*", "1999-01-01")))

    run = backups.run_script(SCRIPT)

    assert "did not exist" in run.messages[0].text, run.describe()


def test_every_configured_pattern_gets_its_own_index(backups):
    """One index per entry, then the summary — so a failure on one retention
    window is its own service."""
    backups.set_script_config("908", config(
        (f"{BACKUPDIR}/ejbcabackup-2026-09-01*", "2026-09-01"),
        (f"{BACKUPDIR}/ejbcabackup-2026-09-14*", "2026-09-14")))

    run = backups.run_script(SCRIPT)

    assert [m.index for m in run.messages] == ["01", "02", "03"], run.describe()
    assert remaining(backups) == []


# --- the summary ------------------------------------------------------------

def test_a_clean_run_ends_with_an_ok_summary(backups):
    run = backups.run_script(SCRIPT)

    assert run.messages[-1].errno == "9081", run.describe()
    assert run.messages[-1].level == "I", run.describe()


def test_no_configured_patterns_still_reports_a_summary(backups):
    """An empty config deletes nothing and reports OK. Pinned rather than
    fixed: unlike `sc_08` and `sc_10`, a `908` with nothing configured is a
    plausible deliberate state, and nothing here silently claims to have
    checked something it did not."""
    backups.set_script_config("908", config())

    run = backups.run_script(SCRIPT)

    assert len(run.messages) == 1, run.describe()
    assert run.messages[0].errno == "9081", run.describe()
    assert len(remaining(backups)) == 3


# --- the date-string guard --------------------------------------------------

def test_an_empty_datestring_is_reported(backups):
    """`DATESTR[i]` comes from `x-days-ago-datestr`. If that fails the pattern
    would collapse to a bare directory glob and delete everything in it, so the
    guard is the difference between a retention policy and `rm -rf`."""
    backups.set_script_config("908", config((f"{BACKUPDIR}/ejbcabackup-*", "")))

    run = backups.run_script(SCRIPT)

    assert run.messages[0].errno == "9084", run.describe()
    assert len(remaining(backups)) == 3, "files were deleted despite the guard"


def test_an_empty_datestring_aborts_the_whole_run(backups):
    """The guard uses `exit`, not `continue`, so one bad date string stops every
    *later* retention window too and no summary is emitted.

    Characterisation, not a defect claim: stopping is arguably right for a
    delete script whose inputs are suspect. Recorded because the behaviour is
    invisible from the messages — the later windows simply never report, and a
    dashboard sees silence rather than an error."""
    backups.set_script_config("908", config(
        (f"{BACKUPDIR}/ejbcabackup-*", ""),
        (f"{BACKUPDIR}/ejbcabackup-2026-09-01*", "2026-09-01")))

    run = backups.run_script(SCRIPT)

    assert [m.errno for m in run.messages] == ["9084"], run.describe()
    assert len(remaining(backups)) == 3


def test_the_date_helper_produces_the_pattern_the_config_expects(backups):
    """`x-days-ago-datestr N` is what builds `DATESTR[]` in the shipped config;
    its output has to be a `%Y-%m-%d` string the backup filenames use."""
    res = backups.exec(
        f"source {backups.home}/lib/libsyscheck.sh 2>/dev/null ; "
        "x-days-ago-datestr 3").check()

    assert res.stdout.strip().count("-") == 2, res.stdout
    assert len(res.stdout.strip()) == 10, res.stdout


@pytest.mark.xfail(strict=True, reason="D73: x-days-ago-datestr with no argument "
                                      "returns a future date instead of defaulting "
                                      "to 0 days")
def test_the_date_helper_defaults_to_today_when_given_no_argument(backups):
    """`lib/libsyscheck.sh` intends to default to 0 days:

        if [ "x$1" == "x" ] ; then
          days = 0
        fi

    but `days = 0` has spaces around the `=`, so bash runs it as a *command*
    (`days: command not found`) and the variable is never set. `date --date
    "now -  days"` then yields **tomorrow**, not today.

    A caller that omits the argument therefore gets a plausible-looking date
    that is wrong in the direction of deleting newer files than intended. No
    caller in the tree does omit it, which is why this has survived."""
    today = backups.exec("date +%Y-%m-%d").check().stdout.strip()
    res = backups.exec(
        f"source {backups.home}/lib/libsyscheck.sh 2>/dev/null ; "
        "x-days-ago-datestr 2>/dev/null")

    assert res.stdout.strip() == today, f"got {res.stdout.strip()}, today is {today}"


# --- message coding ---------------------------------------------------------

@pytest.mark.xfail(strict=True, reason="D74: a successful delete and a pattern that "
                                      "matched nothing share ERRNO[3]")
def test_a_delete_and_a_no_op_are_distinguishable_by_error_code(backups):
    """Line 64 reports a successful delete with `-e ${ERRNO[3]} -d "${DESCR[1]}"`
    — error code 3 paired with description 1 — while line 68 reports "nothing
    matched" with `-e ${ERRNO[3]} -d "${DESCR[3]}"`.

    Both therefore arrive as `9083`, differing only in free text. Anything
    keyed on the error code cannot tell "I deleted your backups" from "there was
    nothing to delete", which for a retention job is exactly the distinction
    worth alerting on. `ERRNO[1]` is the code the success text belongs to."""
    populate(backups, "ejbcabackup-2026-09-01.gz")
    backups.set_script_config("908", config(
        (f"{BACKUPDIR}/ejbcabackup-2026-09-01*", "2026-09-01"),
        (f"{BACKUPDIR}/ejbcabackup-1999-01-01*", "1999-01-01")))

    run = backups.run_script(SCRIPT)

    deleted, absent = run.messages[0], run.messages[1]
    assert deleted.errno != absent.errno, run.describe()


def test_help_documents_every_error_code(backups):
    res = backups.exec([backups.script_path(SCRIPT), "--help"])

    for errno in ("9081", "9082", "9083", "9084"):
        assert f"{errno} / " in res.output, res.output
