"""End-to-end tests for related-available/905_publish_crl.sh.

`905` fetches a CRL from EJBCA, checks it is present, non-empty and still
valid, then publishes it — by copying locally when `REMOTE_HOST` is
`localhost`, or by handing it to `906` otherwise.

Mixed strategy, matching the script's own dependencies:

* **FAKE-BIN** for `ejbca.sh ca getcrl`, which is not in this tree.
* **FIXTURE** for the CRL itself — a real one minted with `openssl ca -gencrl`
  and converted to DER, since `905` reads it with `openssl crl -inform der` and
  runs `lib/cmp_dates.py` against its real validity dates.
* **REAL-OS** for the publish, using the `localhost` path that the shipped
  `config/905.conf` actually configures for every CA.

`905` could not publish anything at all until D133 was fixed on 2026-09-17 — so most of what follows
is written against the documented behaviour and marked xfail. The fixture is
correct and the stub behaves as the real `ejbca.sh` does, so the suite becomes a
functional test once the variable name is corrected.
"""

from __future__ import annotations

import pytest

SCRIPT = "related-available/905_publish_crl.sh"
WORK = "/tmp/905"
EJBCA_HOME = f"{WORK}/ejbca"
PUBLISH_DIR = f"{WORK}/published"
CA_DIR = f"{WORK}/ca"
REMOTE_DIR = "/home/syscheckbak/crl"

pytestmark = pytest.mark.slow

MAKE_CA = r"""
set -e
rm -rf WORKDIR
mkdir -p CADIR/newcerts PUBDIR EJBCADIR/bin
cd CADIR
touch index.txt ; echo 1000 > crlnumber ; echo 1000 > serial
cat > ca.cnf <<'CFG'
[ ca ]
default_ca = CA_default
[ CA_default ]
dir = .
database = $dir/index.txt
new_certs_dir = $dir/newcerts
certificate = $dir/ca.crt
private_key = $dir/ca.key
serial = $dir/serial
crlnumber = $dir/crlnumber
default_md = sha256
default_crl_days = 30
policy = policy_any
[ policy_any ]
commonName = optional
countryName = optional
stateOrProvinceName = optional
organizationName = optional
organizationalUnitName = optional
emailAddress = optional
CFG
openssl req -x509 -newkey rsa:2048 -nodes -keyout ca.key -out ca.crt \
  -subj "/CN=Test CA/O=SysCheck" -days 365 2>/dev/null
openssl ca -config ca.cnf -gencrl -crldays 30 -out fresh.pem 2>/dev/null
openssl crl -in fresh.pem -outform der -out fresh.crl
cp fresh.pem fresh-pem.crl
""".replace("WORKDIR", WORK).replace("CADIR", CA_DIR) \
   .replace("PUBDIR", PUBLISH_DIR).replace("EJBCADIR", EJBCA_HOME)


def install_ejbca(sc, *, source: str | None = None, rc: int = 0) -> None:
    """A stub `ejbca.sh` whose `ca getcrl` writes the fixture CRL to the path
    `905` asks for — which is how the real tool behaves."""
    source = source or f"{CA_DIR}/fresh.crl"
    sc.exec(f"mkdir -p {EJBCA_HOME}/bin").check()
    sc.write_file(
        f"{EJBCA_HOME}/bin/ejbca.sh",
        "#!/bin/bash\n"
        f'echo "$@" >> {WORK}/calls.log\n'
        f"[ {rc} -ne 0 ] && {{ echo 'getcrl failed' ; exit {rc} ; }}\n"
        f'cp {source} "$4" 2>/dev/null || true\n'
        "echo 'CRL written'\n"
        "exit 0\n",
        mode=0o755)


def config(*, caname: str = "TestCA", host: str = "localhost",
           warn: str = "default", error: str = "default",
           directory: str | None = None, user: str = "",
           key: str = "") -> str:
    return ("# generated by test_905_publish_crl.py\n"
            f"CRLCANAME[0]={caname}\n"
            f"REMOTE_HOST[0]={host}\n"
            f"CRLTO_DIR[0]='{directory or PUBLISH_DIR}'\n"
            f"CRL_NAME[0]={caname}.crl\n"
            f"SSHUSER[0]={user}\n"
            f"SSHKEY[0]={key}\n"
            f"CRLWARNTIME[0]={warn}\n"
            f"CRLERRORTIME[0]={error}\n")


@pytest.fixture
def publish(syscheck, sshd_node):
    syscheck.sshd = sshd_node
    syscheck.exec(MAKE_CA).check()
    install_ejbca(syscheck)
    syscheck.set_script_config("905", config())
    return syscheck


def run(sc, *args, seconds: int = 40):
    argv = " ".join(args)
    return sc.exec(f"timeout {seconds} {sc.script_path(SCRIPT)} --screen {argv}",
                   env={"EJBCA_HOME": EJBCA_HOME})


def own(res) -> list:
    from syscheck_harness import parse_messages
    messages, _j, _u = parse_messages(res.stdout + res.stderr)
    return [m for m in messages if m.scriptid == "905"]


def published(sc) -> list[str]:
    r = sc.exec(f"ls -1 {PUBLISH_DIR} 2>/dev/null")
    return sorted(f for f in r.stdout.splitlines() if f.strip())


# --- fetch and publish ------------------------------------------------------

def test_the_crl_is_fetched_from_ejbca(publish):
    run(publish)

    calls = publish.read_file(f"{WORK}/calls.log")
    assert "ca getcrl TestCA" in calls, calls


def test_a_valid_crl_is_published_locally(publish):
    """The `localhost` path, which is what `config/905.conf` configures for
    every CA it ships."""
    run(publish)

    assert published(publish) == ["TestCA.crl"], published(publish)


def test_the_published_crl_is_the_one_that_was_fetched(publish):
    run(publish)

    res = publish.exec(
        f"openssl crl -in {PUBLISH_DIR}/TestCA.crl -issuer -noout").check()
    assert "Test CA" in res.stdout, res.output


def test_a_failed_fetch_publishes_nothing(publish):
    install_ejbca(publish, rc=1)

    run(publish)

    assert published(publish) == [], published(publish)


def test_an_empty_crl_is_not_published(publish):
    """A zero-byte CRL would be worse than none — clients would fetch it and
    treat every certificate as unrevoked."""
    publish.exec(f"rm -f {CA_DIR}/empty.crl && touch {CA_DIR}/empty.crl").check()
    install_ejbca(publish, source=f"{CA_DIR}/empty.crl")

    run(publish)

    assert published(publish) == [], published(publish)


def test_a_missing_crl_file_is_reported(publish):
    """`ejbca.sh` succeeded but wrote nothing — the `! -f` guard in `checkcrl`
    catches it before anything is published."""
    publish.write_file(f"{EJBCA_HOME}/bin/ejbca.sh",
                       "#!/bin/bash\necho 'done'\nexit 0\n", mode=0o755)

    res = run(publish)

    assert published(publish) == []
    assert own(res), "nothing was reported"


def test_each_stage_reports_under_its_own_index(publish):
    """`905` advances `SCRIPTINDEX` per CA and per stage, so fetch, check and
    publish are separate monitoring services."""
    res = run(publish)

    indexes = [m.index for m in own(res)]
    assert indexes, own(res)
    assert len(set(indexes)) > 1, own(res)


def test_the_temporary_directory_is_cleaned_up(publish):
    """The CRL is fetched into `mktemp -d`; leaving those behind on every run
    would fill `/tmp` on a host publishing several CAs hourly."""
    before = publish.exec("ls -1d /tmp/tmp.* 2>/dev/null | wc -l").stdout.strip()

    run(publish)

    after = publish.exec("ls -1d /tmp/tmp.* 2>/dev/null | wc -l").stdout.strip()
    assert after == before, f"{before} -> {after}"


# --- known defects ----------------------------------------------------------

def test_a_der_crl_is_parsed(publish):
    """D133, fixed 2026-09-17. `checkcrl` used to read the CRL's dates with

        LASTUPDATE=$(openssl crl -inform der -in $outname -lastupdate -noout | ...)
        NEXTUPDATE=$(openssl crl -inform der -in $outname -nextupdate -noout | ...)

    but **`outname` was never assigned anywhere in `905`** — a leftover from
    `sc_08_crl_from_webserver.sh`, which does define it. `905` uses `CRLFILE`
    for the same thing everywhere else, including the `! -f` and `stat` guards
    immediately above those two lines.

    Unquoted and empty, `-in $outname` collapsed and openssl read the *next*
    argument as its input file:

        Could not open file or uri for loading CRL from -lastupdate

    Both dates came back empty, `cmp_dates.py` raised on `''`, the CRL was
    graded unparseable and the loop `continue`d — so **no CRL was ever
    published**, by any route. That is the whole script's purpose.

    The two guards also fell through instead of returning, which is why the
    Python traceback reached stderr; they now `return 7` like the branch below
    them."""
    res = run(publish)

    assert "Cant parse file" not in res.output, res.output
    assert published(publish) == ["TestCA.crl"], published(publish)


def test_a_pem_crl_is_parsed(publish):
    """EJBCA's `ca getcrl` writes DER, so that is tried first — but a CRL placed
    by hand, or fetched from a web server, is commonly PEM. Before the fallback
    was added, such a file failed the validity check with "Cant parse file" and
    was silently never published.

    The two formats are indistinguishable by filename, so trying DER and then
    PEM is cheaper than making the operator declare which one they have."""
    install_ejbca(publish, source=f"{CA_DIR}/fresh-pem.crl")

    res = run(publish)

    assert "Cant parse file" not in res.output, res.output
    assert published(publish) == ["TestCA.crl"], published(publish)


def test_an_unparseable_file_is_still_rejected(publish):
    """The fallback must not turn "cannot read this" into "publish it anyway" —
    garbage has to fail both attempts and stop the run."""
    publish.exec(f"echo 'not a crl' > {CA_DIR}/junk.crl").check()
    install_ejbca(publish, source=f"{CA_DIR}/junk.crl")

    res = run(publish)

    assert "Cant parse file" in res.output, res.output
    assert published(publish) == [], published(publish)


def test_the_publish_message_carries_its_description(publish):
    """`905` is inconsistent with itself: **nine** calls write `"${DESCR[N]}"`
    and **eight** write `"$DESCR[N]"` without braces.

    Unbraced, that is `$DESCR` — element 0 of the array, which is unset —
    followed by the literal text `[N]`. So those eight messages arrive as the
    two or three characters `[1]`, `[3]`, `[6]` and so on, with the real text
    dropped and the `%s` arguments unrendered.

    Same defect as D77 in `917`, where every call was affected; here it was
    roughly half, which read like a partial edit that was abandoned. Fixed
    2026-09-17.

    Asserted against the **source**: every affected call site sits past the
    validity check, and until D133 was fixed none could be reached at runtime at
    all. A source check keeps the guarantee whole rather than only covering the
    branches this suite happens to drive."""
    # grep -c exits 1 when the count is zero, so no .check() here
    res = publish.exec(f"grep -c '\"[$]DESCR\\[' {publish.home}/{SCRIPT} || true")

    assert res.stdout.strip() == "0", (
        f"{res.stdout.strip()} printlogmess calls still write $DESCR[N] unbraced")


def test_a_remote_publish_reaches_the_host(publish):
    """`put()` invokes

        906_ssh-copy-to-remote-machine.sh -s $CRLFILE $REMOTEHOST $REMOTEDIR \\
            $SSHUSER $SSHKEY

    while `906` reads only `--file`, `--host`, `--dir`, `--user` and `--key`.
    The positionals land after the `--` separator and are ignored, so `906`
    exits on its missing-file guard and every remote publish fails.

    `925` had exactly this and was converted on 2026-09-16; `905` got the same
    fix on 2026-09-17, and its path moved from `related-enabled/` to
    `related-available/` at the same time, so it no longer depends on `906`
    having been enabled. It was the fifth script in the tree found calling a
    named-option helper positionally, after `913`, `921`, `923`/`924` and
    `919`.

    Driven against a **real** sshd, so a failure here cannot be blamed on an
    unreachable host: the connection would succeed if `906` were given the
    arguments. `906` exits on its own missing-file guard before any ssh is
    attempted, and `905` reports `ERRNO[2]`."""
    publish.exec(f"ln -sf {publish.home}/related-available/906_ssh-copy-to-remote-machine.sh "
                 f"{publish.home}/related-enabled/906_ssh-copy-to-remote-machine.sh").check()
    for scriptid, key in (("906", "SSHTIMEOUT"), ("915", "SSHOPTIONS")):
        publish.set_script_config(
            scriptid,
            f'{key}="-o ConnectTimeout=10 -o StrictHostKeyChecking=no '
            f'-o UserKnownHostsFile=/dev/null -o LogLevel=ERROR"\n')
    publish.exec([
        "ssh", "-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null",
        "-o", "LogLevel=ERROR", "-i", "/root/.ssh/id_syscheck",
        "-l", "syscheckbak", publish.sshd,
        f"rm -rf {REMOTE_DIR} && mkdir -p {REMOTE_DIR}"]).check()
    publish.set_script_config("905", config(host=publish.sshd,
                                            directory=REMOTE_DIR,
                                            user="syscheckbak",
                                            key="/root/.ssh/id_syscheck"))

    res = run(publish)

    assert any(m.errno == "9058" for m in own(res)), own(res)


def test_help_documents_every_error_code(publish):
    res = publish.exec([publish.script_path(SCRIPT), "--help"])

    for n in range(1, 9):
        assert f"905{n} / " in res.output, res.output
