"""End-to-end tests for related-available/900_export_cert.sh.

`900` takes a DER certificate, records its serial, subject and PEM body in a
log, writes a PEM copy into a dated archive directory named after the subject
and serial, then hands the result to `917` for each configured remote host.

FIXTURE: real certificates minted with `openssl req -x509` in the container and
converted to DER — the same approach as `test_934_cert_validity.py`. `900` runs
real `openssl` against them; nothing is mocked.

Until 2026-09-16 this script could not run at all: `--cert` was declared to
`getopt` without a colon, so the option loop never terminated (D82). The colon
is now there, which is what makes this suite possible.
"""

from __future__ import annotations

import pytest

SCRIPT = "related-available/900_export_cert.sh"
WORK = "/tmp/900"
ARCHIVE = f"{WORK}/archive"
CERT_DER = f"{WORK}/cert.der"
CERTLOG = f"{ARCHIVE}/exportcert.log"

pytestmark = pytest.mark.slow


def config(*, archive: str = ARCHIVE, hosts=()) -> str:
    lines = ["# generated by test_900_export_cert.py\n",
             f"OUTPATH={archive}\n",
             f"CERTLOG={archive}/exportcert.log\n",
             "DATE=`date +'%Y-%m-%d_%H.%M.%S'`\n",
             f'OUTPATH2="{archive}"\n']
    for i, host in enumerate(hosts):
        lines.append(f'REMOTE_HOST[{i}]="{host}"\n')
        lines.append(f"REMOTE_USER[{i}]='someuser'\n")
        lines.append(f"REMOTE_DIR[{i}]='/tmp/remote'\n")
        lines.append(f"SSHKEY[{i}]='/root/.ssh/id_syscheck'\n")
    return "".join(lines)


def make_cert(sc, *, subject: str = "/CN=test.example.com/O=SysCheck",
              name: str = "cert") -> str:
    sc.exec(f"mkdir -p {WORK} && openssl req -x509 -newkey rsa:2048 -nodes "
            f"-keyout {WORK}/{name}.key -out {WORK}/{name}.pem "
            f"-subj '{subject}' -days 365 2>/dev/null").check()
    sc.exec(f"openssl x509 -in {WORK}/{name}.pem -outform der "
            f"-out {WORK}/{name}.der").check()
    return f"{WORK}/{name}.der"


@pytest.fixture
def export(syscheck):
    syscheck.exec(f"rm -rf {WORK} && mkdir -p {ARCHIVE}").check()
    make_cert(syscheck)
    syscheck.set_script_config("900", config())
    return syscheck


def run(sc, *args, seconds: int = 20):
    argv = " ".join(args)
    return sc.exec(f"timeout {seconds} {sc.script_path(SCRIPT)} --screen {argv}")


def own(res) -> list:
    from syscheck_harness import parse_messages
    messages, _j, _u = parse_messages(res.stdout + res.stderr)
    return [m for m in messages if m.scriptid == "900"]


def archived(sc) -> list[str]:
    r = sc.exec(f"ls -1 {ARCHIVE} 2>/dev/null")
    return sorted(f for f in r.stdout.splitlines()
                  if f.strip() and not f.endswith(".log"))


# --- it runs at all (D82) ---------------------------------------------------

def test_passing_a_certificate_terminates(export):
    """The D82 regression test. `--cert` used to be declared without a colon,
    so `getopt` emitted `--cert -- '/path'`, the case arm consumed the `--`
    separator and `$1` landed on the path — matching no arm and never being
    shifted. The loop spun forever.

    Measured by exit 124 under a timeout, which is what this asserted before the
    fix."""
    res = run(export, f"--cert={CERT_DER}")

    assert res.exit_code != 124, "the script hung until the timeout fired"


# --- the export -------------------------------------------------------------

def test_a_certificate_is_exported_as_pem(export):
    run(export, f"--cert={CERT_DER}")

    assert len(archived(export)) == 1, archived(export)


def test_the_exported_file_is_valid_pem(export):
    """Not just that a file appeared — that `openssl` can read it back as the
    same certificate."""
    run(export, f"--cert={CERT_DER}")

    name = archived(export)[0]
    res = export.exec(f"openssl x509 -in {ARCHIVE}/{name} -subject -noout").check()
    assert "test.example.com" in res.stdout, res.output


def test_the_filename_carries_the_subject_and_serial(export):
    """The archive is keyed by subject and serial, so one CA's certificates can
    be found without opening them."""
    run(export, f"--cert={CERT_DER}")

    name = archived(export)[0]
    assert name.startswith("archived-cert-"), name
    assert "test.example.com" in name, name


def test_slashes_and_spaces_in_the_subject_are_made_safe(export):
    """A DN is full of `/`, `=` and spaces; all three would break a filename, so
    `900` rewrites them before building the path."""
    cert = make_cert(export, subject="/CN=Space Name/O=Some Org", name="spaced")

    run(export, f"--cert={cert}")

    name = archived(export)[0]
    assert "/" not in name and " " not in name, name
    assert "Space_Name" in name, name


def test_the_log_records_the_serial_subject_and_body(export):
    """`CERTLOG` is the belt-and-braces copy — if the archive is lost the log
    still holds the PEM."""
    run(export, f"--cert={CERT_DER}")

    log = export.read_file(CERTLOG)
    assert "CERTSERIAL:" in log and "CERTSUBJECT:" in log, log
    assert "CERTSTRING:" in log and "BEGIN CERTIFICATE" in log, log[:400]


def test_a_successful_export_is_reported(export):
    res = run(export, f"--cert={CERT_DER}")

    msg = [m for m in own(res) if m.errno == "9001"]
    assert msg and msg[0].level == "I", own(res)


def test_the_archive_directory_is_created_if_missing(export):
    export.set_script_config("900", config(archive=f"{WORK}/fresh"))

    run(export, f"--cert={CERT_DER}")

    assert export.file_exists(f"{WORK}/fresh"), "the output directory was not created"


# --- guards -----------------------------------------------------------------

def test_running_without_a_certificate_is_reported(export):
    res = run(export)

    assert any(m.errno == "9003" for m in own(res)), own(res)


def test_an_unreadable_certificate_is_reported(export):
    res = run(export, "--cert=/tmp/900/no-such-file.der")

    assert any(m.errno == "9003" for m in own(res)), own(res)


def test_a_file_that_is_not_a_certificate_does_not_produce_an_archive(export):
    """Garbage in must not yield a plausible-looking archived file."""
    export.exec(f"echo 'not a certificate' > {WORK}/junk.der").check()

    run(export, f"--cert={WORK}/junk.der")

    assert archived(export) == [], archived(export)


# --- known defects ----------------------------------------------------------

def test_a_corrupt_certificate_is_still_caught(export):
    """`900` reads the serial and subject through pipelines:

        CERTSERIAL=`openssl x509 ... -serial -noout | sed 's/serial=//'`
        if [ $? -ne 0 ] ; then ...

    `$?` after a pipeline is the status of its **last** command — `sed`, which
    succeeds on empty input. Measured: the piped form exits 0 on a corrupt file
    where the bare `openssl` exits 1. So neither of those two guards can ever
    fire.

    The failure is caught anyway, a few lines later, by `CERT=`openssl x509 ...``
    — the one call with no pipe. That is why this passes rather than being a
    defect: no failure is *missed*. What is lost is the attribution, since by
    then two guards have already been skipped, and `CERTSERIAL` and
    `CERTSUBJECT` are silently empty.

    `902` keeps its `openssl` and `sed` calls on separate lines and does not
    have this problem."""
    export.exec(f"echo 'not a certificate' > {WORK}/junk.der").check()

    res = run(export, f"--cert={WORK}/junk.der")

    assert own(res), "a corrupt certificate produced no message at all"
    assert any(m.level == "E" for m in own(res)), own(res)


def test_a_corrupt_certificate_is_not_described_as_a_missing_one(export):
    """D125, fixed 2026-09-17. `900` used `ERRNO[3]` at six call sites,
    `ERRNO[1]` at one, and **`ERRNO[2]` nowhere** — so every failure, including
    a corrupt certificate, was reported with `DESCR[3]`, "script called without
    file". An operator handed that went and checked how the script was invoked,
    which was the one thing that had been fine.

    Now `ERRNO[3]`/`DESCR[3]` is reserved for the missing-file guard and every
    processing failure uses `ERRNO[2]`/`DESCR[2]`, "Export certificate failed
    (%s)" — the description that fits, and the only one carrying a placeholder.

    The `-1 "$?"` those calls passed was useless twice over: `$?` is expanded
    *inside* the branch, where the last command is the `[` test that returned 0
    to enter it, so the value was always the literal `0` — and `DESCR[3]` has no
    `%s` to render it into anyway. The argument is now the file the failure is
    about."""
    export.exec(f"echo 'not a certificate' > {WORK}/junk.der").check()

    res = run(export, f"--cert={WORK}/junk.der")

    failing = [m for m in own(res) if m.level == "E"]
    assert failing, own(res)
    assert "without file" not in failing[0].text, failing[0].text
    assert "junk.der" in failing[0].text, failing[0].text


def test_help_documents_every_error_code(export):
    res = export.exec([export.script_path(SCRIPT), "--help"])

    for errno in ("9001", "9002", "9003"):
        assert f"{errno} / " in res.output, res.output
