"""Tests for syscheck.sh, the orchestrator every check runs under.

`syscheck.sh` is what cron invokes. It parses the operator's flags, decides
which checks run, resets `var/last_status`, and afterwards calls up to three
`related-enabled` hooks. Until now exactly one test touched it — the getopt
regression in `test_shared_library.py` — so the 294 tests in this suite all ran
*under* code that nothing verified.

Two kinds of stand-in are used, and the difference matters:

* **marker scripts** — executables dropped into `scripts-enabled` that record
  that they ran. `syscheck.sh` executes whatever it finds there without caring
  what it is, so these answer "which scripts ran, in what order" exactly.
* **real checks** — `sc_19_alive.sh` (one INFO, no config needed) and
  `sc_15_apache.sh` (one ERROR on this container, since no apache is running)
  for the questions that need genuine syscheck messages, such as what reaches
  `last_status` and in which format.

The hooks are stubbed rather than run: `930_send_filtered_result_to_remote_machine.sh`
copies to a remote host over ssh, and the question here is whether
`syscheck.sh` calls it, not what it does.
"""

from __future__ import annotations

import pytest

SYSCHECK = "syscheck.sh"
RAN_LOG = "/tmp/syscheck-ran.log"
HOLD_FILE_NAME = "var/syscheck-on-hold"

ALIVE = "sc_19_alive.sh"
APACHE = "sc_15_apache.sh"

HOOKS = {
    "filter": "929_filter_syscheck_messages.sh",
    "send": "930_send_filtered_result_to_remote_machine.sh",
    "message": "932_send_result_as_message.sh",
}


def config(**flags) -> str:
    """config/00.conf — empty as shipped, and sourced after common.conf, so it
    is where the after-run hook flags get switched on for a test."""
    lines = ["# generated by test_syscheck_sh.py\n"]
    lines += [f"{name}={value}\n" for name, value in flags.items()]
    return "".join(lines)


@pytest.fixture
def orchestrator(syscheck):
    """A syscheck install with nothing enabled and a clean run log."""
    syscheck.exec(f"rm -f {RAN_LOG}")

    def marker(name: str, available_only: bool = False) -> None:
        """An executable that records that it ran. Lands in scripts-available,
        and in scripts-enabled too unless the test wants it left out."""
        body = f'#!/bin/bash\necho {name} >>{RAN_LOG}\n'
        syscheck.write_file(f"{syscheck.home}/scripts-available/{name}", body, mode=0o755)
        if not available_only:
            syscheck.exec(
                f"ln -sf {syscheck.home}/scripts-available/{name} "
                f"{syscheck.home}/scripts-enabled/{name}"
            ).check()

    def enable(script: str) -> None:
        """Enable one of the real checks."""
        syscheck.exec(
            f"ln -sf {syscheck.home}/scripts-available/{script} "
            f"{syscheck.home}/scripts-enabled/{script}"
        ).check()

    def stub_hook(which: str) -> None:
        body = f'#!/bin/bash\necho hook-{which} >>{RAN_LOG}\n'
        syscheck.write_file(f"{syscheck.home}/related-enabled/{HOOKS[which]}",
                            body, mode=0o755)

    def trim_catalogue(*keep: str) -> None:
        """Empty scripts-available except for `keep`.

        Only for the `--testall` tests: that flag runs the entire catalogue, and
        several real checks block on a network timeout or a 5s sleep, which made
        four tests cost ten minutes between them. What is under test is which
        directory `--testall` reads, not whether all 38 checks work — they have
        their own suites. The harness restores the tree between tests."""
        kept = " ".join(f"! -name {name}" for name in keep)
        syscheck.exec(
            f"find {syscheck.home}/scripts-available -name 'sc_*' {kept} -delete"
        ).check()

    def ran() -> list[str]:
        if not syscheck.file_exists(RAN_LOG):
            return []
        return syscheck.read_file(RAN_LOG).split()

    def run(*args: str):
        return syscheck.run_script(SYSCHECK, *args, screen=False)

    syscheck.marker = marker
    syscheck.enable = enable
    syscheck.trim_catalogue = trim_catalogue
    syscheck.stub_hook = stub_hook
    syscheck.ran = ran
    syscheck.run_syscheck = run
    return syscheck


# --------------------------------------------------------------------------
# which checks run
# --------------------------------------------------------------------------

def test_only_the_scripts_in_scripts_enabled_are_run(orchestrator):
    """`scripts-available` is the catalogue, `scripts-enabled` is the selection.
    A check present but not enabled must stay silent — that is the entire
    mechanism by which a site turns a check off."""
    orchestrator.marker("sc_81_enabled.sh")
    orchestrator.marker("sc_82_not_enabled.sh", available_only=True)

    orchestrator.run_syscheck()

    assert orchestrator.ran() == ["sc_81_enabled.sh"]


def test_the_enabled_scripts_run_in_script_id_order(orchestrator):
    """The glob sorts by filename, which begins with the script id, so the run
    order is by id regardless of what the rest of the name is or of the order
    they were enabled in."""
    orchestrator.marker("sc_44_zulu.sh")
    orchestrator.marker("sc_03_yankee.sh")
    orchestrator.marker("sc_19_alpha.sh")

    orchestrator.run_syscheck()

    assert orchestrator.ran() == ["sc_03_yankee.sh", "sc_19_alpha.sh", "sc_44_zulu.sh"]


def test_a_real_check_reports_through_the_orchestrator(orchestrator):
    orchestrator.enable(ALIVE)

    run = orchestrator.run_syscheck("--screen")

    msg = run.only()
    assert (msg.level, msg.errno, msg.scriptname) == ("I", "193", "alive"), run.describe()


def test_every_enabled_check_reports_once(orchestrator):
    """Two checks, two messages: the loop must not stop at the first, and must
    not run anything twice."""
    orchestrator.enable(ALIVE)
    orchestrator.enable(APACHE)

    run = orchestrator.run_syscheck("--screen")

    assert [m.scriptid for m in run.messages] == ["15", "19"], run.describe()


# --------------------------------------------------------------------------
# the operator's flags
# --------------------------------------------------------------------------

@pytest.mark.parametrize("flag", ["--screen", "-s"])
def test_the_screen_flag_reaches_the_checks(orchestrator, flag):
    """`PRINTTOSCREEN` is exported by `syscheck.sh` and read by every child
    script, so this flag is the only thing standing between an operator running
    syscheck by hand and a completely silent terminal."""
    orchestrator.enable(ALIVE)

    run = orchestrator.run_syscheck(flag)

    assert len(run.messages) == 1, run.describe()


def test_without_the_screen_flag_the_run_is_silent_but_still_logged(orchestrator):
    """Cron mode: nothing on the terminal, everything in the log file."""
    orchestrator.enable(ALIVE)

    run = orchestrator.run_syscheck()

    assert run.messages == [], run.describe()
    assert "alive" in orchestrator.file_log(), orchestrator.file_log()


def test_help_exits_without_running_any_check(orchestrator):
    orchestrator.marker("sc_81_marker.sh")

    res = orchestrator.exec([f"{orchestrator.home}/{SYSCHECK}", "--help"])

    assert res.exit_code == 0, res.output
    assert "Syscheck master script" in res.output, res.output
    assert orchestrator.ran() == []


def test_an_unknown_option_runs_no_checks(orchestrator):
    """Refusing the whole run is the right call — a mistyped flag must not turn
    into a partial run that looks like a complete one."""
    orchestrator.marker("sc_81_marker.sh")

    res = orchestrator.exec([f"{orchestrator.home}/{SYSCHECK}", "--nonsense"])

    assert res.exit_code != 0, res.output
    assert orchestrator.ran() == []


# --------------------------------------------------------------------------
# var/last_status
# --------------------------------------------------------------------------

def test_last_status_starts_with_the_date_of_the_run(orchestrator):
    orchestrator.enable(ALIVE)

    orchestrator.run_syscheck()

    first_line = orchestrator.last_status().splitlines()[0]
    assert orchestrator.exec(f"date -d {first_line!r} +%s").exit_code == 0, first_line


def test_last_status_holds_one_line_per_enabled_check(orchestrator):
    orchestrator.enable(ALIVE)
    orchestrator.enable(APACHE)

    orchestrator.run_syscheck()

    lines = orchestrator.last_status().splitlines()
    assert len(lines) == 3, lines          # the date, then one line per check
    assert "apache" in lines[1], lines
    assert "alive" in lines[2], lines


def test_last_status_is_replaced_by_each_run(orchestrator):
    """It is the *last* status, not a log: `929_filter_syscheck_messages.sh` and
    the monitoring hand-off both read it as the current state of the host, so a
    previous run's findings must not survive into it."""
    orchestrator.enable(ALIVE)
    orchestrator.write_file(f"{orchestrator.home}/var/last_status",
                            "STALE LINE FROM AN EARLIER RUN\n")

    orchestrator.run_syscheck()

    status = orchestrator.last_status()
    assert "STALE" not in status, status
    assert len(status.splitlines()) == 2, status


def test_last_status_is_written_in_oldfmt(orchestrator):
    """`SAVELASTSTATUS_OUTPUTTYPE` defaults to OLDFMT, which is what 929 parses.
    Pinned because the default lives in `syscheck-scripts.conf` while the
    parser lives in another script entirely."""
    orchestrator.enable(ALIVE)

    orchestrator.run_syscheck()

    line = orchestrator.last_status().splitlines()[1]
    assert line.startswith("I-19193-"), line


# --------------------------------------------------------------------------
# --testall
# --------------------------------------------------------------------------

def test_testall_runs_checks_that_are_not_enabled(orchestrator):
    """The point of the flag: try everything in the catalogue, whatever the
    site has turned on."""
    orchestrator.trim_catalogue()
    orchestrator.marker("sc_82_not_enabled.sh", available_only=True)

    orchestrator.run_syscheck("--testall")

    assert "sc_82_not_enabled.sh" in orchestrator.ran()


def test_testall_does_not_run_the_after_run_hooks(orchestrator):
    """A by-hand diagnostic run must not ship its results to the remote machine
    or page anyone."""
    orchestrator.set_script_config("00", config(
        FILTER_SYSCHECK_AFTER_RUN=1,
        SEND_SYSCHECK_RESULT_TO_REMOTE_MACHINE_AFTER_FILTER=1,
        SEND_SYSCHECK_RESULT_AS_MESSAGE=1,
    ))
    for which in HOOKS:
        orchestrator.stub_hook(which)
    orchestrator.trim_catalogue()
    orchestrator.marker("sc_82_not_enabled.sh", available_only=True)

    orchestrator.run_syscheck("--testall")

    assert [name for name in orchestrator.ran() if name.startswith("hook-")] == []


# --------------------------------------------------------------------------
# the after-run hooks
# --------------------------------------------------------------------------

def test_no_hook_runs_when_none_is_enabled(orchestrator):
    """The shipped default: `common.conf` has both documented flags at 0."""
    orchestrator.enable(ALIVE)
    for which in HOOKS:
        orchestrator.stub_hook(which)

    orchestrator.run_syscheck()

    assert orchestrator.ran() == []


@pytest.mark.parametrize("flag, which", [
    ("FILTER_SYSCHECK_AFTER_RUN", "filter"),
    ("SEND_SYSCHECK_RESULT_TO_REMOTE_MACHINE_AFTER_FILTER", "send"),
    ("SEND_SYSCHECK_RESULT_AS_MESSAGE", "message"),
])
def test_each_hook_runs_when_its_flag_is_set(orchestrator, flag, which):
    orchestrator.enable(ALIVE)
    for hook in HOOKS:
        orchestrator.stub_hook(hook)
    orchestrator.set_script_config("00", config(**{flag: 1}))

    orchestrator.run_syscheck()

    assert orchestrator.ran() == [f"hook-{which}"]


def test_the_hooks_run_in_order_after_the_checks(orchestrator):
    """Filter first, then the transfer of the filtered result, then the
    message: 930 sends what 929 produced, so the order is the contract."""
    orchestrator.marker("sc_81_check.sh")
    for which in HOOKS:
        orchestrator.stub_hook(which)
    orchestrator.set_script_config("00", config(
        FILTER_SYSCHECK_AFTER_RUN=1,
        SEND_SYSCHECK_RESULT_TO_REMOTE_MACHINE_AFTER_FILTER=1,
        SEND_SYSCHECK_RESULT_AS_MESSAGE=1,
    ))

    orchestrator.run_syscheck()

    assert orchestrator.ran() == [
        "sc_81_check.sh", "hook-filter", "hook-send", "hook-message",
    ]


# --------------------------------------------------------------------------
# syscheck on hold
# --------------------------------------------------------------------------

def test_a_held_syscheck_runs_nothing(orchestrator):
    """`initscript` calls `isSyscheckOnHold` for scriptid 00 as well, so the
    hold file stops the orchestrator itself, not just the individual checks."""
    orchestrator.marker("sc_81_marker.sh")
    orchestrator.exec(
        f'printf "$(date);maintenance;alice" > {orchestrator.home}/{HOLD_FILE_NAME}'
    ).check()

    orchestrator.run_syscheck("--screen")

    assert orchestrator.ran() == []


def test_a_held_run_prints_the_bare_00_to_the_operator(orchestrator):
    """Pins the behaviour D8 recorded as intentional: `isSyscheckOnHold` runs
    inside `initscript`, before `--screen` has been parsed, so `PRINTTOSCREEN`
    is still 0 and the notice cannot be routed to the terminal. What an
    operator running `syscheck.sh --screen` on a held host actually sees is the
    literal `00` from the bare `printf`. The notice itself reaches the log."""
    orchestrator.exec(
        f'printf "$(date);maintenance;alice" > {orchestrator.home}/{HOLD_FILE_NAME}'
    ).check()

    run = orchestrator.run_syscheck("--screen")

    assert run.output.strip() == "00", run.describe()
    assert "SYSCHECK IS ON HOLD BY: alice" in orchestrator.file_log(), orchestrator.file_log()


# --------------------------------------------------------------------------
# an install with nothing enabled, and an enabled hook that is not installed
#
# Both are by design (D33, withdrawn): syscheck reports on the host, not on its
# own configuration, and an unconfigured install is the operator's business.
# Pinned rather than deleted, because "exits 0 having run nothing" is
# surprising enough that a future reader should find it stated on purpose.
# --------------------------------------------------------------------------

def test_an_empty_scripts_enabled_directory_runs_nothing_and_exits_zero(orchestrator):
    """A fresh install: nothing is enabled, the glob matches nothing, bash
    passes the pattern through literally and `$file` is executed as a filename
    containing `*`. The shell error goes to stderr; the exit status is 0."""
    res = orchestrator.exec([f"{orchestrator.home}/{SYSCHECK}"])

    assert res.exit_code == 0, res.output
    assert "scripts-enabled/sc_*: No such file or directory" in res.output, res.output


def test_an_enabled_hook_that_is_not_installed_exits_zero(orchestrator):
    """`related-enabled` is empty as shipped, so turning on
    `FILTER_SYSCHECK_AFTER_RUN` in `common.conf` without also linking 929 is the
    ordinary way to reach this. Same shape as above: a shell error, exit 0."""
    orchestrator.enable(ALIVE)
    orchestrator.set_script_config("00", config(FILTER_SYSCHECK_AFTER_RUN=1))

    res = orchestrator.exec([f"{orchestrator.home}/{SYSCHECK}"])

    assert res.exit_code == 0, res.output
    assert "929_filter_syscheck_messages.sh: No such file or directory" in res.output


def test_testall_does_not_corrupt_the_last_status_of_the_real_run(orchestrator):
    """The regression guard for D34. `--testall` returns before the `rm -f`/
    `date >` that starts a normal run, but the checks it ran still appended to
    `last_status` through `SAVELASTSTATUS`. So a by-hand `--testall` left the
    file holding the last cron run's date header followed by a mixture of both
    runs — including results from checks this host has deliberately not enabled
    — and whatever read `last_status` next, 929 or the remote transfer, took
    that mixture for the current state of the host."""
    orchestrator.trim_catalogue(ALIVE)
    orchestrator.enable(ALIVE)
    orchestrator.run_syscheck()
    before = orchestrator.last_status()

    orchestrator.marker("sc_82_not_enabled.sh", available_only=True)
    orchestrator.run_syscheck("--testall")

    assert orchestrator.last_status() == before, orchestrator.last_status()[:400]
