"""End-to-end tests for scripts-available/sc_01_diskusage.sh.

The script is exercised against *real* filesystems: the container gets tmpfs
mounts that each test fills to a known percentage, so `df -Ph` parsing, the
threshold comparisons and the message formatting are all covered for real
rather than against a stubbed `df`.

Tests marked `xfail(strict=True)` assert the behaviour the script *should*
have; they are the open defects listed in REPORT.md. When one is fixed the
strict xfail turns into a failure, which is the signal to delete the marker.
"""

from __future__ import annotations

import pytest

FS_A = "/mnt/tfs_a"
FS_B = "/mnt/tfs_b"
SCRIPT = "sc_01_diskusage.sh"


def config(*entries: tuple[str, object, object], extra: str = "") -> str:
    """Build a config/01.conf from (filesystem, err_percent, warn_percent) rows.

    A `None` limit means "leave the array entry unset", which is how an
    operator would express "no value" in the shipped config file.
    """
    lines = ["# generated by the test suite"]
    for i, (filesystem, err, warn) in enumerate(entries):
        lines.append(f'FILESYSTEM[{i}]="{filesystem}"')
        if err is not None:
            lines.append(f"USAGEPERCENT[{i}]={err}")
        if warn is not None:
            lines.append(f"WARN_PERCENT[{i}]={warn}")
    if extra:
        lines.append(extra)
    return "\n".join(lines) + "\n"


@pytest.fixture
def filled(syscheck):
    """Fill FS_A to ~60% and hand back the percentage df actually reports."""
    percent = syscheck.fill_filesystem(FS_A, 60)
    assert 50 < percent < 70, f"tmpfs fill landed at an unexpected {percent}%"
    return percent


# --------------------------------------------------------------- thresholds --


def test_info_when_usage_is_below_the_warn_limit(syscheck, filled):
    syscheck.set_script_config("01", config((FS_A, 95, 90)))
    run = syscheck.run_script(SCRIPT)

    msg = run.only()
    assert msg.level == "I"
    assert msg.errno == "011"
    assert msg.scriptid == "01"
    assert msg.index == "01"
    assert msg.scriptname == "diskusage"
    assert msg.text == f"Diskusage ok ({FS_A} is {filled} percent used: Limit is 90 percent)"


def test_warn_when_usage_is_between_the_warn_and_error_limits(syscheck, filled):
    syscheck.set_script_config("01", config((FS_A, 95, 10)))
    run = syscheck.run_script(SCRIPT)

    msg = run.only()
    assert msg.level == "W"
    assert msg.errno == "012"
    assert msg.text == f"Diskusage exceeded ({FS_A} is {filled} percent used: Limit is 10 percent)"


def test_error_when_usage_is_above_the_error_limit(syscheck, filled):
    syscheck.set_script_config("01", config((FS_A, 10, 5)))
    run = syscheck.run_script(SCRIPT)

    msg = run.only()
    assert msg.level == "E"
    assert msg.errno == "012"
    # the error branch reports the *error* limit, not the warn limit
    assert msg.text == f"Diskusage exceeded ({FS_A} is {filled} percent used: Limit is 10 percent)"


def test_usage_exactly_at_the_limit_is_not_an_error(syscheck, filled):
    """The comparison is `-gt`, so hitting the limit dead on is still OK."""
    syscheck.set_script_config("01", config((FS_A, filled, filled)))
    run = syscheck.run_script(SCRIPT)

    assert run.only().level == "I"


def test_one_percent_over_the_limit_is_an_error(syscheck, filled):
    syscheck.set_script_config("01", config((FS_A, filled - 1, filled - 1)))
    run = syscheck.run_script(SCRIPT)

    assert run.only().level == "E"


def test_warn_percent_falls_back_to_the_error_limit_when_unset(syscheck, filled):
    """With no WARN_PERCENT the script must not warn below the error limit."""
    syscheck.set_script_config("01", config((FS_A, 95, None)))
    run = syscheck.run_script(SCRIPT)

    msg = run.only()
    assert msg.level == "I"
    assert "Limit is 95 percent" in msg.text


def test_warn_percent_accepts_the_literal_default_keyword(syscheck, filled):
    syscheck.set_script_config("01", config((FS_A, 95, "default")))
    run = syscheck.run_script(SCRIPT)

    msg = run.only()
    assert msg.level == "I"
    assert "Limit is 95 percent" in msg.text


# ------------------------------------------------------------- df failures --


def test_nonexistent_filesystem_is_reported_as_an_error(syscheck):
    syscheck.set_script_config("01", config(("/does/not/exist", 90, 80)))
    run = syscheck.run_script(SCRIPT)

    msg = run.only()
    assert msg.level == "E"
    assert msg.errno == "013"
    assert "Diskusage problems" in msg.text
    assert "/does/not/exist" in msg.text
    # the df error text is forwarded to the operator
    assert "No such file or directory" in msg.text


def test_a_broken_entry_does_not_stop_the_remaining_filesystems(syscheck, filled):
    syscheck.set_script_config(
        "01", config(("/does/not/exist", 90, 80), (FS_A, 95, 90), (FS_B, 95, 90))
    )
    run = syscheck.run_script(SCRIPT)

    assert len(run.messages) == 3, run.describe()
    assert run.levels == ["E", "I", "I"]


# ---------------------------------------------------------------- indexing --


def test_each_filesystem_gets_its_own_script_index(syscheck, filled):
    syscheck.set_script_config("01", config((FS_A, 95, 90), (FS_B, 95, 90), ("/", 95, 90)))
    run = syscheck.run_script(SCRIPT)

    assert run.indexes == ["01", "02", "03"], run.describe()
    assert [m.text.split(" is ")[0].split("(")[1] for m in run.messages] == [FS_A, FS_B, "/"]


def test_script_index_is_zero_padded_and_keeps_counting_past_nine(syscheck, filled):
    syscheck.set_script_config("01", config(*[(FS_A, 95, 90)] * 12))
    run = syscheck.run_script(SCRIPT)

    assert run.indexes == [f"{i:02d}" for i in range(1, 13)], run.describe()


# ------------------------------------------------------------ output sinks --


def test_message_is_appended_to_var_last_status(syscheck, filled):
    syscheck.set_script_config("01", config((FS_A, 95, 90)))
    syscheck.run_script(SCRIPT)

    # SAVELASTSTATUS_OUTPUTTYPE defaults to OLDFMT
    assert "I-01011-PKI" in syscheck.last_status()
    assert FS_A in syscheck.last_status()


def test_message_is_appended_to_the_plain_logfile(syscheck, filled):
    syscheck.set_script_config("01", config((FS_A, 95, 90)))
    syscheck.run_script(SCRIPT)

    log = syscheck.file_log()
    assert "01-01-I-011-PKI" in log, log
    assert FS_A in log


def test_message_reaches_syslog(syscheck, filled):
    syscheck.set_script_config("01", config((FS_A, 95, 90)))
    syscheck.run_script(SCRIPT)

    syscheck.exec(
        "for i in $(seq 20); do grep -q 01-01-I-011-PKI /var/log/syslog && break; sleep 0.1; done"
    )
    assert "01-01-I-011-PKI" in syscheck.syslog()


def test_nothing_is_printed_without_the_screen_flag(syscheck, filled):
    syscheck.set_script_config("01", config((FS_A, 95, 90)))
    run = syscheck.run_script(SCRIPT, screen=False)

    assert run.messages == [], run.describe()
    assert run.output.strip() == "", run.output
    # but the message still lands in the other sinks
    assert "01-01-I-011-PKI" in syscheck.file_log()


def test_json_output_format(syscheck, filled):
    syscheck.set_script_config(
        "01", config((FS_A, 95, 90), extra='PRINTTOSCREEN_OUTPUTTYPE="JSON"')
    )
    run = syscheck.run_script(SCRIPT)

    assert len(run.json_messages) == 1, run.describe()
    obj = run.json_messages[0]
    assert obj["SCRIPTNAME"] == "diskusage"
    assert obj["SCRIPTID"] == "01"
    assert obj["SCRIPTINDEX"] == "01"
    assert obj["LEVEL"] == "I"
    assert obj["ERRNO"] == "011"
    assert obj["LONGLEVEL"] == "INFO"
    assert obj["EXTRAARG1"] == FS_A
    assert obj["EXTRAARG2"] == str(filled)
    assert obj["EXTRAARG3"] == "90"
    assert obj["LOGFMT"] == "JSON-1.2"


def test_oldfmt_output_format(syscheck, filled):
    syscheck.set_script_config(
        "01", config((FS_A, 95, 90), extra='PRINTTOSCREEN_OUTPUTTYPE="OLDFMT"')
    )
    run = syscheck.run_script(SCRIPT)

    assert run.output.startswith("I-01011-PKI "), run.output


# --------------------------------------------------------------- metadata --


def test_scriptid_flag(syscheck):
    res = syscheck.exec([syscheck.script_path(SCRIPT), "--scriptid"])
    assert res.stdout.strip() == "01"


def test_scriptname_flag(syscheck):
    res = syscheck.exec([syscheck.script_path(SCRIPT), "--scriptname"])
    assert res.stdout.strip() == "diskusage"


def test_scripthumanname_flag(syscheck):
    res = syscheck.exec([syscheck.script_path(SCRIPT), "--scripthumanname"])
    assert res.stdout.strip() == "Disk usage"


def test_help_documents_every_error_code(syscheck):
    res = syscheck.exec([syscheck.script_path(SCRIPT), "--help"])
    out = res.output

    assert "Scriptid: 01 - Disk usage" in out
    for errno in ("011", "012", "013"):
        assert f"{errno} / " in out, out


def test_help_does_not_emit_a_log_message(syscheck):
    """--help must not pollute last_status / syslog with a fake check result."""
    syscheck.exec([syscheck.script_path(SCRIPT), "--help"])
    assert "01-" not in syscheck.file_log()


# ------------------------------------------------------------- known bugs --


def test_filesystem_path_containing_spaces_is_checked_correctly(syscheck):
    syscheck.exec(f"mkdir -p '{FS_A}/dir with space'").check()
    syscheck.set_script_config("01", config((f"{FS_A}/dir with space", 95, 90)))
    run = syscheck.run_script(SCRIPT)

    msg = run.only()
    assert msg.index == "01", f"script index was corrupted to {msg.index!r}"
    assert msg.level == "I"
    assert f"{FS_A}/dir with space" in msg.text


def test_empty_filesystem_entry_reports_a_config_error(syscheck):
    syscheck.set_script_config("01", config(("", 90, 80)))
    run = syscheck.run_script(SCRIPT)

    msg = run.only()
    assert msg.level == "E"
    assert msg.errno == "013"
    assert "No filesystem specified" in msg.text


def test_missing_usagepercent_reports_a_config_error(syscheck, filled):
    syscheck.set_script_config("01", config((FS_A, None, None)))
    run = syscheck.run_script(SCRIPT)

    msg = run.only()
    assert msg.level == "E"
    assert msg.errno == "013"
    assert "No limit specified" in msg.text


@pytest.mark.known_bug
@pytest.mark.xfail(
    strict=True,
    reason="every syscheck script exits 0 regardless of result, so the nagios / "
           "icinga integration the script header advertises cannot see failures "
           "from the exit code",
)
def test_exit_code_is_nonzero_when_an_error_is_reported(syscheck, filled):
    syscheck.set_script_config("01", config((FS_A, 10, 5)))
    run = syscheck.run_script(SCRIPT)

    assert run.only().level == "E"
    assert run.exit_code != 0


@pytest.mark.known_bug
@pytest.mark.xfail(
    strict=True,
    reason="libsyscheck.sh:17 declares short option -c but default_script_getopt "
           "has no case for it, so the `while true` argument loop never shifts "
           "and the script spins forever",
)
def test_unrecognised_short_option_does_not_hang(syscheck, filled):
    syscheck.set_script_config("01", config((FS_A, 95, 90)))
    res = syscheck.exec(f"timeout 10 {syscheck.script_path(SCRIPT)} -c")

    assert res.exit_code != 124, "script hung until the 10s timeout killed it"


@pytest.mark.known_bug
@pytest.mark.xfail(
    strict=True,
    reason="df -Ph is executed twice per filesystem (sc_01:45 and sc_01:51); the "
           "percentage reported to the operator can differ from the one the "
           "threshold was evaluated against",
)
def test_df_is_only_executed_once_per_filesystem(syscheck, filled):
    syscheck.install_fake_bin(
        "df",
        'echo "$$ $*" >> /tmp/df-calls\nexec /bin/df "$@"\n',
    )
    syscheck.exec("rm -f /tmp/df-calls")
    syscheck.set_script_config("01", config((FS_A, 95, 90)))
    syscheck.run_script(SCRIPT, env={"PATH": "/usr/local/bin:/usr/bin:/bin"})

    calls = syscheck.read_file("/tmp/df-calls").strip().splitlines()
    assert len(calls) == 1, f"df ran {len(calls)} times: {calls}"
