"""End-to-end tests for related-available/904_make_mysql_db_backup.sh.

`904` dumps each configured database with `mysqldump`, gzips it into a
retention subdirectory chosen by the rotation flag (`--daily`, `--weekly`, …),
and reports the file, the elapsed time and the resulting size.

REAL-SVC: a real `mariadb:11` and the real `mariadb-dump`. The backups produced
here are restored again in `test_920_restore_mysql_db_from_backup.py`, so the
pair proves a round trip rather than just that a file appeared.

`904` is one of the better-maintained scripts in `related-available/` — it uses
`set -o pipefail`, array arguments and consistent quoting, and it removes a
partial file when the dump fails. The tests lean on that: most of them assert
real behaviour rather than pinning defects.
"""

from __future__ import annotations

import pytest

from conftest import MARIADB_DATABASE, MARIADB_ROOT_PASSWORD

SCRIPT = "related-available/904_make_mysql_db_backup.sh"
BACKUPDIR = "/tmp/904/backup"
TABLE = "CertificateData"

pytestmark = pytest.mark.slow


def mariadb_config(password: str = MARIADB_ROOT_PASSWORD) -> str:
    return ("# generated by test_904_make_mysql_db_backup.py\n"
            f"DB_NAME={MARIADB_DATABASE}\n"
            f'MYSQLROOT_PASSWORD="{password}"\n'
            "MYSQL_BIN=/usr/bin/mariadb\n"
            "MYSQLDUMP_BIN=/usr/bin/mariadb-dump\n"
            "MYSQLDUMP_OPTIONS=(--single-transaction --quick)\n")


def config(*, databases=(MARIADB_DATABASE,), tables=None,
           backupdir: str = BACKUPDIR) -> str:
    lines = ["# generated by test_904_make_mysql_db_backup.py\n",
             "DATESTING='%Y-%m-%d_%H.%M.%S'\n",
             f"MYSQLBACKUPDIR={backupdir}\n",
             "SUBDIR_DEFAULT=default\n",
             "SUBDIR_DAILY=daily\n",
             "SUBDIR_WEEKLY=weekly\n",
             "SUBDIR_MONTHLY=monthly\n",
             "SUBDIR_YEARLY=yearly\n"]
    for i, db in enumerate(databases):
        lines.append(f'DBNAME[{i}]="{db}"\n')
        lines.append(f'TABLENAMES[{i}]="{(tables or {}).get(db, "")}"\n')
    return "".join(lines)


@pytest.fixture
def backup(syscheck, mariadb_node):
    syscheck.write_file("/root/.my.cnf", f"[client]\nhost={mariadb_node}\n")
    syscheck.exec(f"rm -rf /tmp/904 && mkdir -p {BACKUPDIR}/default "
                  f"{BACKUPDIR}/daily {BACKUPDIR}/weekly "
                  f"{BACKUPDIR}/monthly {BACKUPDIR}/yearly").check()

    def sql(statement: str) -> None:
        syscheck.exec(["mariadb", "-h", mariadb_node, "-uroot",
                       f"-p{MARIADB_ROOT_PASSWORD}", MARIADB_DATABASE,
                       "-e", statement]).check()

    sql(f"DROP TABLE IF EXISTS {TABLE}")
    sql(f"CREATE TABLE {TABLE} (fingerprint VARCHAR(64) PRIMARY KEY)")
    sql(f"INSERT INTO {TABLE} VALUES ('aa'),('bb')")

    syscheck.set_script_config("mariadb", mariadb_config())
    syscheck.set_script_config("904", config())
    syscheck.sql = sql
    return syscheck


def own(run) -> list:
    return [m for m in run.messages if m.scriptid == "904"]


def files_in(sc, subdir: str) -> list[str]:
    res = sc.exec(f"ls -1 {BACKUPDIR}/{subdir} 2>/dev/null")
    return sorted(f for f in res.stdout.splitlines() if f.strip())


# --- a backup is produced ---------------------------------------------------

def test_a_backup_file_is_written(backup):
    backup.run_script(SCRIPT)

    assert len(files_in(backup, "default")) == 1, files_in(backup, "default")


def test_the_backup_is_named_for_the_database_and_the_time(backup):
    """The filename is the only handle on which dump is which, and the
    timestamp is what `908_clean_old_backups.sh` globs on to expire them."""
    backup.run_script(SCRIPT)

    name = files_in(backup, "default")[0]
    assert name.startswith(f"{MARIADB_DATABASE}-"), name
    assert name.endswith(".gz"), name


def test_the_backup_is_real_gzipped_sql(backup):
    """Not merely that a file exists — that it holds the table's data."""
    backup.run_script(SCRIPT)

    name = files_in(backup, "default")[0]
    res = backup.exec(f"zcat {BACKUPDIR}/default/{name}").check()

    assert f"CREATE TABLE `{TABLE}`" in res.stdout, res.stdout[:400]
    assert "'aa'" in res.stdout, res.stdout[:400]


def test_a_successful_backup_reports_the_file_time_and_size(backup):
    """`DESCR[1]` carries all three, and the size is what tells an operator a
    backup silently became empty."""
    run = backup.run_script(SCRIPT)

    msg = own(run)[0]
    assert (msg.level, msg.errno) == ("I", "9041"), run.describe()
    assert ".gz" in msg.text, msg.text
    assert "filesize(bytes): 0" not in msg.text, msg.text


# --- rotation ---------------------------------------------------------------

@pytest.mark.parametrize("flag,subdir", [
    ("--daily", "daily"),
    ("--weekly", "weekly"),
    ("--monthly", "monthly"),
    ("--yearly", "yearly"),
    ("--default", "default"),
])
def test_the_rotation_flag_selects_the_subdirectory(backup, flag, subdir):
    backup.run_script(SCRIPT, flag)

    assert len(files_in(backup, subdir)) == 1, f"{flag} -> {subdir}"


def test_no_rotation_flag_uses_the_default_subdirectory(backup):
    backup.run_script(SCRIPT)

    assert files_in(backup, "default"), "nothing landed in the default subdir"
    assert not files_in(backup, "daily"), "something landed in daily"


def test_a_missing_backup_directory_stops_the_run(backup):
    """Nothing is dumped if there is nowhere to put it — reported rather than
    left to `gzip` to fail per database."""
    backup.set_script_config("904", config(backupdir="/tmp/904/no-such-dir"))

    run = backup.run_script(SCRIPT)

    assert own(run)[0].errno == "9043", run.describe()


# --- several databases ------------------------------------------------------

def test_every_configured_database_is_backed_up(backup):
    backup.sql("CREATE DATABASE IF NOT EXISTS otherdb")

    backup.set_script_config("904", config(databases=(MARIADB_DATABASE, "otherdb")))
    run = backup.run_script(SCRIPT)

    assert len(files_in(backup, "default")) == 2, files_in(backup, "default")
    assert [m.index for m in own(run)] == ["01", "02"], run.describe()


def test_specific_tables_can_be_selected(backup):
    """`TABLENAMES[i]` limits the dump; an empty value means the whole
    database. Read with `read -r -a`, so a space-separated list becomes
    separate arguments rather than one quoted blob."""
    backup.sql("DROP TABLE IF EXISTS OtherTable")
    backup.sql("CREATE TABLE OtherTable (id INT)")

    backup.set_script_config("904", config(tables={MARIADB_DATABASE: TABLE}))
    backup.run_script(SCRIPT)

    name = files_in(backup, "default")[0]
    dump = backup.exec(f"zcat {BACKUPDIR}/default/{name}").check().stdout
    assert f"CREATE TABLE `{TABLE}`" in dump
    assert "OtherTable" not in dump, dump[:400]


# --- failure ----------------------------------------------------------------

def test_a_failing_dump_is_reported_as_an_error(backup):
    backup.set_script_config("mariadb", mariadb_config(password="wrongpw"))

    run = backup.run_script(SCRIPT)

    msg = own(run)[0]
    assert (msg.level, msg.errno) == ("E", "9042"), run.describe()


def test_a_failing_dump_leaves_no_partial_file_behind(backup):
    """The dump is piped into `gzip`, so the output file exists from the moment
    the pipeline starts. Without `set -o pipefail` and the `rm`, a failed dump
    would leave a small valid-looking `.gz` that `908` would later rotate and an
    operator would trust."""
    backup.set_script_config("mariadb", mariadb_config(password="wrongpw"))

    backup.run_script(SCRIPT)

    assert files_in(backup, "default") == [], files_in(backup, "default")


def test_the_error_message_carries_what_mysqldump_said(backup):
    backup.set_script_config("mariadb", mariadb_config(password="wrongpw"))

    run = backup.run_script(SCRIPT)

    assert "denied" in own(run)[0].text.lower(), own(run)[0].text


def test_one_failing_database_does_not_stop_the_others(backup):
    backup.set_script_config("904", config(databases=("no_such_db", MARIADB_DATABASE)))

    run = backup.run_script(SCRIPT)

    assert [m.errno for m in own(run)] == ["9042", "9041"], run.describe()


# --- batch mode -------------------------------------------------------------

def test_batch_mode_prints_the_filename_for_a_caller_to_consume(backup):
    """`--batch` makes `904` usable as a step in a larger job — `931` and `938`
    both want the name of the file just written."""
    res = backup.exec([backup.script_path(SCRIPT), "--batch"])

    printed = [l for l in res.stdout.splitlines() if l.strip().endswith(".gz")]
    assert len(printed) == 1, res.output
    assert backup.file_exists(printed[0]), printed


def test_without_batch_mode_no_filename_is_printed(backup):
    res = backup.exec([backup.script_path(SCRIPT)])

    assert not [l for l in res.stdout.splitlines() if l.strip().endswith(".gz")], \
        res.output


# --- a call that looks wrong but is not -------------------------------------

def test_the_missing_directory_message_identifies_the_script(backup):
    """The guard is spelled differently from every other call in `904`:

        printlogmess ${SCRIPTNAME}  ${SCRIPTID} ${SCRIPTINDEX} -l $ERROR -e ${ERRNO[3]} ...

    The `-n`, `-i` and `-x` flags are missing and the three values are passed as
    bare positional arguments, which the option loop ignores.

    It still reports correctly, and this test exists to record *why* rather than
    to leave the next reader to re-derive it: `printlogmess` is a sourced shell
    function whose `case` arms assign `SCRIPTNAME`, `SCRIPTID` and `SCRIPTINDEX`
    without declaring them `local`. They are therefore the very globals the
    calling script already set, so omitting the flags leaves the correct values
    in place — the function's own "missing scriptid (-i)" guard never fires.

    Recorded as tidiness rather than a defect. It is genuinely fragile: the day
    `printlogmess` makes those variables `local`, this one call site starts
    failing its own guard while every other call keeps working. Unlike D77 in
    `917`, where the referenced `ARCHIVE_DESCR` array does not exist at all, no
    information is lost here."""
    backup.set_script_config("904", config(backupdir="/tmp/904/no-such-dir"))

    run = backup.run_script(SCRIPT)

    assert own(run), run.describe()
    assert own(run)[0].errno == "9043", run.describe()
    assert "printlogmess: missing" not in run.output, run.output


def test_a_second_backup_in_the_same_second_does_not_destroy_the_first(backup):
    """Three correct-looking behaviours combine into data loss.

    `904` names its file from `DATESTING`, `%Y-%m-%d_%H.%M.%S`, so two runs
    within the same second produce the **same path**. `initscript` sets
    `noclobber` (`lib/libsyscheck.sh:56`), so the second run's
    `| gzip -c > "$MYSQLBACKUPFULLFILENAME"` fails with "cannot overwrite
    existing file". `set -o pipefail` correctly notices, and the failure branch
    then runs

        rm -f -- "$MYSQLBACKUPFULLFILENAME"

    intending to clear a half-written file — but the file it deletes is the
    **previous run's complete, valid backup**. The operator is left with one
    error message and zero backups where they had one.

    The `rm` is right in the ordinary case and wrong here because the redirect
    failed before writing anything, so there is no partial file to clean up.
    Guarding the `rm` on the file having been created by *this* run, or using
    `>|`, or giving `DATESTING` sub-second resolution would each break the
    chain.

    Reachable in practice: `920` takes a safety backup of the same database
    immediately before restoring it, and any wrapper calling `904` twice in
    quick succession hits it."""
    first = make_backup_returning_name(backup)
    assert backup.file_exists(first)

    backup.run_script(SCRIPT)

    assert backup.file_exists(first), "the previous backup was deleted"


def make_backup_returning_name(sc) -> str:
    res = sc.exec([sc.script_path(SCRIPT), "--batch"]).check()
    names = [l.strip() for l in res.stdout.splitlines() if l.strip().endswith(".gz")]
    assert len(names) == 1, res.output
    return names[0]


def test_help_documents_every_error_code(backup):
    res = backup.exec([backup.script_path(SCRIPT), "--help"])

    for errno in ("9041", "9042", "9043"):
        assert f"{errno} / " in res.output, res.output
