"""End-to-end tests for scripts-available/sc_33_healthchecker.sh.

`sc_33` is the only check in the tree that *acts* on what it finds: when an
application's health URL stops saying `ALLOK` it runs the configured stop and
start commands, rate-limited to `MAX_RESTARTS` in a rolling 24 hours. That makes
the restart state machine, not the health verdict, the part worth testing — a
check that restarts too eagerly is worse than one that misses an outage.

Two halves:

* the health verdict, driven by a real HTTP server (the harness mock) whose body
  each test chooses — `ALLOK`, `WARNING...`, anything else;
* the restart, driven by a fake `systemctl` that records its argv to a file, so
  "it restarted the right unit, in the right order" is asserted from evidence
  rather than from the absence of an error.

The rate limiter reads `var/auto-restart-<app>.log`, whose rows carry a unix
timestamp. Tests seed that file directly to place restarts inside and outside
the 24h window without waiting.
"""

from __future__ import annotations

import time

import pytest

from syscheck_harness import start_http_server

SCRIPT = "sc_33_healthchecker.sh"
SYSTEMCTL_LOG = "/tmp/systemctl-calls.log"

APP = "certservice-public"
HEALTH = "/app/health"
FULL = "/app/health/display"

pytestmark = pytest.mark.slow


@pytest.fixture(scope="module")
def health_server(syscheck_network):
    srv, _ = start_http_server(syscheck_network, {HEALTH: {"body": "ALLOK"}})
    try:
        yield srv
    finally:
        srv.stop()


def config(host: str, *, checktool: str = "curl", timeout: int = 5,
           pause: int = 0, max_restarts: str | int = 10,
           restartable: bool = True) -> str:
    """One application, pointed at the mock. `pause` is the stop/start gap,
    kept at 0 so the tests do not pay the shipped 10s for every restart."""
    lines = [
        "# generated by test_sc_33_healthchecker.py\n",
        f"TIMEOUT={timeout}\n",
        f"CHECKTOOL={checktool}\n",
        f"STOP_START_PAUSE={pause}\n",
        f"MAX_RESTARTS={max_restarts}\n",
        f'HEALTHCHECK_APP[0]="{APP}"\n',
        f'HEALTHCHECKURL[0]="http://{host}:8080{HEALTH}"\n',
        f'HEALTHCHECKURL_FULL[0]="http://{host}:8080{FULL}"\n',
    ]
    if restartable:
        lines += [
            f'STOP_CMD[0]="systemctl stop tomcat-public"\n',
            f'START_CMD[0]="systemctl start tomcat-public"\n',
        ]
    return "".join(lines)


@pytest.fixture
def health(syscheck, health_server):
    """A healthy app, a fake systemctl that records calls, and nothing else."""
    health_server.set_routes({
        HEALTH: {"body": "ALLOK"},
        FULL: {"body": "Status: ALLOK; Service1: OK"},
    })
    # Neither /tmp nor var/ is restored by `reset()`, and both hold state this
    # script accumulates: the fake's call log, and the rate limiter's memory.
    # Without clearing them each test reads the previous test's restarts.
    syscheck.exec(f"rm -f {SYSTEMCTL_LOG} {syscheck.home}/var/auto-restart-*.log")
    syscheck.install_fake_bin(
        "systemctl",
        f'echo "$*" >> {SYSTEMCTL_LOG}\n'
        'echo "systemctl: $* ok"\n'
        "exit 0\n",
    )
    syscheck.health_server = health_server
    syscheck.set_script_config("33", config(health_server.name))
    return syscheck


def systemctl_calls(sc) -> list[str]:
    if not sc.file_exists(SYSTEMCTL_LOG):
        return []
    return [l for l in sc.read_file(SYSTEMCTL_LOG).splitlines() if l.strip()]


def restart_log(sc, app: str = APP) -> list[str]:
    path = f"{sc.home}/var/auto-restart-{app}.log"
    if not sc.file_exists(path):
        return []
    return [l for l in sc.read_file(path).splitlines() if l.strip()]


def set_health(sc, body: str, full: str = "detail here") -> None:
    sc.health_server.set_routes({HEALTH: {"body": body}, FULL: {"body": full}})


# --- the health verdict -----------------------------------------------------

def test_allok_is_reported_as_healthy_and_restarts_nothing(health):
    run = health.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("I", "331"), run.describe()
    assert APP in msg.text, msg.text
    assert systemctl_calls(health) == [], "a healthy app must not be restarted"


def test_the_detail_url_is_reported_alongside_an_unhealthy_verdict(health):
    """Two URLs are fetched per app: one for the verdict, one for the detail
    shown to the operator. On the failure path the detail is what makes the
    message actionable."""
    set_health(health, "FAIL", full="Service1: OK Service2: DEGRADED")

    run = health.run_script(SCRIPT)

    failure = [m for m in run.messages if m.errno == "332"]
    assert failure, run.describe()
    assert "Service2: DEGRADED" in failure[0].text, failure[0].text


def test_the_detail_url_is_reported_alongside_a_healthy_verdict(health):
    """`HEALTHCHECKURL_FULL` is fetched on every run and passed to
    `printlogmess` as `-2`. `DESCR[1]` gained the second placeholder in the D45
    fix, so the detail now reaches the log instead of being formatted away —
    which is what makes the second request per app worth making."""
    set_health(health, "ALLOK", full="Service1: OK Service2: DEGRADED")

    msg = health.run_script(SCRIPT).only()

    assert "Service2: DEGRADED" in msg.text, msg.text


def test_a_warning_body_is_reported_as_a_warning(health):
    """`WARNING*` is a prefix match, so the app can append its own reason."""
    set_health(health, "WARNING disk filling up")

    msg = health.run_script(SCRIPT).only()

    assert (msg.level, msg.errno) == ("W", "337"), msg.raw


def test_a_warning_does_not_trigger_a_restart(health):
    """The whole point of the WARNING level: degraded but not worth bouncing."""
    set_health(health, "WARNING disk filling up")

    health.run_script(SCRIPT)

    assert systemctl_calls(health) == []


def test_an_unhealthy_body_is_reported_as_an_error(health):
    set_health(health, "FAIL database unreachable")

    run = health.run_script(SCRIPT)

    assert "332" in run.errnos, run.describe()
    assert run.levels[0] == "E", run.describe()


def test_allok_must_be_the_entire_body(health):
    """`[[ $STATUS == ALLOK ]]` is an exact match, unlike sc_02 which greps for
    ALLOK anywhere. An app that answers `ALLOK` plus a detail line is therefore
    read as unhealthy *and restarted*. Pinned because the two checks in this
    tree disagree about what a healthy body looks like."""
    set_health(health, "ALLOK\nService1: OK")

    run = health.run_script(SCRIPT)

    assert "332" in run.errnos, run.describe()
    assert systemctl_calls(health) != [], "the near-miss body also caused a restart"


def test_an_unreachable_app_is_reported_as_an_error(health):
    health.set_script_config("33", config("no-such-app-host"))

    run = health.run_script(SCRIPT)

    assert "332" in run.errnos, run.describe()


def test_every_configured_app_is_checked_in_order(health):
    """Three apps, three verdicts, indexes 01..03 — the first healthy, the
    second warning, the third down."""
    host = health.health_server.name
    health.health_server.set_routes({
        "/a/health": {"body": "ALLOK"}, "/a/full": {"body": "a"},
        "/b/health": {"body": "WARNING b is sad"}, "/b/full": {"body": "b"},
        "/c/health": {"body": "FAIL"}, "/c/full": {"body": "c"},
    })
    conf = ["TIMEOUT=5\n", "CHECKTOOL=curl\n", "STOP_START_PAUSE=0\n",
            "MAX_RESTARTS=10\n"]
    for i, letter in enumerate("abc"):
        conf += [f'HEALTHCHECK_APP[{i}]="app-{letter}"\n',
                 f'HEALTHCHECKURL[{i}]="http://{host}:8080/{letter}/health"\n',
                 f'HEALTHCHECKURL_FULL[{i}]="http://{host}:8080/{letter}/full"\n']
    health.set_script_config("33", "".join(conf))

    run = health.run_script(SCRIPT)

    assert run.levels == ["I", "W", "E"], run.describe()
    assert run.indexes == ["01", "02", "03"], run.describe()


def test_no_configured_app_reports_nothing(health):
    health.set_script_config("33", "TIMEOUT=5\nCHECKTOOL=curl\n"
                                   "STOP_START_PAUSE=0\nMAX_RESTARTS=10\n")

    run = health.run_script(SCRIPT)

    assert run.messages == [], run.describe()


# --- the restart state machine ----------------------------------------------

def test_an_unhealthy_app_is_stopped_then_started(health):
    """The contract the script exists for, asserted from the fake's recorded
    argv: stop first, start second, naming the configured unit."""
    set_health(health, "FAIL")

    health.run_script(SCRIPT)

    assert systemctl_calls(health) == ["stop tomcat-public",
                                       "start tomcat-public"]


def test_a_restart_waits_between_stop_and_start(health):
    """`STOP_START_PAUSE` gives the process time to actually go away; a start
    issued immediately after the stop can hit a port still in TIME_WAIT."""
    set_health(health, "FAIL")
    health.set_script_config("33", config(health.health_server.name, pause=3))

    began = time.monotonic()
    health.run_script(SCRIPT)
    took = time.monotonic() - began

    assert systemctl_calls(health) == ["stop tomcat-public", "start tomcat-public"]
    assert took >= 3, f"stop and start were only {took:.1f}s apart"


def test_an_app_with_no_restart_commands_is_only_reported(health):
    """Most apps are monitored, not managed. Without both commands configured
    the check must report and stop there."""
    set_health(health, "FAIL")
    health.set_script_config("33", config(health.health_server.name,
                                          restartable=False))

    run = health.run_script(SCRIPT)

    assert "332" in run.errnos, run.describe()
    assert systemctl_calls(health) == []


def test_a_restart_is_reported_and_carries_the_command_output(health):
    """A silent restart is the dangerous kind: whoever reads the log has to see
    that the machine acted, and what the commands said."""
    set_health(health, "FAIL")

    run = health.run_script(SCRIPT)

    restart_msgs = [m for m in run.messages if m.errno == "334"]
    assert restart_msgs, run.describe()
    assert any("systemctl" in m.text for m in restart_msgs), run.describe()


def test_a_restart_appends_one_row_to_the_restart_log(health):
    """The log is the rate limiter's only memory, so exactly one row per
    restart — an extra row spends the budget twice, a missing one never."""
    set_health(health, "FAIL")

    health.run_script(SCRIPT)
    assert len(restart_log(health)) == 1, restart_log(health)

    health.run_script(SCRIPT)
    assert len(restart_log(health)) == 2, restart_log(health)


def test_restarts_stop_once_the_24h_budget_is_spent(health):
    """Seed the log with recent restarts so the limiter is already over budget;
    the app stays down and the check says why, rather than bouncing forever."""
    set_health(health, "FAIL")
    health.set_script_config("33", config(health.health_server.name, max_restarts=2))
    now = int(time.time())
    rows = "".join(f"2026-01-01_00.00.0{n};{now - 60};stop;start\n" for n in range(3))
    health.write_file(f"{health.home}/var/auto-restart-{APP}.log", rows)

    run = health.run_script(SCRIPT)

    assert "335" in run.errnos, run.describe()
    assert systemctl_calls(health) == [], "restarted despite being over budget"


def test_restarts_older_than_24h_do_not_count_against_the_budget(health):
    """A rolling window, not a cumulative total: an app that was restarted
    twice last week is still allowed to be restarted today."""
    set_health(health, "FAIL")
    health.set_script_config("33", config(health.health_server.name, max_restarts=2))
    old = int(time.time()) - 86400 - 3600
    rows = "".join(f"2026-01-01_00.00.0{n};{old};stop;start\n" for n in range(5))
    health.write_file(f"{health.home}/var/auto-restart-{APP}.log", rows)

    run = health.run_script(SCRIPT)

    assert "335" not in run.errnos, run.describe()
    assert systemctl_calls(health) == ["stop tomcat-public", "start tomcat-public"]


def test_the_budget_permits_exactly_max_restarts(health):
    """`MAX_RESTARTS=1` must permit exactly one restart in the window. The D44
    fix changed `-gt` to `-ge`: the old comparison blocked only once the count
    had already *passed* the limit, so the app was bounced twice. One restart
    over budget sounds minor, but this setting is the only guard against a
    crash-loop being amplified by the monitor."""
    set_health(health, "FAIL")
    health.set_script_config("33", config(health.health_server.name, max_restarts=1))
    now = int(time.time())
    health.write_file(f"{health.home}/var/auto-restart-{APP}.log",
                      f"2026-01-01_00.00.00;{now - 60};stop;start\n")

    run = health.run_script(SCRIPT)

    assert "335" in run.errnos, run.describe()
    assert systemctl_calls(health) == [], "a second restart was allowed"


def test_an_unset_max_restarts_is_reported_and_blocks_the_restart(health):
    """Without a budget the limiter cannot do its job, so the script says so
    and `restartProcess` bails out rather than restarting unbounded."""
    set_health(health, "FAIL")
    health.set_script_config("33", config(health.health_server.name, max_restarts=""))

    run = health.run_script(SCRIPT)

    assert "336" in run.errnos, run.describe()
    assert systemctl_calls(health) == [], "restarted with no budget configured"


# --- configuration and options ----------------------------------------------

def test_wget_is_supported_as_an_alternative_fetcher(health):
    """`CHECKTOOL=wget` has to reach the same verdict as curl. Before the D46
    fix the branch omitted `-O -`, so wget wrote the body to a file named after
    the URL path and printed nothing: `STATUS` was always empty, no healthy app
    ever matched `ALLOK`, and every one of them was restarted on every cron
    tick. The restart assertion below is the part that matters."""
    health.set_script_config("33", config(health.health_server.name, checktool="wget"))

    run = health.run_script(SCRIPT)

    assert run.only().errno == "331", run.describe()
    assert systemctl_calls(health) == [], "a healthy app was restarted"


def test_an_unknown_checktool_is_reported(health):
    health.set_script_config("33", config(health.health_server.name,
                                          checktool="nosuchtool"))

    run = health.run_script(SCRIPT)

    assert "333" in run.errnos, run.describe()


def test_an_unknown_checktool_does_not_cause_a_restart(health):
    """Nothing was fetched, so nothing is known about the app's health. Before
    the D47 fix the `else` branch reported ERRNO[3] and fell through to
    `[[ $STATUS == ALLOK ]]` with `STATUS` never assigned, took the failure arm
    and restarted the service — so a typo in `CHECKTOOL` bounced every
    configured application on every run. It now `continue`s to the next app."""
    health.set_script_config("33", config(health.health_server.name,
                                          checktool="nosuchtool"))

    health.run_script(SCRIPT)

    assert systemctl_calls(health) == []


def test_an_unhandled_option_exits_instead_of_hanging(health):
    """`sc_33` carries a private copy of the option loop rather than calling
    `default_script_getopt`. Before the D43 fix that copy predated the D1 fix:
    it had no `* )` arm, and its `--options` string listed `c` even though no
    arm handled it, so `-c` matched nothing, nothing shifted, and `while true`
    never ended — one syscheck process per cron tick that never exits.

    Verified by the timeout: exit 124 would mean it was still running when
    killed."""
    res = health.exec(f"timeout 8 {health.script_path(SCRIPT)} -c")

    assert res.exit_code != 124, "-c hung (exit 124)"


def test_an_invalid_option_does_not_restart_anything(health):
    """The same fix from the other direction. `getopt` rejects `-z` and the
    script runs `schelp` — which does not exit on its own, and before the D43
    fix there was no `exit 1` after it, so the script printed its help and then
    went on to check the apps and *restart* them.

    A typo on the command line must not bounce a production service."""
    set_health(health, "FAIL")

    health.exec(f"timeout 30 {health.script_path(SCRIPT)} -z")

    assert systemctl_calls(health) == [], "an invalid option still restarted the app"


@pytest.mark.parametrize("flag, expected", [
    ("--scriptid", "33"),
    ("--scriptname", "healthcheck"),
    ("-a", "Check Health of applications"),
    ("--scripthumanname", "Check Health of applications"),
])
def test_the_identity_flags_answer(health, flag, expected):
    """`-a` was a casualty of the same defect as D43: the case arm handled it,
    but the `--options` string was `"hsvcinf"` — no `a` — so getopt rejected it
    and the script fell into `schelp` and then the spin. Correcting the string
    to `"hsvainf"` fixed the hang and made the short form work."""
    res = health.exec([health.script_path(SCRIPT), flag])

    assert res.output.strip().startswith(expected), res.output


def test_help_documents_every_error_code(health):
    res = health.exec([health.script_path(SCRIPT), "--help"])

    for errno in ("331", "332", "333", "334", "335", "336", "337"):
        assert f"{errno} / " in res.output, res.output
