"""End-to-end tests for scripts-available/sc_42_receipts.sh.

The check runs a site-specific tool, `checkreceipts.sh`, once per configured
receipt type and reads nothing but its exit status — so the fake is a recorder
that exits with whatever the test asks for and writes down the argv it was
called with. There is no output format to get wrong here, which makes this the
one FAKE-BIN suite with no fidelity gap: exit statuses are exit statuses.
"""

from __future__ import annotations

import pytest

SCRIPT = "sc_42_receipts.sh"
TOOL = "/usr/local/bin/checkreceipts.sh"
ARGV_LOG = "/tmp/checkreceipts.argv"

TYPES = ["RA", "CLOUD", "OCSP"]


def config(types: list[str], opts: str = "-s -mt ", first_index: int = 0) -> str:
    lines = [
        "# generated by test_sc_42_receipts.py\n",
        f"RECEIPTS_BIN={TOOL}\n",
        f'RECEIPTS_OPTS="{opts}"\n',
        "SCRIPTNAME=receipts\n",
    ]
    for offset, name in enumerate(types):
        lines.append(f"TYPE[{first_index + offset}]={name}\n")
    return "".join(lines)


@pytest.fixture
def receipts(syscheck):
    """sc_42 with a recording `checkreceipts.sh`."""
    syscheck.exec(f"rm -f {ARGV_LOG}")

    def set_tool(failing: list[str] = ()) -> None:
        cases = "".join(
            f'  {name}) exit 1 ;;\n' for name in failing
        )
        syscheck.install_fake_bin(
            "checkreceipts.sh",
            f'echo "$*" >>{ARGV_LOG}\n'
            'case "${!#}" in\n'
            f"{cases}"
            "  *) exit 0 ;;\n"
            "esac\n",
        )

    syscheck.set_tool = set_tool
    syscheck.set_tool()
    syscheck.set_script_config("42", config(TYPES))
    return syscheck


def test_every_type_with_no_failed_receipts_is_reported_ok(receipts):
    run = receipts.run_script(SCRIPT)

    assert len(run.messages) == len(TYPES), run.describe()
    assert run.levels == ["I"] * len(TYPES), run.describe()
    assert run.errnos == ["421"] * len(TYPES)


def test_each_message_names_its_own_type(receipts):
    run = receipts.run_script(SCRIPT)

    for name, message in zip(TYPES, run.messages):
        assert name in message.text, f"{name} not in {message.text!r}"


def test_a_type_with_failed_receipts_is_reported_as_an_error(receipts):
    receipts.set_tool(failing=["CLOUD"])

    run = receipts.run_script(SCRIPT)

    assert run.levels == ["I", "E", "I"], run.describe()
    assert run.messages[1].errno == "422"
    assert "CLOUD" in run.messages[1].text, run.messages[1].text


def test_every_type_failing_is_reported_separately(receipts):
    receipts.set_tool(failing=TYPES)

    run = receipts.run_script(SCRIPT)

    assert run.levels == ["E"] * len(TYPES), run.describe()


def test_the_tool_is_called_once_per_type_with_the_configured_options(receipts):
    receipts.run_script(SCRIPT)

    calls = receipts.read_file(ARGV_LOG).splitlines()
    assert calls == [f"-s -mt {name}" for name in TYPES], calls


def test_an_absent_tool_is_reported_as_an_error_for_every_type(receipts):
    """`RECEIPTS_BIN` is an absolute path into a site-specific install, so a
    host that does not have it — or has it somewhere else — must not read as
    "no receipts are missing"."""
    receipts.exec(f"rm -f {TOOL}")

    run = receipts.run_script(SCRIPT)

    assert run.levels == ["E"] * len(TYPES), run.describe()


def test_no_configured_types_reports_nothing(receipts):
    receipts.set_script_config("42", config([]))

    run = receipts.run_script(SCRIPT)

    assert run.messages == [], run.describe()


def test_help_documents_every_error_code(receipts):
    res = receipts.exec([receipts.script_path(SCRIPT), "--help"])

    for errno in ("421", "422"):
        assert f"{errno} / " in res.output, res.output


def test_the_message_indexes_start_at_one(receipts):
    """The regression guard for D29. `addOneToIndex` used to be the *last*
    statement in the loop body rather than the first, so the first type reported
    under index 00 — the value `initscript` leaves behind — and the highest
    index was never used. Every receipt type reported one service lower than the
    config reads."""
    run = receipts.run_script(SCRIPT)

    assert run.indexes == ["01", "02", "03"], run.describe()


def test_a_zero_based_type_array_checks_every_configured_type(receipts):
    """The regression guard for D31. The loop used to be

        for (( i = 1 ; i <= ${#TYPE[@]} ; i++ ))

    which worked only because the shipped config numbered its entries from 1.
    Every other array config in this project — `FILESYSTEM`, `PROCNAME`,
    `MDDEV`, `SNMP` — is 0-based, so an operator following that convention here
    silently lost the first receipt type and gained a check of an unset entry,
    which called the tool with no type argument at all. Both halves were silent:
    four configured types still produced four messages."""
    receipts.set_script_config("42", config(TYPES, first_index=0))

    run = receipts.run_script(SCRIPT)

    assert len(run.messages) == len(TYPES), run.describe()
    for name, message in zip(TYPES, run.messages):
        assert name in message.text, f"{name} not in {message.text!r}"
