"""End-to-end tests for scripts-available/sc_08_crl_from_webserver.sh.

This is the highest-consequence check in the tree: a CRL that goes stale without
anyone noticing makes every relying party either fail closed (outage) or fail
open (accepting revoked certificates). So nothing here is simulated except the
web server hosting the file.

The CRLs are **real**, generated by `openssl ca -gencrl` against a real CA
created in the container, with lifetimes chosen per test and served as DER over
HTTP. The script's verdict comes from the real `lib/cmp_dates.py`, which exits
0/1/2/3 for ok/warn/error/expired.

Threshold arithmetic worth keeping in mind while reading: `MINUTES` (warn) and
`ERRMIN` (error) are *minutes of life remaining*, not minutes elapsed. A CRL
with 60 minutes left is a warning when `MINUTES` is 120, because the remaining
life has fallen below the warn floor. That is why these tests hold the CRL
lifetime fixed and move the thresholds, rather than the other way round — it
needs no backdating and exercises exactly the two settings an operator sets.

The server runs on port 80 rather than 8080 because the `CRL_HOST_IP` rewrite
rebuilds the URL as `http://$IP/$PATH` and drops any port, so a ported URL
cannot survive that path.
"""

from __future__ import annotations

import time

import pytest

from syscheck_harness import start_http_server

SCRIPT = "sc_08_crl_from_webserver.sh"
CRL_PATH = "/crl/eIDCA.crl"

pytestmark = pytest.mark.slow

# Builds a throwaway CA and the openssl config `openssl ca -gencrl` needs.
_MAKE_CA = r"""
set -e
rm -rf /tmp/ca
mkdir -p /tmp/ca/newcerts
cd /tmp/ca
: > index.txt
echo 01 > crlnumber
cat > openssl.cnf <<'EOF'
[ ca ]
default_ca = CA_default
[ CA_default ]
dir             = /tmp/ca
database        = $dir/index.txt
new_certs_dir   = $dir/newcerts
crlnumber       = $dir/crlnumber
certificate     = $dir/ca.crt
private_key     = $dir/ca.key
default_md      = sha256
policy          = pol
[ pol ]
commonName = supplied
[ req ]
distinguished_name = dn
prompt = no
[ dn ]
CN = syscheck-test-ca
EOF
openssl req -x509 -newkey rsa:2048 -nodes -keyout ca.key -out ca.crt \
        -days 3650 -config openssl.cnf >/dev/null 2>&1
"""


@pytest.fixture(scope="module")
def crl_ca(_syscheck_session):
    """One CA for the module; /tmp is not restored by `reset()` so it persists."""
    _syscheck_session.exec(_MAKE_CA).check()
    return _syscheck_session


def mint_crl(sc, seconds: int) -> str:
    """Generate a CRL valid for `seconds` and return its DER, base64 encoded.

    `lastUpdate` is always "now" — `openssl ca` offers no way to backdate it —
    so the remaining life equals the full lifetime at the moment of minting.
    """
    sc.exec(
        f"cd /tmp/ca && openssl ca -config openssl.cnf -gencrl -crlsec {seconds} "
        f"-out crl.pem >/dev/null 2>&1 && "
        f"openssl crl -in crl.pem -outform der -out crl.der"
    ).check()
    return sc.exec("base64 -w0 /tmp/ca/crl.der").check().stdout.strip()


def config(host: str, *entries, checktool: str = "curl", timeout: int = 5,
           retries: int = 1, host_ip_all: str | None = None) -> str:
    """`entries` are (path, minutes, errmin, host_ip); None omits the setting.

    `host_ip_all` is set by default in every test that is not about D52,
    because without some `CRL_HOST_IP` in force the script cannot fetch
    anything at all — see `test_a_crl_with_no_host_override_can_be_fetched`.
    """
    lines = ["# generated by test_sc_08_crl_from_webserver.py\n",
             f"TIMEOUT={timeout}\n", f"RETRIES={retries}\n",
             f"CHECKTOOL={checktool}\n"]
    if host_ip_all is not None:
        lines.append(f"CRL_HOST_IP_ALL={host_ip_all}\n")
    for i, entry in enumerate(entries):
        path, minutes, errmin, host_ip = entry
        lines.append(f'CRLS[{i}]="http://{host}{path}"\n')
        if minutes is not None:
            lines.append(f'MINUTES[{i}]="{minutes}"\n')
        if errmin is not None:
            lines.append(f'ERRMIN[{i}]="{errmin}"\n')
        if host_ip is not None:
            lines.append(f"CRL_HOST_IP[{i}]={host_ip}\n")
    return "".join(lines)


def conf(sc, *entries, **kwargs) -> str:
    """`config` bound to the live server, with the host override in force."""
    kwargs.setdefault("host_ip_all", sc.crl_server.name)
    return config(kwargs.pop("host", sc.crl_server.name), *entries, **kwargs)


@pytest.fixture(scope="module")
def crl_server(syscheck_network):
    srv, _ = start_http_server(syscheck_network, {CRL_PATH: {"body": ""}}, port=80)
    try:
        yield srv
    finally:
        srv.stop()


@pytest.fixture
def crl(syscheck, crl_ca, crl_server):
    """A CRL with an hour of life left, served over HTTP, thresholds unset."""
    syscheck.crl_server = crl_server
    syscheck.crl_b64 = mint_crl(syscheck, 3600)
    crl_server.set_routes({CRL_PATH: {"body_b64": syscheck.crl_b64}})
    syscheck.set_script_config("08", conf(syscheck, (CRL_PATH, 10, 5, None)))
    return syscheck


def per_crl(run):
    """The per-CRL messages, i.e. everything but the trailing summary."""
    return run.messages[:-1]


def summary(run):
    return run.messages[-1]


# --- the four verdicts ------------------------------------------------------

def test_a_fresh_crl_is_reported_ok(crl):
    """60 minutes of life left against a 10-minute warn floor."""
    run = crl.run_script(SCRIPT)

    assert [m.errno for m in per_crl(run)] == ["082"], run.describe()
    assert per_crl(run)[0].level == "I", run.describe()


def test_a_crl_below_the_warn_threshold_is_a_warning(crl):
    """Same CRL, warn floor raised above the remaining life."""
    crl.set_script_config("08", conf(crl,
                                       (CRL_PATH, 120, 30, None)))

    run = crl.run_script(SCRIPT)

    msg = per_crl(run)[0]
    assert (msg.level, msg.errno) == ("W", "088"), run.describe()


def test_a_crl_below_the_error_threshold_is_an_error(crl):
    """Error floor raised above the remaining life: more severe than warn, and
    it must win even though the warn floor is also crossed."""
    crl.set_script_config("08", conf(crl,
                                       (CRL_PATH, 120, 90, None)))

    run = crl.run_script(SCRIPT)

    msg = per_crl(run)[0]
    assert (msg.level, msg.errno) == ("E", "087"), run.describe()


def test_an_expired_crl_is_reported_as_expired(crl):
    """Distinct from "past the error level": the CRL's nextUpdate is in the
    past, so relying parties are already rejecting or ignoring it."""
    crl.crl_server.set_routes({CRL_PATH: {"body_b64": mint_crl(crl, 2)}})
    time.sleep(3)

    run = crl.run_script(SCRIPT)

    msg = per_crl(run)[0]
    assert (msg.level, msg.errno) == ("E", "086"), run.describe()


def test_the_threshold_boundary_is_crossed_at_the_configured_minute(crl):
    """Both sides of one boundary, so the comparison direction is pinned: with
    60 minutes left, a 59-minute warn floor is still OK and a 61-minute floor
    is a warning."""
    crl.set_script_config("08", conf(crl, (CRL_PATH, 59, 5, None)))
    assert per_crl(crl.run_script(SCRIPT))[0].level == "I"

    crl.set_script_config("08", conf(crl, (CRL_PATH, 61, 5, None)))

    assert per_crl(crl.run_script(SCRIPT))[0].level == "W"


def test_the_verdict_message_carries_the_time_remaining(crl):
    """`cmp_dates.py`'s text is what tells an operator how long they have."""
    msg = per_crl(crl.run_script(SCRIPT))[0]

    assert "until expire" in msg.text, msg.text


def test_default_thresholds_are_used_when_none_are_configured(crl):
    """With `MINUTES`/`ERRMIN` unset the script passes no `--warnminutes` and
    `cmp_dates.py` falls back to half the CRL lifetime for warn, a quarter for
    error. A 60-minute CRL with 60 minutes left is comfortably inside both."""
    crl.set_script_config("08", conf(crl,
                                       (CRL_PATH, None, None, None)))

    run = crl.run_script(SCRIPT)

    assert per_crl(run)[0].errno == "082", run.describe()


# --- fetching ---------------------------------------------------------------

def test_a_missing_crl_is_reported_once_as_undownloadable(crl):
    """`curl` runs without `-f`, so a 404 exits 0 and the error page is saved as
    if it were the CRL. Before the D53 fix the cascade was:

    * `openssl crl -lastupdate` fails  -> ERROR 081
    * `openssl crl -nextupdate` fails  -> ERROR 081
    * neither branch returned, so `cmp_dates.py` was called with two empty date
      strings, raised `ValueError`, and dumped a Python traceback into the
      check's output
    * Python exits 1 on an uncaught exception, and 1 is `cmp_dates.py`'s code
      for **warn** — so the crash was reported as `CRL has past the WARN level`
      with an empty detail.

    One missing CRL produced three messages, the last and least severe of them a
    fabricated verdict about a validity that was never computed. Both parse
    guards now `return`.

    `if [ "x$CRLCHECK" = "x" ]` could never have caught it: `$?` is always set,
    so that guard is unreachable either way."""
    crl.set_script_config("08", conf(crl, ("/no-such.crl", 10, 5, None)))

    run = crl.run_script(SCRIPT)

    assert len(per_crl(run)) == 1, run.describe()
    assert per_crl(run)[0].level == "E", run.describe()
    assert not [l for l in run.unparsed if "Traceback" in l], run.unparsed


def test_an_unresolvable_host_is_reported_as_undownloadable(crl):
    crl.set_script_config("08", conf(crl, (CRL_PATH, 10, 5, None),
                                     host="no-such-crl-host",
                                     host_ip_all="no-such-crl-host"))

    run = crl.run_script(SCRIPT)

    msg = per_crl(run)[0]
    assert (msg.level, msg.errno) == ("E", "083"), run.describe()


def test_an_empty_crl_file_is_reported_by_size(crl):
    """A web server that answers 200 with nothing — a half-written CRL, or a
    publication job that truncated the file."""
    crl.crl_server.set_routes({CRL_PATH: {"body": ""}})

    run = crl.run_script(SCRIPT)

    msg = per_crl(run)[0]
    assert (msg.level, msg.errno) == ("E", "084"), run.describe()


def test_a_body_that_is_not_a_crl_is_reported_as_unparseable(crl):
    """An HTML error page served with a 200 is the classic way this fails: the
    download "succeeds" and the content is worthless."""
    crl.crl_server.set_routes({CRL_PATH: {"body": "<html>404 not found</html>"}})

    run = crl.run_script(SCRIPT)

    assert "081" in run.errnos, run.describe()
    assert summary(run).level == "E", run.describe()


def test_a_truncated_crl_is_reported_as_unparseable(crl):
    """Valid DER for the first half and nothing after it — openssl must reject
    it rather than read a bogus date out of the fragment."""
    import base64
    der = base64.b64decode(crl.crl_b64)
    half = base64.b64encode(der[: len(der) // 2]).decode()
    crl.crl_server.set_routes({CRL_PATH: {"body_b64": half}})

    run = crl.run_script(SCRIPT)

    assert "081" in run.errnos, run.describe()


def test_a_server_that_answers_too_slowly_is_reported(crl):
    crl.set_script_config("08", conf(crl,
                                       (CRL_PATH, 10, 5, None), timeout=2))
    crl.crl_server.set_routes({CRL_PATH: {"body_b64": crl.crl_b64, "delay": 10}})

    run = crl.run_script(SCRIPT)

    assert per_crl(run)[0].level == "E", run.describe()


def test_wget_is_supported_as_an_alternative_fetcher(crl):
    crl.set_script_config("08", conf(crl,
                                       (CRL_PATH, 10, 5, None), checktool="wget"))

    run = crl.run_script(SCRIPT)

    assert per_crl(run)[0].errno == "082", run.describe()


# --- the summary message ----------------------------------------------------

def test_a_healthy_run_ends_with_an_ok_summary(crl):
    run = crl.run_script(SCRIPT)

    assert summary(run).level == "I", run.describe()


def test_the_summary_reports_the_most_severe_result(crl):
    """One warning among several CRLs has to reach the summary, since that is
    the message a dashboard keyed on the summary index will show."""
    crl.set_script_config("08", conf(crl,
                                       (CRL_PATH, 10, 5, None),
                                       (CRL_PATH, 120, 30, None)))

    run = crl.run_script(SCRIPT)

    assert [m.level for m in per_crl(run)] == ["I", "W"], run.describe()
    assert summary(run).level == "W", run.describe()


def test_an_error_outranks_a_warning_in_the_summary(crl):
    crl.set_script_config("08", conf(crl,
                                       (CRL_PATH, 120, 30, None),
                                       (CRL_PATH, 120, 90, None)))

    run = crl.run_script(SCRIPT)

    assert summary(run).level == "E", run.describe()


def test_the_summary_names_the_crl_that_failed(crl):
    crl.set_script_config("08", conf(crl, ("/no-such.crl", 10, 5, None)))

    run = crl.run_script(SCRIPT)

    assert "no-such.crl" in summary(run).text, summary(run).text


def test_the_summary_has_an_index_of_its_own(crl):
    """`send_mess_to_monitoring` keys the passive check by
    `${SCRIPTID}-${SCRIPTINDEX}`, so the summary needs an index the per-CRL
    verdicts never use. Before the D50 fix it ran after the loop without
    resetting `SCRIPTINDEX` and inherited the last CRL's — with one CRL
    configured both were `08-01`, pushed to the same service, the summary
    arriving second and winning. `sc_10` always did this correctly."""
    run = crl.run_script(SCRIPT)

    assert summary(run).index != per_crl(run)[-1].index, run.describe()


def test_an_empty_crl_list_is_reported_rather_than_summarised_as_ok(crl):
    """No `CRLS[]` entries at all: the loop body never runs. It used to end on an
    INFO summary, so an install that lost its CRL config looked identical to one
    where every CRL was fresh — "green means checked" quietly broken.

    It now reports `ERRNO[5]`, the script's existing "Configuration error" code,
    and the summary is an error. Deliberate behaviour change, matching the guard
    added to `sc_10` at the same time: a check that is enabled but unconfigured
    alerts rather than staying green."""
    crl.set_script_config("08", "TIMEOUT=5\nRETRIES=1\nCHECKTOOL=curl\n")

    run = crl.run_script(SCRIPT)

    assert "085" in run.errnos, run.describe()
    assert summary(run).level == "E", run.describe()


# --- multiple CRLs and the host rewrite -------------------------------------

def test_every_configured_crl_is_checked_in_order(crl):
    crl.set_script_config("08", conf(crl,
                                       (CRL_PATH, 10, 5, None),
                                     (CRL_PATH, 120, 30, None),
                                     (CRL_PATH, 120, 90, None)))

    run = crl.run_script(SCRIPT)

    assert [m.level for m in per_crl(run)] == ["I", "W", "E"], run.describe()
    assert [m.index for m in per_crl(run)] == ["01", "02", "03"], run.describe()


def test_the_host_ip_override_redirects_the_request(crl):
    """`CRL_HOST_IP` exists so a CRL published on a name that does not resolve
    from the monitoring host can still be fetched, by connecting to an address
    and passing the name in a `Host:` header. Proved by pointing the URL at a
    hostname that does not resolve and the override at the live server."""
    crl.set_script_config("08", config("crl.example.com",
                                       (CRL_PATH, 10, 5, crl.crl_server.name)))

    run = crl.run_script(SCRIPT)

    assert per_crl(run)[0].errno == "082", run.describe()


def test_a_crl_with_no_host_override_can_be_fetched(crl):
    """The host override is optional — the obvious config is a bare list of CRL
    URLs, with no `CRL_HOST_IP` at all.

    Before the D52 fix the fetch was built as
    `curl ... ${CHECK_HOST_ARG1} "${CHECK_HOST_ARG2}" ...` with the second
    **quoted**, so with no override it survived as a literal empty argument and
    curl aborted with `option : blank argument where content is expected`
    before making any request — every CRL reported undownloadable. The shipped
    config only escaped it by accident, via D51's leak from the first entry.

    An array expands to nothing when empty, so the bare-URL config now works."""
    crl.set_script_config("08", config(crl.crl_server.name,
                                       (CRL_PATH, 10, 5, None)))

    run = crl.run_script(SCRIPT)

    assert per_crl(run)[0].errno == "082", run.describe()


def test_thresholds_do_not_leak_from_one_crl_to_the_next(crl):
    """`checkcrl` sets `ARGWARNMIN`/`ARGERRMIN` only when the entry configures a
    threshold. They used to be plain globals with no reset on the "default"
    path, so an entry that omits `MINUTES` silently ran with the previous
    entry's value — and the same leak carried an earlier CRL's `Host:` header
    to a later one, which is how a check ends up validating the wrong file.

    Here the first CRL sets a 120-minute warn floor and the second sets none;
    the second must fall back to half its own lifetime and be OK. `local`
    declarations make each call start clean."""
    crl.set_script_config("08", conf(crl,
                                       (CRL_PATH, 120, 30, None),
                                       (CRL_PATH, None, None, None)))

    run = crl.run_script(SCRIPT)

    assert [m.level for m in per_crl(run)] == ["W", "I"], run.describe()


def test_the_temporary_file_is_removed_on_every_exit_path(crl):
    """`checkcrl` creates its download target with `mktemp` and used to remove it
    only on the success path, so each of the five early `return`s leaked a file
    into /tmp — and a CRL that cannot be fetched hits one of them every run.

    A `RETURN` trap now covers all of them. `EXIT` would not: bash traps are
    global, and `checkcrl` is called once per configured CRL, so an `EXIT` trap
    would only clean up after the last one."""
    before = crl.exec("ls -1 /tmp/tmp.* 2>/dev/null | wc -l").check().stdout.strip()

    crl.set_script_config("08", conf(crl,
                                     ("/no-such.crl", 10, 5, None),
                                     (CRL_PATH, 10, 5, None),
                                     ("/also-missing.crl", 10, 5, None)))
    crl.run_script(SCRIPT)

    after = crl.exec("ls -1 /tmp/tmp.* 2>/dev/null | wc -l").check().stdout.strip()
    assert after == before, f"leaked {int(after) - int(before)} temp files"


def test_help_documents_every_error_code(crl):
    res = crl.exec([crl.script_path(SCRIPT), "--help"])

    for n in range(1, 10):
        assert f"08{n} / " in res.output, res.output
