"""End-to-end tests for scripts-available/sc_02_ejbca.sh against a real HTTP server.

`sc_02` fetches EJBCA's healthcheck servlet and classifies the response body:
`ALLOK` anywhere means healthy, `ERROR` anywhere means unhealthy, anything else
means the application server is unavailable. It is therefore a *body* check, not
a status-code check — nothing in the script looks at the HTTP status at all, and
these tests pin that.

The server is the harness mock (`start_http_server`) rather than the repo's own
`test/pyhton-dummy-health-web-server.py`: that one needs Flask in the image and
serves `/health`, `/ok`, `/fail`, while the script requests a hard-coded
`/ejbca/publicweb/healthcheck/ejbcahealth` on a hard-coded port 8080. The
transport is real HTTP over TCP driven by the image's real `curl` and `wget`,
so only EJBCA's *content* is simulated.

Failure paths are produced for real — a stopped server, an unresolvable name, a
server that answers too slowly — not by faking curl.
"""

from __future__ import annotations

import pytest

from syscheck_harness import start_http_server

SCRIPT = "sc_02_ejbca.sh"
HEALTH_PATH = "/ejbca/publicweb/healthcheck/ejbcahealth"

# What a healthy EJBCA healthcheck servlet actually returns.
ALLOK = "ALLOK"
# ... and the shape of a failure, quoted from lang/02.english's HELP[2].
DB_DOWN = "ERROR: Error Connecting to EJBCA Database"

pytestmark = pytest.mark.slow


@pytest.fixture(scope="module")
def health_server(syscheck_network):
    """One mock EJBCA for the whole module; each test sets the body it needs."""
    srv, _ = start_http_server(syscheck_network, {HEALTH_PATH: {"body": ALLOK}})
    try:
        yield srv
    finally:
        srv.stop()


def config(hostname: str, timeout: int = 10, checktool: str = "curl") -> str:
    return (
        "# generated by test_sc_02_ejbca.py\n"
        f"EJBCA_HOSTNAME={hostname}\n"
        f"EJBCA_TIMEOUT={timeout}\n"
        f"CHECKTOOL={checktool}\n"
    )


@pytest.fixture
def ejbca(syscheck, health_server):
    """sc_02 pointed at the live mock, which is reset to healthy for each test."""
    health_server.set_routes({HEALTH_PATH: {"body": ALLOK}})
    syscheck.health_server = health_server
    syscheck.set_script_config("02", config(health_server.name))
    return syscheck


# --- the two states EJBCA actually reports ---------------------------------

def test_allok_is_reported_as_healthy(ejbca):
    run = ejbca.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("I", "021"), run.describe()
    assert ALLOK in msg.text, msg.text


def test_an_error_body_is_reported_as_an_error(ejbca):
    ejbca.health_server.set_routes({HEALTH_PATH: {"body": DB_DOWN}})

    run = ejbca.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "022"), run.describe()
    assert "Error Connecting to EJBCA Database" in msg.text, msg.text


def test_the_verdict_follows_the_body_not_the_http_status(ejbca):
    """EJBCA serves its failures with a 500. The script never inspects the
    status, so the body alone decides — asserted from both directions so that
    adding a `curl -f` later cannot pass silently."""
    ejbca.health_server.set_routes({HEALTH_PATH: {"status": 500, "body": DB_DOWN}})
    assert ejbca.run_script(SCRIPT).only().errno == "022"

    # a 500 carrying a healthy body still reads as healthy
    ejbca.health_server.set_routes({HEALTH_PATH: {"status": 500, "body": ALLOK}})
    run = ejbca.run_script(SCRIPT)

    assert run.only().errno == "021", run.describe()


def test_allok_wins_when_the_body_contains_both_words(ejbca):
    """The `ALLOK` branch is tested first, so a body mentioning both is healthy.
    Worth pinning: if EJBCA ever reported `ALLOK` alongside a per-subsystem
    error line, this check would stay green."""
    ejbca.health_server.set_routes(
        {HEALTH_PATH: {"body": f"{ALLOK} ERROR CAToken is disconnected"}})

    run = ejbca.run_script(SCRIPT)

    assert run.only().errno == "021", run.describe()


# --- the application server not answering -----------------------------------

def test_an_unrecognised_body_is_reported_as_unavailable(ejbca):
    """An app server that is up but not serving EJBCA — a container that has
    not deployed yet, or a load balancer error page."""
    ejbca.health_server.set_routes(
        {HEALTH_PATH: {"status": 503, "body": "<html>Service Unavailable</html>"}})

    run = ejbca.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "024"), run.describe()


def test_a_404_is_reported_as_unavailable(ejbca):
    """The servlet path is gone: the server answers, so curl succeeds, but the
    body is neither ALLOK nor ERROR."""
    ejbca.health_server.set_routes({"/somewhere-else": {"body": ALLOK}})

    run = ejbca.run_script(SCRIPT)

    assert run.only().errno == "024", run.describe()


def test_an_empty_body_is_reported_as_unavailable(ejbca):
    ejbca.health_server.set_routes({HEALTH_PATH: {"body": ""}})

    run = ejbca.run_script(SCRIPT)

    assert run.only().errno == "024", run.describe()


def test_a_refused_connection_is_reported_as_an_error(ejbca, syscheck_network):
    """The real outage this check exists for, produced for real: start a second
    mock, prove it is seen as healthy, stop it, and check the verdict flips."""
    srv, name = start_http_server(syscheck_network, {HEALTH_PATH: {"body": ALLOK}})
    try:
        ejbca.set_script_config("02", config(name))
        assert ejbca.run_script(SCRIPT).only().errno == "021"
    finally:
        srv.stop()

    run = ejbca.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "022"), run.describe()
    # the message carries curl's own diagnosis, which is the only clue an
    # operator gets about *why* it could not connect
    assert "curl" in msg.text.lower() or "connect" in msg.text.lower(), msg.text


def test_a_connection_failure_keeps_the_same_script_index_as_a_healthy_check(ejbca):
    """`SCRIPTINDEX` is initialised to `00` and raised to `01` by
    `addOneToIndex` — but that call sits *after* the curl error branch, so the
    two branches report under different indexes: `02-01` when EJBCA answers,
    `02-00` when it cannot be reached.

    This is not cosmetic. `send_mess_to_monitoring` keys the passive check by
    `${SCRIPTID}-${SCRIPTINDEX}`, so the service that reports OK is a different
    service from the one that reports the outage. The OK service simply stops
    being updated — going stale rather than red — while an `02-00` nobody has
    a check defined for goes critical. Same defect class as D25 and D29."""
    healthy = ejbca.run_script(SCRIPT).only().index

    ejbca.set_script_config("02", config("no-such-ejbca-host"))
    failed = ejbca.run_script(SCRIPT).only()

    assert failed.errno == "022"
    assert failed.index == healthy, f"healthy={healthy} failed={failed.index}"


def test_an_unresolvable_hostname_is_reported_as_an_error(ejbca):
    ejbca.set_script_config("02", config("no-such-ejbca-host"))

    run = ejbca.run_script(SCRIPT)

    assert run.only().errno == "022", run.describe()


def test_a_server_that_answers_too_slowly_times_out(ejbca):
    """`EJBCA_TIMEOUT` is the whole point of the setting; a hung app server that
    holds the connection open must be an error rather than a hang."""
    ejbca.set_script_config("02", config(ejbca.health_server.name, timeout=2))
    ejbca.health_server.set_routes({HEALTH_PATH: {"body": ALLOK, "delay": 10}})

    run = ejbca.run_script(SCRIPT)

    assert run.only().errno == "022", run.describe()


# --- configuration ----------------------------------------------------------

def test_wget_is_supported_as_an_alternative_fetcher(ejbca):
    """`CHECKTOOL` selects between two real binaries, both in the image."""
    ejbca.set_script_config("02", config(ejbca.health_server.name, checktool="wget"))

    run = ejbca.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("I", "021"), run.describe()
    assert ALLOK in msg.text, msg.text


def test_the_two_fetchers_disagree_about_how_an_outage_looks(ejbca):
    """Only the curl branch checks its exit status. With wget, a fetch that
    never connected falls through to the empty-body branch instead, so the same
    outage is classified differently depending on `CHECKTOOL`:

      curl  ->  022 "server not responding", carrying curl's own diagnosis
      wget  ->  024 "application server unavailable", carrying nothing

    Neither verdict is wrong — the server really is unreachable — but the wget
    path throws away the reason, which is the only thing an operator can act
    on. Pinned as a characterisation test rather than a defect: it documents
    that the two settings are not interchangeable."""
    ejbca.set_script_config("02", config("no-such-ejbca-host", checktool="curl"))
    with_curl = ejbca.run_script(SCRIPT).only()

    ejbca.set_script_config("02", config("no-such-ejbca-host", checktool="wget"))
    with_wget = ejbca.run_script(SCRIPT).only()

    assert with_curl.errno == "022" and "resolve" in with_curl.text.lower()
    assert with_wget.errno == "024"
    assert "resolve" not in with_wget.text.lower(), with_wget.text


def test_only_the_first_line_of_a_multi_failure_body_is_reported(ejbca):
    """A real EJBCA healthcheck returns one line per failing subsystem. The
    shared library truncates every message to a single line
    (`lib/printlogmess.sh:193`, `| head -1`), which the one-line-per-record log
    format requires — so the second failure is dropped.

    Filed here rather than as a defect because the truncation is the format
    working as intended, but the consequence belongs on the record: an operator
    paged for the database is not told the HSM is down too."""
    ejbca.health_server.set_routes({HEALTH_PATH: {
        "body": "ERROR: Error Connecting to EJBCA Database\n"
                "ERROR: CA Token is disconnected\n"}})

    run = ejbca.run_script(SCRIPT)

    msg = run.only()
    assert msg.errno == "022", run.describe()
    assert "Error Connecting to EJBCA Database" in msg.text
    assert "CA Token is disconnected" not in msg.text, (
        "truncation has changed — see lib/printlogmess.sh:193")


def test_an_unknown_checktool_is_reported_as_a_tool_failure(ejbca):
    ejbca.set_script_config("02", config(ejbca.health_server.name, checktool="nosuchtool"))

    run = ejbca.run_script(SCRIPT)

    assert "023" in run.errnos, run.describe()


def test_an_unknown_checktool_reports_only_the_tool_failure(ejbca):
    """The `else` branch prints ERRNO[3] but does not `exit`, so the script runs
    on and `cat`s a response file that was never written. The result is two
    messages for one fault, the second of them false: the app server was never
    contacted, so "application server unavailable" is a claim about something
    the script never looked at. It also leaks three `cat: ... No such file`
    lines to stderr.

    The first message is correct; only the trailing one is wrong."""
    ejbca.set_script_config("02", config(ejbca.health_server.name, checktool="nosuchtool"))

    run = ejbca.run_script(SCRIPT)

    assert run.errnos == ["023"], run.describe()
    assert not [line for line in run.unparsed if "cat:" in line], run.unparsed


def test_the_port_is_hard_coded_and_cannot_be_configured(ejbca, syscheck_network):
    """There is no `EJBCA_PORT`: the URL is built as `http://$HOST:8080/...`.
    An EJBCA behind any other port therefore cannot be checked at all, and the
    failure looks exactly like an outage. Pinned so the limitation is visible
    rather than discovered during an incident."""
    srv, name = start_http_server(syscheck_network,
                                  {HEALTH_PATH: {"body": ALLOK}}, port=8888)
    try:
        ejbca.set_script_config("02", config(name))
        run = ejbca.run_script(SCRIPT)
    finally:
        srv.stop()

    assert run.only().level == "E", run.describe()


def test_the_temporary_response_file_does_not_survive_the_run(ejbca):
    """`/tmp/ejbcahealth.log` is a fixed path in a world-writable directory; the
    script removes it on the way out, and a stale one must not be read as this
    run's answer."""
    ejbca.run_script(SCRIPT)

    assert not ejbca.file_exists("/tmp/ejbcahealth.log")


def test_a_stale_response_file_is_not_mistaken_for_a_fresh_answer(ejbca, syscheck_network):
    """The file is removed at the top of the run as well as at the end, so a
    leftover ALLOK from a previous, successful run cannot mask a current outage."""
    ejbca.write_file("/tmp/ejbcahealth.log", ALLOK + "\n")
    ejbca.set_script_config("02", config("no-such-ejbca-host"))

    run = ejbca.run_script(SCRIPT)

    assert run.levels and set(run.levels) == {"E"}, run.describe()


def test_help_documents_every_error_code(ejbca):
    res = ejbca.exec([ejbca.script_path(SCRIPT), "--help"])

    for errno in ("021", "022", "023", "024"):
        assert f"{errno} / " in res.output, res.output
