"""Basic tests for scripts-available/sc_31_hp_health.sh.

`sc_31` reads PSUs, temperatures and fans from HPE's `ilorest`. No HP hardware
is available to capture from, so the fixtures below are **UNVERIFIED SHAPE** —
reconstructed from what the script's own parsing requires, not from a real iLO.
They prove the script's branching and message routing, not that `ilorest` emits
this layout.

The suite is deliberately basic for that reason, and concentrates on the parts
that hold whatever `ilorest` prints:

* the lockfile protocol, which is pure REAL-OS behaviour and needs no fixture;
* `TEMPNO`, a variable the script uses six times and never assigns (D63);
* `HPTEMP`, the configured sensor filter, whose only use discards its own
  result (D64);
* `WARNSTATUS`, which is initialised and never incremented, making the WARNING
  summary unreachable (D65).

How the parsing works, since the fixtures have to satisfy it: each section is
flattened to one value per line (`cut -f2 -d":"`, then `awk '{print $1}'`) and
then regrouped positionally — temperatures in fours, fans in pairs, PSUs by
fixed offset. Every fixture here is therefore ordering-sensitive by design.
"""

from __future__ import annotations

import time

import pytest

SCRIPT = "sc_31_hp_health.sh"
TOOL = "/usr/local/bin/ilorest"
CALL_LOG = "/tmp/ilorest-calls.log"
FIXTURE_DIR = "/tmp/ilorest-fixtures"

pytestmark = pytest.mark.slow

# UNVERIFIED SHAPE. The script greps "State|Health", keeps file order, and reads
# the result as (status, condition) pairs for PSU1, PSU2 and the PSU group - so
# Health must precede State for each. Three PSUs is hard-coded.
POWER_OK = """
PowerSupplies:
  Health: OK
  State: Enabled
  Health: OK
  State: Enabled
  Health: OK
  State: Enabled
"""

# UNVERIFIED SHAPE. Grouped in fours: Location, Current, Critical, Health.
THERMALS_OK = """
Temperatures:
  Location: Ambient
  Current: 21
  Critical: 42
  Health: OK
  Location: CPU
  Current: 40
  Critical: 70
  Health: OK
"""

# UNVERIFIED SHAPE. Grouped in pairs: Reading, Health.
FANS_OK = """
Fans:
  Reading: 20
  Health: OK
  Reading: 22
  Health: OK
"""

FAKE_ILOREST = f"""#!/bin/bash
echo "$*" >> {CALL_LOG}
case "$2" in
  --power)    fixture=power ;;
  --thermals) fixture=thermals ;;
  --fans)     fixture=fans ;;
  *) echo "ilorest: unsupported: $*" >&2 ; exit 1 ;;
esac
cat "{FIXTURE_DIR}/$fixture" 2>/dev/null
"""


def config(*, hptemp: str = "#1 #2", wait: int = 3, tool: str = TOOL) -> str:
    return (
        "# generated by test_sc_31_hp_health.py\n"
        f"HP_HEALTH_TOOL={tool}\n"
        f'HPTEMP="{hptemp}"\n'
        f"LOCKFILE_MAX_WAIT_SEC={wait}\n"
    )


def set_fixtures(sc, *, power=POWER_OK, thermals=THERMALS_OK, fans=FANS_OK) -> None:
    for name, body in (("power", power), ("thermals", thermals), ("fans", fans)):
        sc.write_file(f"{FIXTURE_DIR}/{name}", body)


@pytest.fixture
def hp(syscheck):
    syscheck.exec(f"rm -f {CALL_LOG} {syscheck.home}/var/31.lock ; "
                  f"mkdir -p {FIXTURE_DIR}")
    syscheck.install_fake_bin("ilorest", FAKE_ILOREST)
    set_fixtures(syscheck)
    syscheck.set_script_config("31", config())
    return syscheck


def lockfile(sc) -> str:
    return f"{sc.home}/var/31.lock"


def summary(run):
    return run.messages[-1]


def errors(run):
    """Per-component errors. The summary reuses ERRNO[2], so it has to be
    excluded by index or every count is one too high."""
    return [m for m in run.messages if m.errno == "312" and m.index != "00"]


# --- the tool ---------------------------------------------------------------

def test_a_missing_tool_is_reported_and_stops_the_run(hp):
    hp.set_script_config("31", config(tool="/sbin/ilorest"))

    run = hp.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "314"), run.describe()


def test_all_three_sections_are_queried(hp):
    hp.run_script(SCRIPT)

    called = hp.read_file(CALL_LOG)
    for section in ("--power", "--thermals", "--fans"):
        assert f"serverinfo {section}" in called, called


# --- the happy path ---------------------------------------------------------

def test_a_healthy_server_reports_everything_ok(hp):
    """Three PSUs, two temperatures, two fans, then the summary."""
    run = hp.run_script(SCRIPT)

    assert [m.level for m in run.messages] == ["I"] * 8, run.describe()
    assert summary(run).index == "00", run.describe()


def test_a_failed_psu_is_an_error(hp):
    hp.set_script_config("31", config())
    set_fixtures(hp, power=POWER_OK.replace(
        "  Health: OK\n  State: Enabled\n", "  Health: Failed\n  State: Enabled\n", 1))

    run = hp.run_script(SCRIPT)

    bad = errors(run)
    assert bad, run.describe()
    assert "PSU1" in bad[0].text, bad[0].text


def test_a_temperature_over_its_limit_is_an_error(hp):
    set_fixtures(hp, thermals=THERMALS_OK.replace("  Current: 40", "  Current: 90"))

    run = hp.run_script(SCRIPT)

    bad = errors(run)
    assert len(bad) == 1, run.describe()
    assert "Current: 90" in bad[0].text, bad[0].text


def test_a_fan_that_is_not_ok_is_an_error(hp):
    set_fixtures(hp, fans=FANS_OK.replace(
        "  Reading: 22\n  Health: OK", "  Reading: 22\n  Health: Degraded"))

    run = hp.run_script(SCRIPT)

    bad = [m for m in run.messages if m.errno == "313"]
    assert len(bad) == 1, run.describe()


def test_a_failure_reaches_the_summary(hp):
    set_fixtures(hp, fans=FANS_OK.replace("  Health: OK", "  Health: Degraded", 1))

    run = hp.run_script(SCRIPT)

    assert summary(run).level == "E", run.describe()


# --- the lockfile, which needs no fixture -----------------------------------

def test_a_lockfile_is_taken_for_the_run_and_released(hp):
    """The script serialises itself against a concurrent run, and must not leave
    the lock behind — a stale lock costs the next run `LOCKFILE_MAX_WAIT_SEC`."""
    assert not hp.file_exists(lockfile(hp))

    hp.run_script(SCRIPT)

    assert not hp.file_exists(lockfile(hp)), "the lock was not released"


def test_a_stale_lockfile_is_reported_and_removed(hp):
    """A lock left by a killed run: the script reports that it found one,
    removes it and carries on rather than refusing to run forever."""
    hp.exec(f"touch {lockfile(hp)}")

    run = hp.run_script(SCRIPT)

    stale = [m for m in run.messages if m.errno == "315"]
    assert stale, run.describe()
    assert not hp.file_exists(lockfile(hp))


def test_the_wait_for_a_stale_lockfile_is_bounded_by_the_setting(hp):
    """`LOCKFILE_MAX_WAIT_SEC` caps how long a stale lock delays the run — the
    script sleeps in one-second steps until the lock reaches that age.

    The window is set wide (10s) on purpose. The lock's age is read with
    `stat --format=%Z`, i.e. **ctime**, and the clock starts when the test
    touches the file — so any delay between that `touch` and the script's `stat`
    eats into the remaining wait. With a narrow window and a loaded machine the
    lock can already be expired by the time the script looks, leaving nothing to
    wait for and making the assertion flake. 10s leaves room for several seconds
    of container overhead while still proving the wait happened.

    (A lock cannot be aged with `touch -d`, since that updates mtime and resets
    ctime to now. For a lock left by a killed process ctime is its creation
    time, which is the intended behaviour.)"""
    hp.set_script_config("31", config(wait=10))
    hp.exec(f"touch {lockfile(hp)}")

    began = time.monotonic()
    hp.run_script(SCRIPT)
    took = time.monotonic() - began

    assert 3 <= took < 30, f"wait was not bounded by the setting ({took:.1f}s)"


def test_a_run_killed_while_waiting_does_not_steal_another_runs_lock(hp):
    """The lock is acquired atomically with `set -o noclobber`, and the EXIT
    trap is armed at the top of the script — before anything can fail on the way
    to it — so a crash between acquiring and releasing still cleans up.

    Arming it that early means a run that is killed while *waiting* would also
    fire the trap, and must not remove a lock it never owned. Ownership is
    therefore a property of the lock itself: the acquire writes the holder's pid
    into it, and the trap only removes it if that pid is its own.

    Driven with a long wait and a short timeout, so the script is killed mid-wait
    on a lock belonging to pid 99999."""
    hp.set_script_config("31", config(wait=60))
    hp.exec(f"echo 99999 > {lockfile(hp)}")

    hp.exec(f"timeout -s TERM 3 {hp.script_path(SCRIPT)} --screen")

    assert hp.file_exists(lockfile(hp)), "the other run's lock was deleted"
    assert hp.read_file(lockfile(hp)).strip() == "99999", "the lock was overwritten"


# --- what does not depend on the fixture shape ------------------------------

@pytest.mark.xfail(strict=True, reason="D63 (WONT FIX): TEMPNO is used six times and never "
                                      "assigned, so every temperature message "
                                      "names a blank sensor")
def test_a_temperature_message_names_the_sensor_it_is_about(hp):
    """Every message in `hptemp` is built as `"TEMP ${TEMPNO} ${TEMPNAME} ..."`,
    but `TEMPNO` is never assigned anywhere in the script — `grep -n TEMPNO`
    returns only the six uses. So the sensor number is always empty and the
    messages read `TEMP  Ambient Current: 21 ...` with a doubled space where
    the identifier should be.

    It matters because `TEMPNO` is also what the `HPTEMP` filter matches on
    (D64), and because a temperature alert that cannot name its sensor sends an
    operator looking through every probe on the chassis."""
    run = hp.run_script(SCRIPT)

    temps = [m for m in run.messages if "TEMP" in m.text]
    assert temps, run.describe()
    assert "TEMP  " not in temps[0].text, temps[0].text


@pytest.mark.xfail(strict=True, reason="D64 (WONT FIX): HPTEMP's only use discards its own "
                                      "exit status, so the configured sensor "
                                      "filter selects nothing")
def test_the_configured_sensor_list_limits_which_sensors_are_checked(hp):
    """`HPTEMP` is documented as the list of sensors to watch, and the shipped
    config names 21 of them. Its only appearance in the script is

        echo ${HPTEMP}|egrep -q "${TEMPNO} "

    on a line of its own. The exit status is never tested — no `if`, no `&&` —
    so the result is discarded and every sensor `ilorest` reports is checked
    regardless of the setting. With `TEMPNO` empty (D63) the pattern is just a
    space, so it would match almost anything even if it were consulted.

    Driven here by configuring a list that excludes both sensors in the fixture
    and asserting nothing is reported for them."""
    hp.set_script_config("31", config(hptemp="#99"))

    run = hp.run_script(SCRIPT)

    temps = [m for m in run.messages if "TEMP" in m.text]
    assert temps == [], run.describe()


def test_a_stale_lockfile_alone_produces_a_warning_summary(hp):
    """An otherwise healthy run that had to clear a stale lock is "not an error,
    but not nothing", and the summary should say so.

    Before the D65 fix nothing ever assigned `WARNSTATUS`, so the `elif`
    guarding the WARNING summary could not be taken and `ERRNO[6]` was dead
    code. Two changes were needed, not one: `lockfilewait` now sets
    `WARNSTATUS=1`, **and** the `ERRSTATUS`/`WARNSTATUS` initialisation moved
    above the call — it used to run after, resetting the flag to 0 immediately
    after the lock warning had set it."""
    hp.exec(f"touch {lockfile(hp)}")

    run = hp.run_script(SCRIPT)

    assert [m for m in run.messages if m.errno == "315"], run.describe()
    assert summary(run).level == "W", run.describe()


def test_the_psu_section_assumes_exactly_three_power_supplies(hp):
    """`hppsu` flattens the whole section into one `;`-joined string and reads
    fixed offsets 1-6 from it, so it always reports on exactly three PSUs.

    A server with two returns nothing at offsets 5 and 6, and the third check —
    labelled "PSU Group" — fails on every run. Characterisation rather than a
    defect claim, because without a capture there is no evidence of how many
    entries `ilorest serverinfo --power` emits on a two-PSU chassis, or in what
    order. A capture would settle it."""
    two_psus = "\n".join(POWER_OK.strip().splitlines()[:5]) + "\n"
    set_fixtures(hp, power=two_psus)

    run = hp.run_script(SCRIPT)

    bad = errors(run)
    assert len(bad) == 1, run.describe()
    assert "PSU Group" in bad[0].text, bad[0].text


def test_a_fan_percentage_survives_into_the_message(hp):
    """`hpfans` reports `"... in normal operation ${FANPERCENT}%"`, and the
    literal `%` has to reach the log intact.

    Before the D66 fix `lib/printlogmess.sh` emitted the assembled line with
    `printf "${NEWFMTSTRING}\n"` — the *message* as the format string — so a `%`
    carried in from caller data was reinterpreted as a conversion specifier and
    `20% is OK` came out as `20 0s OK`, destroying the figure and the text after
    it. The emit sites now use `printf '%s\n' "$X"`, which is immune.

    This was a shared-library defect, not a `sc_31` one: every script putting a
    percentage in a message argument was affected."""
    run = hp.run_script(SCRIPT)

    fans = [m for m in run.messages if "FAN" in m.text]
    assert fans, run.describe()
    assert "20%" in fans[0].text, fans[0].text


def test_help_documents_every_error_code(hp):
    res = hp.exec([hp.script_path(SCRIPT), "--help"])

    for n in range(1, 7):
        assert f"31{n} / " in res.output, res.output
