"""End-to-end tests for related-available/938_mariabackup.sh.

`938` drives `mariabackup` to take a full or incremental physical backup of the
data directory.

FAKE-BIN: `mariabackup` is not installed in the test image (and a physical
backup needs the server's data directory, which lives in another container), so
a stub stands in. It records its argv and can be made to succeed or fail. These
tests prove which command `938` builds and how it reports, not that
`mariabackup` behaves as the stub does.

`938` was repaired on 2026-09-15 as item #32 of BUGFIXES_AND_IMPROVEMENTS: an
unterminated `${` meant the file did not parse at all, the dispatch sat above
the function definitions, and the `getopt` declaration was missing most of its
options. This suite covers the script as it now stands.
"""

from __future__ import annotations

import pytest

SCRIPT = "related-available/938_mariabackup.sh"
BASEDIR = "/tmp/938/backup"
INCDIR = "/tmp/938/inc"
CALL_LOG = "/tmp/938/calls.log"

pytestmark = pytest.mark.slow

FAKE = """#!/bin/bash
echo "$@" >> {log}
echo "{out}"
exit {rc}
"""


def install_mariabackup(sc, *, rc: int = 0, out: str = "completed OK!") -> None:
    sc.install_fake_bin("mariabackup", FAKE.format(log=CALL_LOG, out=out, rc=rc))


def config(*, basedir: str = BASEDIR) -> str:
    return ("# generated by test_938_mariabackup.py\n"
            "DATESTING_FULL='%Y-%m-%d'\n"
            "DATESTING_INC='%Y-%m-%d_%H.%M.%S'\n"
            "MARIABACKUP_BIN=/usr/local/bin/mariabackup\n"
            f"MARIABACKUP_BASEDIR={basedir}\n"
            "MARIABACKUP_USER=mariabackup\n"
            "MARIABACKUP_PASS=mariabackup\n"
            "MARIABACKUP_OPTIONS=\n"
            f"FULL_BACKUP_DIR={basedir}\n"
            f"BACKUP_TO_INC_DIR={INCDIR}\n")


@pytest.fixture
def mb(syscheck):
    syscheck.exec(f"rm -rf /tmp/938 && mkdir -p {BASEDIR} {INCDIR}").check()
    install_mariabackup(syscheck)
    syscheck.set_script_config("938", config())
    return syscheck


def own(run) -> list:
    return [m for m in run.messages if m.scriptid == "938"]


def calls(sc) -> list[str]:
    if not sc.file_exists(CALL_LOG):
        return []
    return [l for l in sc.read_file(CALL_LOG).splitlines() if l.strip()]


# --- the command it builds --------------------------------------------------

def test_a_full_backup_targets_the_configured_directory(mb):
    mb.run_script(SCRIPT, "--full")

    assert calls(mb), "mariabackup was never called"
    assert "--backup" in calls(mb)[0], calls(mb)
    assert f"--target-dir={BASEDIR}/" in calls(mb)[0], calls(mb)


def test_the_configured_credentials_are_passed(mb):
    mb.run_script(SCRIPT, "--full")

    assert "--user=mariabackup" in calls(mb)[0], calls(mb)


def test_an_incremental_backup_names_the_full_backup_as_its_basedir(mb):
    """An incremental is only restorable against the full it was based on, so
    `--incremental-basedir` is the part that matters."""
    mb.run_script(SCRIPT, "--incremental")

    assert calls(mb), "mariabackup was never called"
    assert f"--incremental-basedir={BASEDIR}" in calls(mb)[0], calls(mb)
    assert f"--target-dir={INCDIR}" in calls(mb)[0], calls(mb)


# --- reporting --------------------------------------------------------------

def test_a_successful_full_backup_is_reported(mb):
    run = mb.run_script(SCRIPT, "--full")

    assert any(m.errno == "9384" and m.level == "I" for m in own(run)), run.describe()


def test_a_failing_full_backup_is_reported_with_the_tool_output(mb):
    install_mariabackup(mb, rc=1, out="mariabackup: Can't connect to server")

    run = mb.run_script(SCRIPT, "--full")

    failed = [m for m in own(run) if m.errno == "9383"]
    assert failed, run.describe()
    assert "connect" in failed[0].text, failed[0].text


def test_a_successful_incremental_backup_is_reported(mb):
    run = mb.run_script(SCRIPT, "--incremental")

    assert any(m.errno == "9386" for m in own(run)), run.describe()


def test_a_failing_incremental_backup_is_reported(mb):
    install_mariabackup(mb, rc=1, out="boom")

    run = mb.run_script(SCRIPT, "--incremental")

    assert any(m.errno == "9385" for m in own(run)), run.describe()


def test_an_existing_backup_stops_a_full_run(mb):
    """A leftover `xtrabackup_logfile.qp` means a previous backup is still
    there; overwriting it would destroy the only copy."""
    mb.exec(f"touch {BASEDIR}/xtrabackup_logfile.qp").check()

    run = mb.run_script(SCRIPT, "--full")

    assert any(m.errno == "9382" for m in own(run)), run.describe()
    assert not calls(mb), "mariabackup ran despite an existing backup"


# --- dispatch ---------------------------------------------------------------

def test_no_mode_flag_does_nothing(mb):
    """Neither `--full` nor `--incremental` means neither branch runs.

    Characterisation: the script exits silently having taken no backup and said
    nothing. Arguably it should refuse loudly — a cron entry that lost its flag
    would look healthy forever — but `938` has no `ERRNO` for "no mode given"
    and adding one is a change rather than a fix."""
    run = mb.run_script(SCRIPT)

    assert calls(mb) == []
    assert own(run) == [], run.describe()


# --- known defects ----------------------------------------------------------

@pytest.mark.xfail(strict=True, reason="D100: the full-backup function is called with "
                                       "no argument, so its own name guard always "
                                       "fires")
def test_a_full_backup_does_not_report_a_missing_name(mb):
    """`mariabackup_full_backup` opens with

        FULL_BACKUP_NAME=$1
        if [[ -z "${FULL_BACKUP_NAME}" ]] ; then
            printlogmess ... -e "${ERRNO[1]}" -d "${DESCR[1]}"
        fi

    but the dispatch at the bottom calls it as a bare
    `mariabackup_full_backup` with no argument. So `$1` is always empty and
    `ERRNO[1]`, "no name for fullbackup sent", is logged on **every** run.

    The guard does not `exit` either, so the backup proceeds anyway and a
    healthy run emits one spurious error followed by a success. Monitoring sees
    a permanent error on `938-01` that never clears and never means anything —
    the classic way a real alert gets ignored.

    `FULL_BACKUP_NAME` is then never used again in the function, so the
    parameter appears to be vestigial."""
    run = mb.run_script(SCRIPT, "--full")

    assert not any(m.errno == "9381" for m in own(run)), run.describe()


def test_the_existing_backup_message_is_not_truncated(mb):
    """D101, fixed 2026-09-17. That call passed `-d ${DESCR[2]}` without quotes, where
    `DESCR[2]="Mariadb full backup dir already exist"`. Word splitting makes
    `-d` take only `Mariadb`, and the remaining four words become stray
    positional arguments.

    Every other `printlogmess` in `938` quotes its description; this is the only
    one that does not."""
    mb.exec(f"touch {BASEDIR}/xtrabackup_logfile.qp").check()

    run = mb.run_script(SCRIPT, "--full")

    existing = [m for m in own(run) if m.errno == "9382"]
    assert existing, run.describe()
    assert "already exist" in existing[0].text, existing[0].text


def test_help_documents_the_error_codes_that_exist(mb):
    res = mb.exec([mb.script_path(SCRIPT), "--help"])

    for errno in ("9381", "9382", "9383", "9384", "9385", "9386", "9387"):
        assert f"{errno} / " in res.output, res.output
