"""End-to-end tests for related-available/909_activate_CAs.sh.

`909` walks the configured CA list and runs `ejbca.sh ca activateca <name> <pin>`
for each one, reporting per-CA.

FAKE-BIN: a stub `ejbca.sh` under a temporary `EJBCA_HOME`.
`config/common.conf` sets `EJBCA_HOME=${EJBCA_HOME:-"/opt/ejbca"}`, so a pre-set
environment variable wins and becomes the seam.

Fidelity gap: no EJBCA installation was available. These tests prove which
commands `909` issues and how it reports, not that EJBCA behaves as the stub
does.
"""

from __future__ import annotations

import pytest

SCRIPT = "related-available/909_activate_CAs.sh"
EJBCA_HOME = "/tmp/909/ejbca"

pytestmark = pytest.mark.slow


def config(*cas) -> str:
    """`cas` are (name, pin) pairs."""
    lines = ["# generated by test_909_activate_cas.py\n"]
    for i, (name, pin) in enumerate(cas):
        lines.append(f'CANAME[{i}]="{name}"\n')
        lines.append(f'CAPIN[{i}]="{pin}"\n')
    return "".join(lines)


def install_ejbca(sc, *, stdout: str = "", exit_code: int = 0) -> None:
    sc.exec(f"mkdir -p {EJBCA_HOME}/bin").check()
    sc.write_file(f"{EJBCA_HOME}/bin/ejbca.sh",
                  "#!/bin/bash\n"
                  f'echo "$@" >> {EJBCA_HOME}/calls.log\n'
                  f"cat <<'EOF'\n{stdout}\nEOF\n"
                  f"exit {exit_code}\n",
                  mode=0o755)


@pytest.fixture
def cas(syscheck):
    syscheck.exec("rm -rf /tmp/909").check()
    install_ejbca(syscheck)
    syscheck.set_script_config("909", config(("eIDCA", "1111"), ("ServerCA", "2222")))
    return syscheck


def run(sc):
    return sc.run_script(SCRIPT, env={"EJBCA_HOME": EJBCA_HOME})


def calls(sc) -> list[str]:
    if not sc.file_exists(f"{EJBCA_HOME}/calls.log"):
        return []
    return [l for l in sc.read_file(f"{EJBCA_HOME}/calls.log").splitlines() if l.strip()]


def own(run) -> list:
    return [m for m in run.messages if m.scriptid == "909"]


# --- the commands it issues -------------------------------------------------

def test_every_configured_ca_is_activated(cas):
    run(cas)

    assert calls(cas) == ["ca activateca eIDCA 1111",
                          "ca activateca ServerCA 2222"], calls(cas)


def test_a_ca_with_no_pin_is_still_attempted(cas):
    """An empty `CAPIN` is a supported configuration — the script says so, and
    prompts for the pin interactively instead. The unquoted `$PIN` vanishes
    rather than becoming a blank argument."""
    cas.set_script_config("909", config(("eIDCA", "")))

    run(cas)

    assert calls(cas) == ["ca activateca eIDCA"], calls(cas)


def test_an_empty_ca_list_does_nothing(cas):
    cas.set_script_config("909", config())

    r = run(cas)

    assert calls(cas) == []
    assert own(r) == [], r.describe()


# --- reporting --------------------------------------------------------------

def test_each_ca_reports_under_its_own_index(cas):
    """`909` does call `addOneToIndex`, so each CA is its own monitoring service
    — unlike `916`, where a single key is reused for every file."""
    r = run(cas)

    assert [m.index for m in own(r)] == ["01", "02"], r.describe()


def test_a_successful_activation_is_reported_as_ok(cas):
    r = run(cas)

    assert [m.errno for m in own(r)] == ["9091", "9091"], r.describe()


# --- known defect -----------------------------------------------------------

def test_a_failing_activation_is_reported_as_an_error(cas):
    """`909` decides success by re-reading what the tool printed:

        ./bin/ejbca.sh ca activateca $NAME $PIN | tee ${SYSCHECK_HOME}/var/$0.output
        error=$(grep -v "Enter authorization code:" ${SYSCHECK_HOME}/var/$0.output)

    `$0` is the script's full path, so the tee target expands to
    `var//opt/syscheck/related-enabled/909_activate_CAs.sh.output` — a directory
    that does not exist. `tee` writes nothing, the `grep` reads a missing file
    and produces empty output, and empty output is the success condition.

    So `909` reports every CA as activated no matter what EJBCA said. A CA that
    failed to activate because its HSM token was unavailable — precisely what
    `HELP[2]` tells the operator to look for — is reported as healthy.

    Structurally incapable of failing, the same shape as D38 in `sc_40`."""
    install_ejbca(cas, stdout="ERROR: token is not available", exit_code=1)

    r = run(cas)

    assert any(m.errno == "9092" for m in own(r)), r.describe()


def test_help_documents_every_error_code(cas):
    res = cas.exec([cas.script_path(SCRIPT), "--help"])

    for errno in ("9091", "9092"):
        assert f"{errno} / " in res.output, res.output
