"""End-to-end tests for scripts-available/sc_35_dell_raid.sh.

`sc_35` asks Dell OMSA's `omreport` about physical and virtual disks on a RAID
controller. `omreport` is faked as a binary on `PATH` that records its argv and
replays fixtures, the same approach as `sc_36`.

Fixture provenance is good here. `sc_35` carries **real `-fmt ssv` captures in
its own comments**, including the 42-column pdisk header and a full data row,
and those are what the fixtures below are built from — so the column indices the
script `cut`s (`f20` capacity, `f24` vendor, `f26` serial, ...) are pinned
against genuine output rather than a guess.
`sc_36_dell_health_sample_output.txt` supplies matching values for the
human-readable side.

Three defects this suite established, none of which depends on the fixture
shape:

* **D67** (fixed 2026-09-15) — `continue` inside a function does not continue
  the caller's loop in bash; it errored and fell through, so a disk `omreport`
  does not report produced two error messages and a bash diagnostic. Now
  `return 1`.
* **D68** (fixed 2026-09-15) — that first message interpolated `$DISK_INFO`,
  which is assigned *later* in the function, so it carried the previous disk's
  details. `local DISK_INFO=""` now scopes it per call.
* **D69** (fixed 2026-09-15) — `ERRNO[5]` was never used; every non-Ok virtual
  disk was reported with `DESCR[4]`, "LogicalDiscs is rebuilding", whose help
  says to check back later. The state is now matched so a failed volume gets
  `ERRNO[5]`, "investigate ASAP".
"""

from __future__ import annotations

import pytest

SCRIPT = "sc_35_dell_raid.sh"
TOOL = "/usr/local/bin/omreport"
CALL_LOG = "/tmp/omreport35-calls.log"
FIXTURE_DIR = "/tmp/omreport35-fixtures"

pytestmark = pytest.mark.slow

# The 42-column pdisk row is the real `-fmt ssv` capture from the script's own
# comments, with the disk id varied.
PDISK_HEADER = (
    "ID;Status;Name;State;Power Status;Bus Protocol;Media;Part of Cache Pool;"
    "Remaining Rated Write Endurance;Failure Predicted;Revision;Driver Version;"
    "Model Number;T10 PI Capable;Certified;Encryption Capable;Encrypted;Progress;"
    "Mirror Set ID;Capacity;Used RAID Disk Space;Available RAID Disk Space;"
    "Hot Spare;Vendor ID;Product ID;Serial No.;Part Number;Negotiated Speed;"
    "Capable Speed;PCIe Negotiated Link Width;PCIe Maximum Link Width;Sector Size;"
    "Device Write Cache;Manufacture Day;Manufacture Week;Manufacture Year;"
    "SAS Address;Non-RAID HDD Disk Cache Policy;Disk Cache Policy;Form Factor ;"
    "Sub Vendor;ISE Capable"
)


def pdisk_row(disk_id: str, status: str = "Ok", state: str = "Online",
              serial: str = "Z1W5YDAE") -> str:
    return (
        f"{disk_id};{status};Physical Disk {disk_id};{state};Spun Up;SATA;HDD;"
        "Not Applicable;Not Applicable;No;GA6E;Not Applicable;Not Applicable;No;"
        "Yes;No;Not Applicable;Not Applicable;0;"
        "931.00 GB (999653638144 bytes);931.00 GB (999653638144 bytes);"
        f"0.00 GB (0 bytes);No;DELL(tm);ST1000NM0033-9ZM173;{serial};"
        "TH0W69TH2123369M00VJA0;6.00 Gbps;6.00 Gbps;Not Applicable;Not Applicable;"
        "512B;Not Applicable;Not Available;Not Available;Not Available;"
        "4433221106000000;Not Applicable;Not Applicable;Not Available;"
        "Not Available;No"
    )


def vdisk_row(vdisk_id: str, status: str = "Ok", state: str = "Ready") -> str:
    return (
        f"{vdisk_id};{status};vd1;{state};Not Assigned;No;RAID-10;"
        "1,862.00 GB (1999307276288 bytes);No;Not Applicable;/dev/sda;SATA;HDD;"
        "Read Ahead;Write Back;Not Applicable;64 KB;Unchanged"
    )


PDISKS_OK = PDISK_HEADER + "\n" + pdisk_row("0:1:0") + "\n" + pdisk_row(
    "0:1:1", serial="Z1W5YDAF") + "\n"
VDISKS_OK = vdisk_row("0") + "\n"

FAKE_OMREPORT = f"""#!/bin/bash
echo "$*" >> {CALL_LOG}
case "$1 $2" in
  "storage pdisk") fixture=pdisk ;;
  "storage vdisk") fixture=vdisk ;;
  *) echo "omreport: unsupported: $*" >&2 ; exit 1 ;;
esac
cat "{FIXTURE_DIR}/$fixture" 2>/dev/null
"""


def config(*, pds=("0:1:0", "0:1:1"), lds=("0",), controller: int = 0,
           delltool: str = TOOL) -> str:
    lines = ["# generated by test_sc_35_dell_raid.py\n",
             f"DELLTOOL={delltool}\n",
             f"CONTROLLER={controller}\n"]
    for i, pd in enumerate(pds):
        lines.append(f'PHYSICALDRIVE[{i}]="{pd}"\n')
    for i, ld in enumerate(lds):
        lines.append(f'LOGICALDRIVE[{i}]="{ld}"\n')
    return "".join(lines)


def set_fixtures(sc, *, pdisk=PDISKS_OK, vdisk=VDISKS_OK) -> None:
    sc.write_file(f"{FIXTURE_DIR}/pdisk", pdisk)
    sc.write_file(f"{FIXTURE_DIR}/vdisk", vdisk)


@pytest.fixture
def raid(syscheck):
    syscheck.exec(f"rm -f {CALL_LOG} ; mkdir -p {FIXTURE_DIR}")
    syscheck.install_fake_bin("omreport", FAKE_OMREPORT)
    set_fixtures(syscheck)
    syscheck.set_script_config("35", config())
    return syscheck


def calls(sc) -> list[str]:
    if not sc.file_exists(CALL_LOG):
        return []
    return [l for l in sc.read_file(CALL_LOG).splitlines() if l.strip()]


# --- the tool ---------------------------------------------------------------

def test_a_missing_tool_is_reported_and_stops_the_run(raid):
    raid.set_script_config("35", config(delltool="/opt/dell/srvadmin/bin/omreport"))

    run = raid.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "356"), run.describe()


def test_the_controller_from_the_config_is_used(raid):
    raid.set_script_config("35", config(controller=2))

    raid.run_script(SCRIPT)

    assert any("controller=2" in c for c in calls(raid)), calls(raid)


# --- healthy disks ----------------------------------------------------------

def test_a_healthy_array_reports_every_disk_ok(raid):
    """Two physical disks then one virtual disk."""
    run = raid.run_script(SCRIPT)

    assert [m.errno for m in run.messages] == ["351", "351", "353"], run.describe()


def test_each_disk_gets_its_own_message_index(raid):
    run = raid.run_script(SCRIPT)

    assert [m.index for m in run.messages] == ["01", "02", "03"], run.describe()


def test_the_physical_disk_details_come_from_the_right_columns(raid):
    """`cut -f20`, `-f24`, `-f25`, `-f26` pull capacity, vendor, product and
    serial out of a 42-column row. Pinned against the real captured row, since
    an off-by-one here mislabels every disk in the message."""
    run = raid.run_script(SCRIPT, "-v")

    out = run.stdout + run.stderr
    assert "capacity: 931.00 GB (999653638144 bytes)" in out, out[:400]
    assert "vendor: DELL(tm)" in out, out[:400]
    assert "prodid: ST1000NM0033-9ZM173" in out, out[:400]
    assert "serial: Z1W5YDAE" in out, out[:400]


def test_the_virtual_disk_details_come_from_the_right_columns(raid):
    run = raid.run_script(SCRIPT, "-v")

    out = run.stdout + run.stderr
    assert "layout: RAID-10" in out, out[:400]
    assert "device: /dev/sda" in out, out[:400]


# --- failures ---------------------------------------------------------------

@pytest.mark.parametrize("status", ["Critical", "Non-Critical", "Degraded"])
def test_a_physical_disk_that_is_not_ok_is_an_error(raid, status):
    set_fixtures(raid, pdisk=PDISK_HEADER + "\n"
                 + pdisk_row("0:1:0", status=status) + "\n"
                 + pdisk_row("0:1:1", serial="Z1W5YDAF") + "\n")

    run = raid.run_script(SCRIPT)

    bad = [m for m in run.messages if m.errno == "352"]
    assert len(bad) == 1, run.describe()
    assert "0:1:0" in bad[0].text, bad[0].text


def test_a_failed_physical_disk_message_carries_its_details(raid):
    set_fixtures(raid, pdisk=PDISK_HEADER + "\n"
                 + pdisk_row("0:1:0", status="Critical", state="Failed") + "\n"
                 + pdisk_row("0:1:1", serial="Z1W5YDAF") + "\n")

    run = raid.run_script(SCRIPT)

    bad = [m for m in run.messages if m.errno == "352"][0]
    assert "state: Failed" in bad.text, bad.text
    assert "serial: Z1W5YDAE" in bad.text, bad.text


def test_the_single_digit_fallback_finds_a_directly_attached_disk(raid):
    """Some Dell models report a shorter disk id than the config names. The
    script retries with everything after the first colon — `0:1:0` becomes
    `1:0` — rather than reporting the disk missing."""
    set_fixtures(raid, pdisk=PDISK_HEADER + "\n" + pdisk_row("1:0") + "\n")
    raid.set_script_config("35", config(pds=("0:1:0",)))

    run = raid.run_script(SCRIPT)

    assert [m.errno for m in run.messages] == ["351", "353"], run.describe()


# --- the three defects ------------------------------------------------------

def test_a_disk_the_tool_does_not_report_is_reported_once(raid):
    """When neither the configured id nor the single-digit fallback matches,
    `raiddiskcheck` reports ERRNO[2] and stops.

    It used to end that branch with `continue`, but `continue` inside a
    *function* is not loop control for the caller's loop — bash rejects it with

        continue: only meaningful in a `for', `while', or `until' loop

    on stderr and carries straight on. Execution fell into the `cut` block with
    an empty `$DISCSTAT`, so `STATUS` was empty, which is not `Ok`, and ERRNO[2]
    was emitted a **second** time for the same disk. One absent disk produced two
    error messages at the same index plus a bash diagnostic. `return` is what was
    meant."""
    raid.set_script_config("35", config(pds=("9:9:9",), lds=()))

    run = raid.run_script(SCRIPT)

    assert len([m for m in run.messages if m.errno == "352"]) == 1, run.describe()
    assert not [l for l in run.unparsed if "only meaningful in" in l], run.unparsed


def test_a_missing_disk_is_not_described_with_another_disks_details(raid):
    """`$DISK_INFO` is assigned further down `raiddiskcheck`, well after the
    not-found branch that interpolates it. It used to be a plain global with no
    `local`, so on the first disk it was empty and on every later disk it still
    held the *previous* disk's name, state, capacity and serial — a message
    about a missing disk carrying a healthy disk's serial number.

    Same class as D51 in `sc_08`: per-item state kept in globals that are never
    reset."""
    set_fixtures(raid, pdisk=PDISK_HEADER + "\n" + pdisk_row("0:1:0") + "\n")
    raid.set_script_config("35", config(pds=("0:1:0", "9:9:9"), lds=()))

    run = raid.run_script(SCRIPT)

    missing = [m for m in run.messages if "9:9:9" in m.text]
    assert missing, run.describe()
    assert "Z1W5YDAE" not in missing[0].text, missing[0].text


def test_a_failed_virtual_disk_is_not_reported_as_rebuilding(raid):
    """`lang/35.english` defines three outcomes for a virtual disk:

        DESCR[3] LogicalDiscs is OK
        DESCR[4] LogicalDiscs is rebuilding        -> "check back in a while"
        DESCR[5] LogicalDiscs has some other error -> "investigate ASAP"

    Before the D69 fix `raidlogiccheck` only ever used `ERRNO[3]` and
    `ERRNO[4]`, so every non-Ok volume — Failed, Degraded, Offline — was
    reported as **rebuilding** and the help text told the operator to wait for
    it to clear. `ERRNO[5]` was dead code.

    The exact mirror of D62 in `sc_06`, where the rebuilding branch is the
    unreachable one, and the more dangerous direction of the two: a genuinely
    failed RAID volume described as a transient state that resolves itself."""
    set_fixtures(raid, vdisk=vdisk_row("0", status="Critical", state="Failed"))

    run = raid.run_script(SCRIPT)

    vdisk = [m for m in run.messages if "vdisk" in m.text.lower()]
    assert vdisk, run.describe()
    assert vdisk[0].errno == "355", run.describe()


def test_a_rebuilding_virtual_disk_still_gets_the_rebuilding_code(raid):
    """The other side of D69: `ERRNO[4]` must stay reachable, or the fix would
    just have moved the problem.

    UNVERIFIED SHAPE — neither the script's embedded `-fmt ssv` sample nor
    `sc_36_dell_health_sample_output.txt` shows a rebuilding volume; both say
    `Ready`. The `rebuild|resync|initializ` pattern is inferred from OMSA's
    documented vdisk states, so this test proves the branch is reachable and the
    pattern works as written, not that a PERC reports exactly this word.

    The guess is safe in the direction that matters: any state the pattern does
    *not* recognise falls through to `ERRNO[5]`, "investigate ASAP", rather than
    to "wait and see"."""
    set_fixtures(raid, vdisk=vdisk_row("0", status="Non-Critical",
                                       state="Resynching"))

    run = raid.run_script(SCRIPT)

    assert "354" in run.errnos and "355" not in run.errnos, run.describe()


# --- configuration ----------------------------------------------------------

def test_no_configured_disks_reports_nothing(raid):
    """Unlike `sc_06`, `sc_35` has no summary message, so an empty config is
    completely silent — the run produces no output at all."""
    raid.set_script_config("35", config(pds=(), lds=()))

    run = raid.run_script(SCRIPT)

    assert run.messages == [], run.describe()


def test_help_documents_every_error_code(raid):
    res = raid.exec([raid.script_path(SCRIPT), "--help"])

    for n in range(1, 7):
        assert f"35{n} / " in res.output, res.output
