"""End-to-end tests for scripts-available/sc_37_monitor_jnlp.sh.

`sc_37` fetches one URL and looks for the marker `JNLP File generated`, which
the application emits inside an HTML comment. Everything else is a failure.

The interesting part is not the marker but the `Host:` header. The shipped
config addresses the application **by IP** and relies on the header to select
the right virtual host:

    URL="http://10.0.0.1/certservice-public/webResource/tolima/tolima.jnlp"
    HEADER=(--header "Host: public.domain.com")

so if the header does not arrive intact the request lands on the wrong vhost.
The harness mock substitutes `{HOST}` in a response body with the `Host:` header
it actually received, which is the only way to assert this from the outside —
a test that only checked the exit status would pass while the header was
mangled, which is exactly what D48 was.

`HEADER` is a bash array as of the D48 fix. It used to be a string holding
escaped quotes, which no amount of quoting at the use site could have rescued.
"""

from __future__ import annotations

import pytest

from syscheck_harness import start_http_server

SCRIPT = "sc_37_monitor_jnlp.sh"
JNLP_PATH = "/certservice-public/webResource/tolima/tolima.jnlp"
VHOST = "public.domain.com"

# The marker the script greps for, as the application emits it: inside an HTML
# comment, which the script strips with two `sed` calls.
OK_BODY = (
    '<?xml version="1.0" encoding="utf-8"?>\n'
    "<!-- JNLP File generated 2026-09-13 -->\n"
    '<jnlp spec="1.0+" codebase="http://example/">\n'
    "  <information><title>Tolima</title></information>\n"
    "</jnlp>\n"
)

pytestmark = pytest.mark.slow


@pytest.fixture(scope="module")
def jnlp_server(syscheck_network):
    srv, _ = start_http_server(syscheck_network, {JNLP_PATH: {"body": OK_BODY}})
    try:
        yield srv
    finally:
        srv.stop()


def config(host: str, *, path: str = JNLP_PATH, header: str | None = None,
           timeout: int = 5, checktool: str = "curl") -> str:
    """Mirrors the shipped config. `HEADER` is a bash array (the D48 fix); pass
    `header=""` for the no-extra-header case, which must expand to nothing
    rather than to a blank argument."""
    if header is None:
        header = f'--header "Host: {VHOST}"'
    return (
        "# generated by test_sc_37_monitor_jnlp.py\n"
        f'URL="http://{host}:8080{path}"\n'
        f"HEADER=({header})\n"
        f"CURL_TIMEOUT={timeout}\n"
        f"CHECKTOOL={checktool}\n"
    )


@pytest.fixture
def jnlp(syscheck, jnlp_server):
    jnlp_server.set_routes({JNLP_PATH: {"body": OK_BODY}})
    syscheck.jnlp_server = jnlp_server
    syscheck.set_script_config("37", config(jnlp_server.name))
    return syscheck


# --- the marker -------------------------------------------------------------

def test_a_generated_jnlp_is_reported_as_ok(jnlp):
    run = jnlp.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("I", "371"), run.describe()


def test_the_comment_markers_are_stripped_from_the_reported_line(jnlp):
    """Two `sed` calls remove `<!--` and `-->` so the log carries the marker
    text rather than XML punctuation."""
    msg = jnlp.run_script(SCRIPT).only()

    assert "JNLP File generated" in msg.text, msg.text
    assert "<!--" not in msg.text and "-->" not in msg.text, msg.text


def test_a_response_without_the_marker_is_an_error(jnlp):
    """A well-formed XML document that is not a generated JNLP — the shape a
    misconfigured vhost returns."""
    jnlp.jnlp_server.set_routes(
        {JNLP_PATH: {"body": '<?xml version="1.0"?><html>login</html>'}})

    run = jnlp.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "372"), run.describe()


def test_a_truncated_jnlp_is_an_error(jnlp):
    """The body arrives but is cut off before the marker."""
    jnlp.jnlp_server.set_routes(
        {JNLP_PATH: {"body": '<?xml version="1.0" encoding="utf-8"?>\n<jn'}})

    run = jnlp.run_script(SCRIPT)

    assert run.only().errno == "372", run.describe()


def test_a_404_is_an_error(jnlp):
    jnlp.set_script_config("37", config(jnlp.jnlp_server.name, path="/gone.jnlp"))

    run = jnlp.run_script(SCRIPT)

    assert run.only().errno == "372", run.describe()


def test_an_empty_response_is_an_error(jnlp):
    jnlp.jnlp_server.set_routes({JNLP_PATH: {"body": ""}})

    run = jnlp.run_script(SCRIPT)

    assert run.only().errno == "372", run.describe()


def test_the_failure_message_carries_what_was_received(jnlp):
    """`DESCR[2]` is `"problem: %s"` filled with the whole body, newlines
    stripped — the only evidence an operator gets about what came back."""
    jnlp.jnlp_server.set_routes(
        {JNLP_PATH: {"status": 503, "body": "Service Temporarily Unavailable"}})

    msg = jnlp.run_script(SCRIPT).only()

    assert "Service Temporarily Unavailable" in msg.text, msg.text


def test_the_verdict_follows_the_body_not_the_http_status(jnlp):
    """Nothing inspects the status code, so a marker served with a 500 still
    reads as OK. Pinned so the behaviour is deliberate rather than assumed."""
    jnlp.jnlp_server.set_routes({JNLP_PATH: {"status": 500, "body": OK_BODY}})

    run = jnlp.run_script(SCRIPT)

    assert run.only().errno == "371", run.describe()


# --- reachability -----------------------------------------------------------

def test_a_refused_connection_is_an_error(jnlp, syscheck_network):
    srv, name = start_http_server(syscheck_network, {JNLP_PATH: {"body": OK_BODY}})
    try:
        jnlp.set_script_config("37", config(name))
        assert jnlp.run_script(SCRIPT).only().errno == "371"
    finally:
        srv.stop()

    run = jnlp.run_script(SCRIPT)

    assert run.only().errno == "372", run.describe()


def test_an_unresolvable_host_is_an_error(jnlp):
    jnlp.set_script_config("37", config("no-such-jnlp-host"))

    run = jnlp.run_script(SCRIPT)

    assert run.only().errno == "372", run.describe()


def test_a_server_that_answers_too_slowly_is_an_error(jnlp):
    jnlp.set_script_config("37", config(jnlp.jnlp_server.name, timeout=2))
    jnlp.jnlp_server.set_routes({JNLP_PATH: {"body": OK_BODY, "delay": 10}})

    run = jnlp.run_script(SCRIPT)

    assert run.only().errno == "372", run.describe()


# --- the Host header --------------------------------------------------------

def test_the_configured_host_header_reaches_the_server(jnlp):
    """The whole purpose of the setting: the shipped URL addresses the
    application by IP, so the `Host:` header is what selects the virtual host.

    Before the D48 fix `HEADER` was a string holding escaped quotes, expanded
    **unquoted** into curl's argv. Word splitting yielded `--header`, `"Host:`,
    `public.domain.com"`, and the literal quotes were not removed — expansion
    results are not re-parsed for quoting — so curl got a malformed header name
    and a trailing word it read as a second URL. Every request landed on the
    server's default vhost, which may well answer, so the check passed while
    watching the wrong application.

    As an array the value survives intact. Asserted from the server side: the
    mock replaces `{HOST}` with the Host header it actually received, so this
    cannot pass on a request that never carried one."""
    jnlp.jnlp_server.set_routes(
        {JNLP_PATH: {"body": "<!-- JNLP File generated for {HOST} -->"}})

    msg = jnlp.run_script(SCRIPT).only()

    assert VHOST in msg.text, f"server saw Host: {msg.text!r}"


def test_the_check_still_reports_a_verdict_with_no_header_configured(jnlp):
    """`HEADER=()` must expand to nothing at all rather than to a blank
    argument — the trap `sc_08` falls into as D52, where a quoted empty scalar
    makes curl abort before it sends anything. An array cannot do that, and
    this pins it."""
    jnlp.set_script_config("37", config(jnlp.jnlp_server.name, header=""))

    run = jnlp.run_script(SCRIPT)

    assert run.only().errno == "371", run.describe()


# --- configuration ----------------------------------------------------------

def test_an_unknown_checktool_is_reported(jnlp):
    jnlp.set_script_config("37", config(jnlp.jnlp_server.name, checktool="wget"))

    run = jnlp.run_script(SCRIPT)

    assert "373" in run.errnos, run.describe()


def test_an_unknown_checktool_reports_only_the_tool_failure(jnlp):
    """`sc_37`'s `else` branch reports ERRNO[3] without `exit`, so the script
    goes on to `cat` a file nothing wrote and adds a second, misleading
    "problem" message. Identical in shape to D42 in sc_02 and D47 in sc_33 —
    the same missing `exit` in three separate scripts."""
    jnlp.set_script_config("37", config(jnlp.jnlp_server.name, checktool="wget"))

    run = jnlp.run_script(SCRIPT)

    assert run.errnos == ["373"], run.describe()


def test_the_temporary_response_file_does_not_survive_the_run(jnlp):
    """`/tmp/internal-error.txt` is a fixed path in a world-writable directory
    and is removed on the way out, by the EXIT trap added with the D49 fix."""
    jnlp.run_script(SCRIPT)

    assert not jnlp.file_exists("/tmp/internal-error.txt")


@pytest.mark.parametrize("scenario, conf", [
    ("unreachable host", dict(host="no-such-jnlp-host")),
    ("unknown checktool", dict(checktool="wget")),
])
def test_the_response_file_is_removed_on_the_failure_paths_too(jnlp, scenario, conf):
    """The old trailing `rm` only ran if control reached the last line. The trap
    fires on every exit, so a run that fails to fetch — or bails out on a bad
    `CHECKTOOL` — leaves nothing behind for the next run to grade."""
    host = conf.pop("host", jnlp.jnlp_server.name)
    jnlp.set_script_config("37", config(host, **conf))

    jnlp.run_script(SCRIPT)

    assert not jnlp.file_exists("/tmp/internal-error.txt"), scenario


def test_the_cleanup_is_registered_as_an_exit_trap(jnlp):
    """The trailing `rm` only ran if control reached the last line; the trap
    fires on every exit, including a signal — verified separately that bash
    runs an EXIT trap when killed by TERM.

    Asserted against the source rather than end to end, because the signal case
    cannot honestly be forced here: `curl --output` does not create the file
    until the first byte of the response arrives, so a run killed while curl is
    still waiting has no file to clean up and the test would pass whether or not
    the trap existed. This is defence for exit paths that do not exist yet — the
    `CHECKTOOL` guard will gain one when the D42-class defect below is fixed."""
    source = jnlp.read_file(jnlp.script_path(SCRIPT))

    assert "trap 'rm -f \"$OUTPUT\"' EXIT" in source, source


def test_help_documents_every_error_code(jnlp):
    res = jnlp.exec([jnlp.script_path(SCRIPT), "--help"])

    for errno in ("371", "372", "373"):
        assert f"{errno} / " in res.output, res.output
