"""End-to-end tests for scripts-available/sc_18_sqlselect.sh against MariaDB.

The check is a keepalive: run one `SELECT` against a table that should exist and
report whether the server answered. So there is nothing to mock — a real
`mariadb:11` on the test network answers the real client, and every failure path
is produced by breaking something real: dropping the table, using the wrong
password, pointing at a host that is not there, stopping the server.

The one piece of setup worth explaining is `~/.my.cnf`. sc_18 runs

    $MYSQL_BIN $DB_NAME -u root --password=$MYSQLROOT_PASSWORD

with no `-h`, so it can only ever talk to the local server. A host that keeps its
database elsewhere configures the client, not the check — which is what the
`[client] host=` line does here.
"""

from __future__ import annotations

import pytest

from conftest import MARIADB_DATABASE, MARIADB_ROOT_PASSWORD
from syscheck_harness import start_mariadb_node

SCRIPT = "sc_18_sqlselect.sh"
TABLE = "CertificateData"

pytestmark = pytest.mark.slow


def mariadb_config(database: str = MARIADB_DATABASE, table: str = TABLE,
                   password: str = MARIADB_ROOT_PASSWORD,
                   mysql_bin: str = "/usr/bin/mariadb") -> str:
    """config/mariadb.conf — sc_18 sources it explicitly, after its own."""
    return (
        "# generated by test_sc_18_sqlselect.py\n"
        f"DB_NAME={database}\n"
        f"DB_TEST_TABLE={table}\n"
        f"MYSQL_BIN={mysql_bin}\n"
        f'MYSQLROOT_PASSWORD="{password}"\n'
    )


@pytest.fixture
def sqlselect(syscheck, mariadb_node):
    """sc_18 pointed at the shared MariaDB, with the test table present."""

    def client_config(host: str) -> None:
        syscheck.write_file("/root/.my.cnf", f"[client]\nhost={host}\n")

    def sql(statement: str, host: str = mariadb_node) -> None:
        syscheck.exec([
            "mariadb", "-h", host, "-uroot", f"-p{MARIADB_ROOT_PASSWORD}",
            MARIADB_DATABASE, "-e", statement,
        ]).check()

    client_config(mariadb_node)
    sql(f"CREATE TABLE IF NOT EXISTS {TABLE} (fingerprint VARCHAR(64) PRIMARY KEY)")
    syscheck.set_script_config("mariadb", mariadb_config())
    syscheck.client_config = client_config
    syscheck.sql = sql
    syscheck.mariadb_node = mariadb_node
    return syscheck


def test_a_server_that_answers_the_select_is_reported_ok(sqlselect):
    run = sqlselect.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno, msg.index) == ("I", "181", "01"), run.describe()
    assert run.exit_code == 0


def test_an_empty_table_still_counts_as_answering(sqlselect):
    """`SELECT ... LIMIT 1` on an empty table returns no rows and succeeds. This
    is a keepalive, not a data check: an empty CertificateData means a new CA,
    not a broken database."""
    sqlselect.sql(f"DELETE FROM {TABLE}")

    run = sqlselect.run_script(SCRIPT)

    assert run.only().errno == "181", run.describe()


def test_a_populated_table_is_reported_ok(sqlselect):
    sqlselect.sql(f"INSERT IGNORE INTO {TABLE} (fingerprint) VALUES ('abc123')")

    run = sqlselect.run_script(SCRIPT)

    assert run.only().errno == "181", run.describe()


def test_a_missing_table_is_an_error(sqlselect):
    """The server is up and the credentials are right, but the schema is not
    what this check was configured for — a half-finished migration, or a restore
    that did not include the table."""
    sqlselect.set_script_config("mariadb", mariadb_config(table="NoSuchTable"))

    run = sqlselect.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "182"), run.describe()
    assert run.exit_code == 3, run.describe()


def test_a_missing_database_is_an_error(sqlselect):
    sqlselect.set_script_config("mariadb", mariadb_config(database="no_such_db"))

    run = sqlselect.run_script(SCRIPT)

    assert run.only().errno == "182", run.describe()


def test_a_wrong_password_is_an_error(sqlselect):
    """Credentials rotated on the server and not in the config — the check must
    go red rather than keep reporting a database it can no longer reach."""
    sqlselect.set_script_config("mariadb", mariadb_config(password="not-the-password"))

    run = sqlselect.run_script(SCRIPT)

    assert run.only().errno == "182", run.describe()


def test_an_unreachable_server_is_an_error(sqlselect):
    sqlselect.client_config("no-such-database-host")

    run = sqlselect.run_script(SCRIPT)

    assert run.only().errno == "182", run.describe()


def test_a_missing_client_binary_is_an_error(sqlselect):
    """`MYSQL_BIN` is an absolute path in `config/mariadb.conf`, and the two
    plausible values differ by distribution (`mysql` vs `mariadb`)."""
    sqlselect.set_script_config("mariadb", mariadb_config(mysql_bin="/usr/bin/no-such-client"))

    run = sqlselect.run_script(SCRIPT)

    assert run.only().errno == "182", run.describe()


def test_a_stopped_server_is_an_error(sqlselect, syscheck_network):
    """The failure this check exists for, produced for real: its own server,
    proven working, then stopped."""
    tc, name = start_mariadb_node(syscheck_network,
                                  root_password=MARIADB_ROOT_PASSWORD,
                                  database=MARIADB_DATABASE)
    try:
        sqlselect.client_config(name)
        sqlselect.sql(f"CREATE TABLE {TABLE} (fingerprint VARCHAR(64) PRIMARY KEY)",
                      host=name)
        assert sqlselect.run_script(SCRIPT).only().errno == "181"
    finally:
        tc.stop()

    run = sqlselect.run_script(SCRIPT)

    assert run.only().errno == "182", run.describe()


def test_exactly_one_message_is_emitted_per_run(sqlselect):
    run = sqlselect.run_script(SCRIPT)

    assert len(run.messages) == 1, run.describe()


def test_help_documents_every_error_code(sqlselect):
    res = sqlselect.exec([sqlselect.script_path(SCRIPT), "--help"])

    for errno in ("181", "182"):
        assert f"{errno} / " in res.output, res.output
