"""End-to-end tests for related-available/907_make_mysql_db_backup_and_transfer_to_remote_mashine.sh.

`907` is a two-step composition: take a database backup with `904`, then ship it
to each configured host with `906`. It adds no logic of its own beyond the loop
and the reporting.

REAL-SVC throughout — a real `mariadb:11` for the dump and the shared key-only
`sshd_node` for the transfer. Both halves are covered in their own suites, so
what this one proves is the join: that the filename `904` prints on stdout is
the file `906` is asked to send, and that a failure in either half is reported
rather than swallowed.

Like `930`, `907` reaches `906` through `related-enabled/`, so the fixture makes
the symlink an install would.
"""

from __future__ import annotations

import pytest

from conftest import (MARIADB_DATABASE, MARIADB_ROOT_PASSWORD,
                      SSH_KEY, SSH_REMOTE_USER)

SCRIPT = ("related-available/"
          "907_make_mysql_db_backup_and_transfer_to_remote_mashine.sh")
HELPER_SRC = "related-available/906_ssh-copy-to-remote-machine.sh"
HELPER_LINK = "related-enabled/906_ssh-copy-to-remote-machine.sh"
BACKUPDIR = "/tmp/907/backup"
REMOTE_DIR = f"/home/{SSH_REMOTE_USER}/dbbackup"

pytestmark = pytest.mark.slow

SSH_OPTS = ('"-o ConnectTimeout=10 -o StrictHostKeyChecking=no '
            '-o UserKnownHostsFile=/dev/null -o LogLevel=ERROR"')


def mariadb_config() -> str:
    return (f"DB_NAME={MARIADB_DATABASE}\n"
            f'MYSQLROOT_PASSWORD="{MARIADB_ROOT_PASSWORD}"\n'
            "MYSQL_BIN=/usr/bin/mariadb\n"
            "MYSQLDUMP_BIN=/usr/bin/mariadb-dump\n"
            "MYSQLDUMP_OPTIONS=(--single-transaction --quick)\n")


def backup_config(*, backupdir: str = BACKUPDIR) -> str:
    return ("DATESTING='%Y-%m-%d_%H.%M.%S'\n"
            f"MYSQLBACKUPDIR={backupdir}\n"
            "SUBDIR_DEFAULT=default\nSUBDIR_DAILY=daily\n"
            "SUBDIR_WEEKLY=weekly\nSUBDIR_MONTHLY=monthly\nSUBDIR_YEARLY=yearly\n"
            f'DBNAME[0]="{MARIADB_DATABASE}"\nTABLENAMES[0]=""\n')


def config(sc, *, hosts=None) -> str:
    hosts = hosts or [sc.sshd]
    lines = ["# generated by test_907_backup_and_transfer.py\n",
             "SUBDIR_DEFAULT=default\nSUBDIR_DAILY=daily\n",
             "SUBDIR_WEEKLY=weekly\nSUBDIR_MONTHLY=monthly\nSUBDIR_YEARLY=yearly\n"]
    for i, host in enumerate(hosts):
        lines.append(f"BACKUP_HOST[{i}]={host}\n")
        lines.append(f"BACKUP_DIR[{i}]={REMOTE_DIR}\n")
        lines.append(f"BACKUP_USER[{i}]={SSH_REMOTE_USER}\n")
        lines.append(f"BACKUP_SSHFROMKEY[{i}]={SSH_KEY}\n")
    return "".join(lines)


@pytest.fixture
def transfer(syscheck, mariadb_node, sshd_node):
    syscheck.sshd = sshd_node
    syscheck.write_file("/root/.my.cnf", f"[client]\nhost={mariadb_node}\n")
    syscheck.exec(f"ln -sf {syscheck.home}/{HELPER_SRC} "
                  f"{syscheck.home}/{HELPER_LINK}").check()
    syscheck.exec(f"rm -rf /tmp/907 && mkdir -p {BACKUPDIR}/default").check()
    syscheck.exec(["mariadb", "-h", mariadb_node, "-uroot",
                   f"-p{MARIADB_ROOT_PASSWORD}", MARIADB_DATABASE, "-e",
                   "DROP TABLE IF EXISTS CertificateData;"
                   "CREATE TABLE CertificateData (fingerprint VARCHAR(64) PRIMARY KEY);"
                   "INSERT INTO CertificateData VALUES ('aa')"]).check()
    syscheck.set_script_config("mariadb", mariadb_config())
    syscheck.set_script_config("904", backup_config())
    syscheck.set_script_config("906", f"SSHTIMEOUT={SSH_OPTS}\n")
    syscheck.set_script_config("915", f"SSHOPTIONS={SSH_OPTS}\n")
    syscheck.set_script_config("907", config(syscheck))

    def remote(command: str):
        return syscheck.exec([
            "ssh", "-o", "StrictHostKeyChecking=no",
            "-o", "UserKnownHostsFile=/dev/null", "-o", "LogLevel=ERROR",
            "-i", SSH_KEY, "-l", SSH_REMOTE_USER, sshd_node, command])

    remote(f"rm -rf {REMOTE_DIR} && mkdir -p {REMOTE_DIR}/default").check()
    syscheck.remote = remote
    return syscheck


def own(run) -> list:
    return [m for m in run.messages if m.scriptid == "907"]


def remote_files(sc) -> list[str]:
    res = sc.remote(f"ls -1 {REMOTE_DIR}/default 2>/dev/null")
    return sorted(f for f in res.stdout.splitlines() if f.strip())


# --- the join ---------------------------------------------------------------

def test_a_backup_is_taken_and_lands_on_the_remote_host(transfer):
    transfer.run_script(SCRIPT)

    assert len(remote_files(transfer)) == 1, remote_files(transfer)
    assert remote_files(transfer)[0].endswith(".gz"), remote_files(transfer)


def test_the_transferred_file_is_the_one_904_produced(transfer):
    """The join itself: `907` captures `904 --batch`'s stdout and feeds it to
    `906`. If that plumbing broke, a stale or empty name would be sent."""
    transfer.run_script(SCRIPT)

    local = transfer.exec(f"ls -1 {BACKUPDIR}/default").check().stdout.split()
    assert local, "904 produced nothing"
    assert remote_files(transfer) == sorted(local)


def test_the_remote_copy_is_a_valid_dump(transfer):
    """Proving the bytes survived the whole chain, not just that a name
    matched."""
    transfer.run_script(SCRIPT)

    name = remote_files(transfer)[0]
    res = transfer.remote(f"zcat {REMOTE_DIR}/default/{name} | head -40")
    assert "CertificateData" in res.stdout, res.output


def test_a_successful_run_is_reported(transfer):
    run = transfer.run_script(SCRIPT)

    assert any(m.errno == "9071" and m.level == "I" for m in own(run)), run.describe()


def test_every_configured_host_receives_the_backup(transfer):
    transfer.set_script_config("907", config(transfer, hosts=[transfer.sshd,
                                                              transfer.sshd]))

    run = transfer.run_script(SCRIPT)

    assert len(own(run)) == 2, run.describe()


def test_each_transfer_reports_under_its_own_index(transfer):
    transfer.set_script_config("907", config(transfer, hosts=[transfer.sshd,
                                                              transfer.sshd]))

    run = transfer.run_script(SCRIPT)

    indexes = [m.index for m in own(run)]
    assert len(set(indexes)) == len(indexes), run.describe()


# --- failures ---------------------------------------------------------------

def test_a_failing_backup_stops_the_run(transfer):
    """If `904` cannot write, there is nothing to send — `907` reports and
    exits rather than transferring a stale file."""
    transfer.set_script_config("904", backup_config(backupdir="/tmp/907/gone"))

    run = transfer.run_script(SCRIPT)

    assert any(m.errno == "9072" for m in own(run)), run.describe()
    assert remote_files(transfer) == [], "something was transferred anyway"


def test_a_failing_transfer_is_reported(transfer):
    transfer.set_script_config("907", config(transfer, hosts=["no-such-host"]))

    run = transfer.run_script(SCRIPT)

    msg = [m for m in own(run) if m.errno == "9073"]
    assert msg and msg[0].level == "E", run.describe()


def test_a_failing_transfer_leaves_the_local_backup_in_place(transfer):
    """Unlike `931`, `907` never deletes the local copy — so a failed transfer
    is recoverable by hand."""
    transfer.set_script_config("907", config(transfer, hosts=["no-such-host"]))

    transfer.run_script(SCRIPT)

    assert transfer.exec(f"ls -1 {BACKUPDIR}/default").check().stdout.strip()


def test_one_failing_host_does_not_stop_the_others(transfer):
    transfer.set_script_config("907", config(transfer, hosts=["no-such-host",
                                                              transfer.sshd]))

    run = transfer.run_script(SCRIPT)

    assert [m.errno for m in own(run)] == ["9073", "9071"], run.describe()
    assert len(remote_files(transfer)) == 1, remote_files(transfer)


# --- known defect -----------------------------------------------------------

@pytest.mark.xfail(strict=True, reason="D117: neither outcome message names the file "
                                       "or the host, though DESCR[3] has a placeholder")
def test_the_failure_message_names_the_host_it_could_not_reach(transfer):
    """Both calls pass no arguments at all:

        printlogmess ... -e ${ERRNO[3]} -d "${DESCR[3]}"

    `DESCR[3]` is `"Could not send the backup, maybe connection problem or
    problem logging in (%s) "` — the `%s` is never filled, and neither the host
    nor the filename appears anywhere in the message.

    With several backup hosts configured, the log says a transfer failed but not
    which destination, and the index is the only way to tell them apart. `931`,
    which does the same job, passes `-1 "${TRANSFERFILENAME}"`."""
    transfer.set_script_config("907", config(transfer, hosts=["no-such-host"]))

    run = transfer.run_script(SCRIPT)

    failed = [m for m in own(run) if m.errno == "9073"]
    assert failed and "no-such-host" in failed[0].text, failed[0].text if failed else ""


def test_help_documents_every_error_code(transfer):
    res = transfer.exec([transfer.script_path(SCRIPT), "--help"])

    for errno in ("9071", "9072", "9073"):
        assert f"{errno} / " in res.output, res.output
