"""sc_12_mysql.sh against a real MariaDB server.

The check itself — pidfile, stale pidfile, name fallback — is covered with the
three other process checks in `test_sc_process_checks.py`. What that suite
cannot answer is whether the *shipped configuration* matches a real database
server, because it supplies its own `procname` and `pidfile`.

So this file asks a real `mariadb:11` what it is actually called and where it
actually keeps its pidfile, and compares that with `config/12.conf`. The server
runs in its own container — a check that reads the local process table cannot
see into it — so the comparison is made against the container's own `ps` rather
than by running the check against it.
"""

from __future__ import annotations

import pytest

from syscheck_harness import docker_exec

SCRIPT = "sc_12_mysql.sh"

pytestmark = pytest.mark.slow


def config(procname: str, pidfile: str) -> str:
    return (
        "# generated by test_sc_12_mysql.py\n"
        f"pidfile={pidfile}\n"
        f"procname={procname}\n"
    )


@pytest.fixture
def shipped_config(syscheck):
    """`config/12.conf` as shipped, parsed into procname and pidfile."""
    text = syscheck.read_file("/src/config/12.conf")
    values = {}
    for line in text.splitlines():
        line = line.strip()
        if line.startswith("procname=") or line.startswith("pidfile="):
            key, _, value = line.partition("=")
            values[key] = value
    assert {"procname", "pidfile"} <= values.keys(), text
    return values


@pytest.fixture
def server_facts(mariadb_node):
    """What the running server actually calls itself."""
    return {
        "argv": docker_exec(mariadb_node, ["ps", "-eo", "args"]),
        "pidfiles": docker_exec(
            mariadb_node,
            ["bash", "-c", "find /run /var/lib/mysql -name '*.pid' 2>/dev/null"],
        ).split(),
    }


def test_the_server_under_test_is_really_running(server_facts):
    """Guards the two comparisons below: if the server were not up, they would
    pass for the wrong reason."""
    assert "mariadbd" in server_facts["argv"], server_facts["argv"]
    assert server_facts["pidfiles"], "the server wrote no pidfile at all"


def test_a_correctly_configured_check_finds_the_database_process(syscheck):
    """Configured with the name a current MariaDB actually uses, the check works
    — so what D40 is about is the shipped default, not the mechanism."""
    pid = syscheck.start_process("mariadbd")
    syscheck.write_file("/var/run/mariadbd.pid", f"{pid}\n")
    syscheck.set_script_config("12", config("/usr/local/bin/mariadbd",
                                            "/var/run/mariadbd.pid"))

    run = syscheck.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("I", "121"), run.describe()


def test_the_shipped_procname_matches_a_real_server(shipped_config, server_facts):
    """D40, fixed 2026-09-18. `config/12.conf` shipped
    `procname=/usr/sbin/mysqld`. MariaDB 10.5 renamed the daemon and `mariadb:11`
    runs `mariadbd`, so the name fallback — the path taken whenever the pidfile
    is missing, which it also was — matched nothing. The check reported `mysql
    is NOT running` and exited 3 on a host whose database was perfectly healthy.

    It now ships `'mysqld|mariadbd'`, which is an **egrep pattern** rather than
    a path, so this asserts it *matches* rather than that it is a substring.
    `lib/proc_checker.sh` had to quote `"$the_name"` for that to be possible: an
    unquoted alternation makes bash read the `|` as a pipe, so `egrep mysqld`
    would feed into a command called `mariadbd`.

    The path prefix went deliberately. A container shows the process as bare
    `mariadbd`, systemd shows `/usr/sbin/mariadbd`, and a path-anchored pattern
    matches only one of them."""
    import re

    pattern = shipped_config["procname"].strip("'\"")

    assert re.search(pattern, server_facts["argv"]), (
        f"config/12.conf procname={pattern!r} matches nothing in:\n"
        f"{server_facts['argv']}"
    )


def test_the_shipped_pidfile_matches_a_real_server(shipped_config, server_facts):
    """The other half of the same default: the pidfile moved to `/run` years
    ago. Both halves being wrong is what made this a false alarm rather than a
    slow one — the pidfile missed, so the check fell back to the name, and the
    name missed too.

    Fixed alongside. The pidfile matters less than it looks: `proc_checker.sh`
    falls through to the name check when the file is absent, so a wrong path
    degrades rather than fails. Correcting it means the check uses the faster and
    more precise pid path instead."""
    assert shipped_config["pidfile"] in server_facts["pidfiles"], (
        f"config/12.conf pidfile={shipped_config['pidfile']!r}, "
        f"server wrote {server_facts['pidfiles']}"
    )
