"""Basic tests for scripts-available/sc_06_raid_check.sh.

`sc_06` asks HP's `ssacli` about physical and logical drives on a Smart Array
controller. No HP hardware is available to capture from, so the fixtures below
are **UNVERIFIED SHAPE**: written from the documented `ssacli` output format,
not from a real controller. They prove the script's own logic — which branch it
takes, which index it reports under, what the summary says — not that `ssacli`
speaks this dialect.

That distinction matters, and it is why this suite stays deliberately basic. The
one finding it established was independent of the fixture shape: the
"rebuilding" branch compared the *whole* matched line against the bare word
`Rebuilding`, so it could never be taken no matter what `ssacli` printed, and a
routine rebuild was reported as "investigate ASAP". Fixed 2026-09-15 (D62) by
matching `rebuild|recover` within the line, the mirror of the D69 fix in
`sc_35`.

`ssacli` is driven by piping a command into it on **stdin**
(`echo "controller slot=0 pd all show" | ssacli`), so the fake dispatches on
what it reads there rather than on argv.
"""

from __future__ import annotations

import pytest

SCRIPT = "sc_06_raid_check.sh"
TOOL = "/usr/local/bin/ssacli"
CALL_LOG = "/tmp/ssacli-calls.log"
FIXTURE_DIR = "/tmp/ssacli-fixtures"

pytestmark = pytest.mark.slow

# UNVERIFIED SHAPE — the documented `ssacli ... pd all show` layout, not a
# capture. A real `ssacli controller slot=0 pd all show` would replace this.
PD_OK = """
Smart Array P440ar in Slot 0 (Embedded)

   array A

      physicaldrive 1I:3:1 (port 1I:box 3:bay 1, SAS HDD, 600 GB, OK)
      physicaldrive 1I:3:2 (port 1I:box 3:bay 2, SAS HDD, 600 GB, OK)
"""

# UNVERIFIED SHAPE
LD_OK = """
Smart Array P440ar in Slot 0 (Embedded)

   array A

      logicaldrive 1 (558.9 GB, RAID 1, OK)
"""


FAKE_SSACLI = f"""#!/bin/bash
IN=$(cat)
echo "$IN" >> {CALL_LOG}
case "$IN" in
  *"pd all show"*) fixture=pd ;;
  *"ld all show"*) fixture=ld ;;
  *) echo "ssacli: unrecognised command: $IN" >&2 ; exit 1 ;;
esac
cat "{FIXTURE_DIR}/$fixture" 2>/dev/null
"""


def config(*, pds=("physicaldrive 1I:3:1", "physicaldrive 1I:3:2"),
           lds=("logicaldrive 1",), slot: int = 0, hptool: str = TOOL) -> str:
    lines = ["# generated by test_sc_06_raid_check.py\n",
             "SCRIPTNAME=raidcheck\n",
             f"HPTOOL={hptool}\n",
             f"SLOT={slot}\n"]
    for i, pd in enumerate(pds):
        lines.append(f'PHYSICALDRIVE[{i}]="{pd}"\n')
    for i, ld in enumerate(lds):
        lines.append(f'LOGICALDRIVE[{i}]="{ld}"\n')
    return "".join(lines)


def set_fixtures(sc, *, pd=PD_OK, ld=LD_OK) -> None:
    sc.write_file(f"{FIXTURE_DIR}/pd", pd)
    sc.write_file(f"{FIXTURE_DIR}/ld", ld)


@pytest.fixture
def raid(syscheck):
    syscheck.exec(f"rm -f {CALL_LOG} ; mkdir -p {FIXTURE_DIR}")
    syscheck.install_fake_bin("ssacli", FAKE_SSACLI)
    set_fixtures(syscheck)
    syscheck.set_script_config("06", config())
    return syscheck


def calls(sc) -> list[str]:
    if not sc.file_exists(CALL_LOG):
        return []
    return [l for l in sc.read_file(CALL_LOG).splitlines() if l.strip()]


def summary(run):
    return run.messages[-1]


# --- the tool ---------------------------------------------------------------

def test_a_missing_tool_is_reported_and_stops_the_run(raid):
    """Without `ssacli` there is nothing to report about, so the check says so
    once rather than calling every drive failed."""
    raid.set_script_config("06", config(hptool="/sbin/ssacli"))

    run = raid.run_script(SCRIPT)

    msg = run.only()
    assert (msg.level, msg.errno) == ("E", "066"), run.describe()


def test_the_controller_slot_from_the_config_is_used(raid):
    """`SLOT` is the only thing identifying the controller; a check pointed at
    the wrong slot silently reports on different hardware."""
    raid.set_script_config("06", config(slot=3))

    raid.run_script(SCRIPT)

    assert any("controller slot=3 pd all show" in c for c in calls(raid)), calls(raid)
    assert any("controller slot=3 ld all show" in c for c in calls(raid)), calls(raid)


# --- healthy and failed drives ----------------------------------------------

def test_a_healthy_array_reports_every_drive_ok(raid):
    run = raid.run_script(SCRIPT)

    assert [m.errno for m in run.messages] == ["061", "061", "063", "067"], \
        run.describe()


def test_each_drive_gets_its_own_index_and_the_summary_gets_00(raid):
    """Physical drives first, then logical, then the summary — which resets to
    `00` so it does not overwrite the last drive's verdict, the mistake `sc_08`
    made as D50."""
    run = raid.run_script(SCRIPT)

    assert [m.index for m in run.messages] == ["01", "02", "03", "00"], \
        run.describe()


def test_a_failed_physical_drive_is_an_error(raid):
    set_fixtures(raid, pd=PD_OK.replace(
        "600 GB, OK)\n      physicaldrive 1I:3:2", "600 GB, Failed)\n      physicaldrive 1I:3:2"))

    run = raid.run_script(SCRIPT)

    bad = [m for m in run.messages if m.errno == "062"]
    assert len(bad) == 1, run.describe()
    assert "1I:3:1" in bad[0].text, bad[0].text


def test_a_failed_logical_drive_is_an_error(raid):
    set_fixtures(raid, ld=LD_OK.replace("RAID 1, OK", "RAID 1, Failed"))

    run = raid.run_script(SCRIPT)

    assert [m.errno for m in run.messages if m.errno == "065"] == ["065"], \
        run.describe()


def test_a_drive_the_tool_does_not_report_is_an_error(raid):
    """A drive that has vanished from the controller entirely: the `grep` finds
    nothing, so the status is empty and empty is not OK."""
    raid.set_script_config("06", config(pds=("physicaldrive 9I:9:9",)))

    run = raid.run_script(SCRIPT)

    assert "062" in run.errnos, run.describe()


# --- the summary ------------------------------------------------------------

def test_a_clean_run_ends_with_an_ok_summary(raid):
    run = raid.run_script(SCRIPT)

    assert (summary(run).level, summary(run).errno) == ("I", "067"), run.describe()


def test_a_failure_reaches_the_summary_with_a_count(raid):
    set_fixtures(raid,
                 pd=PD_OK.replace("600 GB, OK)", "600 GB, Failed)"),
                 ld=LD_OK.replace("RAID 1, OK", "RAID 1, Failed"))

    run = raid.run_script(SCRIPT)

    assert (summary(run).level, summary(run).errno) == ("E", "068"), run.describe()
    assert "3" in summary(run).text, summary(run).text


def test_no_configured_drives_still_reports_a_summary(raid):
    """An empty config checks nothing and says so as OK — worth pinning, since
    "green means checked" is the assumption it quietly breaks."""
    raid.set_script_config("06", config(pds=(), lds=()))

    run = raid.run_script(SCRIPT)

    assert len(run.messages) == 1, run.describe()
    assert run.messages[0].errno == "067", run.describe()


# --- the one finding that does not depend on the fixture shape --------------

def test_a_rebuilding_logical_drive_is_reported_as_rebuilding(raid):
    """`ERRNO[4]`/`DESCR[4]` exist for a logical drive that is rebuilding — a
    state that resolves itself, whose help says to check back later.

    The guard used to be

        elif [ "xRebuilding" = "x$COMMAND" ]

    comparing the whole matched line against the bare word. `$COMMAND` is the
    line `grep` returned, e.g.
    `logicaldrive 1 (558.9 GB, RAID 1, Rebuilding)`, so it could only ever match
    if `ssacli` printed nothing else — which it never does, because the line
    also contains the drive identifier the `grep` matched on.

    A rebuilding array was therefore reported as `065`, "LogicalDiscs has some
    other error", whose help says *"you need to investigate this error ASAP"*.
    An operator was paged for a routine rebuild.

    This is the mirror of D69 in `sc_35`, where the *rebuilding* branch was the
    reachable one and everything landed there instead."""
    set_fixtures(raid, ld=LD_OK.replace("RAID 1, OK", "RAID 1, Rebuilding"))

    run = raid.run_script(SCRIPT)

    rebuilding = [m for m in run.messages if m.errno == "064"]
    assert rebuilding, run.describe()


def test_a_genuinely_failed_logical_drive_still_gets_the_other_error_code(raid):
    """The other side of D62: `ERRNO[5]` must stay reachable, or the fix would
    just have moved the problem from one unreachable branch to the other.

    UNVERIFIED SHAPE, like the rest of this suite — no real `ssacli` output was
    available, so `rebuild|recover` is inferred from the documented Smart Array
    states. The guess is safe in the direction that matters: anything the
    pattern does not recognise falls to `ERRNO[5]`, "investigate ASAP", rather
    than to "check back later"."""
    set_fixtures(raid, ld=LD_OK.replace("RAID 1, OK", "RAID 1, Failed"))

    run = raid.run_script(SCRIPT)

    assert "065" in run.errnos and "064" not in run.errnos, run.describe()


def test_the_status_check_accepts_ok_anywhere_in_the_line(raid):
    """`STATUS=$(echo $COMMAND | grep "OK")` matches `OK` anywhere on the
    matched line, not a status field. A drive whose model or serial contained
    those two letters would read as healthy whatever its real state.

    Characterisation, not a defect claim: without a real capture there is no
    evidence any HP drive identifier contains `OK`. Recorded because the check
    is looser than it looks, and a capture would settle whether it matters."""
    set_fixtures(raid, pd=PD_OK.replace(
        "SAS HDD, 600 GB, OK)\n      physicaldrive 1I:3:2",
        "SAS HDD OKZ1234, 600 GB, Failed)\n      physicaldrive 1I:3:2"))

    run = raid.run_script(SCRIPT)

    assert run.messages[0].errno == "061", run.describe()


def test_help_documents_every_error_code(raid):
    res = raid.exec([raid.script_path(SCRIPT), "--help"])

    for n in range(1, 9):
        assert f"06{n} / " in res.output, res.output
