# config for sc_37_monitor_jnlp.sh

URL="http://10.0.0.1/certservice-public/webResource/tolima/tolima.jnlp"
# array not string, quotes in a string are passed on to curl literally
HEADER=(--header "Host: public.domain.com")
CURL_TIMEOUT=10
CHECKTOOL=curl
