### Ansible Collection Metadata
namespace: aberosecurity
name: syscheck
version: 2.0.0
readme: README.md
authors:
  - Henrik Andreasson <henrik.andreasson@gmail.com>
description: Ansible Collection for deploying and configuring Syscheck on secure nodes.
license: GPL-3.0-or-later
repository: https://github.com/aberosecurity/syscheck
dependencies: {}
